window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Popüler ve Tanınmış Ülkeler
    { kategori: "Başkent", seviye: 1, soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "İstanbul", B: "İzmir", C: "Bursa", D: "Ankara" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 1, soru: "Fransa'nın başkenti neresidir?", secenekler: { A: "Nice", B: "Lyon", C: "Paris", D: "Marsilya" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 1, soru: "Almanya'nın başkenti neresidir?", secenekler: { A: "Hamburg", B: "Münih", C: "Berlin", D: "Frankfurt" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 2, soru: "İngiltere'nin başkenti neresidir?", secenekler: { A: "Londra", B: "Birmingham", C: "Manchester", D: "Liverpool" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 2, soru: "İtalya'nın başkenti neresidir?", secenekler: { A: "Venedik", B: "Milano", C: "Roma", D: "Floransa" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 2, soru: "İspanya'nın başkenti neresidir?", secenekler: { A: "Barselona", B: "Valensiya", C: "Madrid", D: "Sevilla" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 3, soru: "Rusya'nın başkenti neresidir?", secenekler: { A: "Moskova", B: "Novosibirsk", C: "St. Petersburg", D: "Kazan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 3, soru: "Amerika Birleşik Devletleri'nin başkenti neresidir?", secenekler: { A: "Washington D.C.", B: "Los Angeles", C: "New York", D: "Chicago" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 3, soru: "Japonya'nın başkenti neresidir?", secenekler: { A: "Tokyo", B: "Hiroşima", C: "Kyoto", D: "Osaka" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 4, soru: "Çin'in başkenti neresidir?", secenekler: { A: "Guangzhou", B: "Pekin", C: "Hong Kong", D: "Şanghay" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 4, soru: "Azerbaycan'ın başkenti neresidir?", secenekler: { A: "Bakü", B: "Nahçıvan", C: "Gence", D: "Sumgayıt" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 4, soru: "Yunanistan'ın başkenti neresidir?", secenekler: { A: "Kandiye", B: "Selanik", C: "Patras", D: "Atina" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 5, soru: "Mısır'ın başkenti neresidir?", secenekler: { A: "İskenderiye", B: "Luksor", C: "Kahire", D: "Gize" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 5, soru: "Hollanda'nın başkenti neresidir?", secenekler: { A: "Amsterdam", B: "Rotterdam", C: "Lahey", D: "Utrecht" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 5, soru: "Brezilya'nın başkenti neresidir?", secenekler: { A: "Rio de Janeiro", B: "Salvador", C: "Brasilia", D: "Sao Paulo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 6, soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Incheon", B: "Daegu", C: "Busan", D: "Seul" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 6, soru: "Arjantin'in başkenti neresidir?", secenekler: { A: "Rosario", B: "Buenos Aires", C: "Mendoza", D: "Cordoba" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 6, soru: "Hindistan'ın başkenti neresidir?", secenekler: { A: "Kalküta", B: "Chennai", C: "Yeni Delhi", D: "Mumbai" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 7, soru: "Kanada'nın başkenti neresidir?", secenekler: { A: "Vancouver", B: "Ottawa", C: "Toronto", D: "Montreal" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 7, soru: "İsviçre'nin başkenti neresidir?", secenekler: { A: "Cenevre", B: "Zürih", C: "Bern", D: "Basel" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 7, soru: "Avusturya'nın başkenti neresidir?", secenekler: { A: "Salzburg", B: "Innsbruck", C: "Graz", D: "Viyana" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 8, soru: "İran'ın başkenti neresidir?", secenekler: { A: "Meşhed", B: "İsfahan", C: "Tahran", D: "Tebriz" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 8, soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Basra", B: "Erbil", C: "Bağdat", D: "Musul" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 8, soru: "Suudi Arabistan'ın başkenti neresidir?", secenekler: { A: "Mekke", B: "Cidde", C: "Medine", D: "Riyad" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 9, soru: "Portekiz'in başkenti neresidir?", secenekler: { A: "Coimbra", B: "Lizbon", C: "Porto", D: "Braga" }, dogruCevap: "B" },

    // 26-50: Avrupa ve Asya Detayları
    { kategori: "Başkent", seviye: 10, soru: "Ukrayna'nın başkenti neresidir?", secenekler: { A: "Odessa", B: "Kiev", C: "Lviv", D: "Harkiv" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 10, soru: "Belçika'nın başkenti neresidir?", secenekler: { A: "Gent", B: "Brugge", C: "Brüksel", D: "Anvers" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 11, soru: "Polonya'nın başkenti neresidir?", secenekler: { A: "Krakov", B: "Gdansk", C: "Varşova", D: "Wroclaw" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 11, soru: "Macaristan'ın başkenti neresidir?", secenekler: { A: "Segedin", B: "Debrecen", C: "Pecs", D: "Budapeşte" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 12, soru: "Çek Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Ostrava", B: "Plzen", C: "Prag", D: "Brno" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 12, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Kosice", B: "Bratislava", C: "Zilina", D: "Nitra" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 13, soru: "Hırvatistan'ın başkenti neresidir?", secenekler: { A: "Zadar", B: "Dubrovnik", C: "Split", D: "Zagreb" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 13, soru: "Sırbistan'ın başkenti neresidir?", secenekler: { A: "Novi Sad", B: "Belgrad", C: "Niş", D: "Kragujevac" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 14, soru: "Bulgaristan'ın başkenti neresidir?", secenekler: { A: "Filibe", B: "Varna", C: "Burgas", D: "Sofya" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 14, soru: "Romanya'nın başkenti neresidir?", secenekler: { A: "Kaloşvar", B: "Köstence", C: "Bükreş", D: "Yaş" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 15, soru: "İrlanda'nın başkenti neresidir?", secenekler: { A: "Belfast", B: "Dublin", C: "Cork", D: "Galway" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 15, soru: "İskoçya'nın başkenti neresidir?", secenekler: { A: "Glasgow", B: "Dundee", C: "Edinburgh", D: "Aberdeen" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 16, soru: "Norveç'in başkenti neresidir?", secenekler: { A: "Oslo", B: "Stavanger", C: "Bergen", D: "Trondheim" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 16, soru: "İsveç'in başkenti neresidir?", secenekler: { A: "Goteborg", B: "Malmö", C: "Stockholm", D: "Uppsala" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 17, soru: "Finlandiya'nın başkenti neresidir?", secenekler: { A: "Helsinki", B: "Turku", C: "Tampere", D: "Oulu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 17, soru: "Danimarka'nın başkenti neresidir?", secenekler: { A: "Aalborg", B: "Kopenhag", C: "Aarhus", D: "Odense" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 18, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Phuket", B: "Bangkok", C: "Chiang Mai", D: "Pattaya" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 18, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Bandung", B: "Cakarta", C: "Bali", D: "Surabaya" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 19, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Ho Chi Minh", B: "Hanoi", C: "Hue", D: "Da Nang" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 19, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "İslamabad", B: "Lahor", C: "Peşaver", D: "Karaçi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 20, soru: "Kazakistan'ın başkenti neresidir?", secenekler: { A: "Aktau", B: "Astana", C: "Almati", D: "Çimkent" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 20, soru: "Özbekistan'ın başkenti neresidir?", secenekler: { A: "Buhara", B: "Semerkant", C: "Taşkent", D: "Hiva" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 21, soru: "Türkmenistan'ın başkenti neresidir?", secenekler: { A: "Merv", B: "Türkmenbaşı", C: "Daşoğuz", D: "Aşkabat" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 21, soru: "Kırgızistan'ın başkenti neresidir?", secenekler: { A: "Celal-Abad", B: "Narın", C: "Oş", D: "Bişkek" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 22, soru: "Gürcistan'ın başkenti neresidir?", secenekler: { A: "Batum", B: "Kutaisi", C: "Gori", D: "Tiflis" }, dogruCevap: "D" },

    // 51-75: Orta Doğu, Afrika ve Amerika Kıtası
    { kategori: "Başkent", seviye: 23, soru: "Suriye'nın başkenti neresidir?", secenekler: { A: "Lazkiye", B: "Şam", C: "Halep", D: "Humus" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 23, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Beyrut", B: "Zahle", C: "Sayda", D: "Trablusşam" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 24, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Zarka", B: "Amman", C: "Akabe", D: "İrbid" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 24, soru: "İsrail'in başkenti (uluslararası tanınırlığa göre en büyük şehri) neresidir?", secenekler: { A: "Hayfa", B: "Kudüs", C: "Tel Aviv", D: "Eylat" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 25, soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Fes", B: "Marakeş", C: "Rabat", D: "Kazablanka" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 25, soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Annabe", B: "Cezayir", C: "Konstantin", D: "Oran" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 26, soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Susa", B: "Kayrevan", C: "Bizerte", D: "Tunus" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 26, soru: "Güney Afrika Cumhuriyeti'nin üç başkentinden biri hangisidir?", secenekler: { A: "Soweto", B: "Johannesburg", C: "Durban", D: "Cape Town" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 27, soru: "Nijerya'nın başkenti neresidir?", secenekler: { A: "Abuja", B: "Kano", C: "Lagos", D: "Ibadan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 27, soru: "Kenya'nın başkenti neresidir?", secenekler: { A: "Mombasa", B: "Kisumu", C: "Nakuru", D: "Nairobi" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 28, soru: "Etiyopya'nın başkenti neresidir?", secenekler: { A: "Lalibela", B: "Addis Ababa", C: "Dire Dawa", D: "Gondar" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 28, soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Cancun", B: "Monterrey", C: "Guadalajara", D: "Meksiko" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 29, soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Varadero", B: "Havana", C: "Holguin", D: "Santiago" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 29, soru: "Kolombiya'nın başkenti neresidir?", secenekler: { A: "Medellin", B: "Bogota", C: "Cali", D: "Cartagena" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 30, soru: "Peru'nun başkenti neresidir?", secenekler: { A: "Lima", B: "Iquitos", C: "Cusco", D: "Arequipa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 30, soru: "Şili'nin başkenti neresidir?", secenekler: { A: "Santiago", B: "Valparaiso", C: "Concepcion", D: "Antofagasta" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 31, soru: "Uruguay'ın başkenti neresidir?", secenekler: { A: "Montevideo", B: "Punta del Este", C: "Salto", D: "Colonia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 31, soru: "Avustralya'nın başkenti neresidir?", secenekler: { A: "Canberra", B: "Sidney", C: "Perth", D: "Melbourne" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 32, soru: "Yeni Zelanda'nın başkenti neresidir?", secenekler: { A: "Auckland", B: "Queenstown", C: "Wellington", D: "Christchurch" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 32, soru: "Güney Kıbrıs Rum Yönetimi'nin başkenti neresidir?", secenekler: { A: "Lefkoşa", B: "Larnaka", C: "Baf", D: "Limasol" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 33, soru: "Kuzey Kıbrıs Türk Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Lefkoşa", B: "Girne", C: "Güzelyurt", D: "Gazimağusa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 33, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Kandahar", B: "Kabil", C: "Herat", D: "Mezar-ı Şerif" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 34, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Quezon", B: "Manila", C: "Davao", D: "Cebu" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 34, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "George Town", B: "Melaka", C: "Johor Bahru", D: "Kuala Lumpur" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 35, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ulanbatur", B: "Ölgii", C: "Erdenet", D: "Darhan" }, dogruCevap: "A" },

    // 76-100: Zor ve Daha Az Bilinenler
    { kategori: "Başkent", seviye: 36, soru: "İzlanda'nın başkenti neresidir?", secenekler: { A: "Akureyri", B: "Reykjavik", C: "Keflavik", D: "Vík" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 36, soru: "Malta'nın başkenti neresidir?", secenekler: { A: "Mdina", B: "St. Julian's", C: "Valletta", D: "Sliema" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 37, soru: "Lüksemburg'un başkenti neresidir?", secenekler: { A: "Echternach", B: "Esch", C: "Lüksemburg", D: "Diekirch" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 37, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tartu", B: "Tallinn", C: "Narva", D: "Pärnu" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 38, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Riga", B: "Daugavpils", C: "Jurmala", D: "Liepaja" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 38, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Klaipeda", B: "Siauliai", C: "Vilnius", D: "Kaunas" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 39, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Celje", B: "Maribor", C: "Ljubljana", D: "Koper" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 39, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Vlora", B: "Tiran", C: "Durres", D: "İşkodra" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 40, soru: "Makedonya'nın (Kuzey Makedonya) başkenti neresidir?", secenekler: { A: "Tetovo", B: "Üsküp", C: "Ohrid", D: "Manastır" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 40, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Çetine", B: "Podgorica", C: "Kotor", D: "Budva" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 41, soru: "Bosna-Hersek'in başkenti neresidir?", secenekler: { A: "Tuzla", B: "Mostar", C: "Saraybosna", D: "Banja Luka" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 41, soru: "Ermenistan'ın başkenti neresidir?", secenekler: { A: "Erivan", B: "Dilican", C: "Vanadzor", D: "Gümrü" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 42, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Chittagong", B: "Rajshahi", C: "Sylhet", D: "Dakka" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 42, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Pokhara", B: "Biratnagar", C: "Katmandu", D: "Lalitpur" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 43, soru: "Sri Lanka'nın başkenti neresidir?", secenekler: { A: "Kandy", B: "Jaffna", C: "Kolombo", D: "Galle" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 43, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Doha", B: "Lusail", C: "Al Khor", D: "Al Wakrah" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 44, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Ahmadi", B: "Jahra", C: "Kuveyt", D: "Salmiya" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 44, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Nizwa", B: "Muskat", C: "Salalah", D: "Sohar" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 45, soru: "Yemen'in başkenti neresidir?", secenekler: { A: "Sana", B: "Taiz", C: "Hodeida", D: "Aden" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 45, soru: "Libya'nın başkenti neresidir?", secenekler: { A: "Tobruk", B: "Trablus", C: "Bingazi", D: "Misrata" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 46, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Ziguinchor", B: "Saint-Louis", C: "Dakar", D: "Thies" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 46, soru: "Gana'nın başkenti neresidir?", secenekler: { A: "Sekondi", B: "Tamale", C: "Kumasi", D: "Akra" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 47, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Antsirabe", B: "Mahajanga", C: "Toamasina", D: "Antananarivo" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 48, soru: "Ekvador'un başkenti neresidir?", secenekler: { A: "Quito", B: "Cuenca", C: "Guayaquil", D: "Manta" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 49, soru: "Venezuela'nın başkenti neresidir?", secenekler: { A: "Valencia", B: "Maracaibo", C: "Karakas", D: "Merida" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 50, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Port Sudan", B: "Hartum", C: "Kassala", D: "Omdurman" }, dogruCevap: "B" }, 
    // Başkent Soruları Devamı (51 - 150)
    { kategori: "Başkent", seviye: 51, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Pattaya", B: "Bangkok", C: "Chiang Mai", D: "Phuket" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 52, soru: "Güney Afrika Cumhuriyeti'nin yürütme başkenti hangisidir?", secenekler: { A: "Johannesburg", B: "Durban", C: "Cape Town", D: "Pretoria" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 53, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Hanoi", B: "Ho Chi Minh", C: "Da Nang", D: "Hue" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 54, soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Havana", B: "Varadero", C: "Santiago", D: "Holguin" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 55, soru: "Norveç'in başkenti neresidir?", secenekler: { A: "Trondheim", B: "Stavanger", C: "Oslo", D: "Bergen" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 56, soru: "İsveç'in başkenti neresidir?", secenekler: { A: "Uppsala", B: "Goteborg", C: "Stockholm", D: "Malmö" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 57, soru: "Finlandiya'nın başkenti neresidir?", secenekler: { A: "Helsinki", B: "Espoo", C: "Turku", D: "Tampere" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 58, soru: "Danimarka'nın başkenti neresidir?", secenekler: { A: "Aarhus", B: "Kopenhag", C: "Odense", D: "Aalborg" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 59, soru: "İrlanda'nın başkenti neresidir?", secenekler: { A: "Cork", B: "Galway", C: "Dublin", D: "Belfast" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 60, soru: "İsviçre'nin başkenti neresidir?", secenekler: { A: "Zürih", B: "Cenevre", C: "Bern", D: "Basel" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 61, soru: "Avusturya'nın başkenti neresidir?", secenekler: { A: "Viyana", B: "Graz", C: "Salzburg", D: "Innsbruck" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 62, soru: "Belçika'nın başkenti neresidir?", secenekler: { A: "Gent", B: "Anvers", C: "Brugge", D: "Brüksel" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 63, soru: "Macaristan'ın başkenti neresidir?", secenekler: { A: "Budapeşte", B: "Pécs", C: "Szeged", D: "Debrecen" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 64, soru: "Çek Cumhuriyeti'nın başkenti neresidir?", secenekler: { A: "Prag", B: "Plzeň", C: "Brno", D: "Ostrava" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 65, soru: "Polonya'nın başkenti neresidir?", secenekler: { A: "Gdańsk", B: "Wrocław", C: "Krakov", D: "Varşova" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 66, soru: "Romanya'nın başkenti neresidir?", secenekler: { A: "Köstence", B: "Yaş", C: "Bükreş", D: "Kaloşvar" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 67, soru: "Bulgaristan'ın başkenti neresidir?", secenekler: { A: "Sofya", B: "Burgaz", C: "Filibe", D: "Varna" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 68, soru: "Sırbistan'ın başkenti neresidir?", secenekler: { A: "Niş", B: "Belgrad", C: "Kragujevac", D: "Novi Sad" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 69, soru: "Hırvatistan'ın başkenti neresidir?", secenekler: { A: "Zagreb", B: "Dubrovnik", C: "Split", D: "Rijeka" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 70, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Koper", B: "Maribor", C: "Ljubljana", D: "Celje" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 71, soru: "Lüksemburg'un başkenti neresidir?", secenekler: { A: "Esch", B: "Diekirch", C: "Lüksemburg", D: "Echternach" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 72, soru: "Monako'nun başkenti neresidir?", secenekler: { A: "Nice", B: "Monako", C: "Monte Carlo", D: "Cannes" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 73, soru: "Vatikan'ın başkenti neresidir?", secenekler: { A: "Milano", B: "Floransa", C: "Vatikan", D: "Roma" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 74, soru: "Malta'nın başkenti neresidir?", secenekler: { A: "Sliema", B: "Gozo", C: "Mdina", D: "Valletta" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 75, soru: "İzlanda'nın başkenti neresidir?", secenekler: { A: "Akureyri", B: "Vik", C: "Reykjavik", D: "Keflavik" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 76, soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Kazablanka", B: "Marakeş", C: "Fes", D: "Rabat" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 77, soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Oran", B: "Konstantin", C: "Cezayir", D: "Annabe" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 78, soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Susa", B: "Kayrevan", C: "Safakes", D: "Tunus" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 79, soru: "Libya'nın başkenti neresidir?", secenekler: { A: "Bingazi", B: "Misrata", C: "Trablus", D: "Tobruk" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 80, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Port Sudan", B: "Omdurman", C: "Cub", D: "Hartum" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 81, soru: "Etiyopya'nın başkenti neresidir?", secenekler: { A: "Addis Ababa", B: "Lalibela", C: "Gondar", D: "Dire Dawa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 82, soru: "Kenya'nın başkenti neresidir?", secenekler: { A: "Mombasa", B: "Nairobi", C: "Kisumu", D: "Eldoret" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 83, soru: "Nijerya'nın başkenti neresidir?", secenekler: { A: "Abuja", B: "Ibadan", C: "Lagos", D: "Kano" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 84, soru: "Gana'nın başkenti neresidir?", secenekler: { A: "Kumasi", B: "Sekondi", C: "Akra", D: "Tamale" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 85, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Saint-Louis", B: "Dakar", C: "Ziguinchor", D: "Thiès" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 86, soru: "Somali'nin başkenti neresidir?", secenekler: { A: "Mogadişu", B: "Berbera", C: "Kismayo", D: "Hargeisa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 87, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Trablusşam", B: "Beyrut", C: "Zahle", D: "Sayda" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 88, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Akabe", B: "İrbid", C: "Amman", D: "Zarka" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 89, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Al Jahra", B: "Salmiya", C: "Kuveyt City", D: "Ahmadi" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 90, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Al Khor", B: "Al Wakrah", C: "Doha", D: "Lusail" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 91, soru: "Birleşik Arap Emirlikleri'nin başkenti neresidir?", secenekler: { A: "Abu Dabi", B: "Şarika", C: "Acman", D: "Dubai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 92, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Sohar", B: "Nizwa", C: "Salalah", D: "Maskat" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 93, soru: "Yemen'in başkenti neresidir?", secenekler: { A: "Taiz", B: "Sana", C: "Hudeyde", D: "Aden" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 94, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Herat", B: "Mezar-ı Şerif", C: "Kabil", D: "Kandahar" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 95, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "Karaçi", B: "İslamabad", C: "Peşaver", D: "Lahor" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 96, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Dakka", B: "Chittagong", C: "Sylhet", D: "Rajshahi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 97, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Katmandu", B: "Pokhara", C: "Biratnagar", D: "Lalitpur" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 98, soru: "Sri Lanka'nın idari başkenti neresidir?", secenekler: { A: "Galle", B: "Kolombo", C: "Sri Jayawardenepura Kotte", D: "Kandy" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 99, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ulanbatur", B: "Ölgii", C: "Darhan", D: "Erdenet" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 100, soru: "Kuzey Kore'nin başkenti neresidir?", secenekler: { A: "Wonsan", B: "Kaesong", C: "Hamhung", D: "Pyongyang" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 101, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Manila", B: "Davao", C: "Quezon", D: "Cebu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 102, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "Kuala Lumpur", B: "Kota Kinabalu", C: "Kuching", D: "George Town" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 103, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Surabaya", B: "Bali", C: "Cakarta", D: "Bandung" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 104, soru: "Yeni Zelanda'nın başkenti neresidir?", secenekler: { A: "Wellington", B: "Christchurch", C: "Auckland", D: "Hamilton" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 105, soru: "Avustralya'nın başkenti neresidir?", secenekler: { A: "Brisbane", B: "Canberra", C: "Sidney", D: "Melbourne" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 106, soru: "Kolombiya'nın başkenti neresidir?", secenekler: { A: "Cartagena", B: "Bogota", C: "Cali", D: "Medellin" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 107, soru: "Venezuela'nın başkenti neresidir?", secenekler: { A: "Valencia", B: "Barquisimeto", C: "Maracaibo", D: "Karakas" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 108, soru: "Peru'nun başkenti neresidir?", secenekler: { A: "Trujillo", B: "Cusco", C: "Lima", D: "Arequipa" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 109, soru: "Şili'nin başkenti neresidir?", secenekler: { A: "Concepcion", B: "Valparaiso", C: "Santiago", D: "Antofagasta" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 110, soru: "Uruguay'ın başkenti neresidir?", secenekler: { A: "Salto", B: "Paysandu", C: "Punta del Este", D: "Montevideo" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 111, soru: "Paraguay'ın başkenti neresidir?", secenekler: { A: "Luque", B: "Ciudad del Este", C: "Encarnacion", D: "Asuncion" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 112, soru: "Bolivya'nın idari başkenti neresidir?", secenekler: { A: "La Paz", B: "Santa Cruz", C: "Sucre", D: "Cochabamba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 113, soru: "Ekvador'un başkenti neresidir?", secenekler: { A: "Cuenca", B: "Manta", C: "Quito", D: "Guayaquil" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 114, soru: "Panama'nın başkenti neresidir?", secenekler: { A: "Colon", B: "David", C: "Chitré", D: "Panama City" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 115, soru: "Kosta Rika'nın başkenti neresidir?", secenekler: { A: "San Jose", B: "Alajuela", C: "Limon", D: "Heredia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 116, soru: "Guatemala'nın başkenti neresidir?", secenekler: { A: "Escuintla", B: "Quetzaltenango", C: "Antigua", D: "Guatemala City" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 117, soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Guadalajara", B: "Meksiko", C: "Monterrey", D: "Cancun" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 118, soru: "Jamaika'nın başkenti neresidir?", secenekler: { A: "Montego Bay", B: "Ocho Rios", C: "Negril", D: "Kingston" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 119, soru: "Haiti'nin başkenti neresidir?", secenekler: { A: "Port-au-Prince", B: "Cap-Haitien", C: "Jacmel", D: "Les Cayes" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 120, soru: "Dominik Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Punta Cana", B: "Santo Domingo", C: "La Romana", D: "Santiago" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 121, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Pärnu", B: "Narva", C: "Tartu", D: "Tallinn" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 122, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Jurmala", B: "Daugavpils", C: "Liepaja", D: "Riga" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 123, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Kaunas", B: "Klaipeda", C: "Vilnius", D: "Siauliai" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 124, soru: "Beyaz Rusya (Belarus)'nun başkenti neresidir?", secenekler: { A: "Gomel", B: "Brest", C: "Grodno", D: "Minsk" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 125, soru: "Moldova'nın başkenti neresidir?", secenekler: { A: "Bender", B: "Tiraspol", C: "Kişinev", D: "Balti" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 126, soru: "Gürcistan'ın başkenti neresidir?", secenekler: { A: "Batum", B: "Gori", C: "Kutaisi", D: "Tiflis" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 127, soru: "Ermenistan'ın başkenti neresidir?", secenekler: { A: "Vanadzor", B: "Gümrü", C: "Erivan", D: "Dilican" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 128, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Vlorë", B: "Tiran", C: "Durrës", D: "İşkodra" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 129, soru: "Bosna-Hersek'in başkenti neresidir?", secenekler: { A: "Saraybosna", B: "Mostar", C: "Tuzla", D: "Banja Luka" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 130, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Çetine", B: "Podgorica", C: "Kotor", D: "Budva" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 131, soru: "Kuzey Makedonya'nın başkenti neresidir?", secenekler: { A: "Tetovo", B: "Manastır", C: "Üsküp", D: "Ohrid" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 132, soru: "Kıbrıs Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Larnaka", B: "Lefkoşa", C: "Baf", D: "Limasol" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 133, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Bratislava", B: "Nitra", C: "Žilina", D: "Košice" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 134, soru: "Kamboçya'nın başkenti neresidir?", secenekler: { A: "Siem Reap", B: "Sihanoukville", C: "Battambang", D: "Phnom Penh" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 135, soru: "Laos'un başkenti neresidir?", secenekler: { A: "Savannakhet", B: "Pakse", C: "Luang Prabang", D: "Vientiane" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 136, soru: "Myanmar'ın başkenti neresidir?", secenekler: { A: "Bago", B: "Yangon", C: "Mandalay", D: "Naypyidaw" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 137, soru: "Brunei'nin başkenti neresidir?", secenekler: { A: "Seria", B: "Kuala Belait", C: "Bandar Seri Begawan", D: "Tutong" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 138, soru: "Tanzanya'nın başkenti neresidir?", secenekler: { A: "Dodoma", B: "Darüsselam", C: "Zanzibar", D: "Arusha" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 139, soru: "Uganda'nın başkenti neresidir?", secenekler: { A: "Jinja", B: "Kampala", C: "Entebbe", D: "Mbarara" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 140, soru: "Ruanda'nın başkenti neresidir?", secenekler: { A: "Butare", B: "Kigali", C: "Ruhengeri", D: "Gisenyi" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 141, soru: "Angola'nın başkenti neresidir?", secenekler: { A: "Benguela", B: "Luanda", C: "Huambo", D: "Lobito" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 142, soru: "Zambiya'nın başkenti neresidir?", secenekler: { A: "Lusaka", B: "Ndola", C: "Livingstone", D: "Kitwe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 143, soru: "Zimbabve'nin başkenti neresidir?", secenekler: { A: "Mutare", B: "Gweru", C: "Bulawayo", D: "Harare" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 144, soru: "Botsvana'nın başkenti neresidir?", secenekler: { A: "Francistown", B: "Maun", C: "Gaborone", D: "Kasane" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 145, soru: "Namibya'nın başkenti neresidir?", secenekler: { A: "Windhoek", B: "Lüderitz", C: "Swakopmund", D: "Walvis Bay" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 146, soru: "Mali'nin başkenti neresidir?", secenekler: { A: "Timbuktu", B: "Gao", C: "Bamako", D: "Mopti" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 147, soru: "Fildişi Sahili'nin idari başkenti neresidir?", secenekler: { A: "Bouaké", B: "San-Pédro", C: "Abidjan", D: "Yamoussoukro" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 148, soru: "Kamerun'un başkenti neresidir?", secenekler: { A: "Yaoundé", B: "Douala", C: "Garoua", D: "Bamenda" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 149, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Mahajanga", B: "Antananarivo", C: "Antsirabe", D: "Toamasina" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 150, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Curepipe", B: "Vacoas", C: "Port Louis", D: "Quatre Bornes" }, dogruCevap: "C" }, 
    // 151-350: Yeni Eklenen Başkent Soruları
    { kategori: "Başkent", seviye: 151, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Dakar", B: "Ziguinchor", C: "Saint-Louis", D: "Thiès" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 152, soru: "Gine'nin başkenti neresidir?", secenekler: { A: "Nzérékoré", B: "Conakry", C: "Kindia", D: "Kankan" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 153, soru: "Liberya'nın başkenti neresidir?", secenekler: { A: "Gbarnga", B: "Buchanan", C: "Monrovia", D: "Harper" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 154, soru: "Sierra Leone'nin başkenti neresidir?", secenekler: { A: "Makeni", B: "Kenema", C: "Freetown", D: "Bo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 155, soru: "Burkina Faso'nun başkenti neresidir?", secenekler: { A: "Ouagadougou", B: "Koudougou", C: "Ouahigouya", D: "Bobo-Dioulasso" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 156, soru: "Nijer'in başkenti neresidir?", secenekler: { A: "Maradi", B: "Niamey", C: "Agadez", D: "Zinder" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 157, soru: "Çad'ın başkenti neresidir?", secenekler: { A: "Moundou", B: "Sarh", C: "N'Djamena", D: "Abéché" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 158, soru: "Orta Afrika Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Berbérati", B: "Bimbo", C: "Bangui", D: "Bouar" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 159, soru: "Gabon'un başkenti neresidir?", secenekler: { A: "Oyem", B: "Franceville", C: "Port-Gentil", D: "Libreville" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 160, soru: "Kongo Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Pointe-Noire", B: "Madingou", C: "Dolisie", D: "Brazzaville" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 161, soru: "Demokratik Kongo Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Lubumbashi", B: "Kinşasa", C: "Mbuji-Mayi", D: "Goma" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 162, soru: "Eritre'nin başkenti neresidir?", secenekler: { A: "Massawa", B: "Asmara", C: "Assab", D: "Keren" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 163, soru: "Cibuti'nin başkenti neresidir?", secenekler: { A: "Ali Sabieh", B: "Tadjoura", C: "Cibuti", D: "Dikhil" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 164, soru: "Malavi'nın başkenti neresidir?", secenekler: { A: "Mzuzu", B: "Zomba", C: "Lilongwe", D: "Blantyre" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 165, soru: "Burundi'nin başkenti neresidir?", secenekler: { A: "Gitega", B: "Kayanza", C: "Bujumbura", D: "Ngozi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 166, soru: "Esvatini'nin (Svaziland) idari başkenti neresidir?", secenekler: { A: "Mbabane", B: "Manzini", C: "Big Bend", D: "Lobamba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 167, soru: "Lesotho'nun başkenti neresidir?", secenekler: { A: "Mafeteng", B: "Hlotse", C: "Maseru", D: "Teyateyaneng" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 168, soru: "Moritanya'nın başkenti neresidir?", secenekler: { A: "Kiffa", B: "Nouadhibou", C: "Nouakchott", D: "Rosso" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 169, soru: "Gine-Bissau'nun başkenti neresidir?", secenekler: { A: "Catió", B: "Bissau", C: "Gabú", D: "Bafatá" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 170, soru: "Gambiya'nın başkenti neresidir?", secenekler: { A: "Brikama", B: "Banjul", C: "Serekunda", D: "Bakau" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 171, soru: "Cape Verde'nin (Yeşil Burun Adaları) başkenti neresidir?", secenekler: { A: "Santa Maria", B: "Mindelo", C: "Praia", D: "Assomada" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 172, soru: "Seyşeller'in başkenti neresidir?", secenekler: { A: "Beau Vallon", B: "Anse Royale", C: "Victoria", D: "Cascade" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 173, soru: "Komorlar'ın başkenti neresidir?", secenekler: { A: "Domoni", B: "Mutsamudu", C: "Moroni", D: "Fomboni" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 174, soru: "Bahreyn'in başkenti neresidir?", secenekler: { A: "Muharrak", B: "Hamad", C: "Manama", D: "Riffa" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 175, soru: "Maldivler'in başkenti neresidir?", secenekler: { A: "Male", B: "Fuvahmulah", C: "Kulhudhuffushi", D: "Addu City" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 176, soru: "Bhutan'ın başkenti neresidir?", secenekler: { A: "Phuntsholing", B: "Punakha", C: "Paro", D: "Thimphu" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 177, soru: "Tacikistan'ın başkenti neresidir?", secenekler: { A: "Kulob", B: "Hucend", C: "Bohtar", D: "Duşanbe" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 178, soru: "Doğu Timor'un başkenti neresidir?", secenekler: { A: "Maliana", B: "Dili", C: "Suai", D: "Baucau" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 179, soru: "Papua Yeni Gine'nin başkenti neresidir?", secenekler: { A: "Lae", B: "Mt Hagen", C: "Port Moresby", D: "Arawa" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 180, soru: "Solomon Adaları'nın başkenti neresidir?", secenekler: { A: "Honiara", B: "Gizo", C: "Tulagi", D: "Auki" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 181, soru: "Fiji'nin başkenti neresidir?", secenekler: { A: "Labasa", B: "Nadi", C: "Suva", D: "Lautoka" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 182, soru: "Vanuatu'nun başkenti neresidir?", secenekler: { A: "Port Vila", B: "Luganville", C: "Isangel", D: "Sola" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 183, soru: "Samoa'nın başkenti neresidir?", secenekler: { A: "Faleasiu", B: "Vaitele", C: "Apia", D: "Vailele" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 184, soru: "Tonga'nın başkenti neresidir?", secenekler: { A: "Haveluloto", B: "Neiafu", C: "Vaini", D: "Nuku'alofa" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 185, soru: "Kiribati'nin başkenti neresidir?", secenekler: { A: "Abaiang", B: "Bairiki", C: "Güney Tarava", D: "Betio" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 186, soru: "Mikronezya Federal Devletleri'nin başkenti neresidir?", secenekler: { A: "Palikir", B: "Tol", C: "Kolonia", D: "Weno" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 187, soru: "Marshall Adaları'nın başkenti neresidir?", secenekler: { A: "Ebeye", B: "Majuro", C: "Jaluit", D: "Wotje" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 188, soru: "Palau'nun başkenti neresidir?", secenekler: { A: "Airai", B: "Ngerulmud", C: "Meyuns", D: "Koror" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 189, soru: "Nauru'nun başkenti (resmi başkenti olmasa da hükümet merkezi) neresidir?", secenekler: { A: "Meneng", B: "Denigomodu", C: "Yaren", D: "Aiwo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 190, soru: "Tuvalu'nun başkenti neresidir?", secenekler: { A: "Funafuti", B: "Vaitupu", C: "Niutao", D: "Nanumea" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 191, soru: "Andorra'nın başkenti neresidir?", secenekler: { A: "Encamp", B: "Escaldes", C: "Canillo", D: "Andorra la Vella" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 192, soru: "Liechtenstein'ın başkenti neresidir?", secenekler: { A: "Schaan", B: "Balzers", C: "Triesen", D: "Vaduz" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 193, soru: "San Marino'nun başkenti neresidir?", secenekler: { A: "San Marino", B: "Dogana", C: "Serravalle", D: "Borgo Maggiore" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 194, soru: "Malta'nın başkenti neresidir?", secenekler: { A: "Birkirkara", B: "Mosta", C: "Valletta", D: "Sliema" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 195, soru: "Kıbrıs'ın başkenti neresidir?", secenekler: { A: "Baf", B: "Limasol", C: "Lefkoşa", D: "Larnaka" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 196, soru: "Bahamalar'ın başkenti neresidir?", secenekler: { A: "Freeport", B: "Coopers Town", C: "West End", D: "Nassau" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 197, soru: "Barbados'un başkenti neresidir?", secenekler: { A: "Holetown", B: "Oistins", C: "Speightstown", D: "Bridgetown" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 198, soru: "Grenada'nın başkenti neresidir?", secenekler: { A: "St. George's", B: "Grenville", C: "Victoria", D: "Gouyave" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 199, soru: "Guyana'nın başkenti neresidir?", secenekler: { A: "Linden", B: "Anna Regina", C: "New Amsterdam", D: "Georgetown" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 200, soru: "Surinam'ın başkenti neresidir?", secenekler: { A: "Moengo", B: "Lelydorp", C: "Nieuw Nickerie", D: "Paramaribo" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 201, soru: "Belize'nin başkenti neresidir?", secenekler: { A: "Orange Walk", B: "Belmopan", C: "San Ignacio", D: "Belize City" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 202, soru: "El Salvador'un başkenti neresidir?", secenekler: { A: "Santa Ana", B: "San Salvador", C: "San Miguel", D: "Soyapango" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 203, soru: "Honduras'ın başkenti neresidir?", secenekler: { A: "Choluteca", B: "Tegucigalpa", C: "San Pedro Sula", D: "La Ceiba" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 204, soru: "Nikaragua'nın başkenti neresidir?", secenekler: { A: "Tipitapa", B: "Managua", C: "Leon", D: "Masaya" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 205, soru: "Trinidad ve Tobago'nun başkenti neresidir?", secenekler: { A: "Arima", B: "San Fernando", C: "Chaguanas", D: "Port of Spain" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 206, soru: "Dominika'nın başkenti neresidir?", secenekler: { A: "Berekua", B: "Portsmouth", C: "Roseau", D: "Marigot" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 207, soru: "Saint Lucia'nın başkenti neresidir?", secenekler: { A: "Micoud", B: "Soufrière", C: "Castries", D: "Vieux Fort" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 208, soru: "Saint Vincent ve Grenadinler'in başkenti neresidir?", secenekler: { A: "Georgetown", B: "Barrouallie", C: "Kingstown", D: "Byera" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 209, soru: "Saint Kitts ve Nevis'in başkenti neresidir?", secenekler: { A: "Saddlers", B: "Cayon", C: "Basseterre", D: "Charlestown" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 210, soru: "Antigua ve Barbuda'nın başkenti neresidir?", secenekler: { A: "All Saints", B: "Liberta", C: "Potters Village", D: "St. John's" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 211, soru: "Ekvator Ginesi'nin başkenti neresidir?", secenekler: { A: "Malabo", B: "Mongomo", C: "Ebebiyín", D: "Bata" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 212, soru: "Sao Tome ve Principe'nin başkenti neresidir?", secenekler: { A: "Trindade", B: "São Tomé", C: "Santana", D: "Neves" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 213, soru: "Benin'in resmi başkenti neresidir?", secenekler: { A: "Djougou", B: "Cotonou", C: "Parakou", D: "Porto-Novo" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 214, soru: "Togo'nun başkenti neresidir?", secenekler: { A: "Sokodé", B: "Atakpamé", C: "Lomé", D: "Kara" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 215, soru: "Cibuti'nin başkenti neresidir?", secenekler: { A: "Cibuti City", B: "Dikhil", C: "Ali Sabieh", D: "Arta" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 216, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Port Louis", B: "Beau Bassin", C: "Vacoas", D: "Curepipe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 217, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Maribor", B: "Kranj", C: "Ljubljana", D: "Celje" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 218, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Kosice", B: "Zilina", C: "Presov", D: "Bratislava" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 219, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tallinn", B: "Pärnu", C: "Narva", D: "Tartu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 220, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Jelgava", B: "Daugavpils", C: "Riga", D: "Liepaja" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 221, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Klaipeda", B: "Siauliai", C: "Kaunas", D: "Vilnius" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 222, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Podgorica", B: "Herceg Novi", C: "Nikšić", D: "Pljevlja" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 223, soru: "Kuzey Makedonya'nın başkenti neresidir?", secenekler: { A: "Üsküp", B: "Bitola", C: "Prilep", D: "Kumanovo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 224, soru: "Bosna-Hersek'in başkenti neresidir?", secenekler: { A: "Tuzla", B: "Banja Luka", C: "Zenica", D: "Saraybosna" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 225, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Tiran", B: "Elbasan", C: "Vlorë", D: "Durrës" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 226, soru: "Moldova'nın başkenti neresidir?", secenekler: { A: "Bălți", B: "Tiraspol", C: "Kişinev", D: "Bender" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 227, soru: "Ermenistan'ın başkenti neresidir?", secenekler: { A: "Hrazdan", B: "Gümrü", C: "Erivan", D: "Vanadzor" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 228, soru: "Gürcistan'ın başkenti neresidir?", secenekler: { A: "Batum", B: "Rustavi", C: "Tiflis", D: "Kutaisi" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 229, soru: "Azerbaycan'ın başkenti neresidir?", secenekler: { A: "Bakü", B: "Sumgayıt", C: "Gence", D: "Mingeçevir" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 230, soru: "Türkmenistan'ın başkenti neresidir?", secenekler: { A: "Daşoğuz", B: "Türkmenabat", C: "Merv", D: "Aşkabat" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 231, soru: "Özbekistan'ın başkenti neresidir?", secenekler: { A: "Taşkent", B: "Nemengan", C: "Buhara", D: "Semerkant" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 232, soru: "Kırgızistan'ın başkenti neresidir?", secenekler: { A: "Karakol", B: "Oş", C: "Bişkek", D: "Celal-Abad" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 233, soru: "Tacikistan'ın başkenti neresidir?", secenekler: { A: "Hucend", B: "Duşanbe", C: "Kulob", D: "Bohtar" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 234, soru: "Kazakistan'ın başkenti neresidir?", secenekler: { A: "Çimkent", B: "Almatı", C: "Astana", D: "Karagandı" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 235, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Erdenet", B: "Çoybalsan", C: "Darhan", D: "Ulanbatur" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 236, soru: "Kuzey Kore'nin başkenti neresidir?", secenekler: { A: "Chongjin", B: "Hamhung", C: "Pyongyang", D: "Nampo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 237, soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Daegu", B: "Busan", C: "Incheon", D: "Seul" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 238, soru: "Japonya'nın başkenti neresidir?", secenekler: { A: "Nagoya", B: "Yokohama", C: "Tokyo", D: "Osaka" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 239, soru: "Tayvan'ın başkenti neresidir?", secenekler: { A: "Tainan", B: "Taipei", C: "Taichung", D: "Kaohsiung" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 240, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Manila", B: "Davao City", C: "Quezon City", D: "Cebu City" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 241, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Ho Chi Minh City", B: "Hanoi", C: "Hai Phong", D: "Da Nang" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 242, soru: "Kamboçya'nın başkenti neresidir?", secenekler: { A: "Battambang", B: "Sihanoukville", C: "Siem Reap", D: "Phnom Penh" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 243, soru: "Laos'un başkenti neresidir?", secenekler: { A: "Pakse", B: "Vientiane", C: "Luang Prabang", D: "Savannakhet" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 244, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Nakhon Ratchasima", B: "Nonthaburi", C: "Bangkok", D: "Chiang Mai" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 245, soru: "Myanmar'ın başkenti neresidir?", secenekler: { A: "Bago", B: "Yangon", C: "Naypyidaw", D: "Mandalay" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 246, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "George Town", B: "Shah Alam", C: "Kuala Lumpur", D: "Ipoh" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 247, soru: "Singapur'un başkenti neresidir?", secenekler: { A: "Bedok", B: "Jurong", C: "Tampines", D: "Singapur" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 248, soru: "Brunei'nin başkenti neresidir?", secenekler: { A: "Seria", B: "Bandar Seri Begawan", C: "Tutong", D: "Kuala Belait" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 249, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Medan", B: "Bandung", C: "Surabaya", D: "Cakarta" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 250, soru: "Doğu Timor'un başkenti neresidir?", secenekler: { A: "Lospalos", B: "Dili", C: "Baucau", D: "Ermera" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 251, soru: "Sri Lanka'nın ticari başkenti neresidir?", secenekler: { A: "Kolombo", B: "Sri Jayawardenepura Kotte", C: "Kandy", D: "Galle" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 252, soru: "Maldivler'in başkenti neresidir?", secenekler: { A: "Male", B: "Addu City", C: "Fuvahmulah", D: "Kulhudhuffushi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 253, soru: "Hindistan'ın başkenti neresidir?", secenekler: { A: "Bangalor", B: "Kalküta", C: "Yeni Delhi", D: "Mumbai" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 254, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "İslamabad", B: "Faysalabad", C: "Lahor", D: "Karaçi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 255, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Chittagong", B: "Dakka", C: "Khulna", D: "Rajshahi" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 256, soru: "Bhutan'ın başkenti neresidir?", secenekler: { A: "Phuntsholing", B: "Thimphu", C: "Samdrup Jongkhar", D: "Punakha" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 257, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Katmandu", B: "Pokhara", C: "Biratnagar", D: "Lalitpur" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 258, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Mezar-ı Şerif", B: "Kabil", C: "Herat", D: "Kandahar" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 259, soru: "İran'ın başkenti neresidir?", secenekler: { A: "Meşhed", B: "Tebriz", C: "Tahran", D: "İsfahan" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 260, soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Basra", B: "Bağdat", C: "Musul", D: "Erbil" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 261, soru: "Suriye'nin başkenti neresidir?", secenekler: { A: "Şam", B: "Humus", C: "Lazkiye", D: "Halep" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 262, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Beyrut", B: "Sayda", C: "Zahle", D: "Trablusşam" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 263, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Rusayfe", B: "İrbid", C: "Zarka", D: "Amman" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 264, soru: "İsrail'in başkenti neresidir?", secenekler: { A: "Kudüs", B: "Hayfa", C: "Rişon LeTsiyon", D: "Tel Aviv" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 265, soru: "Filistin'in ilan edilen başkenti neresidir?", secenekler: { A: "Kudüs", B: "Ramallah", C: "Nablus", D: "Gazze" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 266, soru: "Suudi Arabistan'ın başkenti neresidir?", secenekler: { A: "Mekke", B: "Medine", C: "Riyad", D: "Cidde" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 267, soru: "Yemen'in başkenti neresidir?", secenekler: { A: "Aden", B: "Taiz", C: "Hudeyde", D: "Sana" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 268, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Bawshar", B: "Maskat", C: "Seeb", D: "Salalah" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 269, soru: "Birleşik Arap Emirlikleri'nin başkenti neresidir?", secenekler: { A: "Dubai", B: "Şarika", C: "Abu Dabi", D: "Al Ain" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 270, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Umm Salal Muhammed", B: "Al Rayyan", C: "Al Vakrah", D: "Doha" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 271, soru: "Bahreyn'in başkenti neresidir?", secenekler: { A: "Hamad Town", B: "Manama", C: "Al Muharraq", D: "Ar Rifa'" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 272, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Al Ahmadi", B: "Kuveyt", C: "As Salimiyah", D: "Hawalli" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 273, soru: "Mısır'ın başkenti neresidir?", secenekler: { A: "İskenderiye", B: "Gize", C: "Kahire", D: "Şubra el-Hayma" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 274, soru: "Libya'nın başkenti neresidir?", secenekler: { A: "Bayda", B: "Bingazi", C: "Misrata", D: "Trablus" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 275, soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Susa", B: "Safakes", C: "Ettadhamen", D: "Tunus" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 276, soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Cezayir", B: "Annâbe", C: "Oran", D: "Konstantin" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 277, soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Rabat", B: "Fes", C: "Tanca", D: "Kazablanka" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 278, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Hartum Bahri", B: "Nyala", C: "Hartum", D: "Omdurman" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 279, soru: "Güney Sudan'ın başkenti neresidir?", secenekler: { A: "Yei", B: "Malakal", C: "Wau", D: "Cuba" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 280, soru: "Etiyopya'nın başkenti neresidir?", secenekler: { A: "Addis Ababa", B: "Dire Dawa", C: "Gondar", D: "Adama" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 281, soru: "Eritre'nin başkenti neresidir?", secenekler: { A: "Teseney", B: "Keren", C: "Mendefera", D: "Asmara" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 282, soru: "Cibuti'nin başkenti neresidir?", secenekler: { A: "Dikhil", B: "Tadjoura", C: "Cibuti", D: "Ali Sabieh" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 283, soru: "Somali'nin başkenti neresidir?", secenekler: { A: "Mogadişu", B: "Kismayo", C: "Berbera", D: "Hargeisa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 284, soru: "Kenya'nın başkenti neresidir?", secenekler: { A: "Nakuru", B: "Kisumu", C: "Nairobi", D: "Mombasa" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 285, soru: "Uganda'nın başkenti neresidir?", secenekler: { A: "Nansana", B: "Kira", C: "Makindye Ssabagabo", D: "Kampala" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 286, soru: "Ruanda'nın başkenti neresidir?", secenekler: { A: "Gisenyi", B: "Kigali", C: "Gitarama", D: "Butare" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 287, soru: "Burundi'nin başkenti neresidir?", secenekler: { A: "Gitega", B: "Muyinga", C: "Bujumbura", D: "Ngozi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 288, soru: "Tanzanya'nın başkenti neresidir?", secenekler: { A: "Mwanza", B: "Darüsselam", C: "Arusha", D: "Dodoma" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 289, soru: "Malavi'nin başkenti neresidir?", secenekler: { A: "Lilongwe", B: "Blantyre", C: "Mzuzu", D: "Zomba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 290, soru: "Mozambik'in başkenti neresidir?", secenekler: { A: "Maputo", B: "Beira", C: "Matola", D: "Nampula" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 291, soru: "Zambiya'nın başkenti neresidir?", secenekler: { A: "Lusaka", B: "Ndola", C: "Kitwe", D: "Kabwe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 292, soru: "Zimbabve'nin başkenti neresidir?", secenekler: { A: "Harare", B: "Bulawayo", C: "Mutare", D: "Chitungwiza" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 293, soru: "Botsvana'nın başkenti neresidir?", secenekler: { A: "Selibe Phikwe", B: "Gaborone", C: "Francistown", D: "Molepolole" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 294, soru: "Namibya'nın başkenti neresidir?", secenekler: { A: "Walvis Bay", B: "Rundu", C: "Swakopmund", D: "Windhoek" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 295, soru: "Güney Afrika Cumhuriyeti'nin yasama başkenti neresidir?", secenekler: { A: "Johannesburg", B: "Bloemfontein", C: "Cape Town", D: "Pretoria" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 296, soru: "Lesotho'nun başkenti neresidir?", secenekler: { A: "Teyateyaneng", B: "Mafeteng", C: "Maseru", D: "Hlotse" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 297, soru: "Esvatini'nin yasama başkenti neresidir?", secenekler: { A: "Big Bend", B: "Manzini", C: "Lobamba", D: "Mbabane" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 298, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Fianarantsoa", B: "Toamasina", C: "Antananarivo", D: "Antsirabe" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 299, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Vacoas-Phoenix", B: "Curepipe", C: "Port Louis", D: "Beau Bassin-Rose Hill" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 300, soru: "Seyşeller'in başkenti neresidir?", secenekler: { A: "Bel Ombre", B: "Victoria", C: "Anse Boileau", D: "De Quincey" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 301, soru: "Komorlar'ın başkenti neresidir?", secenekler: { A: "Fomboni", B: "Mutsamudu", C: "Domoni", D: "Moroni" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 302, soru: "Angola'nın başkenti neresidir?", secenekler: { A: "Lobito", B: "Huambo", C: "Luanda", D: "Benguela" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 303, soru: "Gabon'un başkenti neresidir?", secenekler: { A: "Libreville", B: "Franceville", C: "Oyem", D: "Port-Gentil" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 304, soru: "Ekvator Ginesi'nin başkenti neresidir?", secenekler: { A: "Aconibe", B: "Bata", C: "Ebebiyín", D: "Malabo" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 305, soru: "Sao Tome ve Principe'nin başkenti neresidir?", secenekler: { A: "Santo Amaro", B: "Santana", C: "Neves", D: "Sao Tome" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 306, soru: "Kamerun'un başkenti neresidir?", secenekler: { A: "Garoua", B: "Douala", C: "Bamenda", D: "Yaoundé" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 307, soru: "Orta Afrika Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Bangui", B: "Carnot", C: "Bimbo", D: "Berberati" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 308, soru: "Çad'ın başkenti neresidir?", secenekler: { A: "Abéché", B: "N'Djamena", C: "Moundou", D: "Sarh" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 309, soru: "Nijer'in başkenti neresidir?", secenekler: { A: "Maradi", B: "Niamey", C: "Tahoua", D: "Zinder" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 310, soru: "Nijerya'nın başkenti neresidir?", secenekler: { A: "Abuja", B: "Kano", C: "Ibadan", D: "Lagos" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 311, soru: "Benin'in başkenti neresidir?", secenekler: { A: "Abomey-Calavi", B: "Porto-Novo", C: "Djaugou", D: "Cotonou" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 312, soru: "Togo'nın başkenti neresidir?", secenekler: { A: "Atakpamé", B: "Sokodé", C: "Lomé", D: "Kara" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 313, soru: "Gana'nın başkenti neresidir?", secenekler: { A: "Ashiaman", B: "Tamale", C: "Akra", D: "Kumasi" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 314, soru: "Fildişi Sahili'nin başkenti neresidir?", secenekler: { A: "Daloa", B: "Bouaké", C: "Yamoussoukro", D: "Abidjan" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 315, soru: "Liberya'nın başkenti neresidir?", secenekler: { A: "Monrovia", B: "Gbarnga", C: "Kakata", D: "Bensonville" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 316, soru: "Sierra Leone'nin başkenti neresidir?", secenekler: { A: "Bo", B: "Kenema", C: "Freetown", D: "Makeni" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 317, soru: "Gine'nin başkenti neresidir?", secenekler: { A: "Kankan", B: "Nzérékoré", C: "Konakri", D: "Kindia" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 318, soru: "Gine-Bissau'nun başkenti neresidir?", secenekler: { A: "Bissorã", B: "Gabú", C: "Bissau", D: "Bafatá" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 319, soru: "Gambiya'nın başkenti neresidir?", secenekler: { A: "Serekunda", B: "Banjul", C: "Brikama", D: "Bakau" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 320, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Touba", B: "Guediawaye", C: "Pikine", D: "Dakar" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 321, soru: "Mali'nin başkenti neresidir?", secenekler: { A: "Sikasso", B: "Mopti", C: "Bamako", D: "Koutiala" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 322, soru: "Moritanya'nın başkenti neresidir?", secenekler: { A: "Nuakşot", B: "Kiffa", C: "Nuadhibou", D: "M'Bout" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 323, soru: "Yeşil Burun Adaları'nın başkenti neresidir?", secenekler: { A: "Praia", B: "Cova Figueira", C: "Mindelo", D: "Santa Maria" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 324, soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Ecatepec", B: "Guadalajara", C: "Meksiko", D: "Puebla" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 325, soru: "Guatemala'nın başkenti neresidir?", secenekler: { A: "Villa Nueva", B: "Quetzaltenango", C: "Mixco", D: "Guatemala" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 326, soru: "Belize'nin başkenti neresidir?", secenekler: { A: "Orange Walk Town", B: "San Ignacio", C: "Belmopan", D: "Belize City" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 327, soru: "El Salvador'un başkenti neresidir?", secenekler: { A: "Santa Tecla", B: "Santa Ana", C: "San Miguel", D: "San Salvador" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 328, soru: "Honduras'ın başkenti neresidir?", secenekler: { A: "Choloma", B: "San Pedro Sula", C: "La Ceiba", D: "Tegucigalpa" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 329, soru: "Nikaragua'nın başkenti neresidir?", secenekler: { A: "Chinandega", B: "Managua", C: "Masaya", D: "Leon" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 330, soru: "Kosta Rika'nın başkenti neresidir?", secenekler: { A: "Heredia", B: "San Jose", C: "Alajuela", D: "Cartago" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 331, soru: "Panama'nın başkenti neresidir?", secenekler: { A: "Tocumen", B: "Panama", C: "San Miguelito", D: "David" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 332, soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Havana", B: "Santiago de Cuba", C: "Camagüey", D: "Holguín" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 333, soru: "Bahamalar'ın başkenti neresidir?", secenekler: { A: "Nassau", B: "West End", C: "Freeport", D: "Lucaya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 334, soru: "Jamaika'nın başkenti neresidir?", secenekler: { A: "Portmore", B: "Spanish Town", C: "Montego Bay", D: "Kingston" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 335, soru: "Haiti'nin başkenti neresidir?", secenekler: { A: "Port-au-Prince", B: "Carrefour", C: "Delmas", D: "Pétion-Ville" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 336, soru: "Dominik Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Santo Domingo Oeste", B: "Santo Domingo Este", C: "Santiago de los Caballeros", D: "Santo Domingo" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 337, soru: "Saint Kitts ve Nevis'in başkenti neresidir?", secenekler: { A: "Saint Paul's", B: "Basseterre", C: "Fig Tree", D: "Market Shop" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 338, soru: "Antigua ve Barbuda'nın başkenti neresidir?", secenekler: { A: "St. John's", B: "Potters Village", C: "Liberta", D: "All Saints" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 339, soru: "Dominika'nın başkenti neresidir?", secenekler: { A: "Roseau", B: "Marigot", C: "Portsmouth", D: "Berekua" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 340, soru: "Saint Lucia'nın başkenti neresidir?", secenekler: { A: "Castries", B: "Bexon", C: "Ciceron", D: "Babonneau" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 341, soru: "Saint Vincent ve Grenadinler'in başkenti neresidir?", secenekler: { A: "Byera Hill", B: "Kingstown", C: "Georgetown", D: "Biabou" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 342, soru: "Barbados'un başkenti neresidir?", secenekler: { A: "Bridgetown", B: "Bathsheba", C: "Speightstown", D: "Oistins" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 343, soru: "Grenada'nın başkenti neresidir?", secenekler: { A: "Grenville", B: "Victoria", C: "Gouyave", D: "St. George's" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 344, soru: "Trinidad ve Tobago'nun başkenti neresidir?", secenekler: { A: "San Fernando", B: "Chaguanas", C: "Port of Spain", D: "Rio Claro" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 345, soru: "Kolombiya'nın başkenti neresidir?", secenekler: { A: "Barranquilla", B: "Bogota", C: "Medellín", D: "Cali" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 346, soru: "Venezuela'nın başkenti neresidir?", secenekler: { A: "Valencia", B: "Barquisimeto", C: "Karakas", D: "Maracaibo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 347, soru: "Guyana'nın başkenti neresidir?", secenekler: { A: "Anna Regina", B: "New Amsterdam", C: "Linden", D: "Georgetown" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 348, soru: "Surinam'ın başkenti neresidir?", secenekler: { A: "Moengo", B: "Paramaribo", C: "Nieuw Nickerie", D: "Lelydorp" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 349, soru: "Ekvador'un başkenti neresidir?", secenekler: { A: "Guayaquil", B: "Cuenca", C: "Santo Domingo", D: "Quito" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 350, soru: "Peru'nun başkenti neresidir?", secenekler: { A: "Chiclayo", B: "Arequipa", C: "Lima", D: "Trujillo" }, dogruCevap: "C" }, 
    // 351-449: Eklenen Yeni Başkent Soruları
    { kategori: "Başkent", seviye: 351, soru: "Bolivya'nın idari başkenti neresidir?", secenekler: { A: "Sucre", B: "Cochabamba", C: "La Paz", D: "Santa Cruz" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 352, soru: "Bolivya'nın resmi başkenti neresidir?", secenekler: { A: "Sucre", B: "La Paz", C: "Potosi", D: "Oruro" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 353, soru: "Paraguay'ın başkenti neresidir?", secenekler: { A: "Encarnacion", B: "Ciudad del Este", C: "Luque", D: "Asuncion" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 354, soru: "Uruguay'ın başkenti neresidir?", secenekler: { A: "Montevideo", B: "Paysandu", C: "Salto", D: "Las Piedras" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 355, soru: "Şili'nin başkenti neresidir?", secenekler: { A: "Santiago", B: "Antofagasta", C: "Concepcion", D: "Valparaiso" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 356, soru: "İzlanda'nın başkenti neresidir?", secenekler: { A: "Reykjavik", B: "Akureyri", C: "Kopavogur", D: "Hafnarfjörður" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 357, soru: "İrlanda'nın başkenti neresidir?", secenekler: { A: "Cork", B: "Limerick", C: "Dublin", D: "Galway" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 358, soru: "Lüksemburg'un başkenti neresidir?", secenekler: { A: "Lüksemburg", B: "Dudelange", C: "Esch-sur-Alzette", D: "Differdange" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 359, soru: "Monako'nun başkenti neresidir?", secenekler: { A: "Monte Carlo", B: "La Condamine", C: "Monako", D: "Fontvieille" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 360, soru: "Vatikan'ın başkenti neresidir?", secenekler: { A: "Vatikan", B: "Roma", C: "Napoli", D: "Milano" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 361, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Salmiya", B: "Kuveyt", C: "Jahra", D: "Fahaheel" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 362, soru: "Yemen'in geçici başkenti neresidir?", secenekler: { A: "Sana", B: "Mukalla", C: "Aden", D: "Taiz" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 363, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Sohar", B: "Nizwa", C: "Maskat", D: "Salalah" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 364, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Al Khor", B: "Al Wakrah", C: "Doha", D: "Madinat ash Shamal" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 365, soru: "Bahreyn'in başkenti neresidir?", secenekler: { A: "Hamad", B: "Riffa", C: "Muharrak", D: "Manama" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 366, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Sidon", B: "Tyre", C: "Trablusşam", D: "Beyrut" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 367, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Amman", B: "Zarka", C: "İrbid", D: "Akabe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 368, soru: "Suriye'nin başkenti neresidir?", secenekler: { A: "Şam", B: "Humus", C: "Lazkiye", D: "Halep" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 369, soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Musul", B: "Bağdat", C: "Erbil", D: "Basra" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 370, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Kabil", B: "Herat", C: "Mezar-ı Şerif", D: "Kandahar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 371, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "Peşaver", B: "Karaçi", C: "İslamabad", D: "Lahor" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 372, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Lalitpur", B: "Pokhara", C: "Katmandu", D: "Biratnagar" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 373, soru: "Bhutan'ın başkenti neresidir?", secenekler: { A: "Paro", B: "Phuntsholing", C: "Thimphu", D: "Punakha" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 374, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Sylhet", B: "Chittagong", C: "Khulna", D: "Dakka" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 375, soru: "Sri Lanka'nın resmi başkenti neresidir?", secenekler: { A: "Sri Jayawardenepura Kotte", B: "Kandy", C: "Kolombo", D: "Galle" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 376, soru: "Maldivler'in başkenti neresidir?", secenekler: { A: "Hulhumale", B: "Male", C: "Gan", D: "Maafushi" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 377, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Darhan", B: "Ulanbatur", C: "Mörön", D: "Erdenet" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 378, soru: "Kuzey Kore'nin başkenti neresidir?", secenekler: { A: "Kaesong", B: "Nampo", C: "Pyongyang", D: "Wonsan" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 379, soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Incheon", B: "Busan", C: "Seul", D: "Daegu" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 380, soru: "Tayvan'ın başkenti neresidir?", secenekler: { A: "Taipei", B: "Kaohsiung", C: "Taichung", D: "Tainan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 381, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Ho Chi Minh City", B: "Hanoi", C: "Da Nang", D: "Hue" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 382, soru: "Laos'un başkenti neresidir?", secenekler: { A: "Luang Prabang", B: "Savannakhet", C: "Vientiane", D: "Pakse" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 383, soru: "Kamboçya'nın başkenti neresidir?", secenekler: { A: "Siem Reap", B: "Phnom Penh", C: "Battambang", D: "Sihanoukville" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 384, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Bangkok", B: "Chiang Mai", C: "Pattaya", D: "Phuket" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 385, soru: "Myanmar'ın (Burma) başkenti neresidir?", secenekler: { A: "Yangon", B: "Mandalay", C: "Naypyidaw", D: "Bago" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 386, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "Johor Bahru", B: "George Town", C: "Kuala Lumpur", D: "Putrajaya" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 387, soru: "Singapur'un başkenti neresidir?", secenekler: { A: "Sentosa", B: "Changi", C: "Jurong", D: "Singapur" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 388, soru: "Brunei'nin başkenti neresidir?", secenekler: { A: "Kuala Belait", B: "Seria", C: "Tutong", D: "Bandar Seri Begawan" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 389, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Surabaya", B: "Bali", C: "Cakarta", D: "Bandung" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 390, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Quezon City", B: "Manila", C: "Davao City", D: "Cebu City" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 391, soru: "Papua Yeni Gine'nin başkenti neresidir?", secenekler: { A: "Madang", B: "Lae", C: "Port Moresby", D: "Goroka" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 392, soru: "Yeni Zelanda'nın başkenti neresidir?", secenekler: { A: "Hamilton", B: "Christchurch", C: "Wellington", D: "Auckland" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 393, soru: "Fiji'nin başkenti neresidir?", secenekler: { A: "Labasa", B: "Lautoka", C: "Nadi", D: "Suva" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 394, soru: "Samoa'nın başkenti neresidir?", secenekler: { A: "Vailele", B: "Vaitele", C: "Apia", D: "Faleasiu" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 395, soru: "Tonga'nın başkenti neresidir?", secenekler: { A: "Vaini", B: "Neiafu", C: "Haveluloto", D: "Nuku'alofa" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 396, soru: "Vanuatu'nun başkenti neresidir?", secenekler: { A: "Port Vila", B: "Luganville", C: "Port Olry", D: "Norsup" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 397, soru: "Solomon Adaları'nın başkenti neresidir?", secenekler: { A: "Honiara", B: "Auki", C: "Tulagi", D: "Gizo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 398, soru: "Mikronezya'nın başkenti neresidir?", secenekler: { A: "Tol", B: "Kolonia", C: "Palikir", D: "Weno" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 399, soru: "Palau'nın başkenti neresidir?", secenekler: { A: "Meyuns", B: "Koror", C: "Ngerulmud", D: "Airai" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 400, soru: "Marshall Adaları'nın başkenti neresidir?", secenekler: { A: "Majuro", B: "Jabor", C: "Arno", D: "Ebeye" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 401, soru: "Kiribati'nin başkenti neresidir?", secenekler: { A: "Abaiang", B: "Betio", C: "Bairiki", D: "Güney Tarava" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 402, soru: "Nauru'nun hükümet merkezi neresidir?", secenekler: { A: "Meneng", B: "Aiwo", C: "Denigomodu", D: "Yaren" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 403, soru: "Tuvalu'nun başkenti neresidir?", secenekler: { A: "Vaitupu", B: "Nanumea", C: "Niutao", D: "Funafuti" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 404, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Mahajanga", B: "Antananarivo", C: "Toamasina", D: "Antsirabe" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 405, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Port Louis", B: "Beau Bassin", C: "Curepipe", D: "Vacoas" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 406, soru: "Seyşeller'in başkenti neresidir?", secenekler: { A: "Cascade", B: "Anse Royale", C: "Victoria", D: "Beau Vallon" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 407, soru: "Komorlar'ın başkenti neresidir?", secenekler: { A: "Domoni", B: "Fomboni", C: "Moroni", D: "Mutsamudu" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 408, soru: "Cape Verde'nin (Yeşil Burun) başkenti neresidir?", secenekler: { A: "Mindelo", B: "Santa Maria", C: "Espargos", D: "Praia" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 409, soru: "Sao Tome ve Principe'nin başkenti neresidir?", secenekler: { A: "Santana", B: "Sao Tome", C: "Santo Amaro", D: "Neves" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 410, soru: "Gambiya'nın başkenti neresidir?", secenekler: { A: "Banjul", B: "Serekunda", C: "Bakau", D: "Brikama" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 411, soru: "Gine-Bissau'nun başkenti neresidir?", secenekler: { A: "Catio", B: "Gabu", C: "Bissau", D: "Bafata" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 412, soru: "Sierra Leone'nin başkenti neresidir?", secenekler: { A: "Kenema", B: "Freetown", C: "Bo", D: "Makeni" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 413, soru: "Liberya'nın başkenti neresidir?", secenekler: { A: "Gbarnga", B: "Buchanan", C: "Monrovia", D: "Kakata" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 414, soru: "Fildişi Sahili'nin başkenti neresidir?", secenekler: { A: "Abidjan", B: "Bouake", C: "Yamoussoukro", D: "Daloa" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 415, soru: "Burkina Faso'nun başkenti neresidir?", secenekler: { A: "Ouagadougou", B: "Koudougou", C: "Bobo-Dioulasso", D: "Ouahigouya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 416, soru: "Togo'nun başkenti neresidir?", secenekler: { A: "Atakpame", B: "Kara", C: "Sokode", D: "Lome" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 417, soru: "Benin'in başkenti neresidir?", secenekler: { A: "Abomey-Calavi", B: "Cotonou", C: "Porto-Novo", D: "Parakou" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 418, soru: "Ekvator Ginesi'nin başkenti neresidir?", secenekler: { A: "Mongomo", B: "Bata", C: "Ebebiyin", D: "Malabo" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 419, soru: "Gabon'un başkenti neresidir?", secenekler: { A: "Port-Gentil", B: "Oyem", C: "Franceville", D: "Libreville" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 420, soru: "Kongo Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Brazzaville", B: "Pointe-Noire", C: "Madingou", D: "Dolisie" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 421, soru: "Orta Afrika Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Carnot", B: "Bangui", C: "Berberati", D: "Bimbo" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 422, soru: "Çad'ın başkenti neresidir?", secenekler: { A: "Moundou", B: "Abeche", C: "N'Djamena", D: "Sarh" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 423, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Hartum Bahri", B: "Hartum", C: "Nyala", D: "Omdurman" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 424, soru: "Güney Sudan'ın başkenti neresidir?", secenekler: { A: "Wau", B: "Yei", C: "Cuba", D: "Malakal" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 425, soru: "Eritre'nin başkenti neresidir?", secenekler: { A: "Keren", B: "Massawa", C: "Asmara", D: "Assab" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 426, soru: "Cibuti'nın başkenti neresidir?", secenekler: { A: "Ali Sabieh", B: "Cibuti", C: "Dikhil", D: "Tadjoura" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 427, soru: "Somali'nin başkenti neresidir?", secenekler: { A: "Hargeisa", B: "Berbera", C: "Kismayo", D: "Mogadişu" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 428, soru: "Uganda'nın başkenti neresidir?", secenekler: { A: "Kampala", B: "Jinja", C: "Mbarara", D: "Entebbe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 429, soru: "Ruanda'nın başkenti neresidir?", secenekler: { A: "Butare", B: "Kigali", C: "Gitarama", D: "Gisenyi" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 330, soru: "Burundi'nin başkenti neresidir?", secenekler: { A: "Muyinga", B: "Ngozi", C: "Gitega", D: "Bujumbura" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 431, soru: "Malavi'nin başkenti neresidir?", secenekler: { A: "Blantyre", B: "Mzuzu", C: "Zomba", D: "Lilongwe" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 432, soru: "Zambiya'nın başkenti neresidir?", secenekler: { A: "Kitwe", B: "Livingstone", C: "Ndola", D: "Lusaka" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 433, soru: "Zimbabve'nin başkenti neresidir?", secenekler: { A: "Gweru", B: "Harare", C: "Mutare", D: "Bulawayo" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 434, soru: "Botsvana'nın başkenti neresidir?", secenekler: { A: "Francistown", B: "Maun", C: "Molepolole", D: "Gaborone" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 435, soru: "Namibya'nın başkenti neresidir?", secenekler: { A: "Rundu", B: "Windhoek", C: "Walvis Bay", D: "Swakopmund" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 436, soru: "Lesotho'nun başkenti neresidir?", secenekler: { A: "Hlotse", B: "Maseru", C: "Mafeteng", D: "Teyateyaneng" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 437, soru: "Esvatini'nin (Svaziland) başkenti neresidir?", secenekler: { A: "Big Bend", B: "Manzini", C: "Mbabane", D: "Lobamba" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 438, soru: "Moritanya'nın başkenti neresidir?", secenekler: { A: "Nuakşot", B: "Kiffa", C: "Rosso", D: "Nuadhibou" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 439, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tallinn", B: "Tartu", C: "Pärnu", D: "Narva" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 440, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Riga", B: "Daugavpils", C: "Liepaja", D: "Jelgava" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 441, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Kaunas", B: "Siauliai", C: "Vilnius", D: "Klaipeda" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 442, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Zilina", B: "Kosice", C: "Presov", D: "Bratislava" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 443, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Maribor", B: "Ljubljana", C: "Celje", D: "Kranj" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 444, soru: "Hırvatistan'ın başkenti neresidir?", secenekler: { A: "Osijek", B: "Zagreb", C: "Split", D: "Rijeka" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 445, soru: "Bosna Hersek'in başkenti neresidir?", secenekler: { A: "Zenica", B: "Saraybosna", C: "Tuzla", D: "Banja Luka" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 446, soru: "Sırbistan'ın başkenti neresidir?", secenekler: { A: "Kragujevac", B: "Belgrad", C: "Novi Sad", D: "Niş" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 447, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Nikšić", B: "Çetine", C: "Pljevlja", D: "Podgorica" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 448, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Durrës", B: "Tiran", C: "Elbasan", D: "Vlorë" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 449, soru: "Makedonya'nın (Kuzey Makedonya) başkenti neresidir?", secenekler: { A: "Bitola", B: "Üsküp", C: "Kumanovo", D: "Prilep" }, dogruCevap: "B" }
 
 
 
);
