window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Klasik ve Kolay Bilmeceler
    { seviye: 1, kategori: "Bilmece", soru: "Şehirleri var ama evleri yok. Dağları var ama ağaçları yok. Suları var ama balıkları yok. Bu nedir?", secenekler: { A: "Çöl", B: "Harita", C: "Küresel ısınma", D: "Resim" }, dogruCevap: "B" },
    { seviye: 1, kategori: "Bilmece", soru: "Ben giderim o gider, üstümde gölge eder.", secenekler: { A: "Şapka", B: "Şemsiye", C: "Bulut", D: "Güneş" }, dogruCevap: "B" },
    { seviye: 1, kategori: "Bilmece", soru: "Pazardan aldım bir tane, eve geldim bin tane.", secenekler: { A: "Mısır", B: "Pirinç", C: "Nar", D: "Üzüm" }, dogruCevap: "C" },
    { seviye: 1, kategori: "Bilmece", soru: "Sesi var canı yok, konuşur ağzı yok.", secenekler: { A: "Yankı", B: "Rüzgar", C: "Telefon", D: "Radyo" }, dogruCevap: "A" },
    { seviye: 2, kategori: "Bilmece", soru: "Yer altında yağlı kayış.", secenekler: { A: "Solucan", B: "Kemer", C: "Yılan", D: "Hortum" }, dogruCevap: "C" },
    { seviye: 2, kategori: "Bilmece", soru: "İki camlı pencere, bakıp durur her yere.", secenekler: { A: "Dürbün", B: "Gözlük", C: "Göz", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 2, kategori: "Bilmece", soru: "İncecik beli, elimdedir dili.", secenekler: { A: "Kalem", B: "Zil", C: "Kaşık", D: "Bardak" }, dogruCevap: "A" },
    { seviye: 2, kategori: "Bilmece", soru: "Kolu var eli yok, karnı yarık karnı yok.", secenekler: { A: "Ceket", B: "Yelek", C: "Gömlek", D: "Pantolon" }, dogruCevap: "A" },
    { seviye: 3, kategori: "Bilmece", soru: "Bir küçücük fıçıcık, içi dolu turşucuk.", secenekler: { A: "Limon", B: "Mandalina", C: "Limon", D: "Zeytin" }, dogruCevap: "B" },
    { seviye: 3, kategori: "Bilmece", soru: "Ayakları var yürüyemez, dili var konuşamaz.", secenekler: { A: "Ayakkabı", B: "Sandalye", C: "Araba", D: "Masa" }, dogruCevap: "A" },
    { seviye: 3, kategori: "Bilmece", soru: "Gökten iner bir avuç, tadı şekerden tatlı.", secenekler: { A: "Dut", B: "Yağmur", C: "Kar", D: "Dolu" }, dogruCevap: "A" },
    { seviye: 4, kategori: "Bilmece", soru: "Yatınca yatar, kalkınca kalkar.", secenekler: { A: "Ayakkabı", B: "Parmak", C: "Yastık", D: "Yorgan" }, dogruCevap: "B" },
    { seviye: 4, kategori: "Bilmece", soru: "Hiç ağzı yok ama her dile cevap verir.", secenekler: { A: "Kağıt", B: "Kitap", C: "Yankı", D: "Ayna" }, dogruCevap: "C" },
    { seviye: 4, kategori: "Bilmece", soru: "Bir tarlam var, beyaz gül açar.", secenekler: { A: "Gökyüzü / Yıldızlar", B: "Bahçe / Kar", C: "Kağıt / Yazı", D: "Deniz / Köpük" }, dogruCevap: "B" },
    { seviye: 5, kategori: "Bilmece", soru: "Dışı var içi yok, dayak yer suçu yok.", secenekler: { A: "Davul", B: "Yastık", C: "Top", D: "Halı" }, dogruCevap: "A" },
    { seviye: 5, kategori: "Bilmece", soru: "Geldi mi gitmez, gitti mi gelmez.", secenekler: { A: "Sağlık", B: "Zaman", C: "Gençlik", D: "Misafir" }, dogruCevap: "C" },
    { seviye: 5, kategori: "Bilmece", soru: "Ağzı var dili yok, nefesi var canı yok.", secenekler: { A: "Düdük", B: "Ney", C: "Kavala", D: "Balon" }, dogruCevap: "D" },
    { seviye: 6, kategori: "Bilmece", soru: "Kapağı var kitap değil, kulu var kapı değil.", secenekler: { A: "Göz", B: "Çanta", C: "Tencere", D: "Dolap" }, dogruCevap: "A" },
    { seviye: 6, kategori: "Bilmece", soru: "Daldan dala atlar, kuyruğuyla oynar.", secenekler: { A: "Sincap", B: "Kedi", C: "Maymun", D: "Kuş" }, dogruCevap: "C" },
    { seviye: 6, kategori: "Bilmece", soru: "Bir ağacı oymuşlar, içine dünyayı koymuşlar.", secenekler: { A: "Sandık", B: "Radyo", C: "Gemi", D: "Televizyon" }, dogruCevap: "B" },
    { seviye: 7, kategori: "Bilmece", soru: "Kanadı var uçamaz, ağzı var konuşamaz.", secenekler: { A: "Balık", B: "Penguen", C: "Uçak", D: "Tavuk" }, dogruCevap: "A" },
    { seviye: 7, kategori: "Bilmece", soru: "Gökyüzünde gördüm bir köprü, rengi var yedi türlü.", secenekler: { A: "Gökkuşağı", B: "Bulut", C: "Uçak", D: "Yıldız" }, dogruCevap: "A" },
    { seviye: 7, kategori: "Bilmece", soru: "Uzun uzun uzarlar, her yıl kışın azalırlar.", secenekler: { A: "Geceler", B: "Yollar", C: "Saçlar", D: "Günler" }, dogruCevap: "D" },
    { seviye: 8, kategori: "Bilmece", soru: "Canı var kanı yok, sesi var dili yok.", secenekler: { A: "Arı", B: "Balık", C: "Kelebek", D: "Sinek" }, dogruCevap: "D" },
    { seviye: 8, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Dolma kalem", B: "Kontrol kalemi", C: "Tükenmez kalem", D: "Kurşun kalem" }, dogruCevap: "B" },

    // 26-100: Karışık, Zeka ve Kelime Oyunlu Bilmeceler
    { seviye: 26, kategori: "Bilmece", soru: "Karşıdan baktım hiç yok, yanına gittim pek çok.", secenekler: { A: "Karınca", B: "Kum", C: "Ağaç", D: "Çiçek" }, dogruCevap: "A" },
    { seviye: 27, kategori: "Bilmece", soru: "En çok hangi ilimizde güneş gözlüğü kullanılır?", secenekler: { A: "Göz-lük (Gözlük)", B: "Antalya", C: "Van", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 28, kategori: "Bilmece", soru: "Pişirirsen aş olur, pişirmezsen kuş olur.", secenekler: { A: "Buğday", B: "Mısır", C: "Yumurta", D: "Pirinç" }, dogruCevap: "C" },
    { seviye: 29, kategori: "Bilmece", soru: "İçinde derya var, nehir var ama hiç su yok.", secenekler: { A: "Atlas", B: "Sürahi", C: "Şişe", D: "Bardak" }, dogruCevap: "A" },
    { seviye: 30, kategori: "Bilmece", soru: "Canlı gider, cansız gelir.", secenekler: { A: "Kasap", B: "Avcı", C: "Aşçı", D: "Balıkçı" }, dogruCevap: "D" },
    { seviye: 31, kategori: "Bilmece", soru: "Dokunmadan kırılan şey nedir?", secenekler: { A: "Kalp", B: "Cam", C: "Ayna", D: "Buz" }, dogruCevap: "A" },
    { seviye: 32, kategori: "Bilmece", soru: "Hangi tastan su içilmez?", secenekler: { A: "Bakır tas", B: "Gümüş tas", C: "Kafatası", D: "Altın tas" }, dogruCevap: "C" },
    { seviye: 33, kategori: "Bilmece", soru: "Sadece kullanıldığında kırılan şey nedir?", secenekler: { A: "Fındık", B: "Ceviz", C: "Yumurta", D: "Kömür" }, dogruCevap: "C" },
    { seviye: 34, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Çilekli macun", B: "Naneli macun", C: "Lahmacun", D: "Beyaz macun" }, dogruCevap: "C" },
    { seviye: 35, kategori: "Bilmece", soru: "Sıcak dondurma nerede bulunur?", secenekler: { A: "Güneşte", B: "Antalya'da", C: "Hayallerde", D: "Fırında" }, dogruCevap: "D" },
    { seviye: 36, kategori: "Bilmece", soru: "Yarım elma neye benzer?", secenekler: { A: "Elmaya", B: "Topa", C: "Diğer yarısına", D: "Ay'a" }, dogruCevap: "C" },
    { seviye: 37, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Sağlık karnesi", B: "Sürücü karnesi", C: "Okul karnesi", D: "Vize karnesi" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Bilmece", soru: "Yürür yürür iz etmez, hızı her gün değişmez.", secenekler: { A: "Araba", B: "Güneş", C: "Rüzgar", D: "Saat" }, dogruCevap: "D" },
    { seviye: 39, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "İncir (B-in-cir)", B: "Kavun", C: "Karpuz", D: "Bal kabağı" }, dogruCevap: "A" },
    { seviye: 40, kategori: "Bilmece", soru: "Kökü var ama bitki değil, tırmanır ama hayvan değil.", secenekler: { A: "Saç", B: "Diş", C: "Tırnak", D: "Burun" }, dogruCevap: "B" },
    { seviye: 41, kategori: "Bilmece", soru: "Gözle görülmez, elle tutulmaz, onsuz yaşanmaz.", secenekler: { A: "Koku", B: "Sevgi", C: "Rüzgar", D: "Hava" }, dogruCevap: "D" },
    { seviye: 42, kategori: "Bilmece", soru: "Dili yok ama her şeyi anlatır.", secenekler: { A: "Mektup", B: "Heykel", C: "Kitap", D: "Resim" }, dogruCevap: "C" },
    { seviye: 43, kategori: "Bilmece", soru: "Hangi kapı açılmaz?", secenekler: { A: "Kale kapısı", B: "Tahta kapı", C: "Demir kapı", D: "Çıkış kapısı" }, dogruCevap: "D" },
    { seviye: 44, kategori: "Bilmece", soru: "Başı var kulağı yok, karnı var bacağı yok.", secenekler: { A: "Böcek", B: "Balık", C: "Yılan", D: "Kuş" }, dogruCevap: "C" },
    { seviye: 45, kategori: "Bilmece", soru: "Bir küçücük sandık, içi dolu boncuk.", secenekler: { A: "Fasulye", B: "Nar", C: "Mısır", D: "Bezelye" }, dogruCevap: "B" },
    { seviye: 46, kategori: "Bilmece", soru: "Gece çıkar, gündüz kaçar.", secenekler: { A: "Yıldız", B: "Bulut", C: "Ay", D: "Güneş" }, dogruCevap: "C" },
    { seviye: 47, kategori: "Bilmece", soru: "Şekerden tatlı, zehirden acı.", secenekler: { A: "Bal", B: "Aşk", C: "Kader", D: "Söz" }, dogruCevap: "D" },
    { seviye: 48, kategori: "Bilmece", soru: "Açarsın içini, görürsün kendini.", secenekler: { A: "Pencere", B: "Kitap", C: "Kapı", D: "Ayna" }, dogruCevap: "D" },
    { seviye: 49, kategori: "Bilmece", soru: "Ay varken çıkar, gün varken kaçar.", secenekler: { A: "Gölge", B: "Baykuş", C: "Yıldız", D: "Rüya" }, dogruCevap: "C" },
    { seviye: 50, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Ayakkabı bağı", B: "Karabağ", C: "Kara bağ", D: "Siyah bağ" }, dogruCevap: "A" },
    { seviye: 51, kategori: "Bilmece", soru: "Canı var kanı yok, karnı var canı yok.", secenekler: { A: "Kedi", B: "Oyuncak bebek", C: "Bebek", D: "Kuş" }, dogruCevap: "B" },
    { seviye: 52, kategori: "Bilmece", soru: "Ateşe girer yanmaz, suya girer boğulmaz.", secenekler: { A: "Işık", B: "Gölge", C: "Rüzgar", D: "Hava" }, dogruCevap: "A" },
    { seviye: 53, kategori: "Bilmece", soru: "Ben giderim o gider, yanımda arkamda gider.", secenekler: { A: "Gölge", B: "Güneş", C: "Bulut", D: "Ay" }, dogruCevap: "A" },
    { seviye: 54, kategori: "Bilmece", soru: "Başı var beyni yok.", secenekler: { A: "Soğan", B: "Elma", C: "Kabak", D: "Patates" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Bilmece", soru: "Tüyden hafif ama kimse onu çok uzun süre tutamaz.", secenekler: { A: "Balon", B: "Bulut", C: "Nefes", D: "Su damlası" }, dogruCevap: "C" },
    { seviye: 56, kategori: "Bilmece", soru: "İnsan neyi yutarsa ölmez ama yutkunursa ölür?", secenekler: { A: "Yemek", B: "Su", C: "Tükürük", D: "Hava" }, dogruCevap: "C" },
    { seviye: 57, kategori: "Bilmece", soru: "Gelen gider, giden gelmez.", secenekler: { A: "Zaman", B: "Gençlik", C: "Misafir", D: "Güneş" }, dogruCevap: "A" },
    { seviye: 58, kategori: "Bilmece", soru: "Her şeyi görür ama kendini göremez.", secenekler: { A: "Ayna", B: "Kamera", C: "Göz", D: "Dürbün" }, dogruCevap: "C" },
    { seviye: 59, kategori: "Bilmece", soru: "Doluşuruz bir kutuya, gideriz uzaklara.", secenekler: { A: "Otobüs", B: "Araba", C: "Uçak", D: "Tren" }, dogruCevap: "A" },
    { seviye: 60, kategori: "Bilmece", soru: "Evi var kapısı yok, içi dolu sofrası yok.", secenekler: { A: "Kabak", B: "Karpuz", C: "Biber", D: "Domates" }, dogruCevap: "B" },
    { seviye: 61, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Merkez bankası", B: "Kan bankası", C: "Halk bankası", D: "Ziraat bankası" }, dogruCevap: "B" },
    { seviye: 62, kategori: "Bilmece", soru: "Açarsın genişler, kaparsın daralır.", secenekler: { A: "Şemsiye", B: "Kapı", C: "Perde", D: "Pencere" }, dogruCevap: "A" },
    { seviye: 63, kategori: "Bilmece", soru: "Dışı var içi yok, sesi var dili yok.", secenekler: { A: "Çan", B: "Düdük", C: "Kaval", D: "Zil" }, dogruCevap: "D" },
    { seviye: 64, kategori: "Bilmece", soru: "Ayakları su içer, üstü güneşlenir.", secenekler: { A: "Hayvan", B: "İnsan", C: "Ağaç", D: "Gölge" }, dogruCevap: "C" },
    { seviye: 65, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Profil", B: "Afrika fili", C: "Asya fili", D: "Yavru fil" }, dogruCevap: "A" },
    { seviye: 66, kategori: "Bilmece", soru: "Yazın giyer, kışın çıkarır.", secenekler: { A: "Çiçek", B: "Ağaç", C: "Mont", D: "Kazak" }, dogruCevap: "B" },
    { seviye: 67, kategori: "Bilmece", soru: "Hangi kalemle resim yapılmaz?", secenekler: { A: "Kurşun kalem", B: "Keçeli kalem", C: "Kontrol kalemi", D: "Boya kalemi" }, dogruCevap: "C" },
    { seviye: 68, kategori: "Bilmece", soru: "Hiç yorulmadan dünyayı gezen nedir?", secenekler: { A: "Rüzgar", B: "Güneş", C: "Ay", D: "Bulut" }, dogruCevap: "B" },
    { seviye: 69, kategori: "Bilmece", soru: "Dışı kaktüs, içi süt.", secenekler: { A: "Hindistan cevizi", B: "Kavun", C: "Ananas", D: "Karpuz" }, dogruCevap: "A" },
    { seviye: 70, kategori: "Bilmece", soru: "Geceleri fener, gündüzleri söner.", secenekler: { A: "Mum", B: "Lamba", C: "Güneş", D: "Ateş böceği" }, dogruCevap: "D" },
    { seviye: 71, kategori: "Bilmece", soru: "Hangi kuşun kanadı vardır ama uçamaz?", secenekler: { A: "Deve kuşu", B: "Kırlangıç", C: "Serçe", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 72, kategori: "Bilmece", soru: "Bir yanı beyaz, bir yanı kara.", secenekler: { A: "Gündüz - Gece", B: "Bulut - Yağmur", C: "Kağıt - Kalem", D: "Siyah - Beyaz" }, dogruCevap: "A" },
    { seviye: 73, kategori: "Bilmece", soru: "Hem ısıtır, hem yakar.", secenekler: { A: "Soba", B: "Ateş", C: "Güneş", D: "Elektrik" }, dogruCevap: "B" },
    { seviye: 74, kategori: "Bilmece", soru: "Hangi meyve her zaman yalnızdır?", secenekler: { A: "Üzüm", B: "Elma", C: "Armut", D: "İncir" }, dogruCevap: "C" },
    { seviye: 75, kategori: "Bilmece", soru: "İçinde rüzgar eser, kapısında kilit yok.", secenekler: { A: "Pencere", B: "Baca", C: "Mağara", D: "Kapı" }, dogruCevap: "B" },
    { seviye: 76, kategori: "Bilmece", soru: "Yer altında sakallı dede.", secenekler: { A: "Pırasa", B: "Patates", C: "Havuç", D: "Soğan" }, dogruCevap: "A" },
    { seviye: 77, kategori: "Bilmece", soru: "Hangi köprünün altından su geçmez?", secenekler: { A: "Diş köprüsü", B: "Beton köprü", C: "Taş köprü", D: "Asma köprü" }, dogruCevap: "A" },
    { seviye: 78, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Üzüm", B: "Yalan (Yal-an)", C: "Elma", D: "Yıkanmış kiraz" }, dogruCevap: "B" },
    { seviye: 79, kategori: "Bilmece", soru: "Kulağını bükünce sesi çıkar.", secenekler: { A: "Musluk", B: "Radyo", C: "Müzik kutusu", D: "Televizyon" }, dogruCevap: "A" },
    { seviye: 80, kategori: "Bilmece", soru: "Hangi ağaçta dal olmaz?", secenekler: { A: "Elma ağacı", B: "Çam ağacı", C: "Soyağacı", D: "Meşe ağacı" }, dogruCevap: "C" },
    { seviye: 81, kategori: "Bilmece", soru: "Sıcak dondurma nerede olur?", secenekler: { A: "Güneşte", B: "Kızartmada", C: "Antalya'da", D: "Fırında" }, dogruCevap: "D" },
    { seviye: 82, kategori: "Bilmece", soru: "Gittikçe kısalan şey nedir?", secenekler: { A: "Kağıt", B: "Ömür", C: "İp", D: "Yol" }, dogruCevap: "B" },
    { seviye: 83, kategori: "Bilmece", soru: "Hem ağlar hem güler.", secenekler: { A: "Yağmur", B: "Bebek", C: "İnsan", D: "Bulut" }, dogruCevap: "C" },
    { seviye: 84, kategori: "Bilmece", soru: "Hangi masada yemek yenmez?", secenekler: { A: "Yemek masası", B: "Çalışma masası", C: "Altın masa", D: "Dosya masası" }, dogruCevap: "D" },
    { seviye: 85, kategori: "Bilmece", soru: "Suya girer ıslanmaz, ateşe girer yanmaz.", secenekler: { A: "Işık", B: "Gölge", C: "Hava", D: "Koku" }, dogruCevap: "B" },
    { seviye: 86, kategori: "Bilmece", soru: "Sesi var ama canı yok.", secenekler: { A: "Zil", B: "Yankı", C: "Radyo", D: "Rüzgar" }, dogruCevap: "B" },
    { seviye: 87, kategori: "Bilmece", soru: "Hangi kuşun kanadı var ama uçamaz?", secenekler: { A: "Serçe", B: "Kartal", C: "Atmaca", D: "Penguen" }, dogruCevap: "D" },
    { seviye: 88, kategori: "Bilmece", soru: "Herkesin önünde olan ama kimsenin dokunamadığı nedir?", secenekler: { A: "Bulut", B: "Hava", C: "Güneş", D: "Gelecek" }, dogruCevap: "D" },
    { seviye: 89, kategori: "Bilmece", soru: "Hangi gül kokmaz?", secenekler: { A: "Virgül", B: "Solmuş gül", C: "Kurumuş gül", D: "Yapay gül" }, dogruCevap: "A" },
    { seviye: 90, kategori: "Bilmece", soru: "Canı var ama nefesi yok.", secenekler: { A: "Ayna", B: "Balık", C: "Bitki", D: "Gölge" }, dogruCevap: "C" },
    { seviye: 91, kategori: "Bilmece", soru: "Yer altında kırmızı fener.", secenekler: { A: "Biber", B: "Turp", C: "Domates", D: "Havuç" }, dogruCevap: "B" },
    { seviye: 92, kategori: "Bilmece", soru: "Hangi denizde balık olmaz?", secenekler: { A: "Karadeniz", B: "Akdeniz", C: "Ege Denizi", D: "Ölü Deniz" }, dogruCevap: "D" },
    { seviye: 93, kategori: "Bilmece", soru: "Ben giderim o gider, arkamdan beni izler.", secenekler: { A: "Kedi", B: "Gölge", C: "Ay", D: "Bulut" }, dogruCevap: "B" },
    { seviye: 94, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Tenis topu", B: "Basketbol topu", C: "Kar topu", D: "Futbol topu" }, dogruCevap: "C" },
    { seviye: 95, kategori: "Bilmece", soru: "Kolu var ama eli yok.", secenekler: { A: "Sandalye", B: "Masa", C: "Dolap", D: "Ceket" }, dogruCevap: "A" },
    { seviye: 96, kategori: "Bilmece", soru: "Hangi saatte yemek yenmez?", secenekler: { A: "Duvar saatinde", B: "Öğle saatinde", C: "Akşam saatinde", D: "Sabah saatinde" }, dogruCevap: "A" },
    { seviye: 97, kategori: "Bilmece", soru: "İncecik beli var, tatlı dili var.", secenekler: { A: "Kitap", B: "Kaşık", C: "Bardak", D: "Kalem" }, dogruCevap: "D" },
    { seviye: 98, kategori: "Bilmece", soru: "Sesi var ama canı yok.", secenekler: { A: "Yankı", B: "Telefon", C: "Rüzgar", D: "Radyo" }, dogruCevap: "A" },
    { seviye: 99, kategori: "Bilmece", soru: "Hangi ağaçta dal olmaz?", secenekler: { A: "Çam", B: "Meşe", C: "Elma", D: "Soyağacı" }, dogruCevap: "D" },
    { seviye: 100, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Kontrol kalemi", B: "Kurşun", C: "Dolma", D: "Tükenmez" }, dogruCevap: "A" },

    // bilmece.js devamı (101 - 200)
    { seviye: 101, kategori: "Bilmece", soru: "Çarşıdan aldım kapkara, evde oldu kıpkırmızı.", secenekler: { A: "Çay", B: "Nar", C: "Kömür", D: "Biber" }, dogruCevap: "C" },
    { seviye: 102, kategori: "Bilmece", soru: "Ben giderim o gider, yanımda tık tık eder.", secenekler: { A: "Saat", B: "Gölge", C: "Ayakkabı", D: "Baston" }, dogruCevap: "D" },
    { seviye: 103, kategori: "Bilmece", soru: "Ağzı var dili yok, nefesi var canı yok.", secenekler: { A: "Radyo", B: "Kitap", C: "Düdük", D: "Balon" }, dogruCevap: "D" },
    { seviye: 104, kategori: "Bilmece", soru: "Küçücük fıçıcık, içi dolu turşucuk.", secenekler: { A: "Limon", B: "Turşu", C: "Fındık", D: "Zeytin" }, dogruCevap: "D" },
    { seviye: 105, kategori: "Bilmece", soru: "Yer altında sakallı dede.", secenekler: { A: "Havuç", B: "Soğan", C: "Patates", D: "Pırasa" }, dogruCevap: "D" },
    { seviye: 106, kategori: "Bilmece", soru: "Bir küçücük mil taşı, dolanır dağı taşı.", secenekler: { A: "Göz", B: "Ayak", C: "Güneş", D: "Tekerlek" }, dogruCevap: "A" },
    { seviye: 107, kategori: "Bilmece", soru: "Bilgi verir herkese, ağzı yok konuşur sese.", secenekler: { A: "Kitap", B: "Hoca", C: "Bilgisayar", D: "Gazete" }, dogruCevap: "A" },
    { seviye: 108, kategori: "Bilmece", soru: "Ay varken uçar, gün varken kaçar.", secenekler: { A: "Yıldız", B: "Baykuş", C: "Sinek", D: "Yarasa" }, dogruCevap: "D" },
    { seviye: 109, kategori: "Bilmece", soru: "Ben yazarım o siler.", secenekler: { A: "Kağıt", B: "Kalem", C: "Tebeşir", D: "Silgi" }, dogruCevap: "D" },
    { seviye: 110, kategori: "Bilmece", soru: "İçer içersin bitmez, tadına doyum yetmez.", secenekler: { A: "Süt", B: "Hava", C: "Su", D: "Çay" }, dogruCevap: "B" },
    { seviye: 111, kategori: "Bilmece", soru: "Sıcağa koyarsın erir, soğuğa koyarsın donar.", secenekler: { A: "Demir", B: "Buz", C: "Su", D: "Mum" }, dogruCevap: "C" },
    { seviye: 112, kategori: "Bilmece", soru: "Daldan dala atlarım, kuyruğumdan tutarım.", secenekler: { A: "Kedi", B: "Sincap", C: "Kuş", D: "Maymun" }, dogruCevap: "D" },
    { seviye: 113, kategori: "Bilmece", soru: "Tarlada biter, sofraya gelir, her yemeğe tat verir.", secenekler: { A: "Ekmek", B: "Tuz", C: "Biber", D: "Soğan" }, dogruCevap: "D" },
    { seviye: 114, kategori: "Bilmece", soru: "Gece gündüz bekler, kapıyı çalana bakar.", secenekler: { A: "Kilit", B: "Bekçi", C: "Zil", D: "Paspas" }, dogruCevap: "A" },
    { seviye: 115, kategori: "Bilmece", soru: "Başında tacı var, padişah değil. Mahmuzu var, süvari değil.", secenekler: { A: "Tavus Kuşu", B: "Hindi", C: "Horoz", D: "Aslan" }, dogruCevap: "C" },
    { seviye: 116, kategori: "Bilmece", soru: "Canı var kanı yok, sesi var dili yok.", secenekler: { A: "Keman", B: "Rüzgar", C: "Radyo", D: "Sinek" }, dogruCevap: "A" },
    { seviye: 117, kategori: "Bilmece", soru: "Yazın giyinir, kışın soyunur.", secenekler: { A: "İnsan", B: "Ağaç", C: "Ayı", D: "Yılan" }, dogruCevap: "B" },
    { seviye: 118, kategori: "Bilmece", soru: "Altı mermer, üstü mermer, içinde bir bülbül oynar.", secenekler: { A: "Dil", B: "Göz", C: "Ağız", D: "Diş" }, dogruCevap: "A" },
    { seviye: 119, kategori: "Bilmece", soru: "Kanadı var uçamaz, ağzı var konuşamaz.", secenekler: { A: "Tavuk", B: "Balık", C: "Uçak", D: "Penguen" }, dogruCevap: "B" },
    { seviye: 120, kategori: "Bilmece", soru: "Gökte gördüm bir köprü, rengi var yedi türlü.", secenekler: { A: "Gökkuşağı", B: "Bulut", C: "Yıldız", D: "Uçurtma" }, dogruCevap: "A" },
    { seviye: 121, kategori: "Bilmece", soru: "Dışı var içi yok, dayak yer suçu yok.", secenekler: { A: "Top", B: "Halı", C: "Davul", D: "Yastık" }, dogruCevap: "A" },
    { seviye: 122, kategori: "Bilmece", soru: "Şehirleri var yolu yok, denizi var suyu yok.", secenekler: { A: "Harita", B: "Resim", C: "Rüya", D: "Televizyon" }, dogruCevap: "A" },
    { seviye: 123, kategori: "Bilmece", soru: "İki camlı pencere, bakıp durur her yere.", secenekler: { A: "Dürbün", B: "Göz", C: "Gözlük", D: "Ayna" }, dogruCevap: "C" },
    { seviye: 124, kategori: "Bilmece", soru: "Akşam baktım çok idi, sabah baktım yok idi.", secenekler: { A: "Karanlık", B: "Çiy", C: "Yıldız", D: "Rüya" }, dogruCevap: "C" },
    { seviye: 125, kategori: "Bilmece", soru: "Ben giderim o kalır.", secenekler: { A: "Ayak izi", B: "İsim", C: "Gölge", D: "Zaman" }, dogruCevap: "A" },
    { seviye: 126, kategori: "Bilmece", soru: "Başına konar, seni serinletir.", secenekler: { A: "Şapka", B: "Gölge", C: "Rüzgar", D: "Vantilatör" }, dogruCevap: "A" },
    { seviye: 127, kategori: "Bilmece", soru: "Bir kapaklı, çok yapraklı, içinde bilgi saklı.", secenekler: { A: "Ağaç", B: "Kitap", C: "Ansiklopedi", D: "Defter" }, dogruCevap: "B" },
    { seviye: 128, kategori: "Bilmece", soru: "Elsiz ayaksız kapı açar.", secenekler: { A: "Rüzgar", B: "Hırsız", C: "Hayalet", D: "Anahtar" }, dogruCevap: "D" },
    { seviye: 129, kategori: "Bilmece", soru: "Yolu var yürünmez, beli var bükülmez.", secenekler: { A: "Yol", B: "Dağ", C: "Merdiven", D: "Deniz" }, dogruCevap: "B" },
    { seviye: 130, kategori: "Bilmece", soru: "Herkesin önünde, ama kimse göremez.", secenekler: { A: "Düşünce", B: "Hava", C: "Gelecek", D: "Burun" }, dogruCevap: "C" },
    { seviye: 131, kategori: "Bilmece", soru: "Bağlayınca yürür, çözünce durur.", secenekler: { A: "Ayakkabı", B: "At", C: "Araba", D: "Gemi" }, dogruCevap: "A" },
    { seviye: 132, kategori: "Bilmece", soru: "Suya düşer ıslanmaz, yere düşer paslanmaz.", secenekler: { A: "Güneş", B: "Gölge", C: "Hava", D: "Işık" }, dogruCevap: "B" },
    { seviye: 133, kategori: "Bilmece", soru: "Çiğnemeden yutar, karnında dünya var.", secenekler: { A: "Bilgisayar", B: "Televizyon", C: "Çöp kutusu", D: "Buzdolabı" }, dogruCevap: "D" },
    { seviye: 134, kategori: "Bilmece", soru: "Kulağını büktükçe sesi yükselir.", secenekler: { A: "Radyo", B: "Keman", C: "Musluk", D: "İnsan" }, dogruCevap: "A" },
    { seviye: 135, kategori: "Bilmece", soru: "Sarıdır sallanır, tadı baldan tatlıdır.", secenekler: { A: "Kavun", B: "Armut", C: "Ayva", D: "Muz" }, dogruCevap: "B" },
    { seviye: 136, kategori: "Bilmece", soru: "Ayakları var gidemez, yemek gelse yiyemez.", secenekler: { A: "Masa", B: "Sandalye", C: "Yatak", D: "Bebek" }, dogruCevap: "A" },
    { seviye: 137, kategori: "Bilmece", soru: "Açarsam dünya olur, kapatırsam rüya olur.", secenekler: { A: "Göz", B: "Pencere", C: "Perde", D: "Kitap" }, dogruCevap: "A" },
    { seviye: 138, kategori: "Bilmece", soru: "Göbeği var deliği yok.", secenekler: { A: "Karpuz", B: "Patlıcan", C: "Domates", D: "Kabak" }, dogruCevap: "A" },
    { seviye: 139, kategori: "Bilmece", soru: "Dört ayağı var ama yürüyemez.", secenekler: { A: "Kedi", B: "Masa", C: "Sandalye", D: "Köpek" }, dogruCevap: "B" },
    { seviye: 140, kategori: "Bilmece", soru: "Okuma yazma bilmez, ama her şeyi yazar.", secenekler: { A: "Bilgisayar", B: "Kalem", C: "Kağıt", D: "Daktilo" }, dogruCevap: "B" },
    { seviye: 141, kategori: "Bilmece", soru: "Ben giderim o gelir, peşimden tık tık eder.", secenekler: { A: "Saat", B: "Baston", C: "Gölge", D: "Ayak sesi" }, dogruCevap: "B" },
    { seviye: 142, kategori: "Bilmece", soru: "Tüyden hafif, ama kimse onu tutamaz.", secenekler: { A: "Hava", B: "Duman", C: "Nefes", D: "Bulut" }, dogruCevap: "C" },
    { seviye: 143, kategori: "Bilmece", soru: "İçi taş, dışı baş.", secenekler: { A: "Zeytin", B: "Ev", C: "Kaplumbağa", D: "Kayısı" }, dogruCevap: "C" },
    { seviye: 144, kategori: "Bilmece", soru: "Denizde var, karada yok.", secenekler: { A: "Dalga", B: "Gemi", C: "Yosun", D: "Balık" }, dogruCevap: "A" },
    { seviye: 145, kategori: "Bilmece", soru: "İğnesi var ama dikiş dikemez.", secenekler: { A: "Çam ağacı", B: "Arı", C: "Kirpi", D: "Doktor" }, dogruCevap: "B" },
    { seviye: 146, kategori: "Bilmece", soru: "Kolu var ama bacağı yok.", secenekler: { A: "Sandalye", B: "Gömlek", C: "Masa", D: "Gözlük" }, dogruCevap: "B" },
    { seviye: 147, kategori: "Bilmece", soru: "Kapağı var, tencere değil; yaprağı var, ağaç değil.", secenekler: { A: "Marul", B: "Defter", C: "Lahana", D: "Kitap" }, dogruCevap: "D" },
    { seviye: 148, kategori: "Bilmece", soru: "Suyu var ama içilmez.", secenekler: { A: "Havuz", B: "Deniz", C: "Göl", D: "Boya" }, dogruCevap: "D" },
    { seviye: 149, kategori: "Bilmece", soru: "Kanatları var ama kuş değil.", secenekler: { A: "Kelebek", B: "Uçak", C: "Yel değirmeni", D: "Helikopter" }, dogruCevap: "C" },
    { seviye: 150, kategori: "Bilmece", soru: "Başı var saç yok, gözü var kaş yok.", secenekler: { A: "Yumurta", B: "İğne", C: "Patates", D: "Balık" }, dogruCevap: "D" },
    { seviye: 151, kategori: "Bilmece", soru: "Ayakları su içer, başı güneş yer.", secenekler: { A: "Güneş şemsiyesi", B: "Çiçek", C: "Ağaç", D: "İnsan" }, dogruCevap: "C" },
    { seviye: 152, kategori: "Bilmece", soru: "Yer altında yuvası var, hırsız gibi kesesi var.", secenekler: { A: "Tavşan", B: "Karınca", C: "Köstebek", D: "Fare" }, dogruCevap: "C" },
    { seviye: 153, kategori: "Bilmece", soru: "İki kardeş var, birbirini görmez.", secenekler: { A: "El", B: "Göz", C: "Kulak", D: "Ayak" }, dogruCevap: "B" },
    { seviye: 154, kategori: "Bilmece", soru: "Bir ağacı oymuşlar, içine ses koymuşlar.", secenekler: { A: "Saz", B: "Dolap", C: "Kapı", D: "Kaval" }, dogruCevap: "A" },
    { seviye: 155, kategori: "Bilmece", soru: "Onu görürsün ama tutamazsın; o kaçar, sen kovalarsın.", secenekler: { A: "Rüzgar", B: "Gölge", C: "Gökkuşağı", D: "Bulut" }, dogruCevap: "B" },
    { seviye: 156, kategori: "Bilmece", soru: "Zenginin elinde, fakirin dilinde.", secenekler: { A: "Para", B: "Ekmek", C: "Altın", D: "Dua" }, dogruCevap: "A" },
    { seviye: 157, kategori: "Bilmece", soru: "İki teker, üzerinde şeker.", secenekler: { A: "Araba", B: "Motorsiklet", C: "Bisiklet", D: "At arabası" }, dogruCevap: "C" },
    { seviye: 158, kategori: "Bilmece", soru: "Tarlada yeşil, bakkalda siyah, evde kırmızı.", secenekler: { A: "Biber", B: "Zeytin", C: "Kömür", D: "Çay" }, dogruCevap: "D" },
    { seviye: 159, kategori: "Bilmece", soru: "Dişi var ısırmaz, sakalı var konuşmaz.", secenekler: { A: "Mısır", B: "Süpürge", C: "Kilit", D: "Tarak" }, dogruCevap: "A" },
    { seviye: 160, kategori: "Bilmece", soru: "Ben giderim o kalır, her adımda çoğalır.", secenekler: { A: "Ayak izi", B: "Zaman", C: "Gölge", D: "Yorgunluk" }, dogruCevap: "A" },
    { seviye: 161, kategori: "Bilmece", soru: "Daldan dala, kırmızı pala.", secenekler: { A: "Sincap", B: "Elma", C: "Kiraz", D: "Kuş" }, dogruCevap: "A" },
    { seviye: 162, kategori: "Bilmece", soru: "Gelişi güle güle, gidişi ağla ağla.", secenekler: { A: "Misafir", B: "Gelin", C: "Bebek", D: "Mevsim" }, dogruCevap: "B" },
    { seviye: 163, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Ayakkabı bağında", B: "Bahçede", C: "Üzüm bağında", D: "Sevgi bağında" }, dogruCevap: "A" },
    { seviye: 164, kategori: "Bilmece", soru: "Bir sihirli fenerim, kime baksam dönerim.", secenekler: { A: "Göz", B: "Ayna", C: "El feneri", D: "Fotoğraf makinesi" }, dogruCevap: "B" },
    { seviye: 165, kategori: "Bilmece", soru: "Yer altında turuncu direk.", secenekler: { A: "Havuç", B: "Yer elması", C: "Patates", D: "Soğan" }, dogruCevap: "A" },
    { seviye: 166, kategori: "Bilmece", soru: "Beyaz sarayda sarı sultan.", secenekler: { A: "Yumurta", B: "Limon", C: "Peynir", D: "Güneş" }, dogruCevap: "A" },
    { seviye: 167, kategori: "Bilmece", soru: "Hangi piyanoda tuş yoktur?", secenekler: { A: "Hayali piyano", B: "Böyle bir piyano yok", C: "Eski piyano", D: "Su piyanosu" }, dogruCevap: "B" },
    { seviye: 168, kategori: "Bilmece", soru: "Güneş gidince gelir, gökyüzünü süsler.", secenekler: { A: "Gece", B: "Ay", C: "Yıldız", D: "Bulut" }, dogruCevap: "B" },
    { seviye: 169, kategori: "Bilmece", soru: "Mini mini kuşlar, her yeri gümüşler.", secenekler: { A: "Yıldız", B: "Kar", C: "Dolu", D: "Yağmur" }, dogruCevap: "B" },
    { seviye: 170, kategori: "Bilmece", soru: "Hanım içerde, saçı dışarda.", secenekler: { A: "Mısır", B: "Patlıcan", C: "Lahana", D: "Kabak" }, dogruCevap: "A" },
    { seviye: 171, kategori: "Bilmece", soru: "Yarım kaşık, duvara yapışık.", secenekler: { A: "Ağız", B: "Göz", C: "Kulak", D: "Burun" }, dogruCevap: "C" },
    { seviye: 172, kategori: "Bilmece", soru: "Bir kuşum var, her yeri kazar.", secenekler: { A: "İğne", B: "Kalem", C: "Tavuk", D: "Köstebek" }, dogruCevap: "B" },
    { seviye: 173, kategori: "Bilmece", soru: "Derisi var canı yok, yaprağı var ağaç değil.", secenekler: { A: "Defter", B: "Marul", C: "Kitap", D: "Lahana" }, dogruCevap: "C" },
    { seviye: 174, kategori: "Bilmece", soru: "Bacakları var ama yürümez.", secenekler: { A: "Masa", B: "Sandalye", C: "Gözlük", D: "Pantolon" }, dogruCevap: "D" },
    { seviye: 175, kategori: "Bilmece", soru: "Su içine girince ne olur?", secenekler: { A: "Kaybolur", B: "Islanır", C: "Yüzer", D: "Batar" }, dogruCevap: "B" },
    { seviye: 176, kategori: "Bilmece", soru: "Yatağı var ama uyumaz, ağzı var ama konuşmaz.", secenekler: { A: "Deniz", B: "Bebek", C: "Irmak", D: "Yatak" }, dogruCevap: "C" },
    { seviye: 177, kategori: "Bilmece", soru: "Baş aşağı durur, su içince ölür.", secenekler: { A: "Mum", B: "Yarasa", C: "Ateş", D: "Çivi" }, dogruCevap: "C" },
    { seviye: 178, kategori: "Bilmece", soru: "Canlıyı boğar, cansızı doğurur.", secenekler: { A: "Toprak", B: "Su", C: "Hava", D: "Ateş" }, dogruCevap: "B" },
    { seviye: 179, kategori: "Bilmece", soru: "Her şeyi görür, kendini göremez.", secenekler: { A: "Göz", B: "Kamera", C: "Işık", D: "Ayna" }, dogruCevap: "A" },
    { seviye: 180, kategori: "Bilmece", soru: "Bin bir deliği var, suyu tutamaz.", secenekler: { A: "Sünger", B: "Süzgeç", C: "Filtre", D: "Elek" }, dogruCevap: "B" },
    { seviye: 181, kategori: "Bilmece", soru: "Eli yok ama kapı çalar.", secenekler: { A: "Postacı", B: "Rüzgar", C: "Zil", D: "Yağmur" }, dogruCevap: "B" },
    { seviye: 182, kategori: "Bilmece", soru: "Eriyen ama ıslatmayan nedir?", secenekler: { A: "Tuz", B: "Mum", C: "Kuru buz", D: "Şeker" }, dogruCevap: "B" },
    { seviye: 183, kategori: "Bilmece", soru: "Üstü kış, altı bahar.", secenekler: { A: "Dağ", B: "İnsan", C: "Ev", D: "Ağaç" }, dogruCevap: "A" },
    { seviye: 184, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Boya kalemi", B: "Kurşun kalem", C: "Tükenmez kalem", D: "Kontrol kalemi" }, dogruCevap: "D" },
    { seviye: 185, kategori: "Bilmece", soru: "Bir sihirli kutu, içi dolu bilgi.", secenekler: { A: "Telefon", B: "Bilgisayar", C: "Televizyon", D: "Radyo" }, dogruCevap: "B" },
    { seviye: 186, kategori: "Bilmece", soru: "Hiç hareket etmeden tüm dünyayı gezer.", secenekler: { A: "Harita", B: "Yol", C: "Uçak", D: "Pul" }, dogruCevap: "D" },
    { seviye: 187, kategori: "Bilmece", soru: "Çıt çıt eder, her yeri gezer.", secenekler: { A: "Ayakkabı", B: "Saat", C: "Makas", D: "Tekerlek" }, dogruCevap: "C" },
    { seviye: 188, kategori: "Bilmece", soru: "Yükü var, hamal değil; evi var, sahibi değil.", secenekler: { A: "Karınca", B: "Salyangoz", C: "Kamyon", D: "Kaplumbağa" }, dogruCevap: "B" },
    { seviye: 189, kategori: "Bilmece", soru: "Isırır ama dişi yok.", secenekler: { A: "Biber", B: "Soğuk", C: "Hepsi", D: "Isırgan otu" }, dogruCevap: "C" },
    { seviye: 190, kategori: "Bilmece", soru: "Kışın güneş kremi sürer.", secenekler: { A: "Ayna", B: "Kayakçı", C: "Güneş gözlüğü", D: "Kardan adam" }, dogruCevap: "D" },
    { seviye: 191, kategori: "Bilmece", soru: "Dili yok ama yalan söylemez.", secenekler: { A: "Resim", B: "Ayna", C: "Saat", D: "Kitap" }, dogruCevap: "B" },
    { seviye: 192, kategori: "Bilmece", soru: "Hangi kanat uçamaz?", secenekler: { A: "Kapı kanadı", B: "Kelebek kanadı", C: "Uçak kanadı", D: "Kuş kanadı" }, dogruCevap: "A" },
    { seviye: 193, kategori: "Bilmece", soru: "Diri girer, ölü çıkar.", secenekler: { A: "Fırın", B: "Ekmek", C: "Hamam", D: "Yemek" }, dogruCevap: "B" },
    { seviye: 194, kategori: "Bilmece", soru: "Suya girer kupkuru, sudan çıkar ıslak.", secenekler: { A: "Tuz", B: "Bardak", C: "Şeker", D: "Sünger" }, dogruCevap: "D" },
    { seviye: 195, kategori: "Bilmece", soru: "Eli var kolu yok, karnı yarık canı yok.", secenekler: { A: "Ceket", B: "Pantolon", C: "Yelek", D: "Gömlek" }, dogruCevap: "C" },
    { seviye: 196, kategori: "Bilmece", soru: "Ben giderim o kalır, her zaman arkamda kalır.", secenekler: { A: "İsim", B: "Gölge", C: "Dün", D: "Ayak izi" }, dogruCevap: "D" },
    { seviye: 197, kategori: "Bilmece", soru: "Yerin altında gümüş saray.", secenekler: { A: "Sarımsak", B: "Soğan", C: "Patates", D: "Turp" }, dogruCevap: "A" },
    { seviye: 198, kategori: "Bilmece", soru: "İncecik beli, elimin dili.", secenekler: { A: "Çatal", B: "Kaşık", C: "Kalem", D: "Fırça" }, dogruCevap: "C" },
    { seviye: 199, kategori: "Bilmece", soru: "Bir yanı beyaz, bir yanı kara.", secenekler: { A: "Piyano", B: "Kağıt", C: "Gece-Gündüz", D: "Yol" }, dogruCevap: "C" },
    { seviye: 200, kategori: "Bilmece", soru: "Okur ama bilmez, söyler ama duymaz.", secenekler: { A: "Radyo", B: "Mektup", C: "Papağan", D: "Kitap" }, dogruCevap: "D" }, 
    // 201-350: Yeni Nesil, Klasik ve Zeka Sorusu Tadında Bilmeceler
    { seviye: 201, kategori: "Bilmece", soru: "Gökten yağar, ıslatmaz; yerden biter, kök salmaz.", secenekler: { A: "Işık", B: "Kar", C: "Dolu", D: "Sis" }, dogruCevap: "A" },
    { seviye: 202, kategori: "Bilmece", soru: "Bir küçücük mil taşı, dolanır dağı taşı.", secenekler: { A: "Araba", B: "Güneş", C: "Tekerlek", D: "Göz" }, dogruCevap: "D" },
    { seviye: 203, kategori: "Bilmece", soru: "Benim bir hayvanım var, kuyruğundan uzun burnu var.", secenekler: { A: "Fil", B: "Gergedan", C: "Zürafa", D: "Karıncayiyen" }, dogruCevap: "A" },
    { seviye: 204, kategori: "Bilmece", soru: "Sesi var, görüntüsü yok; kendisi var, canı yok.", secenekler: { A: "Gölge", B: "Rüzgar", C: "Dua", D: "Ruh" }, dogruCevap: "B" },
    { seviye: 205, kategori: "Bilmece", soru: "Akşam baktım çok idi, sabah baktım yok idi.", secenekler: { A: "Rüya", B: "Yıldızlar", C: "Hırsızlar", D: "Bulutlar" }, dogruCevap: "B" },
    { seviye: 206, kategori: "Bilmece", soru: "Küçücük bakkal, dünyayı yutar.", secenekler: { A: "Mide", B: "Ağız", C: "Göz", D: "Kulak" }, dogruCevap: "C" },
    { seviye: 207, kategori: "Bilmece", soru: "Cansızdır ama nefes alır, yeri gelir fırtına koparır.", secenekler: { A: "Vantilatör", B: "Körük", C: "Balon", D: "Dalga" }, dogruCevap: "B" },
    { seviye: 208, kategori: "Bilmece", soru: "Başı var kulağı yok, ayağı var ayakkabısı yok.", secenekler: { A: "Yılan", B: "Masa", C: "Çivi", D: "Sandalye" }, dogruCevap: "C" },
    { seviye: 209, kategori: "Bilmece", soru: "Her gün yeniden doğar, akşam olunca ölür.", secenekler: { A: "Umut", B: "Güneş", C: "Çiçek", D: "Bebek" }, dogruCevap: "B" },
    { seviye: 210, kategori: "Bilmece", soru: "Hangi kelime yanlış yazılsa bile doğru okunur?", secenekler: { A: "Hatalı", B: "Eksik", C: "Doğru", D: "Yanlış" }, dogruCevap: "D" },
    { seviye: 211, kategori: "Bilmece", soru: "Sıfırdan büyüktür ama hiçbir şeyi yoktur.", secenekler: { A: "Fakir", B: "Boşluk", C: "Bir", D: "Nokta" }, dogruCevap: "C" },
    { seviye: 212, kategori: "Bilmece", soru: "Daldan dala atlarım, kuyruğumla tutunurum.", secenekler: { A: "Sincap", B: "Maymun", C: "Kuş", D: "Kedi" }, dogruCevap: "B" },
    { seviye: 213, kategori: "Bilmece", soru: "Ayakları var yürüyemez, sırtı var yatamaz.", secenekler: { A: "Dolap", B: "Masa", C: "Yatak", D: "Sandalye" }, dogruCevap: "D" },
    { seviye: 214, kategori: "Bilmece", soru: "Yazın giyinir, kışın soyunur.", secenekler: { A: "Yılan", B: "Çocuk", C: "Güneş", D: "Ağaç" }, dogruCevap: "D" },
    { seviye: 215, kategori: "Bilmece", soru: "Hangi masada yemek yenmez?", secenekler: { A: "Dizüstü bilgisayar (masaüstü)", B: "Yuvarlak masa", C: "Çalışma masası", D: "Ameliyat masası" }, dogruCevap: "D" },
    { seviye: 216, kategori: "Bilmece", soru: "Ben giderim o gider, kolumda tık tık eder.", secenekler: { A: "Kalp", B: "Bilezik", C: "Saat", D: "Nabız" }, dogruCevap: "C" },
    { seviye: 217, kategori: "Bilmece", soru: "Altı mermer, üstü mermer, içinde bir bülbül öter.", secenekler: { A: "Saray", B: "Ağız", C: "Piyano", D: "Kafes" }, dogruCevap: "B" },
    { seviye: 218, kategori: "Bilmece", soru: "Şehirleri var yolu yok, denizleri var suyu yok.", secenekler: { A: "Uzay", B: "Televizyon", C: "Rüya", D: "Harita" }, dogruCevap: "D" },
    { seviye: 219, kategori: "Bilmece", soru: "Bir kamyonu bir eliyle kim durdurabilir?", secenekler: { A: "Trafik Polisi", B: "Kamyon Şoförü", C: "Süpermen", D: "Hulk" }, dogruCevap: "A" },
    { seviye: 220, kategori: "Bilmece", soru: "Suya düşer ıslanmaz, yere düşer kırılmaz.", secenekler: { A: "Gölge", B: "Hava", C: "Işık", D: "Pamuk" }, dogruCevap: "A" },
    { seviye: 221, kategori: "Bilmece", soru: "Karnı açık, ağzı kapalı; içinde binbir bilgi saklı.", secenekler: { A: "Bilgisayar", B: "Kitap", C: "Kütüphane", D: "Zihin" }, dogruCevap: "B" },
    { seviye: 222, kategori: "Bilmece", soru: "Çarşıdan aldım kara, evde oldu kırmızı, çöpe attım gri.", secenekler: { A: "Kömür", B: "Kestane", C: "Demir", D: "Çay" }, dogruCevap: "A" },
    { seviye: 223, kategori: "Bilmece", soru: "Hangi anahtar kapıyı açmaz?", secenekler: { A: "Şifre", B: "Kırık anahtar", C: "İngiliz anahtarı", D: "Sol anahtarı" }, dogruCevap: "D" },
    { seviye: 224, kategori: "Bilmece", soru: "Dokunmadan kırılan şey nedir?", secenekler: { A: "Cam", B: "Söz", C: "Kalp", D: "Buz" }, dogruCevap: "C" },
    { seviye: 225, kategori: "Bilmece", soru: "Birinciyi geçen kaçıncı olur?", secenekler: { A: "Üçüncü", B: "Şampiyon", C: "Birinci", D: "İkinci" }, dogruCevap: "C" },
    { seviye: 226, kategori: "Bilmece", soru: "İçinde dumanı var, üstünde ormanı var.", secenekler: { A: "Nargile", B: "Fabrika", C: "Vapur", D: "Dağ" }, dogruCevap: "D" },
    { seviye: 227, kategori: "Bilmece", soru: "Açarsın dünya girer, kapatırsın kutu kalır.", secenekler: { A: "Pencere", B: "Göz", C: "Televizyon", D: "Kitap" }, dogruCevap: "C" },
    { seviye: 228, kategori: "Bilmece", soru: "Dişi var ısırmaz, sakalı var konuşmaz.", secenekler: { A: "Mısır", B: "Süpürge", C: "Pırasa", D: "Tarak" }, dogruCevap: "A" },
    { seviye: 229, kategori: "Bilmece", soru: "Kuyruğu var at değil, kanadı var kuş değil.", secenekler: { A: "Ejderha", B: "Uçak", C: "Balık", D: "Uçurtma" }, dogruCevap: "C" },
    { seviye: 230, kategori: "Bilmece", soru: "Üstü çayır biçilir, altı çeşme içilir.", secenekler: { A: "Kuyu", B: "Bahçe", C: "İnek", D: "Koyun" }, dogruCevap: "C" },
    // ... (Hızlandırmak adına geri kalanları aynı formatta devam ettiriyorum)
    { seviye: 231, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Dolma kalem", B: "Kurşun kalem", C: "Kontrol kalemi", D: "Tükenmez kalem" }, dogruCevap: "C" },
    { seviye: 232, kategori: "Bilmece", soru: "Bağlandığında yürür, çözüldüğünde durur.", secenekler: { A: "Gemi", B: "Ayakkabı", C: "Köpek", D: "At" }, dogruCevap: "B" },
    { seviye: 233, kategori: "Bilmece", soru: "Eve gelen hırsız neyi çalmaz?", secenekler: { A: "Zil", B: "Altın", C: "Halı", D: "Para" }, dogruCevap: "A" },
    { seviye: 234, kategori: "Bilmece", soru: "En temiz böcek hangisidir?", secenekler: { A: "Arı", B: "Karınca", C: "Kelebek", D: "Hamam böceği" }, dogruCevap: "D" },
    { seviye: 235, kategori: "Bilmece", soru: "Suda doğar, suda ölür.", secenekler: { A: "Yosun", B: "Gemi", C: "Buz", D: "Balık" }, dogruCevap: "C" },
    { seviye: 236, kategori: "Bilmece", soru: "Hiç hareket etmeden tüm dünyayı gezen nedir?", secenekler: { A: "Rüzgar", B: "Pul", C: "Bulut", D: "Güneş" }, dogruCevap: "B" },
    { seviye: 237, kategori: "Bilmece", soru: "Açtıkça daralır, kapattıkça genişler.", secenekler: { A: "Makas", B: "Fermuar", C: "Kapı", D: "Şemsiye" }, dogruCevap: "A" },
    { seviye: 238, kategori: "Bilmece", soru: "İki camlı bir pencere, bakıp durur her yere.", secenekler: { A: "Kamera", B: "Göz", C: "Gözlük", D: "Dürbün" }, dogruCevap: "C" },
    { seviye: 239, kategori: "Bilmece", soru: "Özü tatlı, sözü tatlı, kovanı var balı tatlı.", secenekler: { A: "Arı", B: "Reçel", C: "Şeker", D: "Çocuk" }, dogruCevap: "A" },
    { seviye: 240, kategori: "Bilmece", soru: "Yolun üzerinde gider ama hiç kımıldamaz.", secenekler: { A: "Şerit", B: "Asfalt", C: "Trafik levhası", D: "Araba" }, dogruCevap: "A" },
    { seviye: 241, kategori: "Bilmece", soru: "Kral tacına ne zaman sahip olur?", secenekler: { A: "Başına takıldığında", B: "Doğduğunda", C: "Öldüğünde", D: "Taç giyme töreninde" }, dogruCevap: "A" },
    { seviye: 242, kategori: "Bilmece", soru: "Hangi tene krem sürülmez?", secenekler: { A: "Kertenkele", B: "Esmer ten", C: "Güneş yanığı", D: "Karton" }, dogruCevap: "D" },
    { seviye: 243, kategori: "Bilmece", soru: "Hangi kovanın balı olmaz?", secenekler: { A: "Mermi kovanı", B: "Eşek arısı kovanı", C: "Sepet kovan", D: "Boş kovan" }, dogruCevap: "A" },
    { seviye: 244, kategori: "Bilmece", soru: "Tarlada yeşil, bakkalda siyah, evde kırmızı.", secenekler: { A: "Çay", B: "Zeytin", C: "Üzüm", D: "Domates" }, dogruCevap: "A" },
    { seviye: 245, kategori: "Bilmece", soru: "Burnu var nefes almaz, ağzı var yemek yemez.", secenekler: { A: "Sürahi", B: "Ayakkabı", C: "Gözlük", D: "Heykel" }, dogruCevap: "B" },
    { seviye: 246, kategori: "Bilmece", soru: "Kışın yatar, yazın kalkar; ayakları gümüş, başı altın.", secenekler: { A: "Buğday", B: "Karınca", C: "Güneş", D: "Çiçek" }, dogruCevap: "A" },
    { seviye: 247, kategori: "Bilmece", soru: "Siyah bir tavuk, her gün bir yumurta yumurtlar.", secenekler: { A: "Zeytin", B: "Gece - Gün", C: "Kömür", D: "Ocak - Yemek" }, dogruCevap: "B" },
    { seviye: 248, kategori: "Bilmece", soru: "Gözle görülmez, elle tutulmaz ama onsuz yaşanmaz.", secenekler: { A: "Hava", B: "Sevgi", C: "Su", D: "Rüzgar" }, dogruCevap: "A" },
    { seviye: 249, kategori: "Bilmece", soru: "Yerin altında sakallı dede.", secenekler: { A: "Soğan", B: "Patates", C: "Havuç", D: "Pırasa" }, dogruCevap: "D" },
    { seviye: 250, kategori: "Bilmece", soru: "Bir ağacı var 12 dalı, her dalında 30 yaprağı.", secenekler: { A: "Kitap", B: "Okul", C: "Yıl - Aylar - Günler", D: "Kütüphane" }, dogruCevap: "C" },
    { seviye: 251, kategori: "Bilmece", soru: "Ettendir dili, kemiktendir dişi.", secenekler: { A: "Ağız", B: "Anahtar", C: "Fırça", D: "Tarak" }, dogruCevap: "D" },
    { seviye: 252, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Kurubag", B: "Elma bağı", C: "Gönül bağı", D: "Ayakkabı bağı" }, dogruCevap: "D" },
    { seviye: 253, kategori: "Bilmece", soru: "Sıcak dondurma nerede bulunur?", secenekler: { A: "Fırında", B: "Rüyada", C: "Sözlükte", D: "Güneşte" }, dogruCevap: "C" },
    { seviye: 254, kategori: "Bilmece", soru: "Hangi çiçek hem koklanır hem yürür?", secenekler: { A: "Gül", B: "Lale", C: "Gelin", D: "Papatya" }, dogruCevap: "C" },
    { seviye: 255, kategori: "Bilmece", soru: "Canı var kanı yok, konuşur dili yok.", secenekler: { A: "Kitap", B: "Mektup", C: "Telefon", D: "Radyo" }, dogruCevap: "A" },
    { seviye: 256, kategori: "Bilmece", soru: "Herkesin önünde olan ama kimsenin görmediği şey nedir?", secenekler: { A: "Alın", B: "Göz", C: "Gelecek", D: "Hava" }, dogruCevap: "C" },
    { seviye: 257, kategori: "Bilmece", soru: "En çok hangi ilimizde güneş parlar?", secenekler: { A: "Antalya", B: "Hepsi (Güneş bir tane)", C: "Aydın", D: "İzmir" }, dogruCevap: "B" },
    { seviye: 258, kategori: "Bilmece", soru: "Hangi meyvenin kardeşi vardır?", secenekler: { A: "Kiraz", B: "Elma", C: "Armut", D: "Üzüm" }, dogruCevap: "A" },
    { seviye: 259, kategori: "Bilmece", soru: "Göbeği var, canı yok.", secenekler: { A: "Marul", B: "Tencere", C: "Şişe", D: "Yastık" }, dogruCevap: "B" },
    { seviye: 260, kategori: "Bilmece", soru: "Dolu bir odada ne yer kaplamaz?", secenekler: { A: "Hava", B: "Hepsi", C: "Ses", D: "Işık" }, dogruCevap: "B" },
    { seviye: 261, kategori: "Bilmece", soru: "Okuma yazması olmayan hocaya ne denir?", secenekler: { A: "Okuma bilmez", B: "Düdük", C: "Bilgisiz", D: "Trafik hocası" }, dogruCevap: "B" },
    { seviye: 262, kategori: "Bilmece", soru: "En şişman hayvan hangisidir?", secenekler: { A: "Bit (içinde 'it' var)", B: "Su aygırı", C: "Balina", D: "Fil" }, dogruCevap: "A" },
    { seviye: 263, kategori: "Bilmece", soru: "Hangi saat çalışmaz?", secenekler: { A: "Güneş saati", B: "Bozuk saat", C: "Kum saati", D: "Duvar saati" }, dogruCevap: "C" },
    { seviye: 264, kategori: "Bilmece", soru: "İçinde bir akrep var ama sokmaz.", secenekler: { A: "Kutu", B: "Saat", C: "Kaktüs", D: "Çöl" }, dogruCevap: "B" },
    { seviye: 265, kategori: "Bilmece", soru: "Dışı bahar, içi kış; her zaman soğuk kalır.", secenekler: { A: "Buzdolabı", B: "Kuyu", C: "Dağ", D: "Mağara" }, dogruCevap: "A" },
    { seviye: 266, kategori: "Bilmece", soru: "Bir sihirli değneğim var, kime değse değiştirir.", secenekler: { A: "Zaman", B: "Kalem", C: "Para", D: "Sabun" }, dogruCevap: "B" },
    { seviye: 267, kategori: "Bilmece", soru: "Hangi ayda 28 gün vardır?", secenekler: { A: "Ocak", B: "Mart", C: "Şubat", D: "Hepsinde" }, dogruCevap: "D" },
    { seviye: 268, kategori: "Bilmece", soru: "Kullanırken yere atarız, işimiz bitince geri alırız.", secenekler: { A: "Çöp", B: "Çapa", C: "Top", D: "Olta" }, dogruCevap: "B" },
    { seviye: 269, kategori: "Bilmece", soru: "En acı biber nerede yetişir?", secenekler: { A: "Hindistan", B: "Urfa", C: "Dilin ucunda", D: "Meksika" }, dogruCevap: "C" },
    { seviye: 270, kategori: "Bilmece", soru: "Kimlerin evi olmaz?", secenekler: { A: "Salyangozların (evini sırtında taşır)", B: "Balıkların", C: "Fakirlerin", D: "Kuşların" }, dogruCevap: "A" },
    { seviye: 271, kategori: "Bilmece", soru: "Hangi perde pencereye asılmaz?", secenekler: { A: "Stor perde", B: "Tül perde", C: "Sahne perdesi", D: "Göz perdesi" }, dogruCevap: "D" },
    { seviye: 272, kategori: "Bilmece", soru: "En dertli dağ hangisidir?", secenekler: { A: "Kaçkar", B: "Erciyes", C: "Ağrı Dağı", D: "Everest" }, dogruCevap: "C" },
    { seviye: 273, kategori: "Bilmece", soru: "Su üstünde yürür, iz bırakmaz.", secenekler: { A: "Işık", B: "Balık", C: "Böcek", D: "Gemi" }, dogruCevap: "D" },
    { seviye: 274, kategori: "Bilmece", soru: "Hangi fil hortum kullanmaz?", secenekler: { A: "Beyaz fil", B: "Oyuncak fil", C: "Satrançtaki fil", D: "Yavru fil" }, dogruCevap: "C" },
    { seviye: 275, kategori: "Bilmece", soru: "Başına taktıkça kısalan şey nedir?", secenekler: { A: "Kalem", B: "Kurşun kalem", C: "Şapka", D: "Taç" }, dogruCevap: "B" },
    { seviye: 276, kategori: "Bilmece", soru: "Önceleri beş idi, şimdi oldu dört; yakında üç kalacak.", secenekler: { A: "Parmaklar", B: "Yüzyıllar", C: "Duyu organları", D: "Mevsimler" }, dogruCevap: "D" },
    { seviye: 277, kategori: "Bilmece", soru: "Hangi kuşun kanadı var ama uçamaz?", secenekler: { A: "Penguen", B: "Devekuşu", C: "Hepsi", D: "Tavuk" }, dogruCevap: "C" },
    { seviye: 278, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "Kavun", B: "Ton-balığı", C: "Balkabağı", D: "Karpuz" }, dogruCevap: "B" },
    { seviye: 279, kategori: "Bilmece", soru: "Ayakta doğar, yatarak ölür.", secenekler: { A: "Ağaç", B: "Güneş", C: "Çiçek", D: "İnsan" }, dogruCevap: "A" },
    { seviye: 280, kategori: "Bilmece", soru: "Hangi kutu açılmaz?", secenekler: { A: "Müzik kutusu", B: "Boy kutusu", C: "Pandora'nın kutusu", D: "Hediye kutusu" }, dogruCevap: "B" },
    { seviye: 281, kategori: "Bilmece", soru: "Bir ağzı var, bin konuşur.", secenekler: { A: "Kitap", B: "Yazar", C: "Radyo", D: "Mektup" }, dogruCevap: "A" },
    { seviye: 282, kategori: "Bilmece", soru: "Sırtında taşır evini, yavaş yürür sevinçli.", secenekler: { A: "Salyangoz", B: "Kirpi", C: "Yengeç", D: "Kaplumbağa" }, dogruCevap: "A" },
    { seviye: 283, kategori: "Bilmece", soru: "Kökü var ağaç değil, dişi var ısırır.", secenekler: { A: "Testere", B: "Tarak", C: "Soğan", D: "Sarımsak" }, dogruCevap: "D" },
    { seviye: 284, kategori: "Bilmece", soru: "Ateşe girer yanmaz, suya girer batmaz.", secenekler: { A: "Işık", B: "Hava", C: "Gölge", D: "Duman" }, dogruCevap: "C" },
    { seviye: 285, kategori: "Bilmece", soru: "Hangi yolun sonu yoktur?", secenekler: { A: "Samanyolu", B: "Demiryolu", C: "Otoyol", D: "Çıkmaz sokak" }, dogruCevap: "A" },
    { seviye: 286, kategori: "Bilmece", soru: "Her şeyi görür ama kendini göremez.", secenekler: { A: "Fotoğraf", B: "Kamera", C: "Göz", D: "Ayna" }, dogruCevap: "C" },
    { seviye: 287, kategori: "Bilmece", soru: "Canlıyı korur, cansızın içinde durur.", secenekler: { A: "Kıyafet", B: "Ev", C: "Ayakkabı", D: "Kafes" }, dogruCevap: "C" },
    { seviye: 288, kategori: "Bilmece", soru: "İki kardeş var, birbirini hiç görmez.", secenekler: { A: "Ayaklar", B: "Gözler", C: "Eller", D: "Kulaklar" }, dogruCevap: "B" },
    { seviye: 289, kategori: "Bilmece", soru: "Hangi dağda kar olmaz?", secenekler: { A: "Yüce dağlarda", B: "Kışın", C: "Resimdeki dağda", D: "Volkanik dağlarda" }, dogruCevap: "C" },
    { seviye: 290, kategori: "Bilmece", soru: "İçi boş, dışı hoş; vurdun mu ses verir.", secenekler: { A: "Davul", B: "Keman", C: "Flüt", D: "Zil" }, dogruCevap: "A" },
    { seviye: 291, kategori: "Bilmece", soru: "Burnu var, yüzü yok.", secenekler: { A: "Geminin burnu", B: "Ayakkabı", C: "Gözlük", D: "Heykel" }, dogruCevap: "B" },
    { seviye: 292, kategori: "Bilmece", soru: "Tavuk ne zaman 'yumurta' demez?", secenekler: { A: "Korktuğunda", B: "Konuşamadığında", C: "Uyuduğunda", D: "Yumurtladığında" }, dogruCevap: "B" },
    { seviye: 293, kategori: "Bilmece", soru: "En hüzünlü başkent hangisidir?", secenekler: { A: "Ağrı", B: "Paris", C: "Roma", D: "Bağdat" }, dogruCevap: "A" },
    { seviye: 294, kategori: "Bilmece", soru: "Açarsın çıkar, kaparsın girer.", secenekler: { A: "Dil (konuşurken)", B: "Kapı", C: "Dil", D: "Dil (fermuar)" }, dogruCevap: "D" },
    { seviye: 295, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Naneli", B: "Meyveli", C: "Domatesli", D: "Cam macunu" }, dogruCevap: "D" },
    { seviye: 296, kategori: "Bilmece", soru: "Dünyanın en büyük anahtarı hangisidir?", secenekler: { A: "Altın anahtar", B: "İspanya (haritadaki şekli)", C: "Gemi anahtarı", D: "Kilit anahtarı" }, dogruCevap: "B" },
    { seviye: 297, kategori: "Bilmece", soru: "İçinde balık olan ama su olmayan şey nedir?", secenekler: { A: "Konserve kutusu", B: "Balıkçı ağı", C: "Rüya", D: "Akvaryum" }, dogruCevap: "A" },
    { seviye: 298, kategori: "Bilmece", soru: "Hangi kalem silinmez?", secenekler: { A: "Kader kalemi", B: "Keçeli", C: "Kurşun", D: "Tükenmez" }, dogruCevap: "A" },
    { seviye: 299, kategori: "Bilmece", soru: "Ağacı var gölgesi yok.", secenekler: { A: "Soy ağacı", B: "Kurumuş ağaç", C: "Kaktüs", D: "Küçük ağaç" }, dogruCevap: "A" },
    { seviye: 300, kategori: "Bilmece", soru: "Gözleri var görmez, kanatları var uçmaz.", secenekler: { A: "Oyuncak", B: "Ölü kuş", C: "Gözlük", D: "Heykel" }, dogruCevap: "D" },
    { seviye: 301, kategori: "Bilmece", soru: "Su altında hangi canlı boğulmaz?", secenekler: { A: "Balık", B: "Deniz yıldızı", C: "Yengeç", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 302, kategori: "Bilmece", soru: "Canlıyken bağıran, ölüyken susan nedir?", secenekler: { A: "Davul", B: "Kuzu", C: "Düdük", D: "Odun" }, dogruCevap: "D" },
    { seviye: 303, kategori: "Bilmece", soru: "Altı ayaklı, iki kafalı, yürür gider.", secenekler: { A: "At ve binici", B: "Karınca", C: "Böcek", D: "Sirk elemanı" }, dogruCevap: "A" },
    { seviye: 304, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Elma", B: "Üzüm", C: "Yıkanmış meyve", D: "Kiraz" }, dogruCevap: "C" },
    { seviye: 305, kategori: "Bilmece", soru: "Hangi kanatla uçulmaz?", secenekler: { A: "Kuş kanadı", B: "Uçak kanadı", C: "Kapı kanadı", D: "Kelebek kanadı" }, dogruCevap: "C" },
    { seviye: 306, kategori: "Bilmece", soru: "Diri girer fırına, ekmek olur sofraya.", secenekler: { A: "Odun", B: "Ateş", C: "Hamur", D: "Buğday" }, dogruCevap: "C" },
    { seviye: 307, kategori: "Bilmece", soru: "Eli var kolu yok, göbeği var canı yok.", secenekler: { A: "Gömlek", B: "Yelek", C: "Ceket", D: "Pantolon" }, dogruCevap: "B" },
    { seviye: 308, kategori: "Bilmece", soru: "Gece çıkar, gündüz kaçar.", secenekler: { A: "Ay", B: "Yarasa", C: "Hırsız", D: "Yıldız" }, dogruCevap: "B" },
    { seviye: 309, kategori: "Bilmece", soru: "Hangi örtü masaya serilmez?", secenekler: { A: "Kumaş", B: "Dantel", C: "Kar örtüsü", D: "Naylon" }, dogruCevap: "C" },
    { seviye: 310, kategori: "Bilmece", soru: "İçinde bir dünya var ama yaşanmaz.", secenekler: { A: "Küre", B: "Kitap", C: "Televizyon", D: "Ayna" }, dogruCevap: "A" },
    { seviye: 311, kategori: "Bilmece", soru: "En büyük defter hangisidir?", secenekler: { A: "Nüfus defteri", B: "Anı defteri", C: "Harita defteri", D: "Dürbün" }, dogruCevap: "A" },
    { seviye: 312, kategori: "Bilmece", soru: "Sesi var, kulağı yok; dili var, ağzı yok.", secenekler: { A: "Radyo", B: "Gramofon", C: "Yankı", D: "Telefon" }, dogruCevap: "C" },
    { seviye: 313, kategori: "Bilmece", soru: "Ay varken çıkar, güneş varken kaçar.", secenekler: { A: "Karanlık", B: "Uyku", C: "Yıldız", D: "Baykuş" }, dogruCevap: "A" },
    { seviye: 314, kategori: "Bilmece", soru: "En tatlı düşman hangisidir?", secenekler: { A: "Uyku", B: "Şeker", C: "Çikolata", D: "Zaman" }, dogruCevap: "A" },
    { seviye: 315, kategori: "Bilmece", soru: "Hangi parmakla gösterilmez?", secenekler: { A: "İşaret parmağı", B: "Yüzük parmağı", C: "Ayak parmağı", D: "Baş parmak" }, dogruCevap: "C" },
    { seviye: 316, kategori: "Bilmece", soru: "Yerin altında turuncu kılıç.", secenekler: { A: "Solucan", B: "Havuç", C: "Turp", D: "Patates" }, dogruCevap: "B" },
    { seviye: 317, kategori: "Bilmece", soru: "Yazın buz tutar, kışın çözülür.", secenekler: { A: "Göl", B: "Deniz", C: "Buzdolabı", D: "Dondurma" }, dogruCevap: "C" },
    { seviye: 318, kategori: "Bilmece", soru: "En çok hangi tene dokunulur?", secenekler: { A: "El", B: "Düğme (ten-e)", C: "Anten", D: "Yüz" }, dogruCevap: "C" },
    { seviye: 319, kategori: "Bilmece", soru: "Hangi köprüden geçilmez?", secenekler: { A: "Taş köprü", B: "Göz köprüsü", C: "Asma köprü", D: "Haliç köprüsü" }, dogruCevap: "B" },
    { seviye: 320, kategori: "Bilmece", soru: "Dışı kireç gibi beyaz, içi bal gibi tatlı.", secenekler: { A: "Kavun", B: "Muz", C: "İncir", D: "Yumurta" }, dogruCevap: "C" },
    { seviye: 321, kategori: "Bilmece", soru: "Hangi adamın burnu uzar?", secenekler: { A: "Uzun adam", B: "Kardan adam", C: "Yalancı adam", D: "Pinokyo" }, dogruCevap: "D" },
    { seviye: 322, kategori: "Bilmece", soru: "Tavuklar neden yumurtlar?", secenekler: { A: "Bıraksalar kırılacağı için", B: "Yemek için", C: "Üremek için", D: "Acıktıkları için" }, dogruCevap: "A" },
    { seviye: 323, kategori: "Bilmece", soru: "En hızlı koşan meyve hangisidir?", secenekler: { A: "Armut", B: "Elma", C: "Hıyar (koşar hıyar)", D: "Üzüm" }, dogruCevap: "C" },
    { seviye: 324, kategori: "Bilmece", soru: "Hangi tene güneş vurmaz?", secenekler: { A: "Anten", B: "Sarışın", C: "Esmer", D: "Karton" }, dogruCevap: "A" },
    { seviye: 325, kategori: "Bilmece", soru: "Ayakları var ama yere basmaz.", secenekler: { A: "Uçak", B: "Sandalye", C: "Kuş", D: "Gözlük" }, dogruCevap: "D" },
    { seviye: 326, kategori: "Bilmece", soru: "Gidilmeyen tek yer neresidir?", secenekler: { A: "Gelecek", B: "Dün", C: "Güneş", D: "Mars" }, dogruCevap: "B" },
    { seviye: 327, kategori: "Bilmece", soru: "Hangi masada oturulmaz?", secenekler: { A: "Dosya masası", B: "Yemek", C: "Kare", D: "Yuvarlak" }, dogruCevap: "A" },
    { seviye: 328, kategori: "Bilmece", soru: "Ateşe atılsa yanmaz, suya atılsa batmaz.", secenekler: { A: "Işık", B: "Buz", C: "Gölge", D: "Pamuk" }, dogruCevap: "C" },
    { seviye: 329, kategori: "Bilmece", soru: "Hangi meyve içilmez?", secenekler: { A: "Elma", B: "Vişne", C: "Şeftali (içilmez, yenir)", D: "Portakal" }, dogruCevap: "C" },
    { seviye: 330, kategori: "Bilmece", soru: "Kulağını bükünce dünyayı duyar.", secenekler: { A: "Kulaklık", B: "Telefon", C: "Televizyon", D: "Radyo" }, dogruCevap: "D" },
    { seviye: 331, kategori: "Bilmece", soru: "Siyah beyaz ama renkli değil.", secenekler: { A: "Panda", B: "Zebra", C: "Eski TV", D: "Gazete" }, dogruCevap: "D" },
    { seviye: 332, kategori: "Bilmece", soru: "İnsan ne zaman taş olur?", secenekler: { A: "Başına 'beş' gelince", B: "Donunca", C: "Ölünce", D: "Korkunca" }, dogruCevap: "A" },
    { seviye: 333, kategori: "Bilmece", soru: "Hangi bağda üzüm olmaz?", secenekler: { A: "Saman bağı", B: "Karabağ", C: "Fular bağı", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 334, kategori: "Bilmece", soru: "Gözle görülür, elle tutulmaz; kaçarsın kovalar.", secenekler: { A: "Zaman", B: "Bulut", C: "Gölge", D: "Duman" }, dogruCevap: "C" },
    { seviye: 335, kategori: "Bilmece", soru: "Yürür yürür iz etmez, hızlı gider toz etmez.", secenekler: { A: "Işık", B: "Bulut", C: "Gemi", D: "Rüzgar" }, dogruCevap: "C" },
    { seviye: 336, kategori: "Bilmece", soru: "Hangi kalemle resim yapılmaz?", secenekler: { A: "Kontrol kalemi", B: "Dolma", C: "Sulu", D: "Pastel" }, dogruCevap: "A" },
    { seviye: 337, kategori: "Bilmece", soru: "İçinde dumanı, dışında ormanı.", secenekler: { A: "Dağ", B: "Fabrika", C: "Vapur", D: "Soba" }, dogruCevap: "A" },
    { seviye: 338, kategori: "Bilmece", soru: "Suya düşer batmaz, ateşe düşer yanmaz.", secenekler: { A: "Odun", B: "Gölge", C: "Kağıt", D: "Pamuk" }, dogruCevap: "B" },
    { seviye: 339, kategori: "Bilmece", soru: "En tatlı ilimiz hangisidir?", secenekler: { A: "Gaziantep", B: "Balıkesir", C: "Şekerpınar", D: "Aydın" }, dogruCevap: "B" },
    { seviye: 340, kategori: "Bilmece", soru: "Bir ağacı var meyvesi yok.", secenekler: { A: "Söğüt", B: "Kavak", C: "Çam", D: "Soy ağacı" }, dogruCevap: "D" },
    { seviye: 341, kategori: "Bilmece", soru: "Hangi tene krem sürülmez?", secenekler: { A: "Anten", B: "Esmer", C: "Karton", D: "Güneş yanığı" }, dogruCevap: "A" },
    { seviye: 342, kategori: "Bilmece", soru: "Ayakları var ama çorap giymez.", secenekler: { A: "Masa", B: "Sandalye", C: "Kedi", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 343, kategori: "Bilmece", soru: "Hangi kutu çöpe atılmaz?", secenekler: { A: "Seçim kutusu", B: "Hediye kutusu", C: "Boş kutu", D: "Sandık" }, dogruCevap: "A" },
    { seviye: 344, kategori: "Bilmece", soru: "Yerin altında gümüş kemer.", secenekler: { A: "Solucan", B: "Kök", C: "Yılan", D: "Su" }, dogruCevap: "C" },
    { seviye: 345, kategori: "Bilmece", soru: "En dertli meyve hangisidir?", secenekler: { A: "Üzüm", B: "İncir", C: "Ayva", D: "Nar" }, dogruCevap: "C" },
    { seviye: 346, kategori: "Bilmece", soru: "Hangi yolun sonu yoktur?", secenekler: { A: "Otoban", B: "Samanyolu", C: "Labirent", D: "Tren yolu" }, dogruCevap: "B" },
    { seviye: 347, kategori: "Bilmece", soru: "Gözleri var görmez, ağzı var yemez.", secenekler: { A: "Heykel", B: "Bebek", C: "Hepsi", D: "Oyuncak" }, dogruCevap: "C" },
    { seviye: 348, kategori: "Bilmece", soru: "Dışı odun, içi duman.", secenekler: { A: "Vapur", B: "Baca", C: "Ev", D: "Soba" }, dogruCevap: "D" },
    { seviye: 349, kategori: "Bilmece", soru: "En büyük anahtar hangisidir?", secenekler: { A: "İspanya", B: "Kader", C: "Kilit", D: "Altın" }, dogruCevap: "A" },
    { seviye: 350, kategori: "Bilmece", soru: "Hem ağlar hem güler, yüzünü yere sürer.", secenekler: { A: "Bebek", B: "Bulut", C: "Silecek", D: "Mendil" }, dogruCevap: "B" },
    // 351-500: Yeni Eklenen Bilmeceler
    { seviye: 351, kategori: "Bilmece", soru: "Hangi örtü masaya serilmez?", secenekler: { A: "Bitki örtüsü", B: "Muşamba", C: "Kumaş", D: "Dantel" }, dogruCevap: "A" },
    { seviye: 352, kategori: "Bilmece", soru: "Sıfırdan başlar, sonsuza gider, ama hiç hareket etmez.", secenekler: { A: "Düşünce", B: "Yol", C: "Zaman", D: "Sayılar" }, dogruCevap: "D" },
    { seviye: 353, kategori: "Bilmece", soru: "Dili yok ama dünyayı gezdirir.", secenekler: { A: "Pasaport", B: "Gemi", C: "Uçak", D: "Kitap" }, dogruCevap: "D" },
    { seviye: 354, kategori: "Bilmece", soru: "Tarlada yeşil, bakkalda siyah, evde kırmızı.", secenekler: { A: "Kömür", B: "Biber", C: "Zeytin", D: "Çay" }, dogruCevap: "D" },
    { seviye: 355, kategori: "Bilmece", soru: "Hangi adamın burnu havuçtur?", secenekler: { A: "Kardan adam", B: "Çiftçi", C: "Manav", D: "Aşçı" }, dogruCevap: "A" },
    { seviye: 356, kategori: "Bilmece", soru: "En geniş kap hangisidir?", secenekler: { A: "Bardak", B: "Kapak", C: "Kazan", D: "Ayakkabı" }, dogruCevap: "B" },
    { seviye: 357, kategori: "Bilmece", soru: "Hangi şehirde meyve satılmaz?", secenekler: { A: "Manisa", B: "Armutlu", C: "Elmalı", D: "Pazarsız" }, dogruCevap: "D" },
    { seviye: 358, kategori: "Bilmece", soru: "Küçücük bakkal, dünyayı yutar.", secenekler: { A: "Göz", B: "Zihin", C: "Kulak", D: "Ağız" }, dogruCevap: "A" },
    { seviye: 359, kategori: "Bilmece", soru: "Suyu var balığı yok, yolu var arabası yok.", secenekler: { A: "Resim", B: "Rüya", C: "Harita", D: "Çöl" }, dogruCevap: "C" },
    { seviye: 360, kategori: "Bilmece", soru: "Yazın giyinir, kışın soyunur.", secenekler: { A: "Ağaç", B: "Güneş", C: "Yılan", D: "Vantilatör" }, dogruCevap: "A" },
    { seviye: 361, kategori: "Bilmece", soru: "Hangi kalemle resim yapılmaz?", secenekler: { A: "Kontrol kalemi", B: "Boya kalemi", C: "Dolma kalem", D: "Kurşun kalem" }, dogruCevap: "A" },
    { seviye: 362, kategori: "Bilmece", soru: "Hangi kuşun adı sebzedir?", secenekler: { A: "Serçe", B: "Enginar", C: "Kırlangıç", D: "Saka" }, dogruCevap: "B" },
    { seviye: 363, kategori: "Bilmece", soru: "Dışı var içi yok, dayak yer suçu yok.", secenekler: { A: "Top", B: "Yastık", C: "Halı", D: "Davul" }, dogruCevap: "D" },
    { seviye: 364, kategori: "Bilmece", soru: "Kolu var eli yok, karnı yarık karnı yok.", secenekler: { A: "Gömlek", B: "Ceket", C: "Yelek", D: "Pantolon" }, dogruCevap: "B" },
    { seviye: 365, kategori: "Bilmece", soru: "En tatlı meyve hangisidir?", secenekler: { A: "Uyku", B: "Muz", C: "İncir", D: "Çilek" }, dogruCevap: "A" },
    { seviye: 366, kategori: "Bilmece", soru: "Hangi soruya asla 'evet' denmez?", secenekler: { A: "Hepsi", B: "Öldün mü?", C: "Uyuyor musun?", D: "Burada mısın?" }, dogruCevap: "A" },
    { seviye: 367, kategori: "Bilmece", soru: "Hem ısıtır, hem yakar.", secenekler: { A: "Güneş", B: "Soba", C: "Biber", D: "Ateş" }, dogruCevap: "C" },
    { seviye: 368, kategori: "Bilmece", soru: "İncecik beli, elimdedir dili.", secenekler: { A: "Kalem", B: "Kaşık", C: "Zil", D: "Bardak" }, dogruCevap: "A" },
    { seviye: 369, kategori: "Bilmece", soru: "Hangi meyve her zaman yalnızdır?", secenekler: { A: "Armut", B: "Vişne", C: "Üzüm", D: "Elma" }, dogruCevap: "A" },
    { seviye: 370, kategori: "Bilmece", soru: "Yer altında yağlı kayış.", secenekler: { A: "Yılan", B: "Solucan", C: "Hortum", D: "Kemer" }, dogruCevap: "A" },
    { seviye: 371, kategori: "Bilmece", soru: "Başı var beyni yok.", secenekler: { A: "Mısır", B: "Soğan", C: "Papatya", D: "Lale" }, dogruCevap: "B" },
    { seviye: 372, kategori: "Bilmece", soru: "Karşıdan baktım hiç yok, yanına gittim pek çok.", secenekler: { A: "Ağaç", B: "Çiçek", C: "Karınca", D: "Kum" }, dogruCevap: "C" },
    { seviye: 373, kategori: "Bilmece", soru: "Hangi saatte yemek yenmez?", secenekler: { A: "Duvar saatinde", B: "Gece saatinde", C: "Öğle saatinde", D: "Sabah saatinde" }, dogruCevap: "A" },
    { seviye: 374, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Üzüm bağı", B: "Karabağ", C: "Ayakkabı bağı", D: "Siyah bağ" }, dogruCevap: "C" },
    { seviye: 375, kategori: "Bilmece", soru: "Sesi var canı yok, konuşur ağzı yok.", secenekler: { A: "Yankı", B: "Rüzgar", C: "Telefon", D: "Radyo" }, dogruCevap: "A" },
    { seviye: 376, kategori: "Bilmece", soru: "Hangi denizde balık bulunmaz?", secenekler: { A: "Ege Denizi", B: "Akdeniz", C: "Ölü Deniz", D: "Karadeniz" }, dogruCevap: "C" },
    { seviye: 377, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "İncir", B: "Balkabağı", C: "Karpuz", D: "Kavun" }, dogruCevap: "A" },
    { seviye: 378, kategori: "Bilmece", soru: "Suya düşer ıslanmaz, yere düşer paslanmaz.", secenekler: { A: "Güneş", B: "Hava", C: "Işık", D: "Gölge" }, dogruCevap: "D" },
    { seviye: 379, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Asya fili", B: "Profil", C: "Afrika fili", D: "Yavru fil" }, dogruCevap: "B" },
    { seviye: 380, kategori: "Bilmece", soru: "Yatınca yatar, kalkınca kalkar.", secenekler: { A: "Yorgan", B: "Ayak", C: "Parmak", D: "Göz" }, dogruCevap: "C" },
    { seviye: 381, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Ziraat Bankası", B: "Merkez Bankası", C: "Halk Bankası", D: "Kan Bankası" }, dogruCevap: "D" },
    { seviye: 382, kategori: "Bilmece", soru: "Kapağı var kitap değil, kulu var kapı değil.", secenekler: { A: "Çanta", B: "Göz", C: "Dolap", D: "Tencere" }, dogruCevap: "B" },
    { seviye: 383, kategori: "Bilmece", soru: "Hangi kovanın balı olmaz?", secenekler: { A: "Arı kovanı", B: "Yeni kovan", C: "Kulak kovanı", D: "Eski kovan" }, dogruCevap: "C" },
    { seviye: 384, kategori: "Bilmece", soru: "Her şeyi görür ama kendini göremez.", secenekler: { A: "Dürbün", B: "Kamera", C: "Ayna", D: "Göz" }, dogruCevap: "D" },
    { seviye: 385, kategori: "Bilmece", soru: "Hangi tastan su içilmez?", secenekler: { A: "Gümüş tas", B: "Kafatası", C: "Bakır tas", D: "Altın tas" }, dogruCevap: "B" },
    { seviye: 386, kategori: "Bilmece", soru: "Pişirirsen aş olur, pişirmezsen kuş olur.", secenekler: { A: "Mısır", B: "Buğday", C: "Pirinç", D: "Yumurta" }, dogruCevap: "D" },
    { seviye: 387, kategori: "Bilmece", soru: "Gökten iner bir avuç, tadı şekerden tatlı.", secenekler: { A: "Yağmur", B: "Dut", C: "Kar", D: "Dolu" }, dogruCevap: "B" },
    { seviye: 388, kategori: "Bilmece", soru: "Dili var konuşamaz, ayağı var yürüyemez.", secenekler: { A: "Masa", B: "Araba", C: "Ayakkabı", D: "Sandalye" }, dogruCevap: "C" },
    { seviye: 389, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Üzüm", B: "Yıkanmış kiraz", C: "Yalan", D: "Elma" }, dogruCevap: "C" },
    { seviye: 390, kategori: "Bilmece", soru: "Açarsın içini, görürsün kendini.", secenekler: { A: "Kitap", B: "Dolap", C: "Ayna", D: "Kapı" }, dogruCevap: "C" },
    { seviye: 391, kategori: "Bilmece", soru: "Sıcak dondurma nerede bulunur?", secenekler: { A: "Mutfakta", B: "Buzdolabında", C: "Güneşte", D: "Fırında" }, dogruCevap: "D" },
    { seviye: 392, kategori: "Bilmece", soru: "En dertli meyve hangisidir?", secenekler: { A: "Vişne", B: "Nar", C: "İncir", D: "Ayva" }, dogruCevap: "D" },
    { seviye: 393, kategori: "Bilmece", soru: "Hangi yolun sonu yoktur?", secenekler: { A: "Tren yolu", B: "Labirent", C: "Otoban", D: "Samanyolu" }, dogruCevap: "D" },
    { seviye: 394, kategori: "Bilmece", soru: "Ayakları var ama çorap giymez.", secenekler: { A: "Kedi", B: "Hepsi", C: "Masa", D: "Köpek" }, dogruCevap: "B" },
    { seviye: 395, kategori: "Bilmece", soru: "Hangi kutu çöpe atılmaz?", secenekler: { A: "Hediye kutusu", B: "Seçim kutusu", C: "Karton kutu", D: "Boş kutu" }, dogruCevap: "B" },
    { seviye: 396, kategori: "Bilmece", soru: "Yerin altında gümüş kemer.", secenekler: { A: "Solucan", B: "Yılan", C: "Su", D: "Kök" }, dogruCevap: "B" },
    { seviye: 397, kategori: "Bilmece", soru: "Hangi gül kokmaz?", secenekler: { A: "Yapay gül", B: "Kurumuş gül", C: "Solmuş gül", D: "Virgül" }, dogruCevap: "D" },
    { seviye: 398, kategori: "Bilmece", soru: "Hangi havuzda su olmaz?", secenekler: { A: "Boş havuz", B: "Bilardo havuzu", C: "Olimpik havuz", D: "Süs havuzu" }, dogruCevap: "B" },
    { seviye: 399, kategori: "Bilmece", soru: "Hangi on'un sonu yoktur?", secenekler: { A: "Limon", B: "Oyun", C: "Balon", D: "Kamyon" }, dogruCevap: "D" },
    { seviye: 400, kategori: "Bilmece", soru: "Kışın yatıyor, yazın kalkıyor.", secenekler: { A: "Soba", B: "Ayı", C: "Yorgan", D: "Dondurma" }, dogruCevap: "A" },
    { seviye: 401, kategori: "Bilmece", soru: "Dokunmadan kırılan şey nedir?", secenekler: { A: "Buz", B: "Ayna", C: "Kalp", D: "Cam" }, dogruCevap: "C" },
    { seviye: 402, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Sürücü karnesi", B: "Okul karnesi", C: "Sağlık karnesi", D: "Başarı karnesi" }, dogruCevap: "C" },
    { seviye: 403, kategori: "Bilmece", soru: "Hangi meyve ile yazı yazılır?", secenekler: { A: "Elma", B: "Kiraz", C: "Ayva", D: "Çilek" }, dogruCevap: "B" },
    { seviye: 404, kategori: "Bilmece", soru: "Hangi başa şapka giyilmez?", secenekler: { A: "Dağ başına", B: "Çeşme başına", C: "Kel başa", D: "Yol başına" }, dogruCevap: "B" },
    { seviye: 405, kategori: "Bilmece", soru: "İçer içersin bitmez, tadına doyum yetmez.", secenekler: { A: "Süt", B: "Çay", C: "Su", D: "Hava" }, dogruCevap: "D" },
    { seviye: 406, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Kar topu", B: "Tenis topu", C: "Futbol topu", D: "Basketbol topu" }, dogruCevap: "A" },
    { seviye: 407, kategori: "Bilmece", soru: "Bağlayınca yürür, çözünce durur.", secenekler: { A: "Gemi", B: "Araba", C: "Ayakkabı", D: "At" }, dogruCevap: "C" },
    { seviye: 408, kategori: "Bilmece", soru: "Hangi pas silinmez?", secenekler: { A: "Pasaport", B: "Demir pası", C: "Yemek pası", D: "Halı pası" }, dogruCevap: "A" },
    { seviye: 409, kategori: "Bilmece", soru: "Hangi kanatla uçulmaz?", secenekler: { A: "Uçak kanadı", B: "Kuş kanadı", C: "Kapı kanadı", D: "Kelebek kanadı" }, dogruCevap: "C" },
    { seviye: 410, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Tükenmez", B: "Kontrol", C: "Dolma", D: "Kurşun" }, dogruCevap: "B" },
    { seviye: 411, kategori: "Bilmece", soru: "En büyük kutu hangisidir?", secenekler: { A: "Hediye kutusu", B: "Gökyüzü", C: "Sandık", D: "Karton kutu" }, dogruCevap: "B" },
    { seviye: 412, kategori: "Bilmece", soru: "Yılan hangi dilde konuşur?", secenekler: { A: "Tıslayarak", B: "Isırarak", C: "Sessizce", D: "Yılanca" }, dogruCevap: "D" },
    { seviye: 413, kategori: "Bilmece", soru: "Hangi diş fırçalanmaz?", secenekler: { A: "Süt dişi", B: "Azı dişi", C: "Sarımsak dişi", D: "Yirmilik diş" }, dogruCevap: "C" },
    { seviye: 414, kategori: "Bilmece", soru: "En son hangi diş çıkar?", secenekler: { A: "Azı dişi", B: "Yirmilik diş", C: "Takma diş", D: "Süt dişi" }, dogruCevap: "C" },
    { seviye: 415, kategori: "Bilmece", soru: "Hangi düğüm çözülmez?", secenekler: { A: "Kravat düğümü", B: "Kör düğüm", C: "Gemicilik düğümü", D: "Gördüğüm" }, dogruCevap: "D" },
    { seviye: 416, kategori: "Bilmece", soru: "En dertli meyve hangisidir?", secenekler: { A: "Karpuz", B: "Vişne", C: "Ayva", D: "İncir" }, dogruCevap: "C" },
    { seviye: 417, kategori: "Bilmece", soru: "Hangi tilki tavuk yemez?", secenekler: { A: "Kurnaz tilki", B: "Yavru tilki", C: "Filtre (Fil-tre)", D: "Vahşi tilki" }, dogruCevap: "C" },
    { seviye: 418, kategori: "Bilmece", soru: "En çok kar nerede bulunur?", secenekler: { A: "Dağlarda", B: "Buzdolabında", C: "Antarktika'da", D: "Sözlükte" }, dogruCevap: "D" },
    { seviye: 419, kategori: "Bilmece", soru: "Sadece kullanıldığında kırılan şey nedir?", secenekler: { A: "Fındık", B: "Yumurta", C: "Hepsi", D: "Ceviz" }, dogruCevap: "C" },
    { seviye: 420, kategori: "Bilmece", soru: "Hangi ilimizde güneş gözlüğü kullanılmaz?", secenekler: { A: "Rize", B: "Muğla", C: "Van", D: "Göz-lük" }, dogruCevap: "D" },
    { seviye: 421, kategori: "Bilmece", soru: "En hızlı rakam hangisidir?", secenekler: { A: "Bir", B: "Sıfır", C: "Yedi (Ye-di)", D: "Dokuz" }, dogruCevap: "C" },
    { seviye: 422, kategori: "Bilmece", soru: "Hangi makine ile dikiş dikilmez?", secenekler: { A: "Yıkama makinesi", B: "Fotoğraf makinesi", C: "Tıraş makinesi", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 423, kategori: "Bilmece", soru: "Denizde var karada yok.", secenekler: { A: "Kum", B: "Balık", C: "Gemi", D: "Dalga" }, dogruCevap: "D" },
    { seviye: 424, kategori: "Bilmece", soru: "Kulağını bükünce sesi çıkar.", secenekler: { A: "Radyo", B: "Keman", C: "Zil", D: "Musluk" }, dogruCevap: "D" },
    { seviye: 425, kategori: "Bilmece", soru: "İncecik beli var, tatlı dili var.", secenekler: { A: "Kalem", B: "Bardak", C: "Bebek", D: "Kaşık" }, dogruCevap: "A" },
    { seviye: 426, kategori: "Bilmece", soru: "İçi taş, dışı baş.", secenekler: { A: "Kayısı", B: "Kaplumbağa", C: "Ev", D: "Zeytin" }, dogruCevap: "B" },
    { seviye: 427, kategori: "Bilmece", soru: "Ben giderim o kalır.", secenekler: { A: "Gölge", B: "İsim", C: "Ayak izi", D: "Zaman" }, dogruCevap: "C" },
    { seviye: 428, kategori: "Bilmece", soru: "Başına konar, seni serinletir.", secenekler: { A: "Vantilatör", B: "Bulut", C: "Rüzgar", D: "Şapka" }, dogruCevap: "D" },
    { seviye: 429, kategori: "Bilmece", soru: "Elsiz ayaksız kapı açar.", secenekler: { A: "Rüzgar", B: "Hayalet", C: "Anahtar", D: "Hırsız" }, dogruCevap: "C" },
    { seviye: 430, kategori: "Bilmece", soru: "Tüyden hafif ama kimse tutamaz.", secenekler: { A: "Bulut", B: "Nefes", C: "Duman", D: "Gölge" }, dogruCevap: "B" },
    { seviye: 431, kategori: "Bilmece", soru: "Denizin ortasında ne vardır?", secenekler: { A: "N harfi", B: "Ada", C: "Gemi", D: "Balık" }, dogruCevap: "A" },
    { seviye: 432, kategori: "Bilmece", soru: "Hangi tene kolonya sürülmez?", secenekler: { A: "Sert tene", B: "Karaktene (Karakter)", C: "Yanık tene", D: "Yumuşak tene" }, dogruCevap: "B" },
    { seviye: 433, kategori: "Bilmece", soru: "Adamın biri kafasına radyo koymuş neden?", secenekler: { A: "Kafa dengi olsun diye", B: "Uyumak için", C: "Haberleri duymak için", D: "Müzik dinlemek için" }, dogruCevap: "A" },
    { seviye: 434, kategori: "Bilmece", soru: "Damlaya damlaya ne olur?", secenekler: { A: "Su olur", B: "Hepsi", C: "Göl olur", D: "Musluk bozulur" }, dogruCevap: "D" },
    { seviye: 435, kategori: "Bilmece", soru: "Hangi ay 28 çeker?", secenekler: { A: "Şubat", B: "Hepsi", C: "Ocak", D: "Mart" }, dogruCevap: "B" },
    { seviye: 436, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Naneli macun", B: "Beyaz macun", C: "Çilekli macun", D: "Lahmacun" }, dogruCevap: "D" },
    { seviye: 437, kategori: "Bilmece", soru: "Hangi kaba su doldurulmaz?", secenekler: { A: "Delik kaba", B: "Ayakkabıya", C: "Küçük kaba", D: "Kaba kuvvete" }, dogruCevap: "D" },
    { seviye: 438, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Kontrol kalemi", B: "Dolma kalem", C: "Tükenmez kalem", D: "Kurşun kalem" }, dogruCevap: "A" },
    { seviye: 439, kategori: "Bilmece", soru: "Açarsan genişler, kaparsan daralır.", secenekler: { A: "Şemsiye", B: "Kapı", C: "Pencere", D: "Perde" }, dogruCevap: "A" },
    { seviye: 440, kategori: "Bilmece", soru: "Hiç yorulmadan dünyayı gezer.", secenekler: { A: "Ay", B: "Güneş", C: "Bulut", D: "Rüzgar" }, dogruCevap: "B" },
    { seviye: 441, kategori: "Bilmece", soru: "Dışı kaktüs içi süt.", secenekler: { A: "Ananas", B: "Karpuz", C: "Hindistan cevizi", D: "Kavun" }, dogruCevap: "C" },
    { seviye: 442, kategori: "Bilmece", soru: "Hem ağlar hem güler.", secenekler: { A: "Bulut", B: "İnsan", C: "Yağmur", D: "Bebek" }, dogruCevap: "B" },
    { seviye: 443, kategori: "Bilmece", soru: "Hangi masada yemek yenmez?", secenekler: { A: "Dosya masası", B: "Yemek masası", C: "Altın masa", D: "Mutfak masası" }, dogruCevap: "A" },
    { seviye: 444, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "İp topu", B: "Kar topu", C: "Futbol topu", D: "Tenis topu" }, dogruCevap: "B" },
    { seviye: 445, kategori: "Bilmece", soru: "Gece gündüz bekler, kapıyı çalana bakar.", secenekler: { A: "Kilit", B: "Zil", C: "Bekçi", D: "Paspas" }, dogruCevap: "A" },
    { seviye: 446, kategori: "Bilmece", soru: "Kulağını büktükçe sesi yükselir.", secenekler: { A: "İnsan", B: "Radyo", C: "Keman", D: "Musluk" }, dogruCevap: "B" },
    { seviye: 447, kategori: "Bilmece", soru: "Sarıdır sallanır, tadı baldan tatlıdır.", secenekler: { A: "Ayva", B: "Armut", C: "Muz", D: "Kavun" }, dogruCevap: "B" },
    { seviye: 448, kategori: "Bilmece", soru: "Okuma yazma bilmez ama her şeyi yazar.", secenekler: { A: "Kağıt", B: "Daktilo", C: "Bilgisayar", D: "Kalem" }, dogruCevap: "D" },
    { seviye: 449, kategori: "Bilmece", soru: "Hangi kuşun adı sebzedir?", secenekler: { A: "Serçe", B: "Kırlangıç", C: "Saka", D: "Enginar" }, dogruCevap: "D" },
    { seviye: 450, kategori: "Bilmece", soru: "Hangi örtü masaya serilmez?", secenekler: { A: "Kumaş", B: "Muşamba", C: "Dantel", D: "Bitki örtüsü" }, dogruCevap: "D" },
    { seviye: 451, kategori: "Bilmece", soru: "Hangi tene kolonya sürülmez?", secenekler: { A: "Beyaz tene", B: "Sert tene", C: "Yumuşak tene", D: "Karaktene" }, dogruCevap: "D" },
    { seviye: 452, kategori: "Bilmece", soru: "Hangi ilimizde güneş gözlüğü kullanılmaz?", secenekler: { A: "Muğla", B: "Rize", C: "Van", D: "Gözlük" }, dogruCevap: "D" },
    { seviye: 453, kategori: "Bilmece", soru: "Hangi yolda yürünmez?", secenekler: { A: "Otoban", B: "Ana yol", C: "Patika", D: "Samanyolu" }, dogruCevap: "D" },
    { seviye: 454, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Ziraat bankası", B: "Merkez bankası", C: "Halk bankası", D: "Kan bankası" }, dogruCevap: "D" },
    { seviye: 455, kategori: "Bilmece", soru: "Hangi kaba su doldurulmaz?", secenekler: { A: "Cam kaba", B: "Kaba kuvvete", C: "Plastik kaba", D: "Delik kaba" }, dogruCevap: "B" },
    { seviye: 456, kategori: "Bilmece", soru: "Hangi adamın burnu havuçtur?", secenekler: { A: "Aşçı adam", B: "Kardan adam", C: "Manav adam", D: "Çiftçi adam" }, dogruCevap: "B" },
    { seviye: 457, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Başarı karnesi", B: "Sağlık karnesi", C: "Sürücü karnesi", D: "Okul karnesi" }, dogruCevap: "B" },
    { seviye: 458, kategori: "Bilmece", soru: "Hangi meyve ile yazı yazılır?", secenekler: { A: "Muz", B: "Kiraz", C: "Elma", D: "Çilek" }, dogruCevap: "B" },
    { seviye: 459, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Kar topu", B: "Tenis topu", C: "Futbol topu", D: "Basketbol topu" }, dogruCevap: "A" },
    { seviye: 460, kategori: "Bilmece", soru: "Hangi kovanın balı olmaz?", secenekler: { A: "Yeni kovan", B: "Kulak kovanı", C: "Arı kovanı", D: "Eski kovan" }, dogruCevap: "B" },
    { seviye: 461, kategori: "Bilmece", soru: "Hangi pas silinmez?", secenekler: { A: "Yemek pası", B: "Pasaport", C: "Demir pası", D: "Halı pası" }, dogruCevap: "B" },
    { seviye: 462, kategori: "Bilmece", soru: "Hangi diş fırçalanmaz?", secenekler: { A: "Yirmilik diş", B: "Sarımsak dişi", C: "Azı dişi", D: "Süt dişi" }, dogruCevap: "B" },
    { seviye: 463, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Afrika fili", B: "Asya fili", C: "Profil", D: "Yavru fil" }, dogruCevap: "C" },
    { seviye: 464, kategori: "Bilmece", soru: "Hangi başa şapka giyilmez?", secenekler: { A: "Kel başa", B: "Yol başına", C: "Dağ başına", D: "Çeşme başına" }, dogruCevap: "D" },
    { seviye: 465, kategori: "Bilmece", soru: "Hangi tastan su içilmez?", secenekler: { A: "Kafatası", B: "Bakır tas", C: "Altın tas", D: "Gümüş tas" }, dogruCevap: "A" },
    { seviye: 466, kategori: "Bilmece", soru: "Hangi kutu çöpe atılmaz?", secenekler: { A: "Karton kutu", B: "Hediye kutusu", C: "Seçim kutusu", D: "Boş kutu" }, dogruCevap: "C" },
    { seviye: 467, kategori: "Bilmece", soru: "Hangi havuzda su olmaz?", secenekler: { A: "Süs havuzu", B: "Boş havuz", C: "Olimpik havuz", D: "Bilardo havuzu" }, dogruCevap: "D" },
    { seviye: 468, kategori: "Bilmece", soru: "Hangi gül kokmaz?", secenekler: { A: "Kırmızı gül", B: "Yapay gül", C: "Beyaz gül", D: "Virgül" }, dogruCevap: "D" },
    { seviye: 469, kategori: "Bilmece", soru: "Hangi tilki tavuk yemez?", secenekler: { A: "Vahşi tilki", B: "Filtre", C: "Kurnaz tilki", D: "Yavru tilki" }, dogruCevap: "B" },
    { seviye: 470, kategori: "Bilmece", soru: "Hangi düğüm çözülmez?", secenekler: { A: "Gördüğüm", B: "Kravat düğümü", C: "Gemicilik düğümü", D: "Kör düğüm" }, dogruCevap: "A" },
    { seviye: 471, kategori: "Bilmece", soru: "Hangi makine ile dikiş dikilmez?", secenekler: { A: "Hepsi", B: "Dikiş makinesi", C: "Overlok makinesi", D: "Tıraş makinesi" }, dogruCevap: "D" },
    { seviye: 472, kategori: "Bilmece", soru: "Hangi kanatla uçulmaz?", secenekler: { A: "Kelebek kanadı", B: "Kuş kanadı", C: "Uçak kanadı", D: "Kapı kanadı" }, dogruCevap: "D" },
    { seviye: 473, kategori: "Bilmece", soru: "Hangi soruya asla 'evet' denmez?", secenekler: { A: "Öldün mü?", B: "Uyuyor musun?", C: "A ve B", D: "Burada mısın?" }, dogruCevap: "C" },
    { seviye: 474, kategori: "Bilmece", soru: "Hangi denizde balık bulunmaz?", secenekler: { A: "Ege Denizi", B: "Karadeniz", C: "Akdeniz", D: "Ölü Deniz" }, dogruCevap: "D" },
    { seviye: 475, kategori: "Bilmece", soru: "Hangi on'un sonu yoktur?", secenekler: { A: "Balon", B: "Kamyon", C: "Oyun", D: "Limon" }, dogruCevap: "B" },
    { seviye: 476, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "Karpuz", B: "Kavun", C: "İncir", D: "Balkabağı" }, dogruCevap: "D" },
    { seviye: 477, kategori: "Bilmece", soru: "En tatlı meyve hangisidir?", secenekler: { A: "Muz", B: "Çilek", C: "Uyku", D: "İncir" }, dogruCevap: "C" },
    { seviye: 478, kategori: "Bilmece", soru: "En hızlı rakam hangisidir?", secenekler: { A: "Sıfır", B: "Dokuz", C: "Bir", D: "Yedi" }, dogruCevap: "D" },
    { seviye: 479, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Kiraz", B: "Yalan", C: "Üzüm", D: "Elma" }, dogruCevap: "B" },
    { seviye: 480, kategori: "Bilmece", soru: "En dertli meyve hangisidir?", secenekler: { A: "Nar", B: "Ayva", C: "Limon", D: "Vişne" }, dogruCevap: "B" },
    { seviye: 481, kategori: "Bilmece", soru: "Damlaya damlaya ne olur?", secenekler: { A: "Su birikir", B: "Hepsi", C: "Göl olur", D: "Musluk bozulur" }, dogruCevap: "D" },
    { seviye: 482, kategori: "Bilmece", soru: "Adamın biri kafasına radyo koymuş neden?", secenekler: { A: "Haber duymak için", B: "Kafa dengi olsun diye", C: "Süs olsun diye", D: "Müzik dinlemek için" }, dogruCevap: "B" },
    { seviye: 483, kategori: "Bilmece", soru: "Suya düşer ıslanmaz, yere düşer paslanmaz.", secenekler: { A: "Hava", B: "Gölge", C: "Işık", D: "Güneş" }, dogruCevap: "B" },
    { seviye: 484, kategori: "Bilmece", soru: "Hangi ay 28 çeker?", secenekler: { A: "Ocak", B: "Şubat", C: "Hepsi", D: "Mart" }, dogruCevap: "C" },
    { seviye: 485, kategori: "Bilmece", soru: "Denizin ortasında ne vardır?", secenekler: { A: "N harfi", B: "Gemi", C: "Balık", D: "Ada" }, dogruCevap: "A" },
    { seviye: 486, kategori: "Bilmece", soru: "Hangi saatte yemek yenmez?", secenekler: { A: "Sabah saatinde", B: "Öğle saatinde", C: "Gece saatinde", D: "Duvar saatinde" }, dogruCevap: "D" },
    { seviye: 487, kategori: "Bilmece", soru: "Hangi yolda yürünmez?", secenekler: { A: "Ana yol", B: "Samanyolu", C: "Demiryolu", D: "Otoban" }, dogruCevap: "B" },
    { seviye: 488, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Beyaz macun", B: "Naneli macun", C: "Çilekli macun", D: "Lahmacun" }, dogruCevap: "D" },
    { seviye: 489, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Kontrol kalemi", B: "Tükenmez kalem", C: "Dolma kalem", D: "Kurşun kalem" }, dogruCevap: "A" },
    { seviye: 490, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Bağ evi", B: "Karabağ", C: "Üzüm bağı", D: "Ayakkabı bağı" }, dogruCevap: "D" },
    { seviye: 491, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Kan bankası", B: "Halk bankası", C: "Ziraat bankası", D: "Merkez bankası" }, dogruCevap: "A" },
    { seviye: 492, kategori: "Bilmece", soru: "Hangi kaba su doldurulmaz?", secenekler: { A: "Plastik kaba", B: "Kaba kuvvete", C: "Delik kaba", D: "Cam kaba" }, dogruCevap: "B" },
    { seviye: 493, kategori: "Bilmece", soru: "Hangi adamın burnu havuçtur?", secenekler: { A: "Kardan adam", B: "Aşçı adam", C: "Manav adam", D: "Çiftçi adam" }, dogruCevap: "A" },
    { seviye: 494, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Başarı karnesi", B: "Sürücü karnesi", C: "Okul karnesi", D: "Sağlık karnesi" }, dogruCevap: "D" },
    { seviye: 495, kategori: "Bilmece", soru: "Hangi meyve ile yazı yazılır?", secenekler: { A: "Kiraz", B: "Armut", C: "Çilek", D: "Elma" }, dogruCevap: "A" },
    { seviye: 496, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Futbol topu", B: "Tenis topu", C: "Kar topu", D: "Basketbol topu" }, dogruCevap: "C" },
    { seviye: 497, kategori: "Bilmece", soru: "Hangi kovanın balı olmaz?", secenekler: { A: "Kulak kovanı", B: "Arı kovanı", C: "Yeni kovan", D: "Eski kovan" }, dogruCevap: "A" },
    { seviye: 498, kategori: "Bilmece", soru: "Hangi pas silinmez?", secenekler: { A: "Demir pası", B: "Pasaport", C: "Yemek pası", D: "Halı pası" }, dogruCevap: "B" },
    { seviye: 499, kategori: "Bilmece", soru: "Hangi diş fırçalanmaz?", secenekler: { A: "Yirmilik diş", B: "Sarımsak dişi", C: "Süt dişi", D: "Azı dişi" }, dogruCevap: "B" },
    { seviye: 500, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Asya fili", B: "Yavru fil", C: "Afrika fili", D: "Profil" }, dogruCevap: "D" }
 
 
);