window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Memeliler ve Türkiye'nin İkonik Hayvanları
    { seviye: 1, kategori: "Canlılar", soru: "Farklı renkli gözleriyle ünlü, Van ilimize özgü kedi türü hangisidir?", secenekler: { A: "Van Kedisi", B: "Tekir", C: "Siyam", D: "Ankara Kedisi" }, dogruCevap: "A" },
    { seviye: 2, kategori: "Canlılar", soru: "Türkiye'nin en büyük vahşi kedi türü olan ve nesli tehlike altında bulunan canlı hangisidir?", secenekler: { A: "Vaşak", B: "Anadolu Parsı", C: "Aslan", D: "Sırtlan" }, dogruCevap: "B" },
    { seviye: 3, kategori: "Canlılar", soru: "Denizli ilimizin simgesi haline gelen, uzun ötüşüyle bilinen canlı hangisidir?", secenekler: { A: "Keklik", B: "Güvercin", C: "Tavus Kuşu", D: "Denizli Horozu" }, dogruCevap: "D" },
    { seviye: 4, kategori: "Canlılar", soru: "Şanlıurfa Birecik'te koruma altına alınan, nesli tükenme tehlikesindeki kuş türü?", secenekler: { A: "Turna", B: "Pelikan", C: "Kelaynak", D: "Flamingo" }, dogruCevap: "C" },
    { seviye: 5, kategori: "Canlılar", soru: "Yumurtalarını Akdeniz sahillerine (özellikle İztuzu) bırakan deniz kaplumbağası?", secenekler: { A: "Deri Sırtlı", B: "Nil Kaplumbağası", C: "Kara Kaplumbağası", D: "Caretta Caretta" }, dogruCevap: "D" },
    { seviye: 6, kategori: "Canlılar", soru: "Ankara'ya özgü, uzun tüyleriyle bilinen keçi türü hangisidir?", secenekler: { A: "Tiftik Keçisi", B: "Yaban Keçisi", C: "Kıl Keçisi", D: "Dağ Keçisi" }, dogruCevap: "A" },
    { seviye: 7, kategori: "Canlılar", soru: "Türkiye'nin tek endemik deniz memelisi olan ve Akdeniz'de yaşayan canlı?", secenekler: { A: "Akdeniz Foku", B: "Deniz Fili", C: "Balina", D: "Yunus" }, dogruCevap: "A" },
    { seviye: 8, kategori: "Canlılar", soru: "Kangallarıyla meşhur olan ilimiz hangisidir?", secenekler: { A: "Yozgat", B: "Sivas", C: "Kayseri", D: "Tokat" }, dogruCevap: "B" },
    { seviye: 9, kategori: "Canlılar", soru: "Sadece Aksaray çevresinde yetişen ve dünyaca ünlü çoban köpeği türü?", secenekler: { A: "Akbaş", B: "Çatalburun", C: "Malaklı", D: "Kangal" }, dogruCevap: "C" },
    { seviye: 10, kategori: "Canlılar", soru: "Tarsus'a özgü, avcılık yetenekleriyle bilinen köpek türü hangisidir?", secenekler: { A: "Dogo", B: "Terrier", C: "Çatalburun", D: "Kangal" }, dogruCevap: "C" },
    { seviye: 11, kategori: "Canlılar", soru: "Eskişehir'de koruma altında olan, beyaz tüyleriyle ünlü çoban köpeği?", secenekler: { A: "Kangal", B: "Karabaş", C: "Akbaş", D: "Bulldog" }, dogruCevap: "C" },
    { seviye: 12, kategori: "Canlılar", soru: "Türkiye'deki en büyük kemirgen türü hangisidir?", secenekler: { A: "Kunduz", B: "Oklu Kirpi", C: "Tarla Faresi", D: "Hint Oku" }, dogruCevap: "B" },
    { seviye: 13, kategori: "Canlılar", soru: "Anadolu yaban koyunu en çok hangi ilimizde bulunur?", secenekler: { A: "Kayseri", B: "Konya (Bozdağlar)", C: "Niğde", D: "Ankara" }, dogruCevap: "B" },
    { seviye: 14, kategori: "Canlılar", soru: "Doğu Anadolu'da yaşayan ve 'dağ faresi' olarak da bilinen canlı?", secenekler: { A: "Avurtlak", B: "Kör Fare", C: "Dağ Tavşanı", D: "Yediuyur" }, dogruCevap: "A" },
    { seviye: 15, kategori: "Canlılar", soru: "Türkiye'nin en yaygın geyik türü hangisidir?", secenekler: { A: "Kızıl Geyik", B: "Sığın", C: "Karaca", D: "Alageyik" }, dogruCevap: "A" },
    { seviye: 16, kategori: "Canlılar", soru: "Genellikle bozkırlarda yaşayan ve hızlı koşmasıyla bilinen Anadolu memelisi?", secenekler: { A: "Tilki", B: "Ceylan", C: "Kurt", D: "Anadolu Yaban Eşeği" }, dogruCevap: "B" },
    { seviye: 17, kategori: "Canlılar", soru: "Artvin çevresinde yoğun olarak bulunan Türkiye'nin en büyük yırtıcı memelisi?", secenekler: { A: "Boz Ayı", B: "Çakal", C: "Sırtlan", D: "Porsuk" }, dogruCevap: "A" },
    { seviye: 18, kategori: "Canlılar", soru: "Göller yöresinde ve sulak alanlarda yaşayan, 'su iti' olarak da bilinen canlı?", secenekler: { A: "Yunus", B: "Kunduz", C: "Su Samuru", D: "Fok" }, dogruCevap: "C" },
    { seviye: 19, kategori: "Canlılar", soru: "Anadolu'da nesli tükendiği sanılan ancak son yıllarda tekrar görülen çizgili canlı?", secenekler: { A: "Zebra", B: "Pars", C: "Kaplan", D: "Çizgili Sırtlan" }, dogruCevap: "D" },
    { seviye: 20, kategori: "Canlılar", soru: "Türkiye'nin her bölgesinde bulunan, usta bir avcı olan küçük memeli?", secenekler: { A: "Sincap", B: "Kirpi", C: "Fare", D: "Gelincik" }, dogruCevap: "D" },
    { seviye: 21, kategori: "Canlılar", soru: "Ağaçlara tırmanma yeteneğiyle bilinen kuyruğu tüylü kemirgen?", secenekler: { A: "Sincap", B: "Tavşan", C: "Kobay", D: "Hamster" }, dogruCevap: "A" },
    { seviye: 22, kategori: "Canlılar", soru: "Vücudu dikenlerle kaplı, savunma amaçlı top haline gelen canlı?", secenekler: { A: "Porsuk", B: "Kaplumbağa", C: "Kirpi", D: "Köstebek" }, dogruCevap: "C" },
    { seviye: 23, kategori: "Canlılar", soru: "Yer altında tüneller kazarak yaşayan gözleri çok küçük memeli?", secenekler: { A: "Köstebek", B: "Kertenkele", C: "Tarla Faresi", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 24, kategori: "Canlılar", soru: "Kulakları uzun, arka ayakları güçlü, hızlı zıplayan memeli?", secenekler: { A: "Tavşan", B: "Keçi", C: "Geyik", D: "Kanguru" }, dogruCevap: "A" },
    { seviye: 25, kategori: "Canlılar", soru: "Gece avlanan, kurnazlığıyla masallara konu olan canlı?", secenekler: { A: "Çakal", B: "Ayı", C: "Kurt", D: "Tilki" }, dogruCevap: "D" },

    // 26-50: Türkiye Endemik Bitkileri ve Doğa
    { seviye: 26, kategori: "Canlılar", soru: "Sadece Muğla Köyceğiz çevresinde yetişen dünyaca ünlü ağaç?", secenekler: { A: "Sığla (Günlük)", B: "Çınar", C: "Sedir", D: "Ladin" }, dogruCevap: "A" },
    { seviye: 27, kategori: "Canlılar", soru: "Dünyada sadece Şanlıurfa Halfeti'de yetişen çiçek hangisidir?", secenekler: { A: "Kara Gül", B: "Papatya", C: "Lale", D: "Nergis" }, dogruCevap: "A" },
    { seviye: 28, kategori: "Canlılar", soru: "Antalya ve çevresinde yetişen, boyu 40 metreyi bulan anıt ağaç türü?", secenekler: { A: "Gürgen", B: "Sarıçam", C: "Lübnan Sediri", D: "Meşe" }, dogruCevap: "C" },
    { seviye: 29, kategori: "Canlılar", soru: "İstanbul'un simgesi olan ve her yıl festivali yapılan çiçek?", secenekler: { A: "Erguvan", B: "Gül", C: "Karanfil", D: "Lale" }, dogruCevap: "D" },
    { seviye: 30, kategori: "Canlılar", soru: "Türkiye'de yetişen ve dondurma yapımında kullanılan bitki kökü?", secenekler: { A: "Zencefil", B: "Zerdeçal", C: "Tarçın", D: "Salep (Orkide)" }, dogruCevap: "D" },
    { seviye: 31, kategori: "Canlılar", soru: "Kaz Dağları'na özgü endemik göknar türü hangisidir?", secenekler: { A: "Kızılçam", B: "Ladin", C: "Kazdağı Göknarı", D: "Ardıç" }, dogruCevap: "C" },
    { seviye: 32, kategori: "Canlılar", soru: "Türkiye'nin en çok orman alanına sahip bölgesi hangisidir?", secenekler: { A: "Karadeniz", B: "Marmara", C: "Ege", D: "Akdeniz" }, dogruCevap: "A" },
    { seviye: 33, kategori: "Canlılar", soru: "Mantar türleri içinde en değerli olan ve Anadolu'da da yetişen tür?", secenekler: { A: "Trüf Mantarı", B: "Kültür Mantarı", C: "İstiridye", D: "Kuzu Göbeği" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Canlılar", soru: "Çukurova'nın en önemli tarımsal bitkisi (canlısı)?", secenekler: { A: "Arpa", B: "Pirinç", C: "Buğday", D: "Pamuk" }, dogruCevap: "D" },
    { seviye: 35, kategori: "Canlılar", soru: "Anadolu lalesi olarak da bilinen ve koruma altında olan bitki?", secenekler: { A: "Ters Lale", B: "Ağlayan Gelin", C: "Hepsi", D: "Manisa Lalesi" }, dogruCevap: "C" },
    { seviye: 36, kategori: "Canlılar", soru: "Karadeniz'in simgesi olan, iğne yapraklı ve çok uzun yaşayan ağaç?", secenekler: { A: "Meşe", B: "Kavak", C: "Söğüt", D: "Ladin" }, dogruCevap: "D" },
    { seviye: 37, kategori: "Canlılar", soru: "Ege ve Akdeniz mutfağının vazgeçilmezi olan meyve ağacı?", secenekler: { A: "Zeytin", B: "Elma", C: "Vişne", D: "Armut" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Canlılar", soru: "Dünyaca ünlü fındık üretimi hangi bölgemizde yapılır?", secenekler: { A: "Güneydoğu", B: "Akdeniz", C: "Ege", D: "Doğu Karadeniz" }, dogruCevap: "D" },
    { seviye: 39, kategori: "Canlılar", soru: "Isparta ilimizin dünya çapında tanınan çiçeği?", secenekler: { A: "Lale", B: "Papatya", C: "Lavanta", D: "Gül" }, dogruCevap: "D" },
    { seviye: 40, kategori: "Canlılar", soru: "Toros Dağları'nda yetişen ve kokusuyla bilinen şifalı ot?", secenekler: { A: "Dereotu", B: "Kekik", C: "Maydanoz", D: "Nane" }, dogruCevap: "B" },
    { seviye: 41, kategori: "Canlılar", soru: "Türkiye'nin en yüksek noktalarında yetişen dayanıklı ağaç?", secenekler: { A: "Ardıç", B: "Çınar", C: "Kavak", D: "Ladin" }, dogruCevap: "A" },
    { seviye: 42, kategori: "Canlılar", soru: "Meyvesinden yağ elde edilen ve Anadolu'da yaygın olan ağaç?", secenekler: { A: "Çam", B: "Gürgen", C: "Zeytin", D: "Meşe" }, dogruCevap: "C" },
    { seviye: 43, kategori: "Canlılar", soru: "Sulu alanlarda yetişen ve hızlı büyüyen uzun ağaç?", secenekler: { A: "Kavak", B: "Palamut", C: "Sedir", D: "Göknar" }, dogruCevap: "A" },
    { seviye: 44, kategori: "Canlılar", soru: "Yol kenarlarında ve su boylarında sarkan dallarıyla ünlü ağaç?", secenekler: { A: "Gürgen", B: "Salkım Söğüt", C: "Meşe", D: "Kayın" }, dogruCevap: "B" },
    { seviye: 45, kategori: "Canlılar", soru: "Sonbaharda yapraklarını dökmeyen, iğne yapraklı orman ağacı?", secenekler: { A: "Çınar", B: "Çam", C: "Kestane", D: "Ihlamur" }, dogruCevap: "B" },
    { seviye: 46, kategori: "Canlılar", soru: "Kabuklarından çay yapılan ve güzel kokulu çiçekleri olan ağaç?", secenekler: { A: "Kavak", B: "Ihlamur", C: "Ladin", D: "Meşe" }, dogruCevap: "B" },
    { seviye: 47, kategori: "Canlılar", soru: "Anadolu'da heybetiyle bilinen ve bin yıl yaşayabilen ağaç?", secenekler: { A: "Elma", B: "Çınar", C: "Söğüt", D: "Erik" }, dogruCevap: "B" },
    { seviye: 48, kategori: "Canlılar", soru: "Meyveleri dikenli bir kabuk içinde olan orman ağacı?", secenekler: { A: "Ceviz", B: "Badem", C: "Kestane", D: "Fındık" }, dogruCevap: "C" },
    { seviye: 49, kategori: "Canlılar", soru: "İç Anadolu bozkırlarında en çok görülen küçük bitki örtüsü?", secenekler: { A: "Papatya", B: "Orkide", C: "Gül", D: "Geven" }, dogruCevap: "D" },
    { seviye: 50, kategori: "Canlılar", soru: "Bahar aylarında kırlarda sarı-beyaz açan çiçek?", secenekler: { A: "Lale", B: "Sümbül", C: "Menekşe", D: "Papatya" }, dogruCevap: "D" },

    // 51-75: Kuşlar, Böcekler ve Sürüngenler (Türkiye Odaklı)
    { seviye: 51, kategori: "Canlılar", soru: "Türkiye'nin en büyük yırtıcı kuşu hangisidir?", secenekler: { A: "Şahin", B: "Kaya Kartalı", C: "Kızıl Akbaba", D: "Atmaca" }, dogruCevap: "C" },
    { seviye: 52, kategori: "Canlılar", soru: "Baharın müjdecisi olarak bilinen ve çatılara yuva yapan kuş?", secenekler: { A: "Serçe", B: "Leylek", C: "Saka", D: "Kırlangıç" }, dogruCevap: "B" },
    { seviye: 53, kategori: "Canlılar", soru: "Türkiye'deki en zehirli yılan türü hangisidir?", secenekler: { A: "Koca Engerek", B: "Su Yılanı", C: "Kör Yılan", D: "Kara Yılan" }, dogruCevap: "A" },
    { seviye: 54, kategori: "Canlılar", soru: "Ege ve Akdeniz sahillerinde görülen, şarkılara konu olan canlı?", secenekler: { A: "Ağustos Böceği", B: "Ateş Böceği", C: "Kelebek", D: "Arı" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Canlılar", soru: "Sadece gökyüzünde uyuyan ve ömrünün çoğunu uçarak geçiren kuş?", secenekler: { A: "Kartal", B: "Ebubekil (Sağan)", C: "Doğan", D: "Martı" }, dogruCevap: "B" },
    { seviye: 56, kategori: "Canlılar", soru: "Türkiye'de üretilen en kaliteli bal hangi canlıdan elde edilir?", secenekler: { A: "Bombus Arısı", B: "Eşek Arısı", C: "Anzer Arısı", D: "Yaban Arısı" }, dogruCevap: "C" },
    { seviye: 57, kategori: "Canlılar", soru: "Siyah beyaz renkli, zeki ve parlak nesnelere ilgisi olan kuş?", secenekler: { A: "Karga", B: "Saksağan", C: "Güvercin", D: "Kumru" }, dogruCevap: "B" },
    { seviye: 58, kategori: "Canlılar", soru: "Kırmızı göğsüyle bilinen, kışın bahçelerde görülen küçük kuş?", secenekler: { A: "Nar Bülbülü (Narçın)", B: "Serçe", C: "Florya", D: "Kanarya" }, dogruCevap: "A" },
    { seviye: 59, kategori: "Canlılar", soru: "Mavi-yeşil parlak tüyleri olan, dere kenarlarında avlanan kuş?", secenekler: { A: "Ördek", B: "Yalıçapkını", C: "Karabatak", D: "Kaz" }, dogruCevap: "B" },
    { seviye: 60, kategori: "Canlılar", soru: "Geceleri öten, sesiyle ünlü küçük kahverengi kuş?", secenekler: { A: "İspinoz", B: "Çavuşkuşu", C: "Bülbül", D: "Saka" }, dogruCevap: "C" },
    { seviye: 61, kategori: "Canlılar", soru: "Türkiye'nin en renkli ve ibikli kuşlarından biri?", secenekler: { A: "Sülün", B: "Keklik", C: "İbibik (Çavuşkuşu)", D: "Turaç" }, dogruCevap: "C" },
    { seviye: 62, kategori: "Canlılar", soru: "Dağlık bölgelerde yaşayan, eti için avlanan ötücü kuş?", secenekler: { A: "Güvercin", B: "Keklik", C: "Bıldırcın", D: "Atmaca" }, dogruCevap: "B" },
    { seviye: 63, kategori: "Canlılar", soru: "Sert gagasıyla ağaç gövdelerini oyan kuş?", secenekler: { A: "Serçe", B: "Saka", C: "Kırlangıç", D: "Ağaçkakan" }, dogruCevap: "D" },
    { seviye: 64, kategori: "Canlılar", soru: "Dünyanın en hızlı dalış yapan yırtıcı kuşu?", secenekler: { A: "Kartal", B: "Şahin", C: "Akbaba", D: "Gökdoğan" }, dogruCevap: "D" },
    { seviye: 65, kategori: "Canlılar", soru: "İnsanların evlerine yuva yapan, çatallı kuyruklu küçük kuş?", secenekler: { A: "Saka", B: "Serçe", C: "Arıkuşu", D: "Kırlangıç" }, dogruCevap: "D" },
    { seviye: 66, kategori: "Canlılar", soru: "Üzerindeki benekli deseniyle bilinen faydalı böcek?", secenekler: { A: "Hamam Böceği", B: "Pire", C: "Bit", D: "Uğur Böceği" }, dogruCevap: "D" },
    { seviye: 67, kategori: "Canlılar", soru: "Yazın akşamları ışık saçarak uçan böcek?", secenekler: { A: "Ateş Böceği", B: "Güve", C: "Sinek", D: "Arı" }, dogruCevap: "A" },
    { seviye: 68, kategori: "Canlılar", soru: "Renkleri ve kanat desenleriyle doğanın en güzel böceği?", secenekler: { A: "Örümcek", B: "Çekirge", C: "Kelebek", D: "Karınca" }, dogruCevap: "C" },
    { seviye: 69, kategori: "Canlılar", soru: "Kendi boyunun yüzlerce katı zıplayabilen yeşil böcek?", secenekler: { A: "Kene", B: "Arı", C: "Çekirge", D: "Bit" }, dogruCevap: "C" },
    { seviye: 70, kategori: "Canlılar", soru: "Sekiz bacağı olan ve ağ kurarak avlanan canlı?", secenekler: { A: "Arı", B: "Örümcek", C: "Karınca", D: "Sinek" }, dogruCevap: "B" },
    { seviye: 71, kategori: "Canlılar", soru: "Kuyruğu koptuğunda yeniden çıkabilen sürüngen?", secenekler: { A: "Kertenkele", B: "Kurbağa", C: "Timsah", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 72, kategori: "Canlılar", soru: "Sert kabuğuyla yavaş hareket eden sürüngen?", secenekler: { A: "Kaplumbağa", B: "Salyangoz", C: "İstakoz", D: "Yengeç" }, dogruCevap: "A" },
    { seviye: 73, kategori: "Canlılar", soru: "Ayakları olmayan, sürünerek hareket eden uzun canlı?", secenekler: { A: "Kertenkele", B: "Solucan", C: "Tırtıl", D: "Yılan" }, dogruCevap: "D" },
    { seviye: 74, kategori: "Canlılar", soru: "Suda ve karada yaşayan, zıplayan ve vıraklayan canlı?", secenekler: { A: "Balık", B: "Kurbağa", C: "Kaplumbağa", D: "Semender" }, dogruCevap: "B" },
    { seviye: 75, kategori: "Canlılar", soru: "Güneşlenmeyi çok seven, küçük ve hızlı bir kertenkele türü?", secenekler: { A: "Keler", B: "Bukalemun", C: "İguana", D: "Varan" }, dogruCevap: "A" },

    // 76-100: Genel Biyoloji ve Dünya Canlıları
    { seviye: 76, kategori: "Canlılar", soru: "Dünyanın en büyük memeli hayvanı hangisidir?", secenekler: { A: "Mavi Balina", B: "Zürafa", C: "Balina Köpekbalığı", D: "Fil" }, dogruCevap: "A" },
    { seviye: 77, kategori: "Canlılar", soru: "Kendi ağırlığının 50 katını taşıyabilen böcek?", secenekler: { A: "Karınca", B: "Örümcek", C: "Sinek", D: "Arı" }, dogruCevap: "A" },
    { seviye: 78, kategori: "Canlılar", soru: "Kan grubu olmayan ve her şeyi yiyebilen deniz canlısı?", secenekler: { A: "Deniz Yıldızı", B: "Ahtapot", C: "Mürekkep Balığı", D: "Yengeç" }, dogruCevap: "A" },
    { seviye: 79, kategori: "Canlılar", soru: "Işık kirliliğinden en çok etkilenen, ışık saçan böcek?", secenekler: { A: "Ateş Böceği", B: "Uğur Böceği", C: "Hamam Böceği", D: "Çekirge" }, dogruCevap: "A" },
    { seviye: 80, kategori: "Canlılar", soru: "Vücudunda kemik yerine kıkırdak bulunan deniz avcısı?", secenekler: { A: "Yunus", B: "Köpekbalığı", C: "Balina", D: "Palamut" }, dogruCevap: "B" },
    { seviye: 81, kategori: "Canlılar", soru: "Dünyanın en hızlı koşan kara hayvanı?", secenekler: { A: "Tazı", B: "Aslan", C: "Çita", D: "At" }, dogruCevap: "C" },
    { seviye: 82, kategori: "Canlılar", soru: "Renk değiştirme özelliğiyle bilinen sürüngen?", secenekler: { A: "Bukalemun", B: "Timsah", C: "Kertenkele", D: "İguana" }, dogruCevap: "A" },
    { seviye: 83, kategori: "Canlılar", soru: "Yumurta ile çoğalan tek memeli türü?", secenekler: { A: "Koala", B: "Yarasa", C: "Ornitorenk", D: "Kanguru" }, dogruCevap: "C" },
    { seviye: 84, kategori: "Canlılar", soru: "Gözleri kafasından büyük olan gece avcısı kuş?", secenekler: { A: "Baykuş", B: "Kuzgun", C: "Atmaca", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 85, kategori: "Canlılar", soru: "Dünyanın en uzun ömürlü canlısı olarak bilinen denizanası türü?", secenekler: { A: "Kutu Denizanası", B: "Mavi Denizanası", C: "Ölümsüz Denizanası", D: "Aslan Yelesi" }, dogruCevap: "C" },
    { seviye: 86, kategori: "Canlılar", soru: "Bitkilerin nefes almasını sağlayan yaprak bölgesi?", secenekler: { A: "Çiçek", B: "Kök", C: "Stoma", D: "Gövde" }, dogruCevap: "C" },
    { seviye: 87, kategori: "Canlılar", soru: "Arıların bal yapmak için çiçeklerden topladığı sıvı?", secenekler: { A: "Nektar", B: "Polen", C: "Su", D: "Reçine" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Canlılar", soru: "Fotosentez yapabilen tek hücreli canlılara örnek?", secenekler: { A: "Mantarlar", B: "Virüsler", C: "Algler", D: "Bakteriler" }, dogruCevap: "C" },
    { seviye: 89, kategori: "Canlılar", soru: "Kalbi vücudunun dışında olan tek canlı?", secenekler: { A: "Mavi Balina", B: "Yoktur", C: "Karınca", D: "Sinek Kuşu" }, dogruCevap: "B" },
    { seviye: 90, kategori: "Canlılar", soru: "Kış uykusuna yatan bir hayvan örneği?", secenekler: { A: "Zürafa", B: "Köpek", C: "Ayı", D: "At" }, dogruCevap: "C" },
    { seviye: 91, kategori: "Canlılar", soru: "Bitkilerde yeşil rengi veren madde hangisidir?", secenekler: { A: "Melanin", B: "Klorofil", C: "Keratin", D: "Hemoglobin" }, dogruCevap: "B" },
    { seviye: 92, kategori: "Canlılar", soru: "Dünyanın en küçük kuşu hangisidir?", secenekler: { A: "Güvercin", B: "Saka", C: "Serçe", D: "Arı Sinek Kuşu" }, dogruCevap: "D" },
    { seviye: 93, kategori: "Canlılar", soru: "Hangi canlı türü sosyal bir topluluk (koloni) halinde yaşamaz?", secenekler: { A: "Karınca", B: "Kaplan", C: "Termit", D: "Arı" }, dogruCevap: "B" },
    { seviye: 94, kategori: "Canlılar", soru: "İnsan vücudundaki en büyük organ hangisidir?", secenekler: { A: "Beyin", B: "Akciğer", C: "Deri", D: "Karaciğer" }, dogruCevap: "C" },
    { seviye: 95, kategori: "Canlılar", soru: "Böceklerin kaç adet bacağı bulunur?", secenekler: { A: "4", B: "8", C: "10", D: "6" }, dogruCevap: "D" },
    { seviye: 96, kategori: "Canlılar", soru: "Sürüngenlerin vücudu ne ile kaplıdır?", secenekler: { A: "Deri", B: "Pullar", C: "Kıl", D: "Tüyler" }, dogruCevap: "B" },
    { seviye: 97, kategori: "Canlılar", soru: "Balıklar hangi organları ile solunum yaparlar?", secenekler: { A: "Solungaç", B: "Deri", C: "Burun", D: "Akciğer" }, dogruCevap: "A" },
    { seviye: 98, kategori: "Canlılar", soru: "Hem karada hem suda yaşayabilen canlı grubu?", secenekler: { A: "Amfibiler", B: "Balıklar", C: "Memeliler", D: "Kuşlar" }, dogruCevap: "A" },
    { seviye: 99, kategori: "Canlılar", soru: "Bitkilerin güneş ışığını enerjiye dönüştürmesi olayına ne denir?", secenekler: { A: "Solunum", B: "Boşaltım", C: "Terleme", D: "Fotosentez" }, dogruCevap: "D" },
    { seviye: 100, kategori: "Canlılar", soru: "Doğadaki en büyük hücre hangisidir?", secenekler: { A: "Sinir Hücresi", B: "Yumurta Hücresi", C: "Devekuşu Yumurtası", D: "Bakteri" }, dogruCevap: "C" }, 
    { seviye: 100, kategori: "Canlılar", soru: "Hangi kuş türü uçamadığı halde çok hızlı koşabilir?", secenekler: { A: "Leylek", B: "Kartal", C: "Şahin", D: "Deve Kuşu" }, dogruCevap: "D" },
    { seviye: 101, kategori: "Canlılar", soru: "Bukalemunların en bilinen özelliği nedir?", secenekler: { A: "Uçabilmeleri", B: "Suda yaşamaları", C: "Renk değiştirmeleri", D: "Çok hızlı koşmaları" }, dogruCevap: "C" },
    { seviye: 102, kategori: "Canlılar", soru: "Karıncaların iletişim kurmak için salgıladığı kimyasal maddeye ne denir?", secenekler: { A: "Enzim", B: "Zehir", C: "Feromon", D: "Hormon" }, dogruCevap: "C" },
    { seviye: 103, kategori: "Canlılar", soru: "Hangi hayvan türü yavrularını kesesinde taşır?", secenekler: { A: "Maymun", B: "Kanguru", C: "Aslan", D: "Zürafa" }, dogruCevap: "B" },
    { seviye: 104, kategori: "Canlılar", soru: "Bitkilerin güneş ışığını kullanarak besin üretmesine ne ad verilir?", secenekler: { A: "Mayalanma", B: "Solunum", C: "Terleme", D: "Fotosentez" }, dogruCevap: "D" },
    { seviye: 105, kategori: "Canlılar", soru: "Yılanların koku almak için kullandığı organ hangisidir?", secenekler: { A: "Burun", B: "Göz", C: "Dil", D: "Deri" }, dogruCevap: "C" },
    { seviye: 106, kategori: "Canlılar", soru: "Dünyanın en hızlı kara hayvanı hangisidir?", secenekler: { A: "Çita", B: "Tavşan", C: "Kaplan", D: "At" }, dogruCevap: "A" },
    { seviye: 107, kategori: "Canlılar", soru: "Hangi canlı türü hem karada hem de suda yaşayabilir?", secenekler: { A: "Yılan", B: "Kurbağa", C: "Kuş", D: "Balık" }, dogruCevap: "B" },
    { seviye: 108, kategori: "Canlılar", soru: "Arıların bal yaptığı peteklerin şekli nedir?", secenekler: { A: "Kare", B: "Daire", C: "Altıgen", D: "Üçgen" }, dogruCevap: "C" },
    { seviye: 109, kategori: "Canlılar", soru: "Kış uykusuna yatmasıyla bilinen iri cüsseli memeli hayvan hangisidir?", secenekler: { A: "Fil", B: "Kurt", C: "Ayı", D: "Geyik" }, dogruCevap: "C" },
    { seviye: 110, kategori: "Canlılar", soru: "Denizatı hangi grupta yer alan bir canlıdır?", secenekler: { A: "Sürüngen", B: "Balık", C: "Memeli", D: "Böcek" }, dogruCevap: "B" },
    { seviye: 111, kategori: "Canlılar", soru: "Mantar hangi canlı grubuna girer?", secenekler: { A: "Kendi başına bir alemdir", B: "Bitki", C: "Bakteri", D: "Hayvan" }, dogruCevap: "A" },
    { seviye: 112, kategori: "Canlılar", soru: "Ahtapotların kaç adet kalbi vardır?", secenekler: { A: "4", B: "3", C: "1", D: "2" }, dogruCevap: "B" },
    { seviye: 113, kategori: "Canlılar", soru: "Hangi kuş türü kutuplarda yaşar ve uçamaz?", secenekler: { A: "Kuzgun", B: "Martı", C: "Penguen", D: "Pelikan" }, dogruCevap: "C" },
    { seviye: 114, kategori: "Canlılar", soru: "Balinalar hangi organları ile solunum yaparlar?", secenekler: { A: "Deri", B: "Akciğer", C: "Solungaç", D: "Yüzgeç" }, dogruCevap: "B" },
    { seviye: 115, kategori: "Canlılar", soru: "Vücudunda kemik yerine kıkırdak bulunan deniz canlısı hangisidir?", secenekler: { A: "Hamsi", B: "Yunus", C: "Köpek Balığı", D: "Lüfer" }, dogruCevap: "C" },
    { seviye: 116, kategori: "Canlılar", soru: "Kendi vücut ağırlığının 50 katını taşıyabilen böcek hangisidir?", secenekler: { A: "Sinek", B: "Arı", C: "Hamam Böceği", D: "Karınca" }, dogruCevap: "D" },
    { seviye: 117, kategori: "Canlılar", soru: "Zürafaların dilleri ne renktir?", secenekler: { A: "Siyah/Koyu Mor", B: "Kırmızı", C: "Beyaz", D: "Pembe" }, dogruCevap: "A" },
    { seviye: 118, kategori: "Canlılar", soru: "Hangi hayvanın sütü pembe renklidir?", secenekler: { A: "Su Aygırı", B: "Fil", C: "Gergedan", D: "Zebra" }, dogruCevap: "A" },
    { seviye: 119, kategori: "Canlılar", soru: "Gözleri beyinlerinden daha büyük olan kuş hangisidir?", secenekler: { A: "Baykuş", B: "Kartal", C: "Papağan", D: "Deve Kuşu" }, dogruCevap: "D" },
    { seviye: 120, kategori: "Canlılar", soru: "Ayaktayken uyuyabilen hayvan hangisidir?", secenekler: { A: "Aslan", B: "Kedi", C: "At", D: "Köpek" }, dogruCevap: "C" },
    { seviye: 121, kategori: "Canlılar", soru: "Parmak izi insana en çok benzeyen hayvan hangisidir?", secenekler: { A: "Goril", B: "Koala", C: "Şempanze", D: "Orangutan" }, dogruCevap: "B" },
    { seviye: 122, kategori: "Canlılar", soru: "Hangi canlı türü başını 270 derece döndürebilir?", secenekler: { A: "Atmaca", B: "Baykuş", C: "Yılan", D: "Kedi" }, dogruCevap: "B" },
    { seviye: 123, kategori: "Canlılar", soru: "Dili vücudundan daha uzun olabilen canlı hangisidir?", secenekler: { A: "Kurbağa", B: "Zürafa", C: "Bukalemun", D: "Kertenkele" }, dogruCevap: "C" },
    { seviye: 124, kategori: "Canlılar", soru: "Vücudundaki tüm kanı bir tüp içinde toplayabilen, sülük benzeri canlı?", secenekler: { A: "Solucan", B: "Bit", C: "Kene", D: "Sülük" }, dogruCevap: "D" },
    { seviye: 125, kategori: "Canlılar", soru: "Su altında en uzun süre nefes almadan kalabilen memeli hangisidir?", secenekler: { A: "İspermeçet Balinası", B: "Fok", C: "Yunus", D: "Su Aygırı" }, dogruCevap: "A" },
    { seviye: 126, kategori: "Canlılar", soru: "Hangi hayvanın kalbi kafasındadır?", secenekler: { A: "Deniz Yıldızı", B: "Istakoz", C: "Karides", D: "Yengeç" }, dogruCevap: "C" },
    { seviye: 127, kategori: "Canlılar", soru: "İnsan vücudunda bakteri miktarının en yoğun olduğu yer neresidir?", secenekler: { A: "Ağız", B: "Bağırsaklar", C: "Eller", D: "Mide" }, dogruCevap: "B" },
    { seviye: 128, kategori: "Canlılar", soru: "Işık kirliliğinden en çok etkilenen, denizden karaya çıkan canlı?", secenekler: { A: "Deniz Anası", B: "Yengeç", C: "Fok", D: "Caretta Caretta" }, dogruCevap: "D" },
    { seviye: 129, kategori: "Canlılar", soru: "Hangi kuş türü geri geri uçabilir?", secenekler: { A: "Arı Kuşu", B: "Kırlangıç", C: "Sinek Kuşu (Hummingbird)", D: "Serçe" }, dogruCevap: "C" },
    { seviye: 130, kategori: "Canlılar", soru: "Göz kapakları olmayan ve gözlerini diliyle temizleyen canlı?", secenekler: { A: "Yılan", B: "Geko (Kertenkele)", C: "Timsah", D: "Bukalemun" }, dogruCevap: "B" },
    { seviye: 131, kategori: "Canlılar", soru: "Dünyanın en zehirli yılanı hangisidir?", secenekler: { A: "İç Bölge Taypanı", B: "Kara Mamba", C: "Engerek", D: "Kobra" }, dogruCevap: "A" },
    { seviye: 132, kategori: "Canlılar", soru: "Fillerin en çok korktuğu küçük canlı hangisidir?", secenekler: { A: "Örümcek", B: "Arı", C: "Karınca", D: "Fare" }, dogruCevap: "B" },
    { seviye: 133, kategori: "Canlılar", soru: "Kutup ayılarının derisi aslında ne renktir?", secenekler: { A: "Siyah", B: "Pembe", C: "Gri", D: "Beyaz" }, dogruCevap: "A" },
    { seviye: 134, kategori: "Canlılar", soru: "Hangi hayvanın terisi güneş kremi görevi görür ve kırmızımsıdır?", secenekler: { A: "Gergedan", B: "Fil", C: "Domuz", D: "Su Aygırı" }, dogruCevap: "D" },
    { seviye: 135, kategori: "Canlılar", soru: "Deniz yıldızlarının kaç tane beyni vardır?", secenekler: { A: "2", B: "1", C: "5", D: "Beyni yoktur" }, dogruCevap: "D" },
    { seviye: 136, kategori: "Canlılar", soru: "Hangi canlı türü öldükten sonra bile sokabilir?", secenekler: { A: "Örümcek", B: "Arı", C: "Akrep", D: "Yılan" }, dogruCevap: "B" },
    { seviye: 137, kategori: "Canlılar", soru: "Kargaların ortalama ömrü ne kadardır?", secenekler: { A: "50 yıl", B: "100 yıl", C: "15-20 yıl", D: "200 yıl" }, dogruCevap: "C" },
    { seviye: 138, kategori: "Canlılar", soru: "Hangi memeli yumurtlayarak çoğalır?", secenekler: { A: "Yunus", B: "Kanguru", C: "Ornitorenk", D: "Yarasa" }, dogruCevap: "C" },
    { seviye: 139, kategori: "Canlılar", soru: "Kedilerin vücudunda kaç adet kemik bulunur?", secenekler: { A: "230", B: "206", C: "150", D: "300" }, dogruCevap: "A" },
    { seviye: 140, kategori: "Canlılar", soru: "Mavi balinaların dili yaklaşık ne kadar ağırlıktadır?", secenekler: { A: "Bir fil kadar", B: "Bir ton", C: "500 kg", D: "100 kg" }, dogruCevap: "A" },
    { seviye: 141, kategori: "Canlılar", soru: "Hangi hayvanın üç adet göz kapağı vardır?", secenekler: { A: "Deve", B: "Kartal", C: "Kedi", D: "Timsah" }, dogruCevap: "A" },
    { seviye: 142, kategori: "Canlılar", soru: "Bir ıstakozun kanı ne renktir?", secenekler: { A: "Kırmızı", B: "Şeffaf", C: "Yeşil", D: "Mavi" }, dogruCevap: "B" },
    { seviye: 143, kategori: "Canlılar", soru: "Hangi canlı havayı duymak için bacaklarını kullanır?", secenekler: { A: "Çekirge", B: "Cırcır Böceği", C: "Örümcek", D: "Kelebek" }, dogruCevap: "B" },
    { seviye: 144, kategori: "Canlılar", soru: "Dünyanın en küçük kuşu hangisidir?", secenekler: { A: "Arı Sinek Kuşu", B: "Kanarya", C: "Saka", D: "Serçe" }, dogruCevap: "A" },
    { seviye: 145, kategori: "Canlılar", soru: "Hangi hayvanın sütü dondurma yapımında kullanılmaz?", secenekler: { A: "Manda", B: "İnek", C: "Keçi", D: "Balina" }, dogruCevap: "D" },
    { seviye: 146, kategori: "Canlılar", soru: "Penguenlerin sadece neresinde ter bezleri bulunur?", secenekler: { A: "Kanatlarında", B: "Gagalarında", C: "Ter bezleri yoktur", D: "Ayaklarında" }, dogruCevap: "C" },
    { seviye: 147, kategori: "Canlılar", soru: "Yarasalar yönlerini ne ile bulurlar?", secenekler: { A: "Koku", B: "Ses dalgaları (Ekolokasyon)", C: "Isı", D: "Gözleri" }, dogruCevap: "B" },
    { seviye: 148, kategori: "Canlılar", soru: "Hangi hayvan asla unutmamasıyla ünlüdür?", secenekler: { A: "Fil", B: "Karga", C: "Köpek", D: "Maymun" }, dogruCevap: "A" },
    { seviye: 149, kategori: "Canlılar", soru: "Yılanların derisi neyden yapılmıştır?", secenekler: { A: "Keratin", B: "Kalsiyum", C: "Kıkırdak", D: "Lif" }, dogruCevap: "A" },
    { seviye: 150, kategori: "Canlılar", soru: "Kelebeklerin tat alma organları nerededir?", secenekler: { A: "Antenlerinde", B: "Ayaklarında", C: "Kanatlarında", D: "Hortumlarında" }, dogruCevap: "B" },
    { seviye: 151, kategori: "Canlılar", soru: "Bir salyangoz yaklaşık ne kadar süre uyuyabilir?", secenekler: { A: "3 hafta", B: "3 gün", C: "3 yıl", D: "3 ay" }, dogruCevap: "C" },
    { seviye: 152, kategori: "Canlılar", soru: "Hangi hayvanın gözleri dilediği yöne birbirinden bağımsız hareket edebilir?", secenekler: { A: "Kedi", B: "Baykuş", C: "Kartal", D: "Bukalemun" }, dogruCevap: "D" },
    { seviye: 153, kategori: "Canlılar", soru: "Köpeklerin koku alma yeteneği insanınkinden kaç kat daha güçlüdür?", secenekler: { A: "10 kat", B: "40 kat", C: "100 kat", D: "5 kat" }, dogruCevap: "B" },
    { seviye: 154, kategori: "Canlılar", soru: "Karıncaların akciğerleri var mıdır?", secenekler: { A: "Hayır", B: "Yarısında vardır", C: "Evet", D: "Sadece kraliçe karıncanın" }, dogruCevap: "A" },
    { seviye: 155, kategori: "Canlılar", soru: "Bir inek günde yaklaşık kaç litre su tüketir?", secenekler: { A: "100-150 litre", B: "300 litre", C: "50 litre", D: "10 litre" }, dogruCevap: "A" },
    { seviye: 156, kategori: "Canlılar", soru: "Hangi canlı türünün erkekleri doğum yapar (yavruları taşır)?", secenekler: { A: "Kangaroo", B: "Denizatı", C: "Kaplumbağa", D: "Penguen" }, dogruCevap: "B" },
    { seviye: 157, kategori: "Canlılar", soru: "Timsahlar neden taş yutarlar?", secenekler: { A: "Daha derine dalabilmek için", B: "Aç oldukları için", C: "Yuva yapmak için", D: "Dişlerini bilemek için" }, dogruCevap: "A" },
    { seviye: 158, kategori: "Canlılar", soru: "Hangi kuş türü havada uyuyabilir?", secenekler: { A: "Güvercinler", B: "Serçeler", C: "Kargalar", D: "Ebabiller" }, dogruCevap: "D" },
    { seviye: 159, kategori: "Canlılar", soru: "Arılar birbirlerine çiçeklerin yerini nasıl tarif ederler?", secenekler: { A: "Dans ederek", B: "Dokunarak", C: "Renk değiştirerek", D: "Ses çıkararak" }, dogruCevap: "A" },
    { seviye: 160, kategori: "Canlılar", soru: "Tarantulalar ne kadar süre yemek yemeden yaşayabilirler?", secenekler: { A: "2 hafta", B: "2 gün", C: "2 ay", D: "2 yıl" }, dogruCevap: "D" },
    { seviye: 161, kategori: "Canlılar", soru: "Dünyanın en uzun yaşayan hayvanı hangisidir (bilinen)?", secenekler: { A: "Fil", B: "Dev Kaplumbağa", C: "Grönland Köpek Balığı", D: "Mavi Balina" }, dogruCevap: "C" },
    { seviye: 162, kategori: "Canlılar", soru: "Bir sineğin kaç tane gözü vardır?", secenekler: { A: "Binlerce (Petek göz)", B: "4", C: "2", D: "8" }, dogruCevap: "A" },
    { seviye: 163, kategori: "Canlılar", soru: "Kedilerin mırlaması ne anlama gelebilir?", secenekler: { A: "Sadece açlık", B: "Sadece mutluluk", C: "Sadece kızgınlık", D: "Hepsi (Mutluluk, stres, iyileşme)" }, dogruCevap: "D" },
    { seviye: 164, kategori: "Canlılar", soru: "Ayıların yürürken önce hangi tarafın ayaklarını attığı bilinir?", secenekler: { A: "Sadece arkalar", B: "Sadece önler", C: "Çapraz", D: "Önce aynı tarafın (sağ ön-sağ arka)" }, dogruCevap: "D" },
    { seviye: 165, kategori: "Canlılar", soru: "Hangi hayvanın dişleri ömrü boyunca uzamaya devam eder?", secenekler: { A: "Tavşan", B: "Kedi", C: "Köpek", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 166, kategori: "Canlılar", soru: "Zürafalar günde ortalama kaç saat uyurlar?", secenekler: { A: "5 saat", B: "8 saat", C: "30 dakika - 2 saat", D: "12 saat" }, dogruCevap: "C" },
    { seviye: 167, kategori: "Canlılar", soru: "Bir dev mürekkep balığının gözü yaklaşık ne büyüklüktedir?", secenekler: { A: "Plaj topu kadar", B: "Portakal kadar", C: "Misket kadar", D: "Tenis topu kadar" }, dogruCevap: "A" },
    { seviye: 168, kategori: "Canlılar", soru: "Hangi canlı türü su içmeden en uzun süre yaşayabilir?", secenekler: { A: "Akrep", B: "Kanguru Faresi", C: "Yılan", D: "Deve" }, dogruCevap: "B" },
    { seviye: 169, kategori: "Canlılar", soru: "Hangi kuşun kanat açıklığı en büyüktür?", secenekler: { A: "Akbaba", B: "Albatros", C: "Kartal", D: "Pelikan" }, dogruCevap: "B" },
    { seviye: 170, kategori: "Canlılar", soru: "Köpeklerin ter bezleri nerededir?", secenekler: { A: "Sırtlarında", B: "Pati altlarında", C: "Kulaklarında", D: "Dillerinde" }, dogruCevap: "B" },
    { seviye: 171, kategori: "Canlılar", soru: "Dünyanın en ağır böceği hangisidir?", secenekler: { A: "Geyik Böceği", B: "Uğur Böceği", C: "Hamam Böceği", D: "Golyat Böceği" }, dogruCevap: "D" },
    { seviye: 172, kategori: "Canlılar", soru: "Hangi hayvanın sesi yankı yapmaz (şehir efsanesi)?", secenekler: { A: "Ördek", B: "Kaz", C: "Tavuk", D: "Kuğu" }, dogruCevap: "A" },
    { seviye: 173, kategori: "Canlılar", soru: "Kaplanların derisindeki çizgiler sadece tüylerinde mi bulunur?", secenekler: { A: "Sadece yavrularında", B: "Hayır, derilerinde de vardır", C: "Evet, sadece tüylerinde", D: "Sadece kuyruklarında" }, dogruCevap: "B" },
    { seviye: 174, kategori: "Canlılar", soru: "Deve kuşunun beyni mi daha büyüktür gözü mü?", secenekler: { A: "İkisi de eşittir", B: "Beyni", C: "Gözü", D: "Türüne göre değişir" }, dogruCevap: "C" },
    { seviye: 175, kategori: "Canlılar", soru: "Hangi hayvanın kalbi dakikada sadece 9 kez atar?", secenekler: { A: "Timsah", B: "Mavi Balina", C: "Kaplumbağa", D: "Fil" }, dogruCevap: "B" },
    { seviye: 176, kategori: "Canlılar", soru: "Deniz analarının vücudunun yüzde kaçı sudur?", secenekler: { A: "%70", B: "%30", C: "%50", D: "%95" }, dogruCevap: "D" },
    { seviye: 177, kategori: "Canlılar", soru: "Hamam böcekleri kafaları kopsa bile kaç gün yaşayabilirler?", secenekler: { A: "1 gün", B: "1 saat", C: "1 ay", D: "1 hafta" }, dogruCevap: "D" },
    { seviye: 178, kategori: "Canlılar", soru: "Aslanlar bir günde ortalama kaç saat uyurlar?", secenekler: { A: "10 saat", B: "5 saat", C: "20 saat", D: "2 saat" }, dogruCevap: "C" },
    { seviye: 179, kategori: "Canlılar", soru: "Hangi hayvanın dört tane midesi vardır?", secenekler: { A: "Domuz", B: "İnek", C: "At", D: "Köpek" }, dogruCevap: "B" },
    { seviye: 180, kategori: "Canlılar", soru: "Filler neden hortumlarını kullanırlar?", secenekler: { A: "Sadece nefes almak", B: "Hepsi (Nefes alma, su içme, nesne taşıma)", C: "Sadece koku almak", D: "Sadece su içmek" }, dogruCevap: "B" },
    { seviye: 181, kategori: "Canlılar", soru: "Hangi canlı türü DNA olarak insana %98.8 oranında benzer?", secenekler: { A: "Goril", B: "Fare", C: "Yunus", D: "Şempanze" }, dogruCevap: "D" },
    { seviye: 182, kategori: "Canlılar", soru: "Hangi balık türü suyun dışında da nefes alabilir?", secenekler: { A: "Akciğerli Balık", B: "Palamut", C: "Sazan", D: "Uskumru" }, dogruCevap: "A" },
    { seviye: 183, kategori: "Canlılar", soru: "Yılanların kulakları var mıdır?", secenekler: { A: "Dış kulakları yoktur (titreşim hissederler)", B: "Evet, vardır", C: "Sadece büyük yılanlarda", D: "Sadece zehirli olanlarda" }, dogruCevap: "A" },
    { seviye: 184, kategori: "Canlılar", soru: "Kuşların kemiklerinin içi neden boştur?", secenekler: { A: "Daha çok yemek yemek için", B: "Hafif olup uçabilmek için", C: "Daha hızlı koşmak için", D: "Daha iyi duymak için" }, dogruCevap: "B" },
    { seviye: 185, kategori: "Canlılar", soru: "Hangi canlı türü dünyadaki en büyük göçü yapar?", secenekler: { A: "Balina", B: "Kuzey Sumrusu (Artic Tern)", C: "Fil", D: "Geyik" }, dogruCevap: "B" },
    { seviye: 186, kategori: "Canlılar", soru: "Bebekken ağlamayan hayvan hangisidir?", secenekler: { A: "Maymun", B: "Kedi", C: "İnsan", D: "Timsah" }, dogruCevap: "D" },
    { seviye: 187, kategori: "Canlılar", soru: "Baykuşlar neden sessiz uçarlar?", secenekler: { A: "Çok küçük oldukları için", B: "Gece uçtukları için", C: "Tüylerinin özel yapısı sayesinde", D: "Çok hızlı uçtukları için" }, dogruCevap: "C" },
    { seviye: 188, kategori: "Canlılar", soru: "Pireler kendi boylarının kaç katı yükseğe zıplayabilir?", secenekler: { A: "50 kat", B: "1000 kat", C: "10 kat", D: "200 kat" }, dogruCevap: "D" },
    { seviye: 189, kategori: "Canlılar", soru: "Mavi balinaların kalbi ne büyüklüktedir?", secenekler: { A: "Küçük bir araba kadar", B: "Basketbol topu kadar", C: "Bir kova kadar", D: "Bir ev kadar" }, dogruCevap: "A" },
    { seviye: 190, kategori: "Canlılar", soru: "Penguenler neden grup halinde dururlar?", secenekler: { A: "Oyun oynamak için", B: "Yemek yemek için", C: "Isınmak için", D: "Uyumak için" }, dogruCevap: "C" },
    { seviye: 191, kategori: "Canlılar", soru: "Hangi hayvanın dilleri vücutlarından daha uzundur?", secenekler: { A: "Zürafa", B: "Kedi", C: "Bukalemun", D: "Kurbağa" }, dogruCevap: "C" },
    { seviye: 192, kategori: "Canlılar", soru: "Deniz yıldızları kopan kollarını yenileyebilir mi?", secenekler: { A: "Sadece belirli türler", B: "Hayır", C: "Evet", D: "Sadece yavrular" }, dogruCevap: "C" },
    { seviye: 193, kategori: "Canlılar", soru: "Hangi kuş türü yuva yapmaz, yumurtasını başka kuşun yuvasına bırakır?", secenekler: { A: "Kartal", B: "Serçe", C: "Guguk Kuşu", D: "Kırlangıç" }, dogruCevap: "C" },
    { seviye: 194, kategori: "Canlılar", soru: "Kedilerin bıyıkları ne işe yarar?", secenekler: { A: "Süs", B: "Sadece duymak", C: "Koku alma", D: "Denge ve boşluk algısı" }, dogruCevap: "D" },
    { seviye: 195, kategori: "Canlılar", soru: "Balinalar neden su fışkırtırlar?", secenekler: { A: "Yıkanmak için", B: "Serinlemek için", C: "Oyun oynamak için", D: "Nefes vermek için" }, dogruCevap: "D" },
    { seviye: 196, kategori: "Canlılar", soru: "Hangi canlı türü suyun altında en hızlı yüzer?", secenekler: { A: "Köpek Balığı", B: "Yunus", C: "Balina", D: "Yelken Balığı" }, dogruCevap: "D" },
    { seviye: 197, kategori: "Canlılar", soru: "Fillerin hortumunda kaç tane kemik bulunur?", secenekler: { A: "Sıfır", B: "100", C: "1", D: "10" }, dogruCevap: "A" },
    { seviye: 198, kategori: "Canlılar", soru: "İpek böceği hangi ağacın yaprağıyla beslenir?", secenekler: { A: "Çam", B: "Elma", C: "Kavak", D: "Dut" }, dogruCevap: "D" },
    { seviye: 199, kategori: "Canlılar", soru: "Hangi hayvanın sütü en yağlıdır?", secenekler: { A: "İnek", B: "Koyun", C: "Mavi Balina", D: "Keçi" }, dogruCevap: "C" },
    { seviye: 200, kategori: "Canlılar", soru: "Hangi canlı türü yaşlandıkça küçülebilir?", secenekler: { A: "Kuş", B: "Yılan", C: "Fare", D: "Bazı deniz anası türleri" }, dogruCevap: "D" },
    { seviye: 201, kategori: "Canlılar", soru: "Arı kuşu günde yaklaşık kaç böcek yer?", secenekler: { A: "100", B: "Binlerce", C: "50", D: "10" }, dogruCevap: "B" },
    { seviye: 202, kategori: "Canlılar", soru: "Yunuslar neden birbirlerine ıslık çalarlar?", secenekler: { A: "İletişim ve isim niyetine", B: "Şarkı söylemek için", C: "Uyumak için", D: "Korkutmak için" }, dogruCevap: "A" },
    { seviye: 203, kategori: "Canlılar", soru: "Hangi hayvanın kanı şeffaftır?", secenekler: { A: "Kedi", B: "Yılan", C: "Balık", D: "Çekirge" }, dogruCevap: "D" },
    { seviye: 204, kategori: "Canlılar", soru: "Karıncalar uyur mu?", secenekler: { A: "Kısa süreli şekerlemeler yaparlar", B: "İnsanlar gibi 8 saat uyurlar", C: "Sadece kışın uyurlar", D: "Hayır, hiç uyumazlar" }, dogruCevap: "A" },
    { seviye: 205, kategori: "Canlılar", soru: "Hangi hayvanın bakış açısı 360 derecedir?", secenekler: { A: "Bukalemun", B: "Kedi", C: "Baykuş", D: "At" }, dogruCevap: "A" },
    { seviye: 206, kategori: "Canlılar", soru: "Deniz analarının beyni var mıdır?", secenekler: { A: "Hayır", B: "Sadece büyüklerde", C: "Evet", D: "Yarısında vardır" }, dogruCevap: "A" },
    { seviye: 207, kategori: "Canlılar", soru: "Bir tavuğun bilinen en uzun uçuş süresi ne kadardır?", secenekler: { A: "1 dakika", B: "10 dakika", C: "1 saat", D: "13 saniye" }, dogruCevap: "D" },
    { seviye: 208, kategori: "Canlılar", soru: "Hangi hayvanın gözleri kafasından büyüktür?", secenekler: { A: "Kartal", B: "Deve Kuşu", C: "Kedi", D: "Sinek" }, dogruCevap: "B" },
    { seviye: 209, kategori: "Canlılar", soru: "İneklerin kaç tane dişleri vardır?", secenekler: { A: "32", B: "40", C: "10", D: "20" }, dogruCevap: "A" },
    { seviye: 210, kategori: "Canlılar", soru: "Hangi hayvanın grubu 'parlament' olarak adlandırılır?", secenekler: { A: "Filler", B: "Aslanlar", C: "Kargalar", D: "Baykuşlar" }, dogruCevap: "D" },
    { seviye: 211, kategori: "Canlılar", soru: "Su aygırları su altında ne kadar kalabilir?", secenekler: { A: "1 saat", B: "2 dakika", C: "5 dakika", D: "20 dakika" }, dogruCevap: "C" },
    { seviye: 212, kategori: "Canlılar", soru: "Hangi hayvanın kalbi vücuduna göre en büyüğüdür?", secenekler: { A: "Sinek Kuşu", B: "Mavi Balina", C: "Fil", D: "Zürafa" }, dogruCevap: "A" },
    { seviye: 213, kategori: "Canlılar", soru: "Hangi balık türü elektrik üretebilir?", secenekler: { A: "Sazan", B: "Elektrikli Yılan Balığı", C: "Hamsi", D: "Lüfer" }, dogruCevap: "B" },
    { seviye: 214, kategori: "Canlılar", soru: "Kelebeklerin ömrü gerçekten 1 gün müdür?", secenekler: { A: "Sadece bazıları", B: "Sadece kışın", C: "Evet", D: "Hayır, haftalarca hatta aylarca yaşayabilirler" }, dogruCevap: "D" },
    { seviye: 215, kategori: "Canlılar", soru: "Hangi canlı türü kendisini klonlayabilir?", secenekler: { A: "Bazı deniz anası ve kertenkele türleri", B: "Fare", C: "Kuş", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 216, kategori: "Canlılar", soru: "Arılar hangi rengi göremezler?", secenekler: { A: "Mavi", B: "Sarı", C: "Kırmızı", D: "Yeşil" }, dogruCevap: "C" },
    { seviye: 217, kategori: "Canlılar", soru: "Hangi hayvanın kulakları bacaklarındadır?", secenekler: { A: "Örümcek", B: "Karınca", C: "Sinek", D: "Çekirge" }, dogruCevap: "D" },
    { seviye: 218, kategori: "Canlılar", soru: "Zürafalar nasıl ses çıkarırlar?", secenekler: { A: "Miyavlayarak", B: "Kükreyerek", C: "Havlayarak", D: "İnsan kulağının duyamayacağı düşük frekansta" }, dogruCevap: "D" },
    { seviye: 219, kategori: "Canlılar", soru: "Dünyanın en büyük çiçeği hangisidir?", secenekler: { A: "Rafflesia", B: "Gül", C: "Papatya", D: "Lale" }, dogruCevap: "A" },
    { seviye: 220, kategori: "Canlılar", soru: "Hangi ağaç türü binlerce yıl yaşayabilir?", secenekler: { A: "Söğüt", B: "Kavak", C: "Erik", D: "Zeytin ağacı" }, dogruCevap: "D" },
    { seviye: 221, kategori: "Canlılar", soru: "Bambu bir ağaç mıdır ot mudur?", secenekler: { A: "Mantar", B: "Çalı", C: "Ot (Buğdaygiller)", D: "Ağaç" }, dogruCevap: "C" },
    { seviye: 222, kategori: "Canlılar", soru: "Hangi hayvanın kemikleri siyahtır?", secenekler: { A: "Yarasa", B: "Ayam Cemani Tavuğu", C: "Karga", D: "Fare" }, dogruCevap: "B" },
    { seviye: 223, kategori: "Canlılar", soru: "Hangi canlı türü uzay boşluğunda yaşayabilir?", secenekler: { A: "Bakteri", B: "Virüs", C: "Tardigrat (Su Ayısı)", D: "Hamam Böceği" }, dogruCevap: "C" },
    { seviye: 224, kategori: "Canlılar", soru: "Bir ağaçkakan saniyede kaç kez ağaca vurabilir?", secenekler: { A: "100 kez", B: "50 kez", C: "20 kez", D: "5 kez" }, dogruCevap: "C" },
    { seviye: 225, kategori: "Canlılar", soru: "Hangi canlı türü sadece uyurken rüya görmez?", secenekler: { A: "Sürüngenler (çoğunlukla)", B: "Memeliler", C: "Kuşlar", D: "İnsanlar" }, dogruCevap: "A" },
    { seviye: 226, kategori: "Canlılar", soru: "Deniz kaplumbağaları yumurtalarını nereye bırakırlar?", secenekler: { A: "Denize", B: "Yuvaya", C: "Kuma gömerler", D: "Kayalıklara" }, dogruCevap: "C" },
    { seviye: 227, kategori: "Canlılar", soru: "Hangi hayvanın dili bir insan boyundadır?", secenekler: { A: "Mavi Balina", B: "Zürafa", C: "Dev Karıncayiyen", D: "Fil" }, dogruCevap: "A" },
    { seviye: 228, kategori: "Canlılar", soru: "Kangurular neden geri geri yürüyemezler?", secenekler: { A: "Çok ağır oldukları için", B: "Korktukları için", C: "Gözleri görmediği için", D: "Kuyruk ve bacak yapısı nedeniyle" }, dogruCevap: "D" },
    { seviye: 229, kategori: "Canlılar", soru: "Köpek balıkları yüzerken neden ağızlarını açık tutarlar?", secenekler: { A: "Oksijen almak için", B: "Yemek yemek için", C: "Korkutmak için", D: "Uyumak için" }, dogruCevap: "A" },
    { seviye: 230, kategori: "Canlılar", soru: "Hangi hayvanın burnunun izi insanların parmak izi gibi eşsizdir?", secenekler: { A: "Kedi", B: "İnek", C: "Köpek", D: "At" }, dogruCevap: "C" },
    { seviye: 231, kategori: "Canlılar", soru: "Su samurları uyurken neden birbirlerinin elini tutarlar?", secenekler: { A: "Akıntıda sürüklenmemek için", B: "Korktukları için", C: "Sevdikleri için", D: "Oyun için" }, dogruCevap: "A" },
    { seviye: 232, kategori: "Canlılar", soru: "Hangi kuş türü kendi ağırlığının iki katı kadar yemek yiyebilir?", secenekler: { A: "Akbaba", B: "Kartal", C: "Pelikan", D: "Sinek Kuşu" }, dogruCevap: "D" },
    { seviye: 233, kategori: "Canlılar", soru: "Hamsterlar yemeklerini nerede saklarlar?", secenekler: { A: "Midelerinde", B: "Yuvalarında", C: "Toprağın altında", D: "Yanak keselerinde" }, dogruCevap: "D" },
    { seviye: 234, kategori: "Canlılar", soru: "Hangi canlı türü dünyada en çok insana zarar veren canlıdır?", secenekler: { A: "Sivrisinek", B: "Yılan", C: "Köpek Balığı", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 235, kategori: "Canlılar", soru: "Ahtapotların kanı neden mavidir?", secenekler: { A: "Demir içerdiği için", B: "Bakır içerdiği için", C: "Mürekkep olduğu için", D: "Su olduğu için" }, dogruCevap: "B" },
    { seviye: 236, kategori: "Canlılar", soru: "Hangi hayvanın sütü en az yağlıdır?", secenekler: { A: "Koyun", B: "İnek", C: "Eşek", D: "Manda" }, dogruCevap: "C" },
    { seviye: 237, kategori: "Canlılar", soru: "Kediler neden dar yerlerden geçebilirler?", secenekler: { A: "Köprücük kemikleri olmadığı için", B: "Çok esnek oldukları için", C: "Hızlı oldukları için", D: "Tüyleri sayesinde" }, dogruCevap: "A" },
    { seviye: 238, kategori: "Canlılar", soru: "Hangi kuşun yumurtası en küçüktür?", secenekler: { A: "Serçe", B: "Saka", C: "Sinek Kuşu", D: "Kanarya" }, dogruCevap: "C" },
    { seviye: 239, kategori: "Canlılar", soru: "Hangi hayvanın gözbebekleri dikdörtgen şeklindedir?", secenekler: { A: "Keçi", B: "Aslan", C: "Köpek", D: "Kedi" }, dogruCevap: "A" },
    { seviye: 240, kategori: "Canlılar", soru: "Arılar kaç tane göze sahiptir?", secenekler: { A: "2", B: "10", C: "4", D: "5" }, dogruCevap: "D" },
    { seviye: 241, kategori: "Canlılar", soru: "Hangi canlı türü kalbi durunca ölmüş sayılmaz?", secenekler: { A: "Bazı kurbağa türleri (donunca)", B: "Kuş", C: "Yılan", D: "Fare" }, dogruCevap: "A" },
    { seviye: 242, kategori: "Canlılar", soru: "Balinalar uyurken boğulmamak için ne yaparlar?", secenekler: { A: "Hiç uyumazlar", B: "Beyinlerinin yarısı uyanık kalır", C: "Suyun üstünde uyurlar", D: "Nefeslerini tutarlar" }, dogruCevap: "B" },
    { seviye: 243, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile vücut sıcaklıklarını dengelerler?", secenekler: { A: "Kedi", B: "Köpek", C: "At", D: "İnek" }, dogruCevap: "B" },
    { seviye: 244, kategori: "Canlılar", soru: "Hangi böcek türü suyun üstünde yürüyebilir?", secenekler: { A: "Arı", B: "Karınca", C: "Sinek", D: "Su Örümceği" }, dogruCevap: "D" },
    { seviye: 245, kategori: "Canlılar", soru: "Bir istiridye yaklaşık kaç tane inci yapabilir?", secenekler: { A: "Hayatı boyunca çok az (nadirdir)", B: "Yüzlerce", C: "Binlerce", D: "Her gün bir tane" }, dogruCevap: "A" },
    { seviye: 246, kategori: "Canlılar", soru: "Hangi kuş türü sadece pembe yiyecekler yediği için pembedir?", secenekler: { A: "Papağan", B: "Flamingo", C: "Martı", D: "Pelikan" }, dogruCevap: "B" },
    { seviye: 247, kategori: "Canlılar", soru: "Dünyanın en büyük kara memelisi hangisidir?", secenekler: { A: "Afrika Fili", B: "Gergedan", C: "Zürafa", D: "Su Aygırı" }, dogruCevap: "A" },
    { seviye: 248, kategori: "Canlılar", soru: "Hangi canlı türü hem bitki hem hayvan özelliği gösterebilir?", secenekler: { A: "Bakteri", B: "Öglena", C: "Virüs", D: "Mantar" }, dogruCevap: "B" },
    { seviye: 249, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'nehir atı' anlamına gelir?", secenekler: { A: "Yunus", B: "Timsah", C: "Su Aygırı", D: "Fok" }, dogruCevap: "C" }, 

    { seviye: 250, kategori: "Canlılar", soru: "Karıncaların liderine ne ad verilir?", secenekler: { A: "Kral", B: "Başkan", C: "Kraliçe", D: "İşçi" }, dogruCevap: "C" },
    { seviye: 251, kategori: "Canlılar", soru: "Yarasalar hangi canlı grubuna girer?", secenekler: { A: "Memeliler", B: "Sürüngenler", C: "Böcekler", D: "Kuşlar" }, dogruCevap: "A" },
    { seviye: 252, kategori: "Canlılar", soru: "Zürafaların ses telleri var mıdır?", secenekler: { A: "Evet", B: "Sadece yavrularında", C: "Sadece erkeklerinde", D: "Hayır (Çok zayıftır/yoktur)" }, dogruCevap: "D" },
    { seviye: 253, kategori: "Canlılar", soru: "Hangi hayvanın sütü koyu pembe renklidir?", secenekler: { A: "Su Aygırı", B: "Fil", C: "Zürafa", D: "Gergedan" }, dogruCevap: "A" },
    { seviye: 254, kategori: "Canlılar", soru: "Deniz atlarında yavruları hangi ebeveyn taşır?", secenekler: { A: "Dişi", B: "İkisi birden", C: "Erkek", D: "Hiçbiri" }, dogruCevap: "C" },
    { seviye: 255, kategori: "Canlılar", soru: "Hangi kuş türü uçarken uyuyabilir?", secenekler: { A: "Serçe", B: "Ebabil", C: "Kartal", D: "Güvercin" }, dogruCevap: "B" },
    { seviye: 256, kategori: "Canlılar", soru: "Bir ahtapotun kaç tane kalbi vardır?", secenekler: { A: "3", B: "4", C: "1", D: "2" }, dogruCevap: "A" },
    { seviye: 257, kategori: "Canlılar", soru: "Bukalemunlar neden renk değiştirir?", secenekler: { A: "Sadece uyurken", B: "Sadece gizlenmek için", C: "Sadece korkunca", D: "Hepsi (Duygular, sıcaklık, gizlenme)" }, dogruCevap: "D" },
    { seviye: 258, kategori: "Canlılar", soru: "Dünyanın en hızlı balığı hangisidir?", secenekler: { A: "Yelken Balığı", B: "Yunus", C: "Palamut", D: "Köpek Balığı" }, dogruCevap: "A" },
    { seviye: 259, kategori: "Canlılar", soru: "Kutup ayılarının derisi ne renktir?", secenekler: { A: "Gri", B: "Beyaz", C: "Pembe", D: "Siyah" }, dogruCevap: "D" },
    { seviye: 260, kategori: "Canlılar", soru: "Karıncalar kendi ağırlıklarının kaç katını kaldırabilir?", secenekler: { A: "5 kat", B: "50 kat", C: "10 kat", D: "100 kat" }, dogruCevap: "B" },
    { seviye: 261, kategori: "Canlılar", soru: "Kedilerin vücudundaki en esnek yer neresidir?", secenekler: { A: "Bacaklar", B: "Kuyruk", C: "Boyun", D: "Omurga" }, dogruCevap: "D" },
    { seviye: 262, kategori: "Canlılar", soru: "Hangi hayvan su içmeden deveden daha uzun süre yaşayabilir?", secenekler: { A: "Zürafa", B: "Kanguru Faresi", C: "Fil", D: "Aslan" }, dogruCevap: "B" },
    { seviye: 263, kategori: "Canlılar", soru: "Baykuşlar başlarını kaç derece döndürebilir?", secenekler: { A: "270 derece", B: "180 derece", C: "360 derece", D: "90 derece" }, dogruCevap: "A" },
    { seviye: 264, kategori: "Canlılar", soru: "Yılanların koku alma organı hangisidir?", secenekler: { A: "Gözü", B: "Dili", C: "Burnu", D: "Derisi" }, dogruCevap: "B" },
    { seviye: 265, kategori: "Canlılar", soru: "Hangi memeli hayvan yumurtlar?", secenekler: { A: "Yarasa", B: "Balina", C: "Kanguru", D: "Ornitorenk" }, dogruCevap: "D" },
    { seviye: 266, kategori: "Canlılar", soru: "Timsahlar dillerini dışarı çıkarabilir mi?", secenekler: { A: "Evet", B: "Sadece yemek yerken", C: "Sadece suda", D: "Hayır" }, dogruCevap: "D" },
    { seviye: 267, kategori: "Canlılar", soru: "Hangi kuşun gözü beyninden daha büyüktür?", secenekler: { A: "Deve Kuşu", B: "Kartal", C: "Baykuş", D: "Papağan" }, dogruCevap: "A" },
    { seviye: 268, kategori: "Canlılar", soru: "Deniz yıldızlarının kaç beyni vardır?", secenekler: { A: "2", B: "5", C: "Beyinleri yoktur", D: "1" }, dogruCevap: "C" },
    { seviye: 269, kategori: "Canlılar", soru: "Hangi böcek kafası kopsa bile bir hafta yaşayabilir?", secenekler: { A: "Arı", B: "Karınca", C: "Hamam Böceği", D: "Sinek" }, dogruCevap: "C" },
    { seviye: 270, kategori: "Canlılar", soru: "İnsan DNA'sı ile %98 oranında benzerlik gösteren hayvan?", secenekler: { A: "Şempanze", B: "At", C: "Fare", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 271, kategori: "Canlılar", soru: "Mavi balinaların kalbi ne büyüklüktedir?", secenekler: { A: "Bir kova kadar", B: "Küçük bir araba kadar", C: "İnsan kalbi kadar", D: "Futbol topu kadar" }, dogruCevap: "B" },
    { seviye: 272, kategori: "Canlılar", soru: "Arıların kaç gözü vardır?", secenekler: { A: "2", B: "5", C: "4", D: "8" }, dogruCevap: "B" },
    { seviye: 273, kategori: "Canlılar", soru: "Kediler tatlı tadını alabilir mi?", secenekler: { A: "Sadece bazı türler", B: "Evet", C: "Sadece yaşlanınca", D: "Hayır" }, dogruCevap: "D" },
    { seviye: 274, kategori: "Canlılar", soru: "Salyangozlar ne kadar süre uyuyabilir?", secenekler: { A: "3 hafta", B: "3 yıl", C: "3 gün", D: "3 ay" }, dogruCevap: "B" },
    { seviye: 275, kategori: "Canlılar", soru: "Hangi hayvanın parmak izi insanınkine çok benzer?", secenekler: { A: "Rakun", B: "Maymun", C: "Koala", D: "Ayı" }, dogruCevap: "C" },
    { seviye: 276, kategori: "Canlılar", soru: "Zürafalar günde ne kadar uyur?", secenekler: { A: "5 saat", B: "8 saat", C: "Yaklaşık 30 dakika", D: "12 saat" }, dogruCevap: "C" },
    { seviye: 277, kategori: "Canlılar", soru: "Hangi kuş türü geri geri uçabilir?", secenekler: { A: "Kırlangıç", B: "Sinek Kuşu", C: "Serçe", D: "Martı" }, dogruCevap: "B" },
    { seviye: 278, kategori: "Canlılar", soru: "İstakozların kanı ne renktir?", secenekler: { A: "Yeşil", B: "Kırmızı", C: "Şeffaf (Oksijen alınca mavi olur)", D: "Sarı" }, dogruCevap: "C" },
    { seviye: 279, kategori: "Canlılar", soru: "Karideslerin kalbi vücutlarının neresindedir?", secenekler: { A: "Kafasında", B: "Göğsünde", C: "Kuyruğunda", D: "Sırtında" }, dogruCevap: "A" },
    { seviye: 280, kategori: "Canlılar", soru: "Domuzlar fiziksel olarak nereye bakamazlar?", secenekler: { A: "Arkalarına", B: "Yere", C: "Gökyüzüne", D: "Yanlarına" }, dogruCevap: "C" },
    { seviye: 281, kategori: "Canlılar", soru: "Fareler neden sürekli bir şeyleri kemirir?", secenekler: { A: "Dişleri sürekli uzadığı için", B: "Yuva yapmak için", C: "Oyun oynamak için", D: "Aç oldukları için" }, dogruCevap: "A" },
    { seviye: 282, kategori: "Canlılar", soru: "Köpek balıklarının kemiği var mıdır?", secenekler: { A: "Sadece kafasında", B: "Hayır (Kıkırdaktır)", C: "Evet", D: "Sadece yüzgeçlerinde" }, dogruCevap: "B" },
    { seviye: 283, kategori: "Canlılar", soru: "Bir inek ömrü boyunca yaklaşık kaç bardak süt verir?", secenekler: { A: "1.000.000", B: "50.000", C: "10.000", D: "200.000" }, dogruCevap: "D" },
    { seviye: 284, kategori: "Canlılar", soru: "Hangi hayvanın grubu 'parlament' olarak adlandırılır?", secenekler: { A: "Kurt", B: "Aslan", C: "Karga", D: "Baykuş" }, dogruCevap: "D" },
    { seviye: 285, kategori: "Canlılar", soru: "Fillerin hortumunda kaç kemik bulunur?", secenekler: { A: "0 (Sıfır)", B: "10", C: "1", D: "100" }, dogruCevap: "A" },
    { seviye: 286, kategori: "Canlılar", soru: "Pireler kendi boylarının kaç katı uzağa zıplayabilir?", secenekler: { A: "200 kat", B: "10 kat", C: "50 kat", D: "1000 kat" }, dogruCevap: "A" },
    { seviye: 287, kategori: "Canlılar", soru: "Deniz analarının vücudunun yüzde kaçı sudur?", secenekler: { A: "%70", B: "%30", C: "%50", D: "%95" }, dogruCevap: "D" },
    { seviye: 288, kategori: "Canlılar", soru: "Kaplanların derisi de çizgili midir?", secenekler: { A: "Sadece erkeklerde", B: "Hayır", C: "Sadece yaşlılarda", D: "Evet" }, dogruCevap: "D" },
    { seviye: 289, kategori: "Canlılar", soru: "Kelebekler tadı neresiyle alır?", secenekler: { A: "Dili", B: "Anteni", C: "Kanadı", D: "Ayakları" }, dogruCevap: "D" },
    { seviye: 290, kategori: "Canlılar", soru: "Atlar ve fareler kusabilir mi?", secenekler: { A: "Evet", B: "Sadece atlar", C: "Hayır", D: "Sadece fareler" }, dogruCevap: "C" },
    { seviye: 291, kategori: "Canlılar", soru: "Dünyanın en büyük böceği hangisidir?", secenekler: { A: "Sinek", B: "Golyat Böceği", C: "Hamam Böceği", D: "Karınca" }, dogruCevap: "B" },
    { seviye: 292, kategori: "Canlılar", soru: "Penguenler nerede yaşar?", secenekler: { A: "Asya", B: "Ekvator", C: "Güney Kutbu", D: "Kuzey Kutbu" }, dogruCevap: "C" },
    { seviye: 293, kategori: "Canlılar", soru: "Hangi kuş türü kendi yuvasını yapmaz?", secenekler: { A: "Guguk Kuşu", B: "Serçe", C: "Kırlangıç", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 294, kategori: "Canlılar", soru: "Kedilerin bıyıkları ne işe yarar?", secenekler: { A: "Isı ölçümü", B: "Denge ve mesafe ölçümü", C: "Koku alma", D: "Güzellik" }, dogruCevap: "B" },
    { seviye: 295, kategori: "Canlılar", soru: "Balinalar nasıl nefes alır?", secenekler: { A: "Derileriyle", B: "Ağızlarıyla", C: "Solungaçlarıyla", D: "Tepelerindeki delikten (Akciğer solunumu)" }, dogruCevap: "D" },
    { seviye: 296, kategori: "Canlılar", soru: "Bir tavuk yılda yaklaşık kaç yumurta yumurtlar?", secenekler: { A: "100", B: "250-300", C: "500", D: "50" }, dogruCevap: "B" },
    { seviye: 297, kategori: "Canlılar", soru: "Deve hörgüçlerinde ne depolar?", secenekler: { A: "Yağ", B: "Hava", C: "Besin", D: "Su" }, dogruCevap: "A" },
    { seviye: 298, kategori: "Canlılar", soru: "Hangi hayvanın dilleri vücutlarından daha uzundur?", secenekler: { A: "Kedi", B: "Zürafa", C: "Fil", D: "Bukalemun" }, dogruCevap: "D" },
    { seviye: 299, kategori: "Canlılar", soru: "Arılar hangi rengi göremezler?", secenekler: { A: "Kırmızı", B: "Sarı", C: "Yeşil", D: "Mavi" }, dogruCevap: "A" },
    { seviye: 300, kategori: "Canlılar", soru: "Hangi canlı türü sonsuza kadar yaşayabilir (biyolojik olarak)?", secenekler: { A: "Kaplumbağa", B: "Balina", C: "Turritopsis dohrnii (Ölümsüz Deniz Anası)", D: "Fil" }, dogruCevap: "C" },
    { seviye: 301, kategori: "Canlılar", soru: "Köpeklerin koku alma duyusu insandan kaç kat güçlüdür?", secenekler: { A: "10 kat", B: "1000 kat", C: "10.000 - 100.000 kat", D: "100 kat" }, dogruCevap: "C" },
    { seviye: 302, kategori: "Canlılar", soru: "Su aygırları terlediğinde terleri ne renk olur?", secenekler: { A: "Kırmızı", B: "Mavi", C: "Sarı", D: "Şeffaf" }, dogruCevap: "A" },
    { seviye: 303, kategori: "Canlılar", soru: "Hangi hayvanın gözbebekleri dikdörtgendir?", secenekler: { A: "At", B: "Baykuş", C: "Kedi", D: "Keçi" }, dogruCevap: "D" },
    { seviye: 304, kategori: "Canlılar", soru: "Karıncaların akciğerleri var mıdır?", secenekler: { A: "Hayır", B: "Sadece kraliçede", C: "Yarısında", D: "Evet" }, dogruCevap: "A" },
    { seviye: 305, kategori: "Canlılar", soru: "Filler neden hortumlarına su doldurup üzerlerine püskürtür?", secenekler: { A: "Oyun için", B: "Temizlenmek için", C: "Hepsi", D: "Serinlemek için" }, dogruCevap: "C" },
    { seviye: 306, kategori: "Canlılar", soru: "Hangi hayvanın kalbi dakikada 1000 kez atabilir?", secenekler: { A: "Fare", B: "Sinek Kuşu", C: "Kedi", D: "Tavşan" }, dogruCevap: "B" },
    { seviye: 307, kategori: "Canlılar", soru: "Aslanlar bir günde kaç saat uyurlar?", secenekler: { A: "5 saat", B: "2 saat", C: "10 saat", D: "16-20 saat" }, dogruCevap: "D" },
    { seviye: 308, kategori: "Canlılar", soru: "Deniz kaplumbağaları yumurtalarını nereye bırakır?", secenekler: { A: "Kayalıklara", B: "Yuvaya", C: "Denize", D: "Kumsala" }, dogruCevap: "D" },
    { seviye: 309, kategori: "Canlılar", soru: "Hangi hayvanın sütü en yağlıdır?", secenekler: { A: "Keçi", B: "Manda", C: "İnek", D: "Mavi Balina" }, dogruCevap: "D" },
    { seviye: 310, kategori: "Canlılar", soru: "Eşek arıları bal yapar mı?", secenekler: { A: "Sadece yazın", B: "Hayır", C: "Evet", D: "Sadece bazı türleri" }, dogruCevap: "B" },
    { seviye: 311, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile kemiklerini bile temizleyebildiği söylenir?", secenekler: { A: "Kedi", B: "Kaplan", C: "Ayı", D: "Köpek" }, dogruCevap: "B" },
    { seviye: 312, kategori: "Canlılar", soru: "Kargalar kaç yıl yaşayabilir?", secenekler: { A: "200 yıl", B: "100 yıl", C: "10 yıl", D: "20-30 yıl (Doğada)" }, dogruCevap: "D" },
    { seviye: 313, kategori: "Canlılar", soru: "Hamsterlar yemeklerini nerede taşır?", secenekler: { A: "Midelerinde", B: "Sırtlarında", C: "Yanaklarında", D: "Ellerinde" }, dogruCevap: "C" },
    { seviye: 314, kategori: "Canlılar", soru: "Hangi kuşun kanat çırpışı duyulmaz?", secenekler: { A: "Baykuş", B: "Serçe", C: "Atmaca", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 315, kategori: "Canlılar", soru: "Yılanların göz kapakları var mıdır?", secenekler: { A: "Evet", B: "Sadece uyurken", C: "Sadece bazı türlerde", D: "Hayır" }, dogruCevap: "D" },
    { seviye: 316, kategori: "Canlılar", soru: "Bir salyangozun kaç tane dişi olabilir?", secenekler: { A: "32", B: "4", C: "Binlerce (Radula üzerinde)", D: "0" }, dogruCevap: "C" },
    { seviye: 317, kategori: "Canlılar", soru: "Hangi hayvanın ter bezleri sadece ayaklarındadır?", secenekler: { A: "Fil", B: "İnsan", C: "Köpek", D: "At" }, dogruCevap: "C" },
    { seviye: 318, kategori: "Canlılar", soru: "Deniz yıldızları kollarını yenileyebilir mi?", secenekler: { A: "Evet", B: "Hayır", C: "Sadece bir kez", D: "Yıllar sürer" }, dogruCevap: "A" },
    { seviye: 319, kategori: "Canlılar", soru: "Arılar birbirlerine yemeğin yerini nasıl söyler?", secenekler: { A: "Dokunarak", B: "Dans ederek", C: "Ses çıkararak", D: "Renk değiştirerek" }, dogruCevap: "B" },
    { seviye: 320, kategori: "Canlılar", soru: "Mavi balinaların dili ne kadar ağırdır?", secenekler: { A: "100 kg", B: "Bir ton", C: "Bir insan kadar", D: "Bir fil kadar" }, dogruCevap: "D" },
    { seviye: 321, kategori: "Canlılar", soru: "Hangi hayvanın dilleri vücut sıcaklığını ayarlamaya yardımcı olur?", secenekler: { A: "Yılan", B: "Kuş", C: "Kedi", D: "Köpek" }, dogruCevap: "D" },
    { seviye: 322, kategori: "Canlılar", soru: "Iskozlar kaç yıl yaşayabilir?", secenekler: { A: "10 yıl", B: "5 yıl", C: "100 yıla kadar", D: "20 yıl" }, dogruCevap: "C" },
    { seviye: 323, kategori: "Canlılar", soru: "Hangi kuş türü penguenler gibi uçamaz?", secenekler: { A: "Deve Kuşu", B: "Albatros", C: "Pelikan", D: "Martı" }, dogruCevap: "A" },
    { seviye: 324, kategori: "Canlılar", soru: "Kelebeklerin kaç kanadı vardır?", secenekler: { A: "4", B: "6", C: "8", D: "2" }, dogruCevap: "A" },
    { seviye: 325, kategori: "Canlılar", soru: "Hangi hayvanın ismi Türkçede 'nehir atı' anlamına gelir?", secenekler: { A: "Denizatı", B: "Su Aygırı", C: "Timsah", D: "Fok" }, dogruCevap: "B" },
    { seviye: 326, kategori: "Canlılar", soru: "Karıncalar kışın ne yapar?", secenekler: { A: "Sıcak yerlere göç ederler", B: "Yerin altında kış uykusuna benzer bir döneme girer", C: "Aynı şekilde çalışırlar", D: "Ölürler" }, dogruCevap: "B" },
    { seviye: 327, kategori: "Canlılar", soru: "Hangi canlı türü ışık üretebilir (Biyolüminesans)?", secenekler: { A: "Karınca", B: "Ateş Böceği", C: "Sinek", D: "Arı" }, dogruCevap: "B" },
    { seviye: 328, kategori: "Canlılar", soru: "Filler birbirleriyle nasıl iletişim kurar?", secenekler: { A: "Dokunarak", B: "Düşük frekanslı sesler ve ayak sarsıntılarıyla", C: "Sadece bağırarak", D: "İletişim kurmazlar" }, dogruCevap: "B" },
    { seviye: 329, kategori: "Canlılar", soru: "Hangi hayvanın gözleri kafasının arkasını görebilir?", secenekler: { A: "Kuş", B: "Tavşan", C: "Kedi", D: "Köpek" }, dogruCevap: "B" },
    { seviye: 330, kategori: "Canlılar", soru: "Yunuslar uyurken neden bir gözleri açık kalır?", secenekler: { A: "Işığı sevdikleri için", B: "Korktukları için", C: "Yüzmek için", D: "Beyinlerinin yarısı uyanık kaldığı için" }, dogruCevap: "D" },
    { seviye: 331, kategori: "Canlılar", soru: "Hangi bitki böcek yiyerek beslenir?", secenekler: { A: "Gül", B: "Papatya", C: "Kaktüs", D: "Venüs Sinek Kapanı" }, dogruCevap: "D" },
    { seviye: 332, kategori: "Canlılar", soru: "Bambu ağacı günde ne kadar uzayabilir?", secenekler: { A: "90 cm'ye kadar", B: "10 cm", C: "5 metre", D: "1 cm" }, dogruCevap: "A" },
    { seviye: 333, kategori: "Canlılar", soru: "Hangi hayvanın dilleri mavidir?", secenekler: { A: "Fil", B: "Aslan", C: "Köpek", D: "Zürafa" }, dogruCevap: "D" },
    { seviye: 334, kategori: "Canlılar", soru: "Denizatı yavruları neye benzer?", secenekler: { A: "Yetişkinlerin minyatür haline", B: "Yumurta sarısına", C: "Balığa", D: "Larvaya" }, dogruCevap: "A" },
    { seviye: 335, kategori: "Canlılar", soru: "Hangi hayvanın kemikleri derisinin dışındadır?", secenekler: { A: "Balık", B: "Kaplumbağa (Kabuk)", C: "Yılan", D: "Kertenkele" }, dogruCevap: "B" },
    { seviye: 336, kategori: "Canlılar", soru: "Su samurları neden el ele tutuşur?", secenekler: { A: "Akıntıda ayrılmamak için", B: "Sevdikleri için", C: "Oyun için", D: "Isınmak için" }, dogruCevap: "A" },
    { seviye: 337, kategori: "Canlılar", soru: "Hangi kuş türü dünyanın en küçük kuşudur?", secenekler: { A: "Saka", B: "Kanarya", C: "Arı Sinek Kuşu", D: "Serçe" }, dogruCevap: "C" },
    { seviye: 338, kategori: "Canlılar", soru: "Yarasalar karanlıkta yollarını nasıl bulur?", secenekler: { A: "Ses dalgalarıyla (Ekolokasyon)", B: "Kokuyla", C: "Isıyla", D: "Gözleriyle" }, dogruCevap: "A" },
    { seviye: 339, kategori: "Canlılar", soru: "Hangi hayvanın kalbi kafasındadır?", secenekler: { A: "Deniz Yıldızı", B: "Istakoz", C: "Karides", D: "Yengeç" }, dogruCevap: "C" },
    { seviye: 340, kategori: "Canlılar", soru: "Deve kuşları tehlike anında kafalarını kuma gömerler mi?", secenekler: { A: "Sadece yavrular", B: "Evet", C: "Sadece uyurken", D: "Hayır (Bu bir efsanedir)" }, dogruCevap: "D" },
    { seviye: 341, kategori: "Canlılar", soru: "Hangi hayvanın dilleri bir insan vücudu kadar uzundur?", secenekler: { A: "Fil", B: "Dev Karıncayiyen", C: "Zürafa", D: "Mavi Balina" }, dogruCevap: "D" },
    { seviye: 342, kategori: "Canlılar", soru: "Kediler ne kadar yükseğe zıplayabilir?", secenekler: { A: "20 katına kadar", B: "Boyları kadar", C: "Boylarının 6 katına kadar", D: "1 metre" }, dogruCevap: "C" },
    { seviye: 343, kategori: "Canlılar", soru: "Hangi balık türü suyun dışında yaşayabilir?", secenekler: { A: "Hamsi", B: "Akciğerli Balık", C: "Sazan", D: "Lüfer" }, dogruCevap: "B" },
    { seviye: 344, kategori: "Canlılar", soru: "İpek böceği ne yer?", secenekler: { A: "Dut yaprağı", B: "Çiçek", C: "Elma", D: "Ot" }, dogruCevap: "A" },
    { seviye: 345, kategori: "Canlılar", soru: "Hangi hayvanın dilleri pütürlüdür ve zımpara gibidir?", secenekler: { A: "İnek", B: "Kedi", C: "At", D: "Köpek" }, dogruCevap: "B" },
    { seviye: 346, kategori: "Canlılar", soru: "Penguenler neden üşümez?", secenekler: { A: "Kalın yağ tabakası ve su geçirmez tüyleri sayesinde", B: "Sıcak kanlı oldukları için", C: "Sürekli hareket ettikleri için", D: "Tüyleri olmadığı için" }, dogruCevap: "A" },
    { seviye: 347, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'nehir ayısı' anlamına gelebilir?", secenekler: { A: "Su Aygırı (Bazı dillerde)", B: "Kunduz", C: "Fok", D: "Timsah" }, dogruCevap: "A" },
    { seviye: 348, kategori: "Canlılar", soru: "Kutup ayıları nerede yaşar?", secenekler: { A: "Kuzey Kutbu", B: "İzlanda", C: "Güney Kutbu", D: "Norveç" }, dogruCevap: "A" },
    { seviye: 349, kategori: "Canlılar", soru: "Hangi kuş türü en büyük yumurtaya sahiptir?", secenekler: { A: "Pelikan", B: "Albatros", C: "Kartal", D: "Deve Kuşu" }, dogruCevap: "D" },
    { seviye: 350, kategori: "Canlılar", soru: "Arıların kaç kanadı vardır?", secenekler: { A: "4", B: "0", C: "6", D: "2" }, dogruCevap: "A" },
    { seviye: 351, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile kulaklarını temizleyebildiği söylenir?", secenekler: { A: "Köpek", B: "Zürafa", C: "Kedi", D: "Fil" }, dogruCevap: "B" },
    { seviye: 352, kategori: "Canlılar", soru: "Yılanların dilleri neden çatallıdır?", secenekler: { A: "Korkutmak için", B: "Ses çıkarmak için", C: "Daha iyi koku ve yön tayini için", D: "Daha iyi yemek yemek için" }, dogruCevap: "C" },
    { seviye: 353, kategori: "Canlılar", soru: "Hangi canlı türü kendi ağırlığının 850 katını kaldırabilir?", secenekler: { A: "Fil", B: "Karınca", C: "Gergedan Böceği", D: "Aslan" }, dogruCevap: "C" },
    { seviye: 354, kategori: "Canlılar", soru: "Hangi hayvanın midesi yoktur?", secenekler: { A: "Kedi", B: "Denizatı", C: "İnek", D: "Köpek" }, dogruCevap: "B" },
    { seviye: 355, kategori: "Canlılar", soru: "Kediler hayatlarının ne kadarını uyuyarak geçirir?", secenekler: { A: "%90", B: "%20", C: "%50", D: "%70" }, dogruCevap: "D" },
    { seviye: 356, kategori: "Canlılar", soru: "Hangi kuş türü kışın güneye göç etmez?", secenekler: { A: "Kırlangıç", B: "Turna", C: "Serçe", D: "Leylek" }, dogruCevap: "C" },
    { seviye: 357, kategori: "Canlılar", soru: "Balıkların göz kapakları var mıdır?", secenekler: { A: "Hayır", B: "Sadece büyüklerde", C: "Evet", D: "Sadece köpek balıklarında" }, dogruCevap: "A" },
    { seviye: 358, kategori: "Canlılar", soru: "Hangi hayvanın kalbi vücuduna göre en büyüğüdür?", secenekler: { A: "Sinek Kuşu", B: "Mavi Balina", C: "Aslan", D: "Fil" }, dogruCevap: "A" },
    { seviye: 359, kategori: "Canlılar", soru: "Filler neden büyük kulaklara sahiptir?", secenekler: { A: "Vücut sıcaklığını dengelemek için", B: "Uçmak için", C: "Daha iyi duymak için", D: "Sinekleri kovmak için" }, dogruCevap: "A" },
    { seviye: 360, kategori: "Canlılar", soru: "Hangi hayvanın gözleri dilediği yöne bağımsız hareket eder?", secenekler: { A: "Baykuş", B: "Bukalemun", C: "At", D: "Kedi" }, dogruCevap: "B" },
    { seviye: 361, kategori: "Canlılar", soru: "Arı kuşu saniyede kaç kez kanat çırpar?", secenekler: { A: "200 kez", B: "10 kez", C: "80 kez", D: "20 kez" }, dogruCevap: "C" },
    { seviye: 362, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile tat alması imkansızdır?", secenekler: { A: "Yılan", B: "Kedi", C: "Timsah", D: "Kuş" }, dogruCevap: "C" },
    { seviye: 363, kategori: "Canlılar", soru: "Kargalar neden parlak nesneleri toplar?", secenekler: { A: "Sadece oyun", B: "Yemek sanırlar", C: "Uğur getirdiğine inanırlar", D: "Yuva yapmak veya ilgi çekmek için" }, dogruCevap: "D" },
    { seviye: 364, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'su domuzu' anlamına gelir?", secenekler: { A: "Su Aygırı", B: "Mors", C: "Fok", D: "Kapibara" }, dogruCevap: "D" },
    { seviye: 365, kategori: "Canlılar", soru: "Kedilerin kaç tane dişi vardır?", secenekler: { A: "20", B: "30", C: "32", D: "40" }, dogruCevap: "B" },
    { seviye: 366, kategori: "Canlılar", soru: "Hangi kuş türü en uzun süre havada kalabilir?", secenekler: { A: "Albatros", B: "Güvercin", C: "Serçe", D: "Kırlangıç" }, dogruCevap: "A" },
    { seviye: 367, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile ağaçları devirebildiği söylenir?", secenekler: { A: "Zürafa", B: "Aslan", C: "Fil (Hortumuyla)", D: "Ayı" }, dogruCevap: "C" },
    { seviye: 368, kategori: "Canlılar", soru: "Hangi canlı türü ışığa doğru uçar?", secenekler: { A: "Sinek", B: "Arı", C: "Pervane Böceği", D: "Karınca" }, dogruCevap: "C" },
    { seviye: 369, kategori: "Canlılar", soru: "Yılanların dilleri neden ıslaktır?", secenekler: { A: "Su içmek için", B: "Sıcak oldukları için", C: "Havadaki parçacıkları toplamak için", D: "Yemek yemek için" }, dogruCevap: "C" },
    { seviye: 370, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile kendisini temizlediği görülür?", secenekler: { A: "Kuş", B: "Fil", C: "Kedi", D: "Zürafa" }, dogruCevap: "C" },
    { seviye: 371, kategori: "Canlılar", soru: "Köpek balıkları kaç yıl yaşayabilir?", secenekler: { A: "50 yıl", B: "Türe göre 20-400 yıl", C: "100 yıl", D: "10 yıl" }, dogruCevap: "B" },
    { seviye: 372, kategori: "Canlılar", soru: "Hangi kuş türü şarkı söylemesiyle ünlüdür?", secenekler: { A: "Kartal", B: "Bülbül", C: "Karga", D: "Martı" }, dogruCevap: "B" },
    { seviye: 373, kategori: "Canlılar", soru: "Arıların bal yapma amacı nedir?", secenekler: { A: "İnsanlar için", B: "Oyun için", C: "Yuva yapmak için", D: "Kışın beslenmek için" }, dogruCevap: "D" },
    { seviye: 374, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile yönünü bulduğu söylenir?", secenekler: { A: "Kuş", B: "Köpek", C: "Kedi", D: "Yılan" }, dogruCevap: "D" },
    { seviye: 375, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'yavaş yürüyen' anlamına gelir?", secenekler: { A: "Tembel Hayvan", B: "Salyangoz", C: "Koala", D: "Kaplumbağa" }, dogruCevap: "A" },
    { seviye: 376, kategori: "Canlılar", soru: "Kedilerin kuyruğu ne işe yarar?", secenekler: { A: "Isınmaya", B: "Süs olarak", C: "Koku almaya", D: "Denge sağlamaya" }, dogruCevap: "D" },
    { seviye: 377, kategori: "Canlılar", soru: "Hangi kuş türü postacılıkta kullanılmıştır?", secenekler: { A: "Kartal", B: "Karga", C: "Serçe", D: "Güvercin" }, dogruCevap: "D" },
    { seviye: 378, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile ağaç kabuklarını soyduğu söylenir?", secenekler: { A: "Zürafa", B: "Fil", C: "Aslan", D: "Ayı" }, dogruCevap: "A" },
    { seviye: 379, kategori: "Canlılar", soru: "Arılar nasıl vızıldar?", secenekler: { A: "Burnuyla", B: "Ayaklarını sürterek", C: "Kanatlarını çok hızlı çırparak", D: "Ağızlarıyla" }, dogruCevap: "C" },
    { seviye: 380, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile yarasaları yakaladığı söylenir?", secenekler: { A: "Kuş", B: "Kedi", C: "Yılan", D: "Aslan" }, dogruCevap: "C" },
    { seviye: 381, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'orman adamı' anlamına gelir?", secenekler: { A: "Maymun", B: "Orangutan", C: "Goril", D: "Şempanze" }, dogruCevap: "B" },
    { seviye: 382, kategori: "Canlılar", soru: "Kediler neden mırlar?", secenekler: { A: "Sadece korkunca", B: "Sadece aç olduklarında", C: "Hepsi (Mutluluk, iyileşme, stres)", D: "Sadece mutlu olduklarında" }, dogruCevap: "C" },
    { seviye: 383, kategori: "Canlılar", soru: "Hangi kuş türü renkli tüyleriyle ünlüdür?", secenekler: { A: "Serçe", B: "Güvercin", C: "Papağan", D: "Karga" }, dogruCevap: "C" },
    { seviye: 384, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile çiçek özlerini topladığı söylenir?", secenekler: { A: "Sinek", B: "Arı (Hortumuyla)", C: "Kuş", D: "Kelebek" }, dogruCevap: "B" },
    { seviye: 385, kategori: "Canlılar", soru: "Arıların zehri ne işe yarar?", secenekler: { A: "Oyun oynamaya", B: "Bal yapmaya", C: "Kendilerini korumaya", D: "Beslenmeye" }, dogruCevap: "C" },
    { seviye: 386, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile ağaçları oyduğu söylenir?", secenekler: { A: "Fil", B: "Zürafa", C: "Ağaçkakan (Gagasıyla)", D: "Ayı" }, dogruCevap: "C" },
    { seviye: 387, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'dik diken' anlamına gelebilir?", secenekler: { A: "Domuz", B: "Fare", C: "Kedi", D: "Kirpi" }, dogruCevap: "D" },
    { seviye: 388, kategori: "Canlılar", soru: "Kediler neden yüksekten düşerken dört ayak üstüne düşer?", secenekler: { A: "Hafif oldukları için", B: "Doğrulma refleksi sayesinde", C: "Şanslı oldukları için", D: "Uçabildikleri için" }, dogruCevap: "B" },
    { seviye: 389, kategori: "Canlılar", soru: "Hangi kuş türü suyun altına dalarak balık yakalar?", secenekler: { A: "Karga", B: "Serçe", C: "Karabatak", D: "Güvercin" }, dogruCevap: "C" },
    { seviye: 390, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile yavrularını taşıdığı söylenir?", secenekler: { A: "Aslan", B: "Kedi", C: "Timsah", D: "Ayı" }, dogruCevap: "C" },
    { seviye: 391, kategori: "Canlılar", soru: "Arılar kaç rekat... (Şaka: Arılar kaç kanatlıdır?)", secenekler: { A: "2", B: "0", C: "4", D: "6" }, dogruCevap: "C" },
    { seviye: 392, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile avını yakaladığı söylenir?", secenekler: { A: "Fil", B: "Kurbağa", C: "Zürafa", D: "Aslan" }, dogruCevap: "B" },
    { seviye: 393, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'çöl gemisi'dir?", secenekler: { A: "Eşek", B: "At", C: "Fil", D: "Deve" }, dogruCevap: "D" },
    { seviye: 394, kategori: "Canlılar", soru: "Kediler neden gece daha iyi görür?", secenekler: { A: "Gözleri büyük olduğu için", B: "Gece yaşadıkları için", C: "Gözlerindeki özel tabaka (Tapetum lucidum) sayesinde", D: "Gözleri parladığı için" }, dogruCevap: "C" },
    { seviye: 395, kategori: "Canlılar", soru: "Hangi kuş türü çok uzak mesafelerden göç eder?", secenekler: { A: "Karga", B: "Serçe", C: "Kuzey Sumrusu", D: "Güvercin" }, dogruCevap: "C" },
    { seviye: 396, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile termitleri topladığı söylenir?", secenekler: { A: "Fil", B: "Aslan", C: "Karıncayiyen", D: "Zürafa" }, dogruCevap: "C" },
    { seviye: 397, kategori: "Canlılar", soru: "Arılar nasıl bal yapar?", secenekler: { A: "Çiçek özlerini toplayıp mide enzimleriyle karıştırarak", B: "Toprakla", C: "Çiçekleri yiyerek", D: "Su içerek" }, dogruCevap: "A" },
    { seviye: 398, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile buzları yaladığı söylenir?", secenekler: { A: "Aslan", B: "Fil", C: "Zürafa", D: "Kutup Ayısı" }, dogruCevap: "D" },
    { seviye: 399, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'deniz aslanı'dır?", secenekler: { A: "Mors", B: "Balina", C: "Deniz Aslanı", D: "Fok" }, dogruCevap: "C" },
    { seviye: 400, kategori: "Canlılar", soru: "Hangi kuş türü 'orman doktoru' olarak bilinir?", secenekler: { A: "Baykuş", B: "Kartal", C: "Serçe", D: "Ağaçkakan" }, dogruCevap: "D" },
    { seviye: 401, kategori: "Canlılar", soru: "Karıncalar koku almak için hangi organlarını kullanırlar?", secenekler: { A: "Gözlerini", B: "Antenlerini", C: "Bacaklarını", D: "Ağızlarını" }, dogruCevap: "B" },
    { seviye: 402, kategori: "Canlılar", soru: "Vücudunda kemik yerine sadece kıkırdak bulunan dev deniz canlısı?", secenekler: { A: "Mavi Balina", B: "Yunus", C: "Kılıç Balığı", D: "Balina Köpekbalığı" }, dogruCevap: "D" },
    { seviye: 403, kategori: "Canlılar", soru: "Hangi hayvanın dilleri mor veya mavimsi bir renktedir?", secenekler: { A: "Su Aygırı", B: "Fil", C: "Kaplan", D: "Zürafa" }, dogruCevap: "D" },
    { seviye: 404, kategori: "Canlılar", soru: "Gözleri vücuduna oranla en büyük olan memeli hangisidir?", secenekler: { A: "Tarsier (Uzun bacaklı makak)", B: "Tavşan", C: "Kedi", D: "Fare" }, dogruCevap: "A" },
    { seviye: 405, kategori: "Canlılar", soru: "Hangi hayvanın sütünün rengi parlak pembedir?", secenekler: { A: "Su Aygırı", B: "Zürafa", C: "Zebra", D: "Gergedan" }, dogruCevap: "A" },
    { seviye: 406, kategori: "Canlılar", soru: "Ahtapotların kaç tane beyni vardır?", secenekler: { A: "9", B: "1", C: "5", D: "3" }, dogruCevap: "A" },
    { seviye: 407, kategori: "Canlılar", soru: "Bitkilerin terleme yaptığı gözeneklere ne ad verilir?", secenekler: { A: "Hücre Çeperi", B: "Koful", C: "Stoma", D: "Kloroplast" }, dogruCevap: "C" },
    { seviye: 408, kategori: "Canlılar", soru: "Hangi canlı türü su altında en uzun süre nefes almadan kalabilir?", secenekler: { A: "Deniz Kaplumbağası", B: "İspermeçet Balinası", C: "Yunus", D: "Fok" }, dogruCevap: "B" },
    { seviye: 409, kategori: "Canlılar", soru: "Yılanların göz kapakları olmadığı için gözlerini ne korur?", secenekler: { A: "Şeffaf bir tabaka (Pul)", B: "Tüyler", C: "Hiçbir şey", D: "Gözlük" }, dogruCevap: "A" },
    { seviye: 410, kategori: "Canlılar", soru: "Bir bal arısı hayatı boyunca ne kadar bal üretebilir?", secenekler: { A: "Bir yemek kaşığı", B: "Bir kavanoz", C: "Bir çay kaşığının 12'de biri kadar", D: "Bir kilo" }, dogruCevap: "C" },
    { seviye: 411, kategori: "Canlılar", soru: "Hangi kuşun kanat açıklığı 3.5 metreyi bulabilir?", secenekler: { A: "Albatros", B: "Kartal", C: "Leylek", D: "Akbaba" }, dogruCevap: "A" },
    { seviye: 412, kategori: "Canlılar", soru: "Karasineklerin kaç tane gözü vardır?", secenekler: { A: "10", B: "Yaklaşık 4000 (Petek göz)", C: "4", D: "2" }, dogruCevap: "B" },
    { seviye: 413, kategori: "Canlılar", soru: "Hangi hayvanın dilleri kaba bir zımpara kağıdı gibidir?", secenekler: { A: "Köpek", B: "Kaplan", C: "At", D: "İnek" }, dogruCevap: "B" },
    { seviye: 414, kategori: "Canlılar", soru: "Denizatı hangi balık sınıfına girer?", secenekler: { A: "Yumuşakçalar", B: "Sürüngenler", C: "Kemikli Balıklar", D: "Memeliler" }, dogruCevap: "C" },
    { seviye: 415, kategori: "Canlılar", soru: "Dünyanın en zehirli deniz canlısı hangisidir?", secenekler: { A: "Kutu Deniz Anası", B: "Ahtapot", C: "Mürekkep Balığı", D: "Köpekbalığı" }, dogruCevap: "A" },
    { seviye: 416, kategori: "Canlılar", soru: "Kelebekler kışın ne yapar?", secenekler: { A: "Hepsi ölür", B: "Besin toplarlar", C: "Suda yaşarlar", D: "Türüne göre göç eder veya kış uykusuna yatar" }, dogruCevap: "D" },
    { seviye: 417, kategori: "Canlılar", soru: "Hangi kuş türü suda yürüyormuş gibi görünür?", secenekler: { A: "Ördek", B: "Kuğu", C: "Jakana", D: "Pelikan" }, dogruCevap: "C" },
    { seviye: 418, kategori: "Canlılar", soru: "Hangi canlı türü sadece okaliptüs yapraklarıyla beslenir?", secenekler: { A: "Koala", B: "Panda", C: "Maymun", D: "Kanguru" }, dogruCevap: "A" },
    { seviye: 419, kategori: "Canlılar", soru: "Tarantulalar tehlike anında ne yaparlar?", secenekler: { A: "Uçarlar", B: "Ölü taklidi yaparlar", C: "Karınlarındaki tüyleri fırlatırlar", D: "Renk değiştirirler" }, dogruCevap: "C" },
    { seviye: 420, kategori: "Canlılar", soru: "Arıların kaç kanadı vardır?", secenekler: { A: "4", B: "2", C: "0", D: "6" }, dogruCevap: "A" },
    { seviye: 421, kategori: "Canlılar", soru: "Fillerin hortumu kaç litre su alabilir?", secenekler: { A: "100 Litre", B: "1 Litre", C: "50 Litre", D: "8-10 Litre" }, dogruCevap: "D" },
    { seviye: 422, kategori: "Canlılar", soru: "Hangi kuşun gagası vücudundan daha uzun olabilir?", secenekler: { A: "Tukan", B: "Leylek", C: "Pelikan", D: "Kılıç Gagalı Sinek Kuşu" }, dogruCevap: "D" },
    { seviye: 423, kategori: "Canlılar", soru: "Köpeklerin burun izi neye benzer?", secenekler: { A: "Tüylüdür", B: "Yaşlandıkça silinir", C: "Hepsi aynıdır", D: "İnsan parmak izi gibi eşsizdir" }, dogruCevap: "D" },
    { seviye: 424, kategori: "Canlılar", soru: "Yarasalar neden baş aşağı uyurlar?", secenekler: { A: "Kan akışı için", B: "Hafif kemikleri uçmaya daha kolay başlamak içindir", C: "Öyle sevdikleri için", D: "Düşmanları göremesin diye" }, dogruCevap: "B" },
    { seviye: 425, kategori: "Canlılar", soru: "Hangi canlı türünün kanı yeşildir?", secenekler: { A: "Kuş", B: "Tavşan", C: "Bazı kertenkele türleri", D: "Fare" }, dogruCevap: "C" },
    { seviye: 426, kategori: "Canlılar", soru: "Zürafaların boyunlarındaki kemik sayısı kaçtır?", secenekler: { A: "100", B: "50", C: "20", D: "7 (İnsanla aynı)" }, dogruCevap: "D" },
    { seviye: 427, kategori: "Canlılar", soru: "Ateş böcekleri neden ışık yayarlar?", secenekler: { A: "Eş bulmak ve iletişim için", B: "Isınmak için", C: "Yolunu bulmak için", D: "Korkutmak için" }, dogruCevap: "A" },
    { seviye: 428, kategori: "Canlılar", soru: "Hangi balık türü geri geri yüzebilir?", secenekler: { A: "Hamsi", B: "Lüfer", C: "Sazan", D: "Tetik Balığı" }, dogruCevap: "D" },
    { seviye: 429, kategori: "Canlılar", soru: "Baykuşların kulakları neden asimetriktir?", secenekler: { A: "Sesin kaynağını tam bulmak için", B: "Rüzgarı engellemek için", C: "Daha iyi duymak için", D: "Doğuştan hatadır" }, dogruCevap: "A" },
    { seviye: 430, kategori: "Canlılar", soru: "Karıncaların ortalama ömrü ne kadardır?", secenekler: { A: "100 yıl", B: "10 yıl", C: "İşçiler birkaç ay, kraliçeler yıllarca", D: "1 gün" }, dogruCevap: "C" },
    { seviye: 431, kategori: "Canlılar", soru: "Penguenlerin sadece neresi tüysüzdür?", secenekler: { A: "Karnı", B: "Kanatları", C: "Sırtı", D: "Ayakları ve gagasının bir kısmı" }, dogruCevap: "D" },
    { seviye: 432, kategori: "Canlılar", soru: "Hangi hayvanın dilleri boyundan daha uzundur?", secenekler: { A: "Fare", B: "Kedi", C: "Köpek", D: "Bukalemun" }, dogruCevap: "D" },
    { seviye: 433, kategori: "Canlılar", soru: "Mavi balinalar günde kaç ton karides benzeri canlı (krill) yer?", secenekler: { A: "1 Ton", B: "100 Kilo", C: "10 Ton", D: "4 Ton" }, dogruCevap: "D" },
    { seviye: 434, kategori: "Canlılar", soru: "Bukalemunların dilleri avına ne kadar sürede ulaşır?", secenekler: { A: "Saniyenin 1/16'sında", B: "10 saniyede", C: "1 saniyede", D: "5 saniyede" }, dogruCevap: "A" },
    { seviye: 435, kategori: "Canlılar", soru: "Hangi kuş türü yuvasını çamurdan yapar?", secenekler: { A: "Güvercin", B: "Karga", C: "Kırlangıç", D: "Serçe" }, dogruCevap: "C" },
    { seviye: 436, kategori: "Canlılar", soru: "Balinalar neden suyun üzerine fırlarlar?", secenekler: { A: "Hepsi (Parazit dökmek, iletişim, oyun)", B: "Sadece nefes almak", C: "Yıkanmak için", D: "Sadece oyun" }, dogruCevap: "A" },
    { seviye: 437, kategori: "Canlılar", soru: "Deve kuşları saatte kaç km hızla koşabilir?", secenekler: { A: "70 km", B: "20 km", C: "120 km", D: "40 km" }, dogruCevap: "A" },
    { seviye: 438, kategori: "Canlılar", soru: "Bir ipek böceği kozasını örmek için ne kadar ip üretir?", secenekler: { A: "10 metre", B: "900 metre", C: "100 metre", D: "5 km" }, dogruCevap: "B" },
    { seviye: 439, kategori: "Canlılar", soru: "Hangi hayvanın dişleri kemikten değil, fildişinden oluşur?", secenekler: { A: "Ayı", B: "Fil", C: "Gergedan", D: "Aslan" }, dogruCevap: "B" },
    { seviye: 440, kategori: "Canlılar", soru: "Kedilerin kulaklarında kaç adet kas bulunur?", secenekler: { A: "100", B: "10", C: "32", D: "2" }, dogruCevap: "C" },
    { seviye: 441, kategori: "Canlılar", soru: "Hangi canlı türü dilleri ile su içmez, suyu derisiyle emer?", secenekler: { A: "Yılan", B: "Kuş", C: "Kurbağa", D: "Kertenkele" }, dogruCevap: "C" },
    { seviye: 442, kategori: "Canlılar", soru: "Hamam böcekleri radyasyona ne kadar dayanıklıdır?", secenekler: { A: "İnsandan 15 kat daha fazla", B: "Sadece sıcakta dayanır", C: "Dayanıksızdır", D: "Hiç etkilenmez" }, dogruCevap: "A" },
    { seviye: 443, kategori: "Canlılar", soru: "Hangi hayvanın gözleri beyninden daha ağırdır?", secenekler: { A: "Baykuş", B: "Kartal", C: "Deve Kuşu", D: "Dev Mürekkep Balığı" }, dogruCevap: "C" },
    { seviye: 444, kategori: "Canlılar", soru: "Yengeçler neden yan yürürler?", secenekler: { A: "Daha hızlı gitmek için", B: "Öyle sevdikleri için", C: "Bacak eklemleri o yöne büküldüğü için", D: "Dengede kalmak için" }, dogruCevap: "C" },
    { seviye: 445, kategori: "Canlılar", soru: "Hangi kuş türü havada asılı kalabilir?", secenekler: { A: "Kırlangıç", B: "Sinek Kuşu", C: "Atmaca", D: "Serçe" }, dogruCevap: "B" },
    { seviye: 446, kategori: "Canlılar", soru: "Karıncaların akciğerleri var mıdır?", secenekler: { A: "Büyüyünce oluşur", B: "Evet", C: "Sadece su altındayken", D: "Hayır, vücutlarındaki deliklerden nefes alırlar" }, dogruCevap: "D" },
    { seviye: 447, kategori: "Canlılar", soru: "Hangi canlı türü kendisini iyileştirmek için bitkileri kullanır?", secenekler: { A: "Şempanzeler", B: "Köpekler", C: "Kuşlar", D: "Kediler" }, dogruCevap: "A" },
    { seviye: 448, kategori: "Canlılar", soru: "Ahtapotlar kaç tane kalbe sahiptir?", secenekler: { A: "2", B: "1", C: "3", D: "5" }, dogruCevap: "C" },
    { seviye: 449, kategori: "Canlılar", soru: "Hangi balık türü yumurtalarını ağzında taşır?", secenekler: { A: "Sazan", B: "Hamsi", C: "Palamut", D: "Ciklet Balığı" }, dogruCevap: "D" },
    { seviye: 450, kategori: "Canlılar", soru: "Deniz kaplumbağalarının cinsiyetini ne belirler?", secenekler: { A: "Yiyecekler", B: "Kumsalın sıcaklığı", C: "Rastgele", D: "Derinlik" }, dogruCevap: "B" },
    { seviye: 451, kategori: "Canlılar", soru: "Hangi hayvanın dilleri bir insanın kolu kadar uzayabilir?", secenekler: { A: "Yılan", B: "Zürafa", C: "Dev Karıncayiyen", D: "Bukalemun" }, dogruCevap: "C" },
    { seviye: 452, kategori: "Canlılar", soru: "Fillerin hortumunda kaç tane kas vardır?", secenekler: { A: "100", B: "10", C: "1000", D: "Yaklaşık 40.000" }, dogruCevap: "D" },
    { seviye: 453, kategori: "Canlılar", soru: "Hangi kuş türü karda yuva yapar?", secenekler: { A: "Serçe", B: "Kar Baykuşu", C: "Martı", D: "İmparator Penguen" }, dogruCevap: "D" },
    { seviye: 454, kategori: "Canlılar", soru: "Yılanlar neden dillerini sürekli dışarı çıkarırlar?", secenekler: { A: "Sıcakladıkları için", B: "Havayı koklamak ve tatmak için", C: "Su içmek için", D: "Korkutmak için" }, dogruCevap: "B" },
    { seviye: 455, kategori: "Canlılar", soru: "Hangi balık türü ağaca tırmanabilir?", secenekler: { A: "Uçan Balık", B: "Lüfer", C: "Sazan", D: "Çamur Zıpzıpı" }, dogruCevap: "D" },
    { seviye: 456, kategori: "Canlılar", soru: "Hangi hayvanın midesi yoktur?", secenekler: { A: "Denizatı", B: "Fare", C: "İnek", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 457, kategori: "Canlılar", soru: "Arılar balı neyden yaparlar?", secenekler: { A: "Yaprak", B: "Polen", C: "Su", D: "Çiçek nektarı" }, dogruCevap: "D" },
    { seviye: 458, kategori: "Canlılar", soru: "Hangi kuş türü en zeki kuşlardan biri sayılır?", secenekler: { A: "Serçe", B: "Karga", C: "Tavuk", D: "Güvercin" }, dogruCevap: "B" },
    { seviye: 459, kategori: "Canlılar", soru: "Kediler ne kadar uzağı görebilir?", secenekler: { A: "Uzağı bulanık, yakını çok net görürler", B: "İnsanla aynıdır", C: "Kartal gibidirler", D: "Görmezler" }, dogruCevap: "A" },
    { seviye: 460, kategori: "Canlılar", soru: "Hangi canlı türü dünyada en çok bulunan canlıdır?", secenekler: { A: "Nematodlar (Yuvarlak solucanlar)", B: "Karıncalar", C: "Balıklar", D: "İnsanlar" }, dogruCevap: "A" },
    { seviye: 461, kategori: "Canlılar", soru: "Atlar neden ayakta uyurlar?", secenekler: { A: "Yatamadıkları için", B: "Dizleri kitlendiği için", C: "Dinlenmek için", D: "Tehlikelere karşı hızlı kaçabilmek için" }, dogruCevap: "D" },
    { seviye: 462, kategori: "Canlılar", soru: "Hangi hayvanın parmak izi neredeyse insanla aynıdır?", secenekler: { A: "Şempanze", B: "Ayı", C: "Koala", D: "Rakun" }, dogruCevap: "C" },
    { seviye: 463, kategori: "Canlılar", soru: "Kelebeklerin tat alma organları nerededir?", secenekler: { A: "Ayaklarında", B: "Antenlerinde", C: "Dillerinde", D: "Kanatlarında" }, dogruCevap: "A" },
    { seviye: 464, kategori: "Canlılar", soru: "Hangi hayvan asla unutmamasıyla ünlüdür?", secenekler: { A: "Karga", B: "Köpek", C: "Fil", D: "Aslan" }, dogruCevap: "C" },
    { seviye: 465, kategori: "Canlılar", soru: "Tavşanların kaç tane dişi vardır?", secenekler: { A: "32", B: "4", C: "28", D: "10" }, dogruCevap: "C" },
    { seviye: 466, kategori: "Canlılar", soru: "Hangi canlı türü suyun üstünde koşabilir?", secenekler: { A: "Baziliski Kertenkelesi", B: "Fare", C: "Kurbağa", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 467, kategori: "Canlılar", soru: "Arılar hangi renkleri görebilirler?", secenekler: { A: "Siyah beyaz", B: "Mavi, yeşil ve ultraviyole", C: "Tüm renkler", D: "Sadece kırmızı" }, dogruCevap: "B" },
    { seviye: 468, kategori: "Canlılar", soru: "Hangi kuşun kanatları yüzgeç görevi görür?", secenekler: { A: "Penguen", B: "Pelikan", C: "Kuğu", D: "Martı" }, dogruCevap: "A" },
    { seviye: 469, kategori: "Canlılar", soru: "Yunuslar neden birbirlerine ıslık çalarlar?", secenekler: { A: "Kavga etmek için", B: "Yol bulmak için", C: "Birbirlerine isimleriyle seslenmek için", D: "Şarkı söylemek için" }, dogruCevap: "C" },
    { seviye: 470, kategori: "Canlılar", soru: "Hangi hayvanın sütü dondurma yapımında kullanılmaz?", secenekler: { A: "Keçi", B: "Manda", C: "İnek", D: "Balina" }, dogruCevap: "D" },
    { seviye: 471, kategori: "Canlılar", soru: "Arı kuşu saniyede kaç kez kanat çırpar?", secenekler: { A: "10 kez", B: "200 kez", C: "5 kez", D: "80 kez" }, dogruCevap: "D" },
    { seviye: 472, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile kulaklarını temizlediği söylenir?", secenekler: { A: "Fil", B: "Aslan", C: "Zürafa", D: "Kedi" }, dogruCevap: "C" },
    { seviye: 473, kategori: "Canlılar", soru: "Karıncalar neden birbirini takip eder?", secenekler: { A: "Bırakılan feromon (koku) izini izledikleri için", B: "Seslendikleri için", C: "Gördükleri için", D: "Elele tutuştukları için" }, dogruCevap: "A" },
    { seviye: 474, kategori: "Canlılar", soru: "Hangi hayvanın kalbi kafasındadır?", secenekler: { A: "Yengeç", B: "Karides", C: "Istakoz", D: "Deniz Yıldızı" }, dogruCevap: "B" },
    { seviye: 475, kategori: "Canlılar", soru: "Baykuşlar başlarını kaç derece döndürebilir?", secenekler: { A: "180 derece", B: "90 derece", C: "270 derece", D: "360 derece" }, dogruCevap: "C" },
    { seviye: 476, kategori: "Canlılar", soru: "Hangi canlı türü yaşlandıkça küçülür?", secenekler: { A: "Bazı deniz anası türleri", B: "Yılan", C: "Kuş", D: "Fare" }, dogruCevap: "A" },
    { seviye: 477, kategori: "Canlılar", soru: "Iskozların kanı ne renktir?", secenekler: { A: "Şeffaf", B: "Mavi", C: "Kırmızı", D: "Sarı" }, dogruCevap: "B" },
    { seviye: 478, kategori: "Canlılar", soru: "Hangi hayvanın dilleri pütürlüdür?", secenekler: { A: "Köpek", B: "İnek", C: "Kedi", D: "At" }, dogruCevap: "C" },
    { seviye: 479, kategori: "Canlılar", soru: "Penguenler nerede yaşar?", secenekler: { A: "Kuzey Kutbu", B: "Güney Kutbu", C: "Ekvator", D: "Asya" }, dogruCevap: "B" },
    { seviye: 480, kategori: "Canlılar", soru: "Hangi kuş türü havada uyuyabilir?", secenekler: { A: "Serçe", B: "Güvercin", C: "Karga", D: "Ebabil" }, dogruCevap: "D" },
    { seviye: 481, kategori: "Canlılar", soru: "Zürafalar nasıl su içerler?", secenekler: { A: "Su içmezler", B: "Ön bacaklarını yanlara açarak", C: "Yatarak", D: "Zıplayarak" }, dogruCevap: "B" },
    { seviye: 482, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile ağaçları devirdiği söylenir?", secenekler: { A: "Zürafa", B: "Fil (Hortumuyla)", C: "Aslan", D: "Ayı" }, dogruCevap: "B" },
    { seviye: 483, kategori: "Canlılar", soru: "Arıların zehri ne içerir?", secenekler: { A: "Melittin", B: "Su", C: "Şeker", D: "Tuz" }, dogruCevap: "A" },
    { seviye: 484, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'nehir atı'dır?", secenekler: { A: "Su Aygırı", B: "Balina", C: "Fok", D: "Timsah" }, dogruCevap: "A" },
    { seviye: 485, kategori: "Canlılar", soru: "Hangi kuş türü yuva yapmaz?", secenekler: { A: "Serçe", B: "Kırlangıç", C: "Guguk Kuşu", D: "Kartal" }, dogruCevap: "C" },
    { seviye: 486, kategori: "Canlılar", soru: "Hangi hayvanın dilleri mor renktedir?", secenekler: { A: "Kedi", B: "Fil", C: "Zürafa", D: "Kaplan" }, dogruCevap: "C" },
    { seviye: 487, kategori: "Canlılar", soru: "Kediler neden ot yerler?", secenekler: { A: "Sevdikleri için", B: "Midelerini temizlemek için", C: "Aç oldukları için", D: "Oyun için" }, dogruCevap: "B" },
    { seviye: 488, kategori: "Canlılar", soru: "Hangi hayvanın gözleri dilediği yöne hareket eder?", secenekler: { A: "Baykuş", B: "At", C: "Bukalemun", D: "Kedi" }, dogruCevap: "C" },
    { seviye: 489, kategori: "Canlılar", soru: "Arıların kaç gözü vardır?", secenekler: { A: "4", B: "5", C: "10", D: "2" }, dogruCevap: "B" },
    { seviye: 490, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'yavaş yürüyen'dir?", secenekler: { A: "Tembel Hayvan", B: "Kaplumbağa", C: "Koala", D: "Salyangoz" }, dogruCevap: "A" },
    { seviye: 491, kategori: "Canlılar", soru: "Hangi kuş türü renkli tüyleriyle ünlüdür?", secenekler: { A: "Serçe", B: "Güvercin", C: "Papağan", D: "Karga" }, dogruCevap: "C" },
    { seviye: 492, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile avını yakaladığı söylenir?", secenekler: { A: "Fil", B: "Aslan", C: "Kurbağa", D: "Zürafa" }, dogruCevap: "C" },
    { seviye: 493, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'çöl gemisi'dir?", secenekler: { A: "Deve", B: "Fil", C: "Eşek", D: "At" }, dogruCevap: "A" },
    { seviye: 494, kategori: "Canlılar", soru: "Kediler neden mırlar?", secenekler: { A: "Oyun için", B: "Korktukları için", C: "Mutluluk ve iyileşme için", D: "Aç oldukları için" }, dogruCevap: "C" },
    { seviye: 495, kategori: "Canlılar", soru: "Hangi kuş türü çok uzaklara göç eder?", secenekler: { A: "Serçe", B: "Karga", C: "Güvercin", D: "Kuzey Sumrusu" }, dogruCevap: "D" },
    { seviye: 496, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile termitleri toplar?", secenekler: { A: "Zürafa", B: "Fil", C: "Karıncayiyen", D: "Aslan" }, dogruCevap: "C" },
    { seviye: 497, kategori: "Canlılar", soru: "Arılar nasıl bal yapar?", secenekler: { A: "Toprakla", B: "Su içerek", C: "Çiçekleri yiyerek", D: "Nektarı midelerinde işleyerek" }, dogruCevap: "D" },
    { seviye: 498, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile buzları yalar?", secenekler: { A: "Kutup Ayısı", B: "Aslan", C: "Fil", D: "Zürafa" }, dogruCevap: "A" },
    { seviye: 499, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'deniz aslanı'dır?", secenekler: { A: "Balina", B: "Fok", C: "Mors", D: "Deniz Aslanı" }, dogruCevap: "D" }
 
 

);
