window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Türkiye Fiziki Coğrafyası (Dağlar, Göller, Akarsular)
    { seviye: 1, kategori: "Coğrafya", soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "Ankara", B: "İstanbul", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 2, kategori: "Coğrafya", soru: "Türkiye'nin en yüksek dağı hangisidir?", secenekler: { A: "Erciyes", B: "Süphan", C: "Ağrı Dağı", D: "Kaçkar" }, dogruCevap: "C" },
    { seviye: 3, kategori: "Coğrafya", soru: "Türkiye'nin yüzölçümü bakımından en büyük gölü hangisidir?", secenekler: { A: "Eğirdir Gölü", B: "Tuz Gölü", C: "Beyşehir Gölü", D: "Van Gölü" }, dogruCevap: "D" },
    { seviye: 4, kategori: "Coğrafya", soru: "Türkiye'nin en uzun nehri (tamamı ülke sınırları içinde) hangisidir?", secenekler: { A: "Fırat", B: "Yeşilırmak", C: "Kızılırmak", D: "Dicle" }, dogruCevap: "C" },
    { seviye: 5, kategori: "Coğrafya", soru: "Türkiye'nin en büyük deltası hangisidir?", secenekler: { A: "Çukurova", B: "Silifke", C: "Bafra", D: "Çarşamba" }, dogruCevap: "A" },
    { seviye: 6, kategori: "Coğrafya", soru: "Ege Bölgesi'nde dağlar denize nasıl uzanır?", secenekler: { A: "Kesik", B: "Paralel", C: "Dik", D: "Çapraz" }, dogruCevap: "C" },
    { seviye: 7, kategori: "Coğrafya", soru: "Türkiye'nin en büyük adası hangisidir?", secenekler: { A: "Gökçeada", B: "Marmara Adası", C: "Bozcaada", D: "Büyükada" }, dogruCevap: "A" },
    { seviye: 8, kategori: "Coğrafya", soru: "Nemrut Dağı ve üzerindeki dev heykeller hangi ilimizdedir?", secenekler: { A: "Malatya", B: "Şanlıurfa", C: "Adıyaman", D: "Bitlis" }, dogruCevap: "C" },
    { seviye: 9, kategori: "Coğrafya", soru: "Manyas (Kuş) Gölü hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Manisa", B: "Çanakkale", C: "Bursa", D: "Balıkesir" }, dogruCevap: "D" },
    { seviye: 10, kategori: "Coğrafya", soru: "Türkiye'nin en kuzey noktası olan İnceburun hangi ilimizdedir?", secenekler: { A: "Kırklareli", B: "Sinop", C: "Kastamonu", D: "Artvin" }, dogruCevap: "B" },
    { seviye: 11, kategori: "Coğrafya", soru: "Dünyanın en büyük peribacaları oluşumları hangi bölgemizdedir?", secenekler: { A: "İç Anadolu", B: "Doğu Anadolu", C: "Güneydoğu Anadolu", D: "Ege" }, dogruCevap: "A" },
    { seviye: 12, kategori: "Coğrafya", soru: "Hangi ilimiz hem Asya hem de Avrupa kıtasında toprağa sahiptir?", secenekler: { A: "Kocaeli", B: "İstanbul", C: "Çanakkale", D: "Edirne" }, dogruCevap: "B" },
    { seviye: 13, kategori: "Coğrafya", soru: "Türkiye'nin en az yağış alan yöresi hangisidir?", secenekler: { A: "Ergene Havzası", B: "Tuz Gölü Çevresi", C: "Iğdır Ovası", D: "Güneydoğu Anadolu" }, dogruCevap: "B" },
    { seviye: 14, kategori: "Coğrafya", soru: "Toros Dağları hangi coğrafi bölgemizin karakteristik dağıdır?", secenekler: { A: "Karadeniz", B: "Akdeniz", C: "Marmara", D: "Ege" }, dogruCevap: "B" },
    { seviye: 15, kategori: "Coğrafya", soru: "Yedi Göller Milli Parkı hangi ilimizdedir?", secenekler: { A: "Zonguldak", B: "Karabük", C: "Düzce", D: "Bolu" }, dogruCevap: "D" },
    { seviye: 16, kategori: "Coğrafya", soru: "Türkiye'nin en batı ucu olan Avlaka Burnu hangi adadadır?", secenekler: { A: "Gökçeada", B: "Kefken", C: "Cunda", D: "Bozcaada" }, dogruCevap: "A" },
    { seviye: 17, kategori: "Coğrafya", soru: "Mavi Tünel Projesi hangi ovamızın sulanması için yapılmıştır?", secenekler: { A: "Gediz Ovası", B: "Konya Ovası", C: "Harran Ovası", D: "Iğdır Ovası" }, dogruCevap: "B" },
    { seviye: 18, kategori: "Coğrafya", soru: "Türkiye'de kış ılıklığının en belirgin olduğu bölge hangisidir?", secenekler: { A: "Ege", B: "Güneydoğu Anadolu", C: "Akdeniz", D: "Marmara" }, dogruCevap: "C" },
    { seviye: 19, kategori: "Coğrafya", soru: "Tortum Şelalesi hangi ilimizdedir?", secenekler: { A: "Trabzon", B: "Artvin", C: "Rize", D: "Erzurum" }, dogruCevap: "D" },
    { seviye: 20, kategori: "Coğrafya", soru: "Türkiye'nin 'Sakin Şehir' (Cittaslow) ünvanlı ilk ilçesi hangisidir?", secenekler: { A: "Seferihisar", B: "Halfeti", C: "Taraklı", D: "Akyaka" }, dogruCevap: "A" },
    { seviye: 21, kategori: "Coğrafya", soru: "Ihlara Vadisi hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Nevşehir", B: "Niğde", C: "Kayseri", D: "Aksaray" }, dogruCevap: "D" },
    { seviye: 22, kategori: "Coğrafya", soru: "Türkiye'nin en güneyindeki il hangisidir?", secenekler: { A: "Mersin", B: "Hatay", C: "Muğla", D: "Antalya" }, dogruCevap: "B" },
    { seviye: 23, kategori: "Coğrafya", soru: "İzmir'de bulunan meşhur kuş cennetinin adı nedir?", secenekler: { A: "Birecik", B: "Çamaltı", C: "Sultan Sazlığı", D: "Gala" }, dogruCevap: "B" },
    { seviye: 24, kategori: "Coğrafya", soru: "Sakarya Nehri hangi denize dökülür?", secenekler: { A: "Marmara", B: "Karadeniz", C: "Ege", D: "Akdeniz" }, dogruCevap: "B" },
    { seviye: 25, kategori: "Coğrafya", soru: "Erciyes Dağı hangi ilimizdedir?", secenekler: { A: "Sivas", B: "Aksaray", C: "Konya", D: "Kayseri" }, dogruCevap: "D" },

    // 26-50: Türkiye Ekonomik Coğrafyası (Tarım, Sanayi, Madenler)
    { seviye: 26, kategori: "Coğrafya", soru: "Dünyada fındık üretiminde 1. sırada olan ülke hangisidir?", secenekler: { A: "Türkiye", B: "İtalya", C: "ABD", D: "Gürcistan" }, dogruCevap: "A" },
    { seviye: 27, kategori: "Coğrafya", soru: "Türkiye'de çay tarımı nerede yoğunlaşmıştır?", secenekler: { A: "Doğu Karadeniz", B: "Ege", C: "Akdeniz", D: "Batı Karadeniz" }, dogruCevap: "A" },
    { seviye: 28, kategori: "Coğrafya", soru: "Türkiye'de petrolün en çok çıkarıldığı il hangisidir?", secenekler: { A: "Diyarbakır", B: "Batman", C: "Siirt", D: "Adıyaman" }, dogruCevap: "B" },
    { seviye: 29, kategori: "Coğrafya", soru: "Zonguldak denilince akla gelen en önemli maden hangisidir?", secenekler: { A: "Bakır", B: "Taş Kömürü", C: "Linyit", D: "Demir" }, dogruCevap: "B" },
    { seviye: 30, kategori: "Coğrafya", soru: "Dünya bor rezervlerinin yaklaşık %70'inden fazlasına sahip ülke?", secenekler: { A: "Çin", B: "Rusya", C: "Türkiye", D: "ABD" }, dogruCevap: "C" },
    { seviye: 31, kategori: "Coğrafya", soru: "Türkiye'de pamuk üretiminde ilk sırada yer alan ilimiz?", secenekler: { A: "Şanlıurfa", B: "Adana", C: "Aydın", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 32, kategori: "Coğrafya", soru: "Kayısı üretimiyle dünya çapında meşhur olan ilimiz?", secenekler: { A: "Elazığ", B: "Erzincan", C: "Iğdır", D: "Malatya" }, dogruCevap: "D" },
    { seviye: 33, kategori: "Coğrafya", soru: "Türkiye'de ipek böcekçiliği ve ipekli dokumada lider şehir?", secenekler: { A: "Bilecik", B: "Diyarbakır", C: "Sakarya", D: "Bursa" }, dogruCevap: "D" },
    { seviye: 34, kategori: "Coğrafya", soru: "Lüle taşı sadece hangi ilimizde çıkarılır?", secenekler: { A: "Eskişehir", B: "Erzurum", C: "Afyon", D: "Kütahya" }, dogruCevap: "A" },
    { seviye: 35, kategori: "Coğrafya", soru: "Oltu taşı hangi ilimizin simgesidir?", secenekler: { A: "Erzincan", B: "Bayburt", C: "Erzurum", D: "Gümüşhane" }, dogruCevap: "C" },
    { seviye: 36, kategori: "Coğrafya", soru: "Türkiye'de jeotermal enerjiden elektrik üretilen ilk yer?", secenekler: { A: "Soma (Manisa)", B: "Yatağan (Muğla)", C: "Germencik (Aydın)", D: "Sarayköy (Denizli)" }, dogruCevap: "D" },
    { seviye: 37, kategori: "Coğrafya", soru: "Hangi ilimiz 'Güller Diyarı' olarak bilinir?", secenekler: { A: "Antalya", B: "Isparta", C: "Afyon", D: "Burdur" }, dogruCevap: "B" },
    { seviye: 38, kategori: "Coğrafya", soru: "Türkiye'nin en büyük demir-çelik fabrikası hangisidir?", secenekler: { A: "Kardemir", B: "Erdemir", C: "İsdemir", D: "Asil Çelik" }, dogruCevap: "B" },
    { seviye: 39, kategori: "Coğrafya", soru: "GAP (Güneydoğu Anadolu Projesi) kapsamındaki en büyük baraj?", secenekler: { A: "Ilısu Barajı", B: "Keban Barajı", C: "Karakaya Barajı", D: "Atatürk Barajı" }, dogruCevap: "D" },
    { seviye: 40, kategori: "Coğrafya", soru: "Türkiye'de muz üretiminin yapıldığı tek bölge hangisidir?", secenekler: { A: "Akdeniz", B: "Marmara", C: "Ege", D: "Güneydoğu Anadolu" }, dogruCevap: "A" },
    { seviye: 41, kategori: "Coğrafya", soru: "Ayçiçeği üretimi en çok hangi bölgemizde yapılır?", secenekler: { A: "Marmara (Trakya)", B: "Karadeniz", C: "İç Anadolu", D: "Ege" }, dogruCevap: "A" },
    { seviye: 42, kategori: "Coğrafya", soru: "Türkiye'de rüzgar enerjisi santrali (RES) ilk kez nerede kuruldu?", secenekler: { A: "İzmir (Alaçatı)", B: "Çanakkale", C: "Balıkesir", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 43, kategori: "Coğrafya", soru: "Turunçgil üretimi için kış ılıklığı şarttır. Hangi ilde bu üretim zordur?", secenekler: { A: "Mersin", B: "Sivas", C: "Adana", D: "Antalya" }, dogruCevap: "B" },
    { seviye: 44, kategori: "Coğrafya", soru: "Türkiye'nin en çok ithal (satın alma) ettiği enerji kaynağı?", secenekler: { A: "Güneş Paneli", B: "Elektrik", C: "Kömür", D: "Petrol ve Doğalgaz" }, dogruCevap: "D" },
    { seviye: 45, kategori: "Coğrafya", soru: "Sığla ağacı dünyada sadece nerede bulunur?", secenekler: { A: "Artvin", B: "Antalya (Kaş)", C: "Rize", D: "Muğla (Köyceğiz)" }, dogruCevap: "D" },
    { seviye: 46, kategori: "Coğrafya", soru: "Türkiye'de en çok mısır üretimi son yıllarda hangi bölgeye kaymıştır?", secenekler: { A: "Güneydoğu Anadolu", B: "Karadeniz", C: "Marmara", D: "Ege" }, dogruCevap: "A" },
    { seviye: 47, kategori: "Coğrafya", soru: "Kümes hayvancılığı neden büyük şehirlerin yakınında gelişmiştir?", secenekler: { A: "İklim uygunluğu", B: "Tüketici nüfus (pazar)", C: "Su kaynakları", D: "Yem fabrikaları" }, dogruCevap: "B" },
    { seviye: 48, kategori: "Coğrafya", soru: "Türkiye'nin en modern ve büyük konteyner limanı hangisidir?", secenekler: { A: "İstanbul Limanı", B: "Trabzon Limanı", C: "İzmir Limanı", D: "Mersin Limanı" }, dogruCevap: "D" },
    { seviye: 49, kategori: "Coğrafya", soru: "Zeytin üretimi en çok hangi bölgede yapılır?", secenekler: { A: "Ege", B: "Güneydoğu Anadolu", C: "Marmara", D: "Akdeniz" }, dogruCevap: "A" },
    { seviye: 50, kategori: "Coğrafya", soru: "Türkiye'nin ilk nükleer güç santrali nerede inşa edilmektedir?", secenekler: { A: "Kırklareli", B: "Mersin (Akkuyu)", C: "Sinop", D: "Adana" }, dogruCevap: "B" },

    // 51-75: Türkiye Beşeri Coğrafya, İller ve Sınırlar
    { seviye: 51, kategori: "Coğrafya", soru: "Türkiye'nin nüfus bakımından en büyük ili hangisidir?", secenekler: { A: "İstanbul", B: "İzmir", C: "Bursa", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 52, kategori: "Coğrafya", soru: "Türkiye'nin en uzun sınır komşusu hangi ülkedir?", secenekler: { A: "Yunanistan", B: "İran", C: "Irak", D: "Suriye" }, dogruCevap: "D" },
    { seviye: 53, kategori: "Coğrafya", soru: "Nahçıvan üzerinden hangi ülke ile sınırımız vardır?", secenekler: { A: "Gürcistan", B: "Ermenistan", C: "İran", D: "Azerbaycan" }, dogruCevap: "D" },
    { seviye: 54, kategori: "Coğrafya", soru: "Türkiye'de nüfus yoğunluğu en az olan ilimiz genellikle hangisidir?", secenekler: { A: "Tunceli", B: "Bayburt", C: "Gümüşhane", D: "Ardahan" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Coğrafya", soru: "Güneydoğu Anadolu'nun en gelişmiş sanayi şehri hangisidir?", secenekler: { A: "Diyarbakır", B: "Mardin", C: "Gaziantep", D: "Şanlıurfa" }, dogruCevap: "C" },
    { seviye: 56, kategori: "Coğrafya", soru: "Türkiye'de doğurganlık oranının en yüksek olduğu bölge hangisidir?", secenekler: { A: "İç Anadolu", B: "Güneydoğu Anadolu", C: "Doğu Anadolu", D: "Karadeniz" }, dogruCevap: "B" },
    { seviye: 57, kategori: "Coğrafya", soru: "Hangi ilimizin adı daha önce 'Maraş' iken değiştirilmiştir?", secenekler: { A: "Kahramanmaraş", B: "Afyonkarahisar", C: "Şanlıurfa", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 58, kategori: "Coğrafya", soru: "Aşağıdakilerden hangisi bir sınır kapımız değildir?", secenekler: { A: "Esenboğa", B: "Kapıkule", C: "Habur", D: "Sarp" }, dogruCevap: "A" },
    { seviye: 59, kategori: "Coğrafya", soru: "Türkiye'nin en kalabalık 3. şehri hangisidir?", secenekler: { A: "İzmir", B: "Adana", C: "Antalya", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 60, kategori: "Coğrafya", soru: "İpek Yolu'nun Anadolu'daki önemli duraklarından biri olan şehir?", secenekler: { A: "Erzurum", B: "Kayseri", C: "Hepsi", D: "Konya" }, dogruCevap: "C" },
    { seviye: 61, kategori: "Coğrafya", soru: "Dünyanın en eski yerleşimlerinden Çatalhöyük hangi ilimizdedir?", secenekler: { A: "Karaman", B: "Konya", C: "Çorum", D: "Aksaray" }, dogruCevap: "B" },
    { seviye: 62, kategori: "Coğrafya", soru: "Türkiye'nin kış turizminde önde gelen 'Palandöken' merkezi nerededir?", secenekler: { A: "Bursa", B: "Kayseri", C: "Bolu", D: "Erzurum" }, dogruCevap: "D" },
    { seviye: 63, kategori: "Coğrafya", soru: "Marmara ve Ege Denizi'ni birbirine bağlayan boğaz?", secenekler: { A: "Cebelitarık Boğazı", B: "Korint Kanalı", C: "İstanbul Boğazı", D: "Çanakkale Boğazı" }, dogruCevap: "D" },
    { seviye: 64, kategori: "Coğrafya", soru: "Türkiye'nin yüzölçümü en büyük ili hangisidir?", secenekler: { A: "Ankara", B: "Sivas", C: "Erzurum", D: "Konya" }, dogruCevap: "D" },
    { seviye: 65, kategori: "Coğrafya", soru: "Fındık ve Çay dışında 'Kivi' üretimiyle de öne çıkan bölgemiz?", secenekler: { A: "Karadeniz", B: "Akdeniz", C: "Ege", D: "Marmara" }, dogruCevap: "A" },
    { seviye: 66, kategori: "Coğrafya", soru: "Karadeniz ve Akdeniz'i birbirine bağlayacak olan tünel projeleri?", secenekler: { A: "Zigana", B: "Ovit", C: "Hepsi", D: "Ecevit" }, dogruCevap: "C" },
    { seviye: 67, kategori: "Coğrafya", soru: "Türkiye'nin tek fiyord tipi kıyısı nerededir?", secenekler: { A: "Sinop (Hamsilos)", B: "İzmir (Foça)", C: "Muğla (Fethiye)", D: "Antalya (Kaş)" }, dogruCevap: "A" },
    { seviye: 68, kategori: "Coğrafya", soru: "Göbeklitepe hangi ilimizde bulunmaktadır?", secenekler: { A: "Gaziantep", B: "Mardin", C: "Adıyaman", D: "Şanlıurfa" }, dogruCevap: "D" },
    { seviye: 69, kategori: "Coğrafya", soru: "Mardin'in mimarisiyle meşhur eski evleri hangi taştan yapılır?", secenekler: { A: "Mermer", B: "Kalker", C: "Sarı Kalker (Mardin Taşı)", D: "Granit" }, dogruCevap: "C" },
    { seviye: 70, kategori: "Coğrafya", soru: "Türkiye'nin pirinç üretim merkezi neresidir?", secenekler: { A: "Kastamonu", B: "Samsun", C: "Edirne (Meriç)", D: "Sinop" }, dogruCevap: "C" },
    { seviye: 71, kategori: "Coğrafya", soru: "Hangi ilimizde 'Kapadokya' benzeri 'Narman Peribacaları' bulunur?", secenekler: { A: "Nevşehir", B: "Van", C: "Erzurum", D: "Manisa" }, dogruCevap: "C" },
    { seviye: 72, kategori: "Coğrafya", soru: "Türkiye'de en çok göç veren bölge hangisidir?", secenekler: { A: "İç Anadolu", B: "Ege", C: "Doğu Anadolu", D: "Karadeniz" }, dogruCevap: "C" },
    { seviye: 73, kategori: "Coğrafya", soru: "Büyükşehir statüsünde olan en son ilimiz hangisidir?", secenekler: { A: "Tekirdağ", B: "Mardin", C: "Muğla", D: "Ordu" }, dogruCevap: "D" },
    { seviye: 74, kategori: "Coğrafya", soru: "Türkiye'nin en doğusu ile en batısı arasındaki zaman farkı?", secenekler: { A: "90 Dakika", B: "60 Dakika", C: "40 Dakika", D: "76 Dakika" }, dogruCevap: "D" },
    { seviye: 75, kategori: "Coğrafya", soru: "Hangi dağımızda buzul (glasiye) oluşumlarına rastlanmaz?", secenekler: { A: "Yıldız Dağları", B: "Cilo", C: "Kaçkar", D: "Ağrı" }, dogruCevap: "A" },

    // 76-100: Dünya Coğrafyası Genel Kültür
    { seviye: 76, kategori: "Coğrafya", soru: "Dünyanın en büyük okyanusu hangisidir?", secenekler: { A: "Kuzey Buz", B: "Atlas", C: "Hint", D: "Pasifik" }, dogruCevap: "D" },
    { seviye: 77, kategori: "Coğrafya", soru: "Dünyanın en yüksek noktası olan Everest hangi sıradağlardadır?", secenekler: { A: "Himalayalar", B: "Kayalık Dağları", C: "Andlar", D: "Alpler" }, dogruCevap: "A" },
    { seviye: 78, kategori: "Coğrafya", soru: "Dünyanın en uzun nehri hangisidir?", secenekler: { A: "Mississipi", B: "Amazon", C: "Ganj", D: "Nil" }, dogruCevap: "D" },
    { seviye: 79, kategori: "Coğrafya", soru: "Dünyanın en geniş yüzölçümüne sahip ülkesi?", secenekler: { A: "Rusya", B: "Kanada", C: "Çin", D: "ABD" }, dogruCevap: "A" },
    { seviye: 80, kategori: "Coğrafya", soru: "Güney Amerika'nın en büyük ülkesi hangisidir?", secenekler: { A: "Şili", B: "Arjantin", C: "Brezilya", D: "Kolombiya" }, dogruCevap: "C" },
    { seviye: 81, kategori: "Coğrafya", soru: "Afrika kıtasının en yüksek dağı hangisidir?", secenekler: { A: "Kongo Dağı", B: "Kenya Dağı", C: "Atlas Dağları", D: "Kilimanjaro" }, dogruCevap: "D" },
    { seviye: 82, kategori: "Coğrafya", soru: "Dünyanın en derin noktası Mariana Çukuru nerededir?", secenekler: { A: "Atlas Okyanusu", B: "Hint Okyanusu", C: "Akdeniz", D: "Pasifik Okyanusu" }, dogruCevap: "D" },
    { seviye: 83, kategori: "Coğrafya", soru: "Hangi ülke 'Yükselen Güneşin Ülkesi' olarak anılır?", secenekler: { A: "Tayland", B: "Çin", C: "Japonya", D: "Güney Kore" }, dogruCevap: "C" },
    { seviye: 84, kategori: "Coğrafya", soru: "Dünyanın en büyük çölü hangisidir?", secenekler: { A: "Sahra Çölü", B: "Kalahari", C: "Gobi Çölü", D: "Atacama" }, dogruCevap: "A" },
    { seviye: 85, kategori: "Coğrafya", soru: "Fransa ve İngiltere'yi deniz altından bağlayan tünel?", secenekler: { A: "Süveyş", B: "Manş Tüneli", C: "Cebelitarık", D: "Bering Tüneli" }, dogruCevap: "B" },
    { seviye: 86, kategori: "Coğrafya", soru: "Hangi kanal Akdeniz ile Kızıldeniz'i birbirine bağlar?", secenekler: { A: "Panama Kanalı", B: "Süveyş Kanalı", C: "Korint Kanalı", D: "Kanal İstanbul" }, dogruCevap: "B" },
    { seviye: 87, kategori: "Coğrafya", soru: "Dünyanın en kalabalık ülkesi (2024 verilerine göre)?", secenekler: { A: "Hindistan", B: "Çin", C: "Endonezya", D: "ABD" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Coğrafya", soru: "Kanguruları ile ünlü olan kıta ülke?", secenekler: { A: "Afrika", B: "Avustralya", C: "Antarktika", D: "Asya" }, dogruCevap: "B" },
    { seviye: 90, kategori: "Coğrafya", soru: "Hangi ülke hem Asya hem Avrupa kıtasında yer alır?", secenekler: { A: "Hindistan", B: "Almanya", C: "Çin", D: "Türkiye ve Rusya" }, dogruCevap: "D" },
    { seviye: 91, kategori: "Coğrafya", soru: "Dünyanın en küçük yüzölçümlü ülkesi?", secenekler: { A: "Monako", B: "Andorra", C: "Vatikan", D: "San Marino" }, dogruCevap: "C" },
    { seviye: 92, kategori: "Coğrafya", soru: "İskandinav ülkeleri hangi kıtadadır?", secenekler: { A: "Afrika", B: "Amerika", C: "Asya", D: "Avrupa" }, dogruCevap: "D" },
    { seviye: 93, kategori: "Coğrafya", soru: "Amazon yağmur ormanları hangi kıtadadır?", secenekler: { A: "Kuzey Amerika", B: "Asya", C: "Afrika", D: "Güney Amerika" }, dogruCevap: "D" },
    { seviye: 94, kategori: "Coğrafya", soru: "İzlanda'da çok sayıda bulunan jeotermal oluşum?", secenekler: { A: "Obruk", B: "Fiyord", C: "Delta", D: "Gayzer" }, dogruCevap: "D" },
    { seviye: 95, kategori: "Coğrafya", soru: "Dünyanın en soğuk kıtası hangisidir?", secenekler: { A: "Avrupa", B: "Asya (Sibirya)", C: "Kuzey Amerika", D: "Antarktika" }, dogruCevap: "D" },
    { seviye: 96, kategori: "Coğrafya", soru: "Dünyanın en büyük tatlı su gölü hangisidir?", secenekler: { A: "Baykal Gölü", B: "Victoria Gölü", C: "Superior Gölü", D: "Hazar Denizi" }, dogruCevap: "C" },
    { seviye: 97, kategori: "Coğrafya", soru: "Hangi ülke topraklarında hiç nehir bulunmaz?", secenekler: { A: "Irak", B: "Libya", C: "Suudi Arabistan", D: "Mısır" }, dogruCevap: "C" },
    { seviye: 98, kategori: "Coğrafya", soru: "Ekvator çizgisinin geçtiği ülkelerden biri?", secenekler: { A: "Ekvador", B: "Arjantin", C: "Meksika", D: "Kanada" }, dogruCevap: "A" },
    { seviye: 99, kategori: "Coğrafya", soru: "Ganj Nehri hangi ülke için kutsal sayılır?", secenekler: { A: "Mısır", B: "Pakistan", C: "Hindistan", D: "Çin" }, dogruCevap: "C" },
    { seviye: 100, kategori: "Coğrafya", soru: "Dünya'nın kendi ekseni etrafında dönme hızı nerede en fazladır?", secenekler: { A: "Ekvator", B: "Yengeç Dönencesi", C: "Oğlak Dönencesi", D: "Kutuplar" }, dogruCevap: "A" }, 
    // 101-151: Dünya Coğrafyası, İklimler, Ülkeler ve Ekstrem Olaylar
    { seviye: 101, kategori: "Coğrafya", soru: "Dünyanın en derin noktası olan Mariana Çukuru hangi okyanustadır?", secenekler: { A: "Atlas Okyanusu", B: "Arktik Okyanusu", C: "Hint Okyanusu", D: "Büyük Okyanus (Pasifik)" }, dogruCevap: "D" },
    { seviye: 102, kategori: "Coğrafya", soru: "Yüzölçümü bakımından dünyanın en büyük ülkesi hangisidir?", secenekler: { A: "Kanada", B: "Rusya", C: "Çin", D: "ABD" }, dogruCevap: "B" },
    { seviye: 103, kategori: "Coğrafya", soru: "Yeryüzünde en çok yağış alan yer olarak bilinen Çerapunçi hangi ülkededir?", secenekler: { A: "Hindistan", B: "Endonezya", C: "Kongo", D: "Brezilya" }, dogruCevap: "A" },
    { seviye: 104, kategori: "Coğrafya", soru: "Dünyanın en uzun sıradağı hangisidir?", secenekler: { A: "Himalayalar", B: "Kayalık Dağları", C: "Alpler", D: "And Dağları" }, dogruCevap: "D" },
    { seviye: 105, kategori: "Coğrafya", soru: "İskandinav ülkelerinde buzulların aşındırmasıyla oluşan derin vadilere ne ad verilir?", secenekler: { A: "Kanyon", B: "Fiyort", C: "Obruk", D: "Delta" }, dogruCevap: "B" },
    { seviye: 106, kategori: "Coğrafya", soru: "Yüzölçümü en küçük olan kıta hangisidir?", secenekler: { A: "Antarktika", B: "Okyanusya (Avustralya)", C: "Güney Amerika", D: "Avrupa" }, dogruCevap: "B" },
    { seviye: 107, kategori: "Coğrafya", soru: "Dünyanın en büyük sıcak çölü hangisidir?", secenekler: { A: "Kalahari Çölü", B: "Gobi Çölü", C: "Sahra Çölü", D: "Atacama Çölü" }, dogruCevap: "C" },
    { seviye: 108, kategori: "Coğrafya", soru: "Süveyş Kanalı hangi iki denizi birbirine bağlar?", secenekler: { A: "Akdeniz - Kızıldeniz", B: "Hazar Denizi - Karadeniz", C: "Akdeniz - Karadeniz", D: "Umman Denizi - Kızıldeniz" }, dogruCevap: "A" },
    { seviye: 109, kategori: "Coğrafya", soru: "Dünyanın en yüksek şelalesi olan Angel Şelalesi hangi ülkededir?", secenekler: { A: "ABD", B: "Brezilya", C: "Venezuela", D: "Zambiya" }, dogruCevap: "C" },
    { seviye: 110, kategori: "Coğrafya", soru: "Dünyanın kendi ekseni etrafındaki dönüş hızı (çizgisel hız) nerede en fazladır?", secenekler: { A: "Ekvator", B: "Güney Kutbu", C: "Kuzey Kutbu", D: "Yengeç Dönencesi" }, dogruCevap: "A" },
    { seviye: 111, kategori: "Coğrafya", soru: "Haritalarda yükseltiyi göstermek için kullanılan, aynı yükseltiye sahip noktaları birleştiren eğrilere ne denir?", secenekler: { A: "İzobat", B: "İzoterm", C: "İzohips", D: "İzobar" }, dogruCevap: "C" },
    { seviye: 112, kategori: "Coğrafya", soru: "Atmosferin en alt ve hava olaylarının yaşandığı katmanı hangisidir?", secenekler: { A: "Termosfer", B: "Stratosfer", C: "Mezosfer", D: "Troposfer" }, dogruCevap: "D" },
    { seviye: 113, kategori: "Coğrafya", soru: "Akdeniz ikliminin karakteristik bitki örtüsü hangisidir?", secenekler: { A: "Bozkır", B: "Tundra", C: "Savann", D: "Maki" }, dogruCevap: "D" },
    { seviye: 114, kategori: "Coğrafya", soru: "Depremin büyüklüğünü ölçmek için kullanılan ölçeğin adı nedir?", secenekler: { A: "Richter", B: "Anemometre", C: "Barometre", D: "Fahrenheit" }, dogruCevap: "A" },
    { seviye: 115, kategori: "Coğrafya", soru: "Sıcaklık ve nemin yıl boyunca yüksek olduğu, her mevsimin yağışlı geçtiği iklim?", secenekler: { A: "Savan İklimi", B: "Muson İklimi", C: "Ekvatoral İklim", D: "Çöl İklimi" }, dogruCevap: "C" },
    { seviye: 116, kategori: "Coğrafya", soru: "Hangi ülke 'Yükselen Güneşin Ülkesi' olarak bilinir?", secenekler: { A: "Çin", B: "Tayland", C: "Japonya", D: "Güney Kore" }, dogruCevap: "C" },
    { seviye: 117, kategori: "Coğrafya", soru: "Dünyanın en yoğun nüfuslu kıtası hangisidir?", secenekler: { A: "Kuzey Amerika", B: "Asya", C: "Afrika", D: "Avrupa" }, dogruCevap: "B" },
    { seviye: 118, kategori: "Coğrafya", soru: "Bering Boğazı hangi iki kıtayı birbirine en çok yaklaştırır?", secenekler: { A: "Asya - Kuzey Amerika", B: "Afrika - Avrupa", C: "Asya - Avrupa", D: "Güney Amerika - Antarktika" }, dogruCevap: "A" },
    { seviye: 119, kategori: "Coğrafya", soru: "Yeryüzündeki tatlı su rezervlerinin en büyük kısmı nerede bulunur?", secenekler: { A: "Göller", B: "Yeraltı suları", C: "Nehirler", D: "Buzullar" }, dogruCevap: "D" },
    { seviye: 120, kategori: "Coğrafya", soru: "Arap Yarımadası ile Afrika arasında yer alan deniz hangisidir?", secenekler: { A: "Kızıldeniz", B: "Aden Körfezi", C: "Basra Körfezi", D: "Umman Denizi" }, dogruCevap: "A" },
    { seviye: 121, kategori: "Coğrafya", soru: "Dünya üzerindeki bir noktanın Ekvator'a olan uzaklığının açı cinsinden değerine ne denir?", secenekler: { A: "Enlem", B: "Yerel Saat", C: "Boylam", D: "Yörünge" }, dogruCevap: "A" },
    { seviye: 122, kategori: "Coğrafya", soru: "Hangi okyanusun kıyısı 'Pasifik Ateş Çemberi' olarak adlandırılan yoğun volkanik bölgedir?", secenekler: { A: "Büyük Okyanus", B: "Atlas Okyanusu", C: "Güney Okyanusu", D: "Hint Okyanusu" }, dogruCevap: "A" },
    { seviye: 123, kategori: "Coğrafya", soru: "İsviçre, Avusturya ve Fransa boyunca uzanan Avrupa'nın en büyük sıradağ sistemi?", secenekler: { A: "Pireneler", B: "Ural Dağları", C: "Alpler", D: "Karpatlar" }, dogruCevap: "C" },
    { seviye: 124, kategori: "Coğrafya", soru: "Dünyanın en kalabalık Müslüman nüfusuna sahip ülkesi hangisidir?", secenekler: { A: "Endonezya", B: "Pakistan", C: "Suudi Arabistan", D: "Mısır" }, dogruCevap: "A" },
    { seviye: 125, kategori: "Coğrafya", soru: "Amazon Nehri hangi okyanusa dökülür?", secenekler: { A: "Arktik Okyanusu", B: "Hint Okyanusu", C: "Pasifik Okyanusu", D: "Atlas Okyanusu (Atlantik)" }, dogruCevap: "D" },
    { seviye: 126, kategori: "Coğrafya", soru: "Kuzey ve Güney yarım küreleri birbirinden ayıran hayali çizgiye ne denir?", secenekler: { A: "Oğlak Dönencesi", B: "Kutup Dairesi", C: "Ekvator", D: "Başlangıç Meridyeni" }, dogruCevap: "C" },
    { seviye: 127, kategori: "Coğrafya", soru: "Atlas Okyanusu ile Büyük Okyanus'u birbirine bağlayan yapay kanal hangisidir?", secenekler: { A: "Kiel Kanalı", B: "Korint Kanalı", C: "Panama Kanalı", D: "Süveyş Kanalı" }, dogruCevap: "C" },
    { seviye: 128, kategori: "Coğrafya", soru: "Avrupa ve Afrika kıtalarını birbirine en çok yaklaştıran boğaz hangisidir?", secenekler: { A: "Hürmüz Boğazı", B: "Malakka Boğazı", C: "Cebelitarık Boğazı", D: "Babülmendep Boğazı" }, dogruCevap: "C" },
    { seviye: 129, kategori: "Coğrafya", soru: "Dünyanın en tuzlu denizi hangisidir?", secenekler: { A: "Manş Denizi", B: "Umman Denizi", C: "Akdeniz", D: "Kızıldeniz" }, dogruCevap: "D" },
    { seviye: 130, kategori: "Coğrafya", soru: "Güneydoğu Asya'da yaz aylarında bol yağış getiren rüzgarlara ne denir?", secenekler: { A: "Alizeler", B: "Batı Rüzgarları", C: "Muson Rüzgarları", D: "Fön Rüzgarları" }, dogruCevap: "C" },
    { seviye: 131, kategori: "Coğrafya", soru: "Dünyanın en büyük adası hangisidir?", secenekler: { A: "Borneo", B: "Madagaskar", C: "Grönland", D: "Yeni Gine" }, dogruCevap: "C" },
    { seviye: 132, kategori: "Coğrafya", soru: "Nüfus sayımını ve nüfusun özelliklerini inceleyen bilim dalı hangisidir?", secenekler: { A: "Kartografya", B: "Demografi", C: "Litoloji", D: "Jeoloji" }, dogruCevap: "B" },
    { seviye: 133, kategori: "Coğrafya", soru: "Avrupa'nın en uzun nehri hangisidir?", secenekler: { A: "Volga", B: "Ren", C: "Tuna", D: "Elbe" }, dogruCevap: "A" },
    { seviye: 134, kategori: "Coğrafya", soru: "Magmanın yeryüzüne çıktığı noktada oluşturduğu çukurluğa ne ad verilir?", secenekler: { A: "Krater", B: "Polye", C: "Lapyalar", D: "Mağara" }, dogruCevap: "A" },
    { seviye: 135, kategori: "Coğrafya", soru: "Kireç taşlarının (kalker) su ile erimesi sonucu oluşan yer şekillerine ne denir?", secenekler: { A: "Buzul", B: "Karstik", C: "Volkanik", D: "Rüzgar aşınımı" }, dogruCevap: "B" },
    { seviye: 136, kategori: "Coğrafya", soru: "Avustralya kıtasının en tanınmış yerli halkına ne ad verilir?", secenekler: { A: "Aborjin", B: "İnka", C: "Maori", D: "Aztek" }, dogruCevap: "A" },
    { seviye: 137, kategori: "Coğrafya", soru: "Hangi ülke toprakları üzerinde en çok zaman dilimi (saat farkı) barındırır?", secenekler: { A: "Rusya", B: "Çin", C: "ABD", D: "Fransa (deniz aşırı toprakları dahil)" }, dogruCevap: "D" },
    { seviye: 138, kategori: "Coğrafya", soru: "Kalıcı kar sınırının en yüksek olduğu bölge neresidir?", secenekler: { A: "Dönenceler", B: "Kutuplar", C: "Ekvator", D: "Orta Kuşak" }, dogruCevap: "C" },
    { seviye: 139, kategori: "Coğrafya", soru: "Kuzey ışıkları olarak da bilinen doğa olayının bilimsel adı nedir?", secenekler: { A: "Aurora Borealis", B: "Sirocco", C: "Hortum", D: "Tsunami" }, dogruCevap: "A" },
    { seviye: 140, kategori: "Coğrafya", soru: "Hangi kıtada aktif volkan bulunmaz?", secenekler: { A: "Avrupa", B: "Antarktika", C: "Avustralya", D: "Afrika" }, dogruCevap: "C" },
    { seviye: 141, kategori: "Coğrafya", soru: "Gel-git (med-cezir) olayının temel sebebi hangisidir?", secenekler: { A: "Rüzgarlar", B: "Okyanus akıntıları", C: "Dünyanın iç ısısı", D: "Ay'ın çekim gücü" }, dogruCevap: "D" },
    { seviye: 142, kategori: "Coğrafya", soru: "Yeryüzünde sıcaklık değerleri en düşük olan yerleşim birimleri hangi ülkededir?", secenekler: { A: "İzlanda", B: "Kanada", C: "Rusya", D: "Norveç" }, dogruCevap: "C" },
    { seviye: 143, kategori: "Coğrafya", soru: "Asya ile Avrupa'yı birbirinden ayıran doğal sınır kabul edilen dağlar?", secenekler: { A: "Ural Dağları", B: "Kafkas Dağları", C: "Himalayalar", D: "Toroslar" }, dogruCevap: "A" },
    { seviye: 144, kategori: "Coğrafya", soru: "Dünyanın en büyük mercan resifi sistemi hangi ülkenin kıyısındadır?", secenekler: { A: "Endonezya", B: "Avustralya", C: "Maldivler", D: "Meksika" }, dogruCevap: "B" },
    { seviye: 145, kategori: "Coğrafya", soru: "Deniz seviyesindeki atmosfer basıncı ortalama kaç milibardır?", secenekler: { A: "1013", B: "980", C: "1000", D: "1025" }, dogruCevap: "A" },
    { seviye: 146, kategori: "Coğrafya", soru: "Peri bacalarının oluşumunda iç kuvvetlerden hangisi etkilidir?", secenekler: { A: "Orojenez", B: "Epirojenez", C: "Volkanizma", D: "Deprem" }, dogruCevap: "C" },
    { seviye: 147, kategori: "Coğrafya", soru: "Dünyanın en küçük bağımsız devleti hangisidir?", secenekler: { A: "San Marino", B: "Vatikan", C: "Monako", D: "Liechtenstein" }, dogruCevap: "B" },
    { seviye: 148, kategori: "Coğrafya", soru: "Hangi rüzgar türü estiği yamaçta sıcaklığı artırarak kar erimelerine neden olur?", secenekler: { A: "Poyraz", B: "Meltem", C: "Fön", D: "Mistral" }, dogruCevap: "C" },
    { seviye: 149, kategori: "Coğrafya", soru: "Nil Nehri hangi denize dökülür?", secenekler: { A: "Kızıldeniz", B: "Hint Okyanusu", C: "Akdeniz", D: "Basra Körfezi" }, dogruCevap: "C" },
    { seviye: 150, kategori: "Coğrafya", soru: "Atmosferdeki ozon tabakasının temel görevi nedir?", secenekler: { A: "Sıcaklığı iletmek", B: "Zararlı güneş ışınlarını tutmak", C: "Oksijen üretmek", D: "Yağışı başlatmak" }, dogruCevap: "B" },
    { seviye: 151, kategori: "Coğrafya", soru: "Güney Yarım Küre'de en uzun gündüzün yaşandığı tarih hangisidir?", secenekler: { A: "21 Mart", B: "21 Haziran", C: "23 Eylül", D: "21 Aralık" }, dogruCevap: "D" },
    // 152-200: Türkiye Fiziki ve Beşeri Coğrafya Detayları
    { seviye: 152, kategori: "Coğrafya", soru: "Türkiye'nin en büyük kapalı havzası hangisidir?", secenekler: { A: "Konya Havzası", B: "Van Gölü Havzası", C: "Akarçay Havzası", D: "Tuz Gölü Havzası" }, dogruCevap: "D" },
    { seviye: 153, kategori: "Coğrafya", soru: "Kaçkar Dağları hangi sıradağlar içerisinde yer alır?", secenekler: { A: "Aydın Dağları", B: "Toroslar", C: "Canik Dağları", D: "Doğu Karadeniz Dağları" }, dogruCevap: "D" },
    { seviye: 154, kategori: "Coğrafya", soru: "Türkiye'nin en doğusundaki sınır kapısı hangisidir?", secenekler: { A: "Esendere", B: "Sarp", C: "Gürbulak", D: "Dilucu" }, dogruCevap: "D" },
    { seviye: 155, kategori: "Coğrafya", soru: "Manavgat Şelalesi hangi ilimizdedir?", secenekler: { A: "Antalya", B: "Burdur", C: "Mersin", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 156, kategori: "Coğrafya", soru: "Türkiye'de rüzgar aşınım şekillerine en çok hangi bölgede rastlanır?", secenekler: { A: "İç Anadolu", B: "Karadeniz", C: "Ege", D: "Marmara" }, dogruCevap: "A" },
    { seviye: 157, kategori: "Coğrafya", soru: "Büyük Menderes ve Küçük Menderes nehirlerinin oluşturduğu kıyı tipi?", secenekler: { A: "Ria", B: "Ege Tipi (Enine)", C: "Dalmaçya", D: "Limanlı" }, dogruCevap: "B" },
    { seviye: 158, kategori: "Coğrafya", soru: "Türkiye'nin tek aktif volkanik arazisi olmayan ancak en genç volkanik alanı?", secenekler: { A: "Tendürek", B: "Kula Tepeleri", C: "Nemrut", D: "Erciyes" }, dogruCevap: "B" },
    { seviye: 159, kategori: "Coğrafya", soru: "Aşağıdakilerden hangisi bir tektonik göldür?", secenekler: { A: "Sapanca Gölü", B: "Sera Gölü", C: "Mebre Gölü", D: "Çıldır Gölü" }, dogruCevap: "A" },
    { seviye: 160, kategori: "Coğrafya", soru: "Kızılırmak nehrinin Karadeniz'e döküldüğü yerde oluşan delta?", secenekler: { A: "Silifke", B: "Meriç", C: "Bafra", D: "Çarşamba" }, dogruCevap: "C" },
    { seviye: 161, kategori: "Coğrafya", soru: "Türkiye'de taş kömürü ile çalışan ilk termik santral hangisidir?", secenekler: { A: "Yatağan", B: "Soma", C: "Hamitabat", D: "Çatalağzı" }, dogruCevap: "D" },
    { seviye: 162, kategori: "Coğrafya", soru: "Gökçeada ve Bozcaada hangi ilimize bağlıdır?", secenekler: { A: "Edirne", B: "Çanakkale", C: "İzmir", D: "Balıkesir" }, dogruCevap: "B" },
    { seviye: 163, kategori: "Coğrafya", soru: "Erzurum-Kars platosunda en yaygın toprak tipi hangisidir?", secenekler: { A: "Laterit", B: "Terra Rossa", C: "Çernezyom", D: "Podzol" }, dogruCevap: "C" },
    { seviye: 164, kategori: "Coğrafya", soru: "Türkiye'nin en uzun tüneli olan Ovit Dağı Tüneli hangi illeri bağlar?", secenekler: { A: "Bolu - Düzce", B: "Trabzon - Gümüşhane", C: "Artvin - Ardahan", D: "Rize - Erzurum" }, dogruCevap: "D" },
    { seviye: 165, kategori: "Coğrafya", soru: "İğneada Longoz Ormanları hangi ilimizdedir?", secenekler: { A: "Kırklareli", B: "İstanbul", C: "Tekirdağ", D: "Kocaeli" }, dogruCevap: "A" },
    { seviye: 166, kategori: "Coğrafya", soru: "Hangi maden Türkiye'nin ihracatında önemli bir paya sahiptir?", secenekler: { A: "Mermer", B: "Petrol", C: "Platin", D: "Doğalgaz" }, dogruCevap: "A" },
    { seviye: 167, kategori: "Coğrafya", soru: "Sultan Sazlığı Kuş Cenneti hangi ilimizdedir?", secenekler: { A: "Aksaray", B: "Konya", C: "Kayseri", D: "Kırşehir" }, dogruCevap: "C" },
    { seviye: 168, kategori: "Coğrafya", soru: "Türkiye'de demiryolu bağlantısı olmayan liman şehri?", secenekler: { A: "Samsun", B: "Trabzon", C: "Zonguldak", D: "İskenderun" }, dogruCevap: "B" },
    { seviye: 169, kategori: "Coğrafya", soru: "Akdeniz'de yer alan ve 'Güller Gölü' olarak da bilinen göl?", secenekler: { A: "Beyşehir", B: "Burdur", C: "Salda", D: "Eğirdir" }, dogruCevap: "D" },
    { seviye: 170, kategori: "Coğrafya", soru: "Türkiye'nin ilk kağıt fabrikası (SEKA) nerede kurulmuştur?", secenekler: { A: "Muğla", B: "İzmit", C: "Zonguldak", D: "Giresun" }, dogruCevap: "B" },
    { seviye: 171, kategori: "Coğrafya", soru: "Ankara'nın simgesi olan ve tiftiği ile meşhur hayvan?", secenekler: { A: "Ankara Kedisi", B: "Van Kedisi", C: "Ankara Keçisi", D: "Ankara Tavşanı" }, dogruCevap: "C" },
    { seviye: 172, kategori: "Coğrafya", soru: "Fırat ve Dicle nehirleri birleşerek hangi adı alır?", secenekler: { A: "Şattülarap", B: "Kızıldeniz", C: "Mezopotamya", D: "Aras" }, dogruCevap: "A" },
    { seviye: 173, kategori: "Coğrafya", soru: "Türkiye'nin Maldivler'i olarak bilinen göl?", secenekler: { A: "Bafa Gölü", B: "Van Gölü", C: "Salda Gölü", D: "Meke Gölü" }, dogruCevap: "C" },
    { seviye: 174, kategori: "Coğrafya", soru: "Türkiye'de güneş enerjisinden faydalanma potansiyeli en düşük bölge?", secenekler: { A: "Güneydoğu Anadolu", B: "İç Anadolu", C: "Akdeniz", D: "Karadeniz" }, dogruCevap: "D" },
    { seviye: 175, kategori: "Coğrafya", soru: "Kop Geçidi hangi iki il arasındadır?", secenekler: { A: "Antalya - Isparta", B: "Trabzon - Gümüşhane", C: "Erzurum - Bayburt", D: "Adana - Niğde" }, dogruCevap: "C" },
    { seviye: 176, kategori: "Coğrafya", soru: "Antalya kıyılarında görülen, adalarla kaplı kıyı tipi?", secenekler: { A: "Fiyort", B: "Boyuna", C: "Ria", D: "Dalmaçya" }, dogruCevap: "D" },
    { seviye: 177, kategori: "Coğrafya", soru: "Türkiye'nin en büyük yer altı barajı nerede yapılmıştır?", secenekler: { A: "İstanbul (Şile)", B: "Konya (Kulu)", C: "Ankara (Kalecik)", D: "İzmir (Çeşme)" }, dogruCevap: "A" },
    { seviye: 178, kategori: "Coğrafya", soru: "Tuz Gölü'nden sonra Türkiye'nin tuz ihtiyacını karşılayan deniz kaynağı?", secenekler: { A: "Çamaltı Tuzlası", B: "Fethiye Tuzlası", C: "Ayvalık Tuzlası", D: "Mersin Tuzlası" }, dogruCevap: "A" },
    { seviye: 179, kategori: "Coğrafya", soru: "Hangi ilimizde doğalgaz çıkarma işlemi yapılmaktadır?", secenekler: { A: "Mardin", B: "Kırklareli (Hamitabat)", C: "Batman", D: "Zonguldak" }, dogruCevap: "B" },
    { seviye: 180, kategori: "Coğrafya", soru: "Türkiye'nin kenevir üretim merkezi haline gelen ilimiz?", secenekler: { A: "Rize", B: "Kastamonu", C: "Samsun", D: "Amasya" }, dogruCevap: "C" },
    { seviye: 181, kategori: "Coğrafya", soru: "Zeytin ağacının yetişme sınırı hangi iklimin sınırını belirler?", secenekler: { A: "Step İklimi", B: "Karadeniz İklimi", C: "Sert Karasal", D: "Akdeniz İklimi" }, dogruCevap: "D" },
    { seviye: 182, kategori: "Coğrafya", soru: "Söke, Aydın ve Torbalı ovaları hangi akarsuyun havzasındadır?", secenekler: { A: "Bakırçay", B: "Büyük Menderes", C: "Sakarya", D: "Gediz" }, dogruCevap: "B" },
    { seviye: 183, kategori: "Coğrafya", soru: "Türkiye'nin en büyük şeker fabrikası nerededir?", secenekler: { A: "Uşak", B: "Afyon", C: "Erzurum", D: "Konya" }, dogruCevap: "D" },
    { seviye: 184, kategori: "Coğrafya", soru: "Bakır madeni denilince akla gelen 'Küre' yatakları hangi ildedir?", secenekler: { A: "Artvin", B: "Rize", C: "Elazığ", D: "Kastamonu" }, dogruCevap: "D" },
    { seviye: 185, kategori: "Coğrafya", soru: "Boksit (Alüminyum) madeninin çıkarıldığı 'Seydişehir' hangi ile bağlıdır?", secenekler: { A: "Konya", B: "Muğla", C: "Antalya", D: "Isparta" }, dogruCevap: "A" },
    { seviye: 186, kategori: "Coğrafya", soru: "Anzer Balı ile ünlü olan yayla hangi ilimizdedir?", secenekler: { A: "Rize", B: "Giresun", C: "Trabzon", D: "Artvin" }, dogruCevap: "A" },
    { seviye: 187, kategori: "Coğrafya", soru: "Dünyanın en büyük 'Mermer Antik Kenti' olan Aphrodisias hangi ildedir?", secenekler: { A: "Muğla", B: "İzmir", C: "Denizli", D: "Aydın" }, dogruCevap: "D" },
    { seviye: 188, kategori: "Coğrafya", soru: "Türkiye'de fındık üretiminde Ordu'dan sonra ikinci gelen il?", secenekler: { A: "Sakarya", B: "Trabzon", C: "Giresun", D: "Samsun" }, dogruCevap: "C" },
    { seviye: 189, kategori: "Coğrafya", soru: "Yat turizminin en çok geliştiği 'Mavi Yolculuk' rotası hangi bölgedir?", secenekler: { A: "Güney Ege - Batı Akdeniz", B: "Doğu Karadeniz", C: "Güney Marmara", D: "Çukurova" }, dogruCevap: "A" },
    { seviye: 190, kategori: "Coğrafya", soru: "İskenderun'da demir-çelik sanayisinin kurulma sebebi nedir?", secenekler: { A: "Ulaşım (Liman)", B: "Hammadde", C: "İş gücü", D: "Enerji kaynağı" }, dogruCevap: "A" },
    { seviye: 191, kategori: "Coğrafya", soru: "Türkiye'de büyükbaş hayvancılığın (mera) en yoğun olduğu yer?", secenekler: { A: "Erzurum-Kars Bölümü", B: "Ege", C: "İç Anadolu", D: "Marmara" }, dogruCevap: "A" },
    { seviye: 192, kategori: "Coğrafya", soru: "GAP kapsamında sulamaya açılan ilk büyük ova?", secenekler: { A: "Harran Ovası", B: "Ceylanpınar Ovası", C: "Birecik Ovası", D: "Suruç Ovası" }, dogruCevap: "A" },
    { seviye: 193, kategori: "Coğrafya", soru: "Bitlis'te bulunan ve dünyanın ikinci büyük krater gölü olan yer?", secenekler: { A: "Nemrut Krater Gölü", B: "Gölcük", C: "Acıgöl", D: "Meke" }, dogruCevap: "A" },
    { seviye: 194, kategori: "Coğrafya", soru: "Türkiye'nin en büyük milli parkı hangisidir?", secenekler: { A: "Ağrı Dağı Milli Parkı", B: "Küre Dağları", C: "Beyşehir Gölü", D: "Munzur Vadisi" }, dogruCevap: "A" },
    { seviye: 195, kategori: "Coğrafya", soru: "Ülkemizde yerel saati en ileri olan ilimiz hangisidir?", secenekler: { A: "Hakkari", B: "Van", C: "Iğdır", D: "Artvin" }, dogruCevap: "C" },
    { seviye: 196, kategori: "Coğrafya", soru: "Türkiye'de kıyı uzunluğu en fazla olan bölgemiz?", secenekler: { A: "Akdeniz", B: "Marmara", C: "Karadeniz", D: "Ege" }, dogruCevap: "D" },
    { seviye: 197, kategori: "Coğrafya", soru: "İstanbul ve Çanakkale boğazları hangi jeolojik zamanda oluşmuştur?", secenekler: { A: "3. Zaman", B: "2. Zaman", C: "1. Zaman", D: "4. Zaman (Kuvaterner)" }, dogruCevap: "D" },
    { seviye: 198, kategori: "Coğrafya", soru: "Türkiye'de kışın en soğuk il genellikle hangisidir?", secenekler: { A: "Ağrı", B: "Kars", C: "Ardahan", D: "Erzurum" }, dogruCevap: "C" },
    { seviye: 199, kategori: "Coğrafya", soru: "Yaz turizmi sezonunun en erken açıldığı ilimiz?", secenekler: { A: "Mersin", B: "Antalya", C: "İzmir", D: "Muğla" }, dogruCevap: "B" },
    { seviye: 200, kategori: "Coğrafya", soru: "Porsuk Çayı hangi ilimizin içinden geçer?", secenekler: { A: "Eskişehir", B: "Afyon", C: "Bilecik", D: "Kütahya" }, dogruCevap: "A" },

    // 201-250: Dünya Ülkeleri, Başkentler ve Önemli Yerler
    { seviye: 201, kategori: "Coğrafya", soru: "Almanya'nın başkenti neresidir?", secenekler: { A: "Hamburg", B: "Münih", C: "Frankfurt", D: "Berlin" }, dogruCevap: "D" },
    { seviye: 202, kategori: "Coğrafya", soru: "Fransa'nın simgesi olan Eyfel Kulesi hangi şehirdedir?", secenekler: { A: "Paris", B: "Nice", C: "Marsilya", D: "Lyon" }, dogruCevap: "A" },
    { seviye: 203, kategori: "Coğrafya", soru: "İtalya'nın başkenti neresidir?", secenekler: { A: "Milano", B: "Roma", C: "Venedik", D: "Floransa" }, dogruCevap: "B" },
    { seviye: 204, kategori: "Coğrafya", soru: "İspanya'nın başkenti neresidir?", secenekler: { A: "Sevilla", B: "Madrid", C: "Valencia", D: "Barselona" }, dogruCevap: "B" },
    { seviye: 205, kategori: "Coğrafya", soru: "Rusya'nın başkenti neresidir?", secenekler: { A: "Sibirya", B: "Moskova", C: "St. Petersburg", D: "Kazan" }, dogruCevap: "B" },
    { seviye: 206, kategori: "Coğrafya", soru: "Mısır'daki ünlü piramitler hangi şehirdedir?", secenekler: { A: "Asvan", B: "İskenderiye", C: "Luksor", D: "Kahire (Gize)" }, dogruCevap: "D" },
    { seviye: 207, kategori: "Coğrafya", soru: "Amerika Birleşik Devletleri'nin (ABD) başkenti neresidir?", secenekler: { A: "Washington D.C.", B: "New York", C: "Chicago", D: "Los Angeles" }, dogruCevap: "A" },
    { seviye: 208, kategori: "Coğrafya", soru: "Kanada'nın başkenti neresidir?", secenekler: { A: "Ottawa", B: "Vancouver", C: "Montreal", D: "Toronto" }, dogruCevap: "A" },
    { seviye: 209, kategori: "Coğrafya", soru: "Çin'in başkenti neresidir?", secenekler: { A: "Hong Kong", B: "Pekin", C: "Şanghay", D: "Guangzhou" }, dogruCevap: "B" },
    { seviye: 210, kategori: "Coğrafya", soru: "Japonya'nın başkenti neresidir?", secenekler: { A: "Tokyo", B: "Kyoto", C: "Hiroşima", D: "Osaka" }, dogruCevap: "A" },
    { seviye: 211, kategori: "Coğrafya", soru: "Hindistan'ın başkenti neresidir?", secenekler: { A: "Kalküta", B: "Bangalore", C: "Yeni Delhi", D: "Mumbai" }, dogruCevap: "C" },
    { seviye: 212, kategori: "Coğrafya", soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Busan", B: "Daegu", C: "Seul", D: "Incheon" }, dogruCevap: "C" },
    { seviye: 213, kategori: "Coğrafya", soru: "Avustralya'nın başkenti neresidir?", secenekler: { A: "Sidney", B: "Melbourne", C: "Brisbane", D: "Canberra" }, dogruCevap: "D" },
    { seviye: 214, kategori: "Coğrafya", soru: "Brezilya'nın başkenti neresidir?", secenekler: { A: "Rio de Janeiro", B: "Sao Paulo", C: "Salvador", D: "Brasilia" }, dogruCevap: "D" },
    { seviye: 215, kategori: "Coğrafya", soru: "Arjantin'in başkenti neresidir?", secenekler: { A: "Rosario", B: "Cordoba", C: "Mendoza", D: "Buenos Aires" }, dogruCevap: "D" },
    { seviye: 216, kategori: "Coğrafya", soru: "Güney Afrika Cumhuriyeti'nin üç başkentinden biri hangisidir?", secenekler: { A: "Durban", B: "Soweto", C: "Johannesburg", D: "Cape Town" }, dogruCevap: "D" },
    { seviye: 217, kategori: "Coğrafya", soru: "İngiltere'nin (Birleşik Krallık) başkenti neresidir?", secenekler: { A: "Birmingham", B: "Liverpool", C: "Londra", D: "Manchester" }, dogruCevap: "C" },
    { seviye: 218, kategori: "Coğrafya", soru: "Yunanistan'ın başkenti neresidir?", secenekler: { A: "Patras", B: "Selanik", C: "Atina", D: "Girit" }, dogruCevap: "C" },
    { seviye: 219, kategori: "Coğrafya", soru: "İran'ın başkenti neresidir?", secenekler: { A: "Tebriz", B: "Meşhed", C: "Tahran", D: "İsfahan" }, dogruCevap: "C" },
    { seviye: 220, kategori: "Coğrafya", soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Basra", B: "Erbil", C: "Bağdat", D: "Musul" }, dogruCevap: "C" },
    { seviye: 221, kategori: "Coğrafya", soru: "Suriye'nin başkenti neresidir?", secenekler: { A: "Şam", B: "Lazkiye", C: "Halep", D: "Humus" }, dogruCevap: "A" },
    { seviye: 222, kategori: "Coğrafya", soru: "Azerbaycan'ın başkenti neresidir?", secenekler: { A: "Gence", B: "Nahçıvan", C: "Sumgayıt", D: "Bakü" }, dogruCevap: "D" },
    { seviye: 223, kategori: "Coğrafya", soru: "Hollanda'nın başkenti neresidir?", secenekler: { A: "Rotterdam", B: "Utrecht", C: "Amsterdam", D: "Lahey" }, dogruCevap: "C" },
    { seviye: 224, kategori: "Coğrafya", soru: "Belçika'nın başkenti ve AB merkezi olan şehir?", secenekler: { A: "Brugge", B: "Anvers", C: "Gent", D: "Brüksel" }, dogruCevap: "D" },
    { seviye: 225, kategori: "Coğrafya", soru: "İsviçre'nin başkenti neresidir?", secenekler: { A: "Basel", B: "Zürih", C: "Cenevre", D: "Bern" }, dogruCevap: "D" },
    { seviye: 226, kategori: "Coğrafya", soru: "Avusturya'nın başkenti neresidir?", secenekler: { A: "Viyana", B: "Innsbruck", C: "Salzburg", D: "Graz" }, dogruCevap: "A" },
    { seviye: 227, kategori: "Coğrafya", soru: "Portekiz'in başkenti neresidir?", secenekler: { A: "Coimbra", B: "Porto", C: "Braga", D: "Lizbon" }, dogruCevap: "D" },
    { seviye: 228, kategori: "Coğrafya", soru: "İsveç'in başkenti neresidir?", secenekler: { A: "Göteborg", B: "Uppsala", C: "Malmö", D: "Stokholm" }, dogruCevap: "D" },
    { seviye: 229, kategori: "Coğrafya", soru: "Norveç'in başkenti neresidir?", secenekler: { A: "Trondheim", B: "Oslo", C: "Stavanger", D: "Bergen" }, dogruCevap: "B" },
    { seviye: 230, kategori: "Coğrafya", soru: "Finlandiya'nın başkenti neresidir?", secenekler: { A: "Espoo", B: "Helsinki", C: "Tampere", D: "Turku" }, dogruCevap: "B" },
    { seviye: 231, kategori: "Coğrafya", soru: "Danimarka'nın başkenti neresidir?", secenekler: { A: "Kopenhag", B: "Aalborg", C: "Odense", D: "Aarhus" }, dogruCevap: "A" },
    { seviye: 232, kategori: "Coğrafya", soru: "Macaristan'ın başkenti neresidir?", secenekler: { A: "Debrecen", B: "Miskolc", C: "Szeged", D: "Budapeşte" }, dogruCevap: "D" },
    { seviye: 233, kategori: "Coğrafya", soru: "Polonya'nın başkenti neresidir?", secenekler: { A: "Varşova", B: "Krakow", C: "Wroclaw", D: "Gdansk" }, dogruCevap: "A" },
    { seviye: 234, kategori: "Coğrafya", soru: "Ukrayna'nın başkenti neresidir?", secenekler: { A: "Harkiv", B: "Lviv", C: "Kiev", D: "Odessa" }, dogruCevap: "C" },
    { seviye: 235, kategori: "Coğrafya", soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Guadalajara", B: "Monterrey", C: "Meksiko", D: "Cancun" }, dogruCevap: "C" },
    { seviye: 236, kategori: "Coğrafya", soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Varadero", B: "Havana", C: "Holguin", D: "Santiago" }, dogruCevap: "B" },
    { seviye: 237, kategori: "Coğrafya", soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Pattaya", B: "Phuket", C: "Chiang Mai", D: "Bangkok" }, dogruCevap: "D" },
    { seviye: 238, kategori: "Coğrafya", soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Hanoi", B: "Da Nang", C: "Hue", D: "Ho Chi Minh" }, dogruCevap: "A" },
    { seviye: 239, kategori: "Coğrafya", soru: "Suudi Arabistan'ın başkenti neresidir?", secenekler: { A: "Riyad", B: "Cidde", C: "Medine", D: "Mekke" }, dogruCevap: "A" },
    { seviye: 240, kategori: "Coğrafya", soru: "Birleşik Arap Emirlikleri'nin başkenti neresidir?", secenekler: { A: "Acman", B: "Şarika", C: "Dubai", D: "Abu Dabi" }, dogruCevap: "D" },
    { seviye: 241, kategori: "Coğrafya", soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Al Khor", B: "Doha", C: "Al Wakrah", D: "Lusail" }, dogruCevap: "B" },
    { seviye: 242, kategori: "Coğrafya", soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Fes", B: "Kazablanka", C: "Marakeş", D: "Rabat" }, dogruCevap: "D" },
    { seviye: 243, kategori: "Coğrafya", soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Annaba", B: "Konstantin", C: "Cezayir", D: "Vahran" }, dogruCevap: "C" },
    { seviye: 244, kategori: "Coğrafya", soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Sfaks", B: "Susa", C: "Tunus", D: "Kayrevan" }, dogruCevap: "C" },
    { seviye: 245, kategori: "Coğrafya", soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "Karaçi", B: "İslamabad", C: "Lahor", D: "Peşaver" }, dogruCevap: "B" },
    { seviye: 246, kategori: "Coğrafya", soru: "Kazakistan'ın başkenti (yeni adıyla) neresidir?", secenekler: { A: "Almatı", B: "Çimkent", C: "Astana", D: "Aktau" }, dogruCevap: "C" },
    { seviye: 247, kategori: "Coğrafya", soru: "Özbekistan'ın başkenti neresidir?", secenekler: { A: "Semerkant", B: "Taşkent", C: "Buhara", D: "Hiva" }, dogruCevap: "B" },
    { seviye: 248, kategori: "Coğrafya", soru: "Türkmenistan'ın başkenti neresidir?", secenekler: { A: "Merv", B: "Daşoğuz", C: "Türkmenbaşı", D: "Aşkabat" }, dogruCevap: "D" },
    { seviye: 249, kategori: "Coğrafya", soru: "Kırgızistan'ın başkenti neresidir?", secenekler: { A: "Karakol", B: "Celal-Abad", C: "Bişkek", D: "Oş" }, dogruCevap: "C" },
    { seviye: 250, kategori: "Coğrafya", soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ölgiy", B: "Darhan", C: "Erdenet", D: "Ulan Batur" }, dogruCevap: "D" },

    // 251-301: Dünya Genel Kültür, Coğrafi Terimler ve Ekstrem Bilgiler
    { seviye: 251, kategori: "Coğrafya", soru: "Dünyanın en yüksek debili nehri hangisidir?", secenekler: { A: "Mississippi", B: "Nil", C: "Ganj", D: "Amazon" }, dogruCevap: "D" },
    { seviye: 252, kategori: "Coğrafya", soru: "Dünyanın en büyük gölü (yüzölçümü) hangisidir?", secenekler: { A: "Hazar Denizi", B: "Baykal Gölü", C: "Victoria Gölü", D: "Superior Gölü" }, dogruCevap: "A" },
    { seviye: 253, kategori: "Coğrafya", soru: "Hangi ülke en çok adaya sahiptir (yaklaşık 267.000)?", secenekler: { A: "İsveç", B: "Norveç", C: "Endonezya", D: "Filipinler" }, dogruCevap: "A" },
    { seviye: 254, kategori: "Coğrafya", soru: "Dünyanın en kurak çölü hangisidir?", secenekler: { A: "Gobi", B: "Kalahari", C: "Sahra", D: "Atacama" }, dogruCevap: "D" },
    { seviye: 255, kategori: "Coğrafya", soru: "Panama Kanalı hangi iki kıtayı ayırır?", secenekler: { A: "Afrika - Asya", B: "Avrupa - Afrika", C: "Asya - Avrupa", D: "Kuzey Amerika - Güney Amerika" }, dogruCevap: "D" },
    { seviye: 256, kategori: "Coğrafya", soru: "Dünyanın en geniş boğazı hangisidir?", secenekler: { A: "Drake Boğazı", B: "Malakka", C: "Cebelitarık", D: "Bering Boğazı" }, dogruCevap: "A" },
    { seviye: 257, kategori: "Coğrafya", soru: "Güneşin hiç batmadığı 'Gece Yarısı Güneşi' olayı nerede görülür?", secenekler: { A: "Kutup Daireleri", B: "Ekvator", C: "Orta Kuşak", D: "Dönenceler" }, dogruCevap: "A" },
    { seviye: 258, kategori: "Coğrafya", soru: "Hangi deniz tamamen kara ile çevrilidir (Limanı yoktur)?", secenekler: { A: "Karadeniz", B: "Umman Denizi", C: "Hazar Denizi", D: "Kızıldeniz" }, dogruCevap: "C" },
    { seviye: 259, kategori: "Coğrafya", soru: "Dünyanın en büyük yarımadası hangisidir?", secenekler: { A: "Hindistan", B: "Anadolu", C: "İskandinavya", D: "Arap Yarımadası" }, dogruCevap: "D" },
    { seviye: 260, kategori: "Coğrafya", soru: "Hangi ülkeye 'Bin Göller Ülkesi' denir?", secenekler: { A: "Kanada", B: "Finlandiya", C: "İsveç", D: "Norveç" }, dogruCevap: "B" },
    { seviye: 261, kategori: "Coğrafya", soru: "Dünyanın en yüksek başkenti (La Paz) hangi ülkededir?", secenekler: { A: "Nepal", B: "Ekvador", C: "Peru", D: "Bolivya" }, dogruCevap: "D" },
    { seviye: 262, kategori: "Coğrafya", soru: "Bering Boğazı hangi iki ülkeyi birbirinden ayırır?", secenekler: { A: "İngiltere - Fransa", B: "Kanada - Grönland", C: "Japonya - Çin", D: "ABD - Rusya" }, dogruCevap: "D" },
    { seviye: 263, kategori: "Coğrafya", soru: "Hangi nehir Avrupa'nın 10 ülkesinden geçerek Karadeniz'e dökülür?", secenekler: { A: "Ren", B: "Elbe", C: "Volga", D: "Tuna" }, dogruCevap: "D" },
    { seviye: 264, kategori: "Coğrafya", soru: "Machu Picchu antik kenti hangi ülkededir?", secenekler: { A: "Kolombiya", B: "Peru", C: "Şili", D: "Meksika" }, dogruCevap: "B" },
    { seviye: 265, kategori: "Coğrafya", soru: "Dünyanın en büyük mercan resifi hangisidir?", secenekler: { A: "Andaman Resifi", B: "Kızıldeniz Resifi", C: "Belize Resifi", D: "Büyük Set Resifi" }, dogruCevap: "D" },
    { seviye: 266, kategori: "Coğrafya", soru: "Hangi nehir üzerine kurulu Victoria Şelalesi ile ünlüdür?", secenekler: { A: "Nijer", B: "Kongo", C: "Zambezi", D: "Nil" }, dogruCevap: "C" },
    { seviye: 267, kategori: "Coğrafya", soru: "Dünyanın en büyük ormanlık alanı (Tayga) hangi ülkededir?", secenekler: { A: "Kanada", B: "Brezilya", C: "ABD", D: "Rusya" }, dogruCevap: "D" },
    { seviye: 268, kategori: "Coğrafya", soru: "Dünya nüfusunun yaklaşık yarısı hangi kıtada yaşar?", secenekler: { A: "Amerika", B: "Afrika", C: "Asya", D: "Avrupa" }, dogruCevap: "C" },
    { seviye: 269, kategori: "Coğrafya", soru: "Kilimanjaro Dağı hangi ülkededir?", secenekler: { A: "Tanzanya", B: "Kenya", C: "Uganda", D: "Etiyopya" }, dogruCevap: "A" },
    { seviye: 270, kategori: "Coğrafya", soru: "Hangi boğaz Basra Körfezi'ni Umman Denizi'ne bağlar ve petrol taşımacılığında kritiktir?", secenekler: { A: "Malakka", B: "Hürmüz", C: "Babülmendep", D: "Hürmüz" }, dogruCevap: "B" },
    { seviye: 271, kategori: "Coğrafya", soru: "Dünyanın en küçük okyanusu hangisidir?", secenekler: { A: "Güney", B: "Hint", C: "Arktik (Kuzey Buz)", D: "Atlas" }, dogruCevap: "C" },
    { seviye: 272, kategori: "Coğrafya", soru: "Hangi ülke iki kıtada toprağı olmasına rağmen Avrupa ülkesi sayılır?", secenekler: { A: "Türkiye", B: "Rusya", C: "Kazakistan", D: "Mısır" }, dogruCevap: "B" },
    { seviye: 273, kategori: "Coğrafya", soru: "İzlanda hangi okyanustadır?", secenekler: { A: "Hint", B: "Atlas", C: "Pasifik", D: "Arktik" }, dogruCevap: "B" },
    { seviye: 274, kategori: "Coğrafya", soru: "Dünyanın en derin gölü hangisidir?", secenekler: { A: "Superior", B: "Tanganika", C: "Baykal", D: "Hazar" }, dogruCevap: "C" },
    { seviye: 275, kategori: "Coğrafya", soru: "Ekvator çizgisi hangi kıtadan geçmez?", secenekler: { A: "Güney Amerika", B: "Asya", C: "Afrika", D: "Avrupa" }, dogruCevap: "D" },
    { seviye: 276, kategori: "Coğrafya", soru: "Hangi ülke topraklarında hiç dağ yoktur?", secenekler: { A: "Danimarka", B: "Maldivler", C: "Katar", D: "Hollanda" }, dogruCevap: "B" },
    { seviye: 277, kategori: "Coğrafya", soru: "Dünyanın en kalabalık adası hangisidir?", secenekler: { A: "Büyük Britanya", B: "Manhattan", C: "Honshu", D: "Java" }, dogruCevap: "D" },
    { seviye: 278, kategori: "Coğrafya", soru: "Everest Dağı'na tırmanan ilk kişiler kimlerdir?", secenekler: { A: "Neil Armstrong", B: "Edmund Hillary - Tenzing Norgay", C: "Marco Polo", D: "Christopher Columbus" }, dogruCevap: "B" },
    { seviye: 279, kategori: "Coğrafya", soru: "Hangi rüzgar türü sadece tropikal kuşakta görülür?", secenekler: { A: "Poyraz", B: "Meltem", C: "Mistral", D: "Tayfun" }, dogruCevap: "D" },
    { seviye: 280, kategori: "Coğrafya", soru: "Atlas Dağları hangi kıtadadır?", secenekler: { A: "Asya", B: "Afrika", C: "Güney Amerika", D: "Avrupa" }, dogruCevap: "B" },
    { seviye: 281, kategori: "Coğrafya", soru: "Dünyanın en büyük limanı (konteyner trafiği) hangisidir?", secenekler: { A: "Şanghay", B: "Singapur", C: "Dubai", D: "Rotterdam" }, dogruCevap: "A" },
    { seviye: 282, kategori: "Coğrafya", soru: "Hangi ülkeye 'Gökkuşağı Ulusu' denir?", secenekler: { A: "ABD", B: "Hindistan", C: "Brezilya", D: "Güney Afrika" }, dogruCevap: "D" },
    { seviye: 283, kategori: "Coğrafya", soru: "Dünyanın en uzun demiryolu hattı (Trans-Sibirya) nerededir?", secenekler: { A: "Çin", B: "Kanada", C: "ABD", D: "Rusya" }, dogruCevap: "D" },
    { seviye: 284, kategori: "Coğrafya", soru: "Kızıldeniz ile Hint Okyanusu'nu bağlayan boğaz?", secenekler: { A: "Malakka", B: "Süveyş", C: "Hürmüz", D: "Babülmendep" }, dogruCevap: "D" },
    { seviye: 285, kategori: "Coğrafya", soru: "Dünyanın en eski metrosu hangi şehirdedir?", secenekler: { A: "Paris", B: "İstanbul", C: "New York", D: "Londra" }, dogruCevap: "D" },
    { seviye: 286, kategori: "Coğrafya", soru: "Hangi ülke hem Akdeniz'e hem Atlas Okyanusu'na kıyısı vardır?", secenekler: { A: "İtalya", B: "Yunanistan", C: "Fransa", D: "Mısır" }, dogruCevap: "C" },
    { seviye: 287, kategori: "Coğrafya", soru: "Dünyanın en büyük buzulu hangi kıtadadır?", secenekler: { A: "Antarktika", B: "Asya", C: "Avrupa", D: "Kuzey Amerika" }, dogruCevap: "A" },
    { seviye: 288, kategori: "Coğrafya", soru: "Ölü Deniz (Lut Gölü) deniz seviyesinden yaklaşık kaç metre aşağıdadır?", secenekler: { A: "430m", B: "1200m", C: "800m", D: "100m" }, dogruCevap: "A" },
    { seviye: 289, kategori: "Coğrafya", soru: "Hangi nehir New York şehrinin içinden geçer?", secenekler: { A: "Thames", B: "Seine", C: "Hudson", D: "Danube" }, dogruCevap: "C" },
    { seviye: 290, kategori: "Coğrafya", soru: "Dünyanın en büyük kahve üreticisi hangisidir?", secenekler: { A: "Kolombiya", B: "Vietnam", C: "Etiyopya", D: "Brezilya" }, dogruCevap: "D" },
    { seviye: 291, kategori: "Coğrafya", soru: "Paskalya Adası hangi ülkeye bağlıdır?", secenekler: { A: "Şili", B: "Peru", C: "Avustralya", D: "Ekvador" }, dogruCevap: "A" },
    { seviye: 292, kategori: "Coğrafya", soru: "Hangi ülke topraklarında nehir olmamasına rağmen yeraltı suları ile tarım yapar?", secenekler: { A: "Mısır", B: "Umman", C: "Ürdün", D: "Suudi Arabistan" }, dogruCevap: "D" },
    { seviye: 293, kategori: "Coğrafya", soru: "Dünyanın en büyük çöllerinden biri olan Gobi Çölü hangi iki ülke arasındadır?", secenekler: { A: "Çin - Moğolistan", B: "Hindistan - Pakistan", C: "Mısır - Libya", D: "İran - Irak" }, dogruCevap: "A" },
    { seviye: 294, kategori: "Coğrafya", soru: "Madagaskar adası hangi okyanustadır?", secenekler: { A: "Güney", B: "Atlas", C: "Hint", D: "Pasifik" }, dogruCevap: "C" },
    { seviye: 295, kategori: "Coğrafya", soru: "Hangi kıta 'Karanlık Kıta' olarak adlandırılırdı?", secenekler: { A: "Antarktika", B: "Asya", C: "Afrika", D: "Avrupa" }, dogruCevap: "C" },
    { seviye: 296, kategori: "Coğrafya", soru: "Dünyanın en yüksek yanardağı hangisidir?", secenekler: { A: "Ojos del Salado", B: "Fuji", C: "Etna", D: "Vezüv" }, dogruCevap: "A" },
    { seviye: 297, kategori: "Coğrafya", soru: "Hangi boğaz Asya ve Avrupa'yı ayırırken aynı zamanda İstanbul'un kalbidir?", secenekler: { A: "İstanbul Boğazı", B: "Cebelitarık", C: "Hürmüz Boğazı", D: "Çanakkale Boğazı" }, dogruCevap: "A" },
    { seviye: 298, kategori: "Coğrafya", soru: "Dünyanın en büyük stadyumu olan Rungrado 1 Mayıs Stadyumu nerededir?", secenekler: { A: "Güney Kore", B: "Kuzey Kore", C: "Çin", D: "Brezilya" }, dogruCevap: "B" },
    { seviye: 299, kategori: "Coğrafya", soru: "Dünyanın en çok yağış alan adası (Hawaii'de) hangisidir?", secenekler: { A: "Oahu", B: "Kauai", C: "Maui", D: "Lana'i" }, dogruCevap: "B" },
    { seviye: 300, kategori: "Coğrafya", soru: "Türkiye'nin matematiksel konumu (paralel) hangisidir?", secenekler: { A: "26-45 Doğu", B: "36-42 Güney", C: "26-45 Batı", D: "36-42 Kuzey" }, dogruCevap: "D" },
    { seviye: 301, kategori: "Coğrafya", soru: "Dünya'nın şekli kutuplardan basık, ekvatordan şişkindir. Bu şekle ne denir?", secenekler: { A: "Daire", B: "Küre", C: "Geoid", D: "Elips" }, dogruCevap: "C" } 
 
);
 