// Eğer dizi yoksa oluştur, varsa içine ekle
window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-20: Türkiye Coğrafyası ve Şehirler
    { kategori: "Genel Kültür", seviye: 1, soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "İstanbul", B: "İzmir", C: "Ankara", D: "Bursa" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 2, soru: "Türkiye'nin en yüksek dağı hangisidir?", secenekler: { A: "Süphan", B: "Erciyes", C: "Kaçkar", D: "Ağrı Dağı" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 3, soru: "Ege Bölgesi'nin en kalabalık şehri hangisidir?", secenekler: { A: "İzmir", B: "Aydın", C: "Muğla", D: "Denizli" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 4, soru: "Türkiye'nin en büyük gölü hangisidir?", secenekler: { A: "Beyşehir Gölü", B: "Van Gölü", C: "Tuz Gölü", D: "Eğirdir Gölü" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 5, soru: "Yedi göller hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Rize", B: "Trabzon", C: "Bolu", D: "Artvin" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 6, soru: "Pamukkale Travertenleri hangi ilimizdedir?", secenekler: { A: "Denizli", B: "Uşak", C: "Manisa", D: "Afyon" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 7, soru: "Türkiye'nin en uzun nehri hangisidir?", secenekler: { A: "Sakarya", B: "Dicle", C: "Kızılırmak", D: "Fırat" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 8, soru: "Güneydoğu Anadolu'nun 'Peygamberler Şehri' olarak bilinen ili hangisidir?", secenekler: { A: "Gaziantep", B: "Diyarbakır", C: "Mardin", D: "Şanlıurfa" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 9, soru: "Peri Bacaları hangi turistik bölgemizde yer alır?", secenekler: { A: "Kapadokya", B: "Ihlara Vadisi", C: "Pamukkale", D: "Efes" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 10, soru: "Mevlana Müzesi hangi ilimizdedir?", secenekler: { A: "Sivas", B: "Ankara", C: "Kayseri", D: "Konya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 11, soru: "Türkiye'nin üç tarafı denizlerle çevrili olması nedeniyle hangi coğrafi tanıma uyar?", secenekler: { A: "Vaha", B: "Körfez", C: "Ada", D: "Yarımada" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 12, soru: "Dünyanın en eski yerleşim yerlerinden biri olan Göbeklitepe hangi ilimizdedir?", secenekler: { A: "Batman", B: "Adıyaman", C: "Şanlıurfa", D: "Hatay" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 13, soru: "Aspendos Antik Tiyatrosu hangi ilimizdedir?", secenekler: { A: "Mersin", B: "Muğla", C: "Antalya", D: "İzmir" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 14, soru: "Çay üretimiyle meşhur olan Karadeniz ilimiz hangisidir?", secenekler: { A: "Rize", B: "Giresun", C: "Ordu", D: "Artvin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 15, soru: "Kayısısı ile ünlü ilimiz hangisidir?", secenekler: { A: "Malatya", B: "Kars", C: "Elazığ", D: "Erzincan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 16, soru: "İstiklal Madalyası alan ilk ilçemiz hangisidir?", secenekler: { A: "Kazan", B: "Polatlı", C: "İnebolu", D: "Maraş" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 17, soru: "Çanakkale Boğazı ile İstanbul Boğazı arasındaki deniz hangisidir?", secenekler: { A: "Marmara Denizi", B: "Ege Denizi", C: "Karadeniz", D: "Akdeniz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 18, soru: "Cumhuriyet döneminin ilk barajı hangisidir?", secenekler: { A: "Keban Barajı", B: "Atatürk Barajı", C: "Çubuk Barajı", D: "Hirfanlı Barajı" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 19, soru: "Türkiye'nin en kuzey noktası olan İnceburun hangi ilimizdedir?", secenekler: { A: "Kırklareli", B: "Zonguldak", C: "Artvin", D: "Sinop" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 20, soru: "Ülkemizin en büyük adası hangisidir?", secenekler: { A: "Gökçeada", B: "Büyükada", C: "Cunda", D: "Bozcaada" }, dogruCevap: "A" },

    // 21-40: Türk Tarihi ve Milli Değerler
    { kategori: "Genel Kültür", seviye: 21, soru: "İstiklal Marşı'mızın şairi kimdir?", secenekler: { A: "Ziya Gökalp", B: "Mehmet Akif Ersoy", C: "Yahya Kemal", D: "Namık Kemal" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 22, soru: "Cumhuriyet kaç yılında ilan edilmiştir?", secenekler: { A: "1921", B: "1920", C: "1923", D: "1924" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 23, soru: "Anadolu'nun kapılarını Türklere açan savaş hangisidir?", secenekler: { A: "Malazgirt", B: "Dandanakan", C: "Miryokefalon", D: "Pasinler" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 24, soru: "İstanbul hangi yıl fethedilmiştir?", secenekler: { A: "1453", B: "1517", C: "1299", D: "1071" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 25, soru: "Osmanlı Devleti'nin kurucusu kimdir?", secenekler: { A: "Ertuğrul Gazi", B: "Orhan Bey", C: "Selçuk Bey", D: "Osman Bey" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 26, soru: "Türkiye Büyük Millet Meclisi (TBMM) hangi tarihte açılmıştır?", secenekler: { A: "19 Mayıs 1919", B: "23 Nisan 1920", C: "29 Ekim 1923", D: "30 Ağustos 1922" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 27, soru: "Mustafa Kemal Atatürk'ün nüfusa kayıtlı olduğu il hangisidir?", secenekler: { A: "Gaziantep", B: "İstanbul", C: "Ankara", D: "Selanik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 28, soru: "Atatürk'ün ebedi istirahatgahı olan Anıtkabir hangi şehrimizdedir?", secenekler: { A: "Samsun", B: "İstanbul", C: "Ankara", D: "İzmir" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 29, soru: "Tarihte Türk adıyla kurulan ilk devlet hangisidir?", secenekler: { A: "Göktürkler", B: "Hunlar", C: "Selçuklular", D: "Uygurlar" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 30, soru: "Sivas Kongresi hangi binada yapılmıştır?", secenekler: { A: "Gök Medrese", B: "Ulu Cami", C: "Hükümet Konağı", D: "Sivas Lisesi" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 31, soru: "Çanakkale Zaferi hangi gün kutlanır?", secenekler: { A: "29 Ekim", B: "19 Mayıs", C: "18 Mart", D: "30 Ağustos" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 32, soru: "Osmanlı'nın ilk başkenti neresidir?", secenekler: { A: "Edirne", B: "İznik", C: "Söğüt", D: "Bursa" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 33, soru: "Hangi padişah 'Fatih' unvanını almıştır?", secenekler: { A: "I. Süleyman", B: "II. Abdülhamid", C: "II. Mehmet", D: "I. Selim" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 34, soru: "Türklere özgü, dünyanın en eski yaylı çalgılarından biri hangisidir?", secenekler: { A: "Ud", B: "Kopuz", C: "Kanun", D: "Bağlama" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 35, soru: "Orhun Abideleri günümüzde hangi ülke sınırları içerisindedir?", secenekler: { A: "Türkiye", B: "Özbekistan", C: "Moğolistan", D: "Kazakistan" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 36, soru: "Dede Korkut hikayeleri hangi Türk boyuna aittir?", secenekler: { A: "Oğuzlar", B: "Kıpçaklar", C: "Karluklar", D: "Uygurlar" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 37, soru: "Mimar Sinan'ın 'Ustalık Eserim' dediği cami hangisidir?", secenekler: { A: "Şehzade Camii", B: "Sultan Ahmet Camii", C: "Selimiye Camii", D: "Süleymaniye Camii" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 38, soru: "Lale Devri hangi padişah zamanında yaşanmıştır?", secenekler: { A: "Abdülaziz", B: "II. Mahmud", C: "IV. Murad", D: "III. Ahmed" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 39, soru: "Cumhuriyet tarihinin ilk kadın muhtarı kimdir?", secenekler: { A: "Türkan Saylan", B: "Sabiha Gökçen", C: "Gül Esin", D: "Afet İnan" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 40, soru: "Türklerin kullandığı ilk takvim hangisidir?", secenekler: { A: "12 Hayvanlı Türk Takvimi", B: "Hicri Takvim", C: "Rumi Takvim", D: "Miladi Takvim" }, dogruCevap: "A" },

    // 41-60: Türk Edebiyatı ve Sanat
    { kategori: "Genel Kültür", seviye: 41, soru: "Şair-i Azam olarak bilinen şairimiz kimdir?", secenekler: { A: "Abdülhak Hamit Tarhan", B: "Cahit Sıtkı Tarancı", C: "Nazım Hikmet", D: "Tevfik Fikret" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 42, soru: "Mai ve Siyah romanı kime aittir?", secenekler: { A: "Halit Ziya Uşaklıgil", B: "Yakup Kadri", C: "Peyami Safa", D: "Reşat Nuri" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 43, soru: "Hababam Sınıfı'nın yazarı kimdir?", secenekler: { A: "Aziz Nesin", B: "Yaşar Kemal", C: "Rıfat Ilgaz", D: "Orhan Kemal" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 44, soru: "Kuyucaklı Yusuf romanı kime aittir?", secenekler: { A: "Ahmet Hamdi Tanpınar", B: "Sabahattin Ali", C: "Peyami Safa", D: "Tarık Buğra" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 45, soru: "Vatan Şairi olarak bilinen yazarımız?", secenekler: { A: "Namık Kemal", B: "Mehmet Akif", C: "Ziya Paşa", D: "Necip Fazıl" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 46, soru: "Türkçenin ilk sözlüğü hangisidir?", secenekler: { A: "Muhakemetü'l-Lügateyn", B: "Kamusu Türki", C: "Lehçe-i Osmani", D: "Divanü Lügati't-Türk" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 47, soru: "Çalıkuşu romanının baş kahramanı kimdir?", secenekler: { A: "Bihter", B: "Feride", C: "Zehra", D: "Eylül" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 48, soru: "Türk edebiyatında ilk yerli roman hangisidir?", secenekler: { A: "İntibah", B: "Karabibik", C: "Araba Sevdası", D: "Taaşşuk-ı Talat ve Fitnat" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 49, soru: "Sinekli Bakkal romanı kime aittir?", secenekler: { A: "Ömer Seyfettin", B: "Reşat Nuri", C: "Yakup Kadri", D: "Halide Edip Adıvar" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 50, soru: "Yaprak Dökümü romanı kime aittir?", secenekler: { A: "Reşat Nuri Güntekin", B: "Peyami Safa", C: "Tarık Buğra", D: "Kemal Tahir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 51, soru: "Mesnevi eseri kime aittir?", secenekler: { A: "Hacı Bektaş Veli", B: "Ahmet Yesevi", C: "Mevlana", D: "Yunus Emre" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 52, soru: "Risaletü'n-Nushiyye kime aittir?", secenekler: { A: "Karacaoğlan", B: "Kaygusuz Abdal", C: "Yunus Emre", D: "Pir Sultan Abdal" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 53, soru: "Şerbetçi ve dondurmacı tiplemeleriyle ünlü Türk gölge oyunu?", secenekler: { A: "Meddah", B: "Orta Oyunu", C: "Karagöz ve Hacivat", D: "Köy Seyirlik Oyunları" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 54, soru: "Geleneksel Türk tiyatrosunda doğaçlama yapılan oyun?", secenekler: { A: "Trajedi", B: "Orta Oyunu", C: "Opera", D: "Komedi" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 55, soru: "Makber şiiri kime aittir?", secenekler: { A: "Muallim Naci", B: "Recaizade Mahmut Ekrem", C: "Şinasi", D: "Abdülhak Hamit Tarhan" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 56, soru: "Modern Türk öykücülüğünün öncüsü kimdir?", secenekler: { A: "Sabahattin Ali", B: "Memduh Şevket Esendal", C: "Ömer Seyfettin", D: "Sait Faik Abasıyanık" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 57, soru: "Otuz Beş Yaş şiiriyle tanınan şairimiz?", secenekler: { A: "Ziya Osman Saba", B: "Cahit Sıtkı Tarancı", C: "Behçet Necatigil", D: "Ahmet Muhip Dıranas" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 58, soru: "İnce Memed romanı kime aittir?", secenekler: { A: "Kemal Tahir", B: "Yaşar Kemal", C: "Fakir Baykurt", D: "Orhan Kemal" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 59, soru: "Dokuzuncu Hariciye Koğuşu kime aittir?", secenekler: { A: "Samiha Ayverdi", B: "Tarık Buğra", C: "Peyami Safa", D: "Ahmet Hamdi Tanpınar" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 60, soru: "Safahat eseri kime aittir?", secenekler: { A: "Ziya Gökalp", B: "Mehmet Akif Ersoy", C: "Yahya Kemal", D: "Tevfik Fikret" }, dogruCevap: "B" },

    // 61-80: Türk Kültürü, Gelenek ve Spor
    { kategori: "Genel Kültür", seviye: 61, soru: "Türklerin milli sporu olarak kabul edilen spor dalı?", secenekler: { A: "Cirit", B: "Güreş", C: "Binicilik", D: "Okçuluk" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 62, soru: "Dünyanın en eski güreş festivali hangisidir?", secenekler: { A: "Kırkpınar Yağlı Güreşleri", B: "Elmalı Güreşleri", C: "Kurtdere Güreşleri", D: "Karakucak Güreşleri" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 63, soru: "Türklere özgü, at üzerinde oynanan geleneksel spor?", secenekler: { A: "Cirit", B: "Tepük", C: "Gökbörü", D: "Matrak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 64, soru: "Türk kahvesi pişirilirken kullanılan küçük saplı kaba ne denir?", secenekler: { A: "Güğüm", B: "Cezve", C: "Semaver", D: "İbrik" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 65, soru: "Erzurum ve çevresinde oynanan halk oyunu?", secenekler: { A: "Horon", B: "Halay", C: "Zeybek", D: "Bar" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 66, soru: "Ege Bölgesi ile özdeşleşmiş halk oyunu?", secenekler: { A: "Zeybek", B: "Bengi", C: "Kaşık Oyunu", D: "Horon" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 67, soru: "Karadeniz bölgesine ait, kemençe eşliğinde oynanan oyun?", secenekler: { A: "Halay", B: "Horon", C: "Çayda Çıra", D: "Atabarı" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 68, soru: "Trakya yöresine ait ünlü halk oyunu?", secenekler: { A: "Mengi", B: "Zeybek", C: "Hora", D: "Bar" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 69, soru: "Türk mutfağının vazgeçilmezi olan, fermente edilmiş süt ürünü?", secenekler: { A: "Krema", B: "Kefir", C: "Yoğurt", D: "Peynir" }, dogruCevap: "C" },
    
    { kategori: "Genel Kültür", seviye: 71, soru: "Keloğlan hangi Türk kültür ögesine aittir?", secenekler: { A: "Masal", B: "Destan", C: "Efsane", D: "Ağıt" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 72, soru: "Nasreddin Hoca fıkralarıyla ünlü şehrimiz?", secenekler: { A: "Afyon", B: "Eskişehir", C: "Akşehir", D: "Kütahya" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 73, soru: "Baharın müjdecisi olarak kutlanan Türk bayramı?", secenekler: { A: "Kurban Bayramı", B: "Hıdırellez", C: "Nevruz", D: "Ramazan Bayramı" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 74, soru: "Geleneksel Türk ebru sanatında kullanılan ana malzeme?", secenekler: { A: "Kitre", B: "Kil", C: "Yağ", D: "Alçı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 75, soru: "Hat sanatı ile uğraşan sanatçılara ne denir?", secenekler: { A: "Müzehhip", B: "Nakkaş", C: "Hattat", D: "Ebruli" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 76, soru: "Eski yazma kitapları süsleyen küçük resim sanatı?", secenekler: { A: "Tezhip", B: "Minyatür", C: "Çini", D: "Fresk" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 77, soru: "Çini sanatı ile dünyaca ünlü ilimiz?", secenekler: { A: "Kütahya", B: "Konya", C: "İzmit", D: "Bursa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 78, soru: "Dünyanın en eski askeri bandosu hangisidir?", secenekler: { A: "Orkestra", B: "Mehter Takımı", C: "Bando Mızıka", D: "Filarmoni" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 79, soru: "Türk bayrağındaki hilal ve yıldız neyi temsil eder (sembolik olarak)?", secenekler: { A: "Bereket", B: "Barış", C: "Bağımsızlık", D: "Adalet" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 80, soru: "Atatürk'ün 'En büyük eserim' dediği şey hangisidir?", secenekler: { A: "TBMM", B: "Anıtkabir", C: "Nutuk", D: "Türkiye Cumhuriyeti" }, dogruCevap: "D" },

    // 81-100: Dünya Genel Kültürü ve Karışık
    { kategori: "Genel Kültür", seviye: 81, soru: "Dünyanın en kalabalık ülkesi hangisidir?", secenekler: { A: "Hindistan", B: "Çin", C: "ABD", D: "Rusya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 82, soru: "En büyük yüzölçümüne sahip ülke hangisidir?", secenekler: { A: "Rusya", B: "Kanada", C: "Çin", D: "Brezilya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 83, soru: "Eyfel Kulesi hangi şehirdedir?", secenekler: { A: "Londra", B: "Berlin", C: "Paris", D: "Roma" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 84, soru: "Pisa Kulesi hangi ülkededir?", secenekler: { A: "İspanya", B: "Fransa", C: "Yunanistan", D: "İtalya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 85, soru: "Kızıl Meydan hangi şehirdedir?", secenekler: { A: "Prag", B: "Kiev", C: "Varşova", D: "Moskova" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 86, soru: "Özgürlük Heykeli hangi ülkededir?", secenekler: { A: "İngiltere", B: "Fransa", C: "Kanada", D: "ABD" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 87, soru: "Kolezyum hangi şehirdedir?", secenekler: { A: "Atina", B: "Roma", C: "Venedik", D: "Floransa" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 88, soru: "Piramitler hangi ülkededir?", secenekler: { A: "Mısır", B: "Meksika", C: "Peru", D: "Sudan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 89, soru: "Dünyanın en uzun nehri hangisidir?", secenekler: { A: "Ganj", B: "Mississippi", C: "Nil", D: "Amazon" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 90, soru: "En derin okyanus hangisidir?", secenekler: { A: "Büyük Okyanus", B: "Hint Okyanusu", C: "Kuzey Buz Denizi", D: "Atlas Okyanusu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 91, soru: "Mona Lisa tablosu kime aittir?", secenekler: { A: "Picasso", B: "Van Gogh", C: "Salvador Dali", D: "Leonardo da Vinci" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 92, soru: "Telefonun mucidi kimdir?", secenekler: { A: "Marconi", B: "Graham Bell", C: "Tesla", D: "Edison" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 93, soru: "Hangi ülke 'Güneşin Doğduğu Ülke' olarak bilinir?", secenekler: { A: "Tayland", B: "Güney Kore", C: "Çin", D: "Japonya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 94, soru: "Dünya kupasını en çok kazanan ülke hangisidir?", secenekler: { A: "Arjantin", B: "Almanya", C: "İtalya", D: "Brezilya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 95, soru: "Kanarya Adaları hangi ülkeye bağlıdır?", secenekler: { A: "İspanya", B: "Fas", C: "Fransa", D: "Portekiz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 96, soru: "Avrupa Birliği'nin merkezi hangi şehirdir?", secenekler: { A: "Strazburg", B: "Brüksel", C: "Lüksemburg", D: "Cenevre" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 97, soru: "Dünyanın yedi harikasından biri olan Tac Mahal nerededir?", secenekler: { A: "Hindistan", B: "Afganistan", C: "Pakistan", D: "İran" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 98, soru: "İnce Memed kimin eseridir?", secenekler: { A: "Zülfü Livaneli", B: "Elif Şafak", C: "Yaşar Kemal", D: "Orhan Pamuk" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 99, soru: "Güneş sistemindeki en küçük gezegen hangisidir?", secenekler: { A: "Mars", B: "Venüs", C: "Merkür", D: "Neptün" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 100, soru: "Türkiye'nin ilk yerli otomobilinin adı nedir?", secenekler: { A: "TOGG", B: "Şahin", C: "Devrim", D: "Anadol" }, dogruCevap: "A" }, 
    // 101-300: Yeni Genel Kültür Soruları
    { kategori: "Genel Kültür", seviye: 101, soru: "Oksijeni keşfeden bilim insanı kimdir?", secenekler: { A: "Albert Einstein", B: "Joseph Priestley", C: "Isaac Newton", D: "Marie Curie" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 102, soru: "İstiklal Marşı hangi yıl kabul edilmiştir?", secenekler: { A: "1924", B: "1923", C: "1921", D: "1920" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 103, soru: "Dünyanın en yüksek şelalesi hangisidir?", secenekler: { A: "Angel Şelalesi", B: "Victoria", C: "Iguazu", D: "Niagara" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 104, soru: "Sinekli Bakkal romanının yazarı kimdir?", secenekler: { A: "Yakup Kadri", B: "Peyami Safa", C: "Halide Edip Adıvar", D: "Reşat Nuri Güntekin" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 105, soru: "Hangi gezegen 'Kızıl Gezegen' olarak bilinir?", secenekler: { A: "Mars", B: "Venüs", C: "Jüpiter", D: "Satürn" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 106, soru: "Aspirin'in hammaddesi olan ağaç hangisidir?", secenekler: { A: "Kavak", B: "Çam", C: "Söğüt", D: "Meşe" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 107, soru: "Türkiye'nin en büyük adası hangisidir?", secenekler: { A: "Büyükada", B: "Gökçeada", C: "Bozcaada", D: "Heybeliada" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 108, soru: "Kuduz aşısını bulan bilim insanı kimdir?", secenekler: { A: "Alexander Fleming", B: "Edward Jenner", C: "Louis Pasteur", D: "Robert Koch" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 109, soru: "İlk modern olimpiyatlar hangi yıl yapılmıştır?", secenekler: { A: "1920", B: "1912", C: "1900", D: "1896" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 110, soru: "İnce Memed romanı kime aittir?", secenekler: { A: "Orhan Kemal", B: "Yaşar Kemal", C: "Kemal Tahir", D: "Sait Faik" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 111, soru: "Dünyanın en küçük kıtası hangisidir?", secenekler: { A: "Avrupa", B: "Güney Amerika", C: "Antarktika", D: "Avustralya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 112, soru: "Suyun kaldırma kuvvetini kim bulmuştur?", secenekler: { A: "Galileo", B: "Pascal", C: "Newton", D: "Arşimet" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 113, soru: "Fatih Sultan Mehmet'in hocası kimdir?", secenekler: { A: "Molla Fenari", B: "Ebu Suud Efendi", C: "Hacı Bayram Veli", D: "Akşemseddin" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 114, soru: "Türkiye'nin en çok sınır komşusu olan ili hangisidir?", secenekler: { A: "Hakkari", B: "Edirne", C: "Iğdır", D: "Van" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 115, soru: "Nobel ödülleri hangi ülkede verilmektedir?", secenekler: { A: "İsveç", B: "Norveç", C: "Danimarka", D: "İsviçre" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 116, soru: "Satrancın ana vatanı neresidir?", secenekler: { A: "Hindistan", B: "Mısır", C: "Çin", D: "İran" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 117, soru: "Damlataş Mağarası hangi ilimizdedir?", secenekler: { A: "Isparta", B: "Antalya", C: "Burdur", D: "Muğla" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 118, soru: "Kuzey Kutbu'nu keşfeden kişi kimdir?", secenekler: { A: "Roald Amundsen", B: "Christopher Columbus", C: "Robert Peary", D: "James Cook" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 119, soru: "Pi sayısının yaklaşık değeri kaçtır?", secenekler: { A: "3,14", B: "2,14", C: "3,16", D: "3,18" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 120, soru: "Osmanlı Devleti'nin son padişahı kimdir?", secenekler: { A: "Abdülaziz", B: "Reşat", C: "Vahdettin", D: "Abdülhamid" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 121, soru: "Dünyanın en büyük çölü hangisidir?", secenekler: { A: "Gobi Çölü", B: "Sahra Çölü", C: "Atacama", D: "Kalahari" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 122, soru: "Ulu Önder Atatürk'ün doğum yeri neresidir?", secenekler: { A: "Selanik", B: "Sofya", C: "İstanbul", D: "Manastır" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 123, soru: "Fahrenheit ölçeğinde su kaç derecede donar?", secenekler: { A: "212", B: "100", C: "0", D: "32" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 124, soru: "Hangi ilimiz 'Güller Diyarı' olarak bilinir?", secenekler: { A: "Antalya", B: "Burdur", C: "Afyon", D: "Isparta" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 125, soru: "Sultan Ahmet Camii'nin mimarı kimdir?", secenekler: { A: "Mimar Hayrettin", B: "Mimar Kemalettin", C: "Sedefkar Mehmet Ağa", D: "Mimar Sinan" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 126, soru: "İlk Türk kadın pilot kimdir?", secenekler: { A: "Leman Bozkurt", B: "Sabiha Rıfat", C: "Sabiha Gökçen", D: "Bedriye Tahir Gökmen" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 127, soru: "Güneş sistemindeki en büyük gezegen hangisidir?", secenekler: { A: "Neptün", B: "Satürn", C: "Dünya", D: "Jüpiter" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 128, soru: "Türkiye'nin en büyük gölü hangisidir?", secenekler: { A: "Van Gölü", B: "Beyşehir Gölü", C: "Eğirdir Gölü", D: "Tuz Gölü" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 129, soru: "Ampulü kim icat etmiştir?", secenekler: { A: "Thomas Edison", B: "Nikola Tesla", C: "Benjamin Franklin", D: "Alexander Graham Bell" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 130, soru: "Tuz Gölü hangi üç ilin sınırları içerisindedir?", secenekler: { A: "Ankara-Konya-Aksaray", B: "Ankara-Kırşehir-Niğde", C: "Kayseri-Nevşehir-Aksaray", D: "Konya-Aksaray-Niğde" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 131, soru: "DNA'nın yapısını keşfeden bilim insanlarından biri kimdir?", secenekler: { A: "James Watson", B: "Gregor Mendel", C: "Louis Pasteur", D: "Charles Darwin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 132, soru: "Hangi hayvanın sütü pembe renklidir?", secenekler: { A: "Zürafa", B: "Su aygırı", C: "Gergedan", D: "Fil" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 133, soru: "Ünlü 'Düşünen Adam' heykeli kime aittir?", secenekler: { A: "Michelangelo", B: "Auguste Rodin", C: "Bernini", D: "Donatello" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 134, soru: "Ankara hangi yıl başkent olmuştur?", secenekler: { A: "1922", B: "1924", C: "1923", D: "1920" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 135, soru: "Sineklerin kaç bacağı vardır?", secenekler: { A: "6", B: "10", C: "4", D: "8" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 136, soru: "Yüzölçümü en küçük olan ilimiz hangisidir?", secenekler: { A: "Bartın", B: "Yalova", C: "Bilecik", D: "Bayburt" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 137, soru: "Pusulayı kimler icat etmiştir?", secenekler: { A: "Çinliler", B: "Araplar", C: "Yunanlar", D: "Mısırlılar" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 138, soru: "Hangi elementin simgesi 'Au'dur?", secenekler: { A: "Altın", B: "Bakır", C: "Gümüş", D: "Alüminyum" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 139, soru: "Türkçenin ilk sözlüğü hangisidir?", secenekler: { A: "Kamusu Türki", B: "Muhakemetü'l-Lügateyn", C: "Divanü Lügati't-Türk", D: "Lehçe-i Osmani" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 140, soru: "Dünyanın en uzun duvarı hangisidir?", secenekler: { A: "Çin Seddi", B: "Hadrian Duvarı", C: "Ağlama Duvarı", D: "Berlin Duvarı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 141, soru: "İnsan vücudundaki en büyük organ hangisidir?", secenekler: { A: "Akciğer", B: "Karaciğer", C: "Deri", D: "Bağırsak" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 142, soru: "Nemrut Dağı heykelleri hangi ilimizdedir?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Malatya", D: "Adıyaman" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 143, soru: "Fransız İhtilali hangi yıl gerçekleşmiştir?", secenekler: { A: "1815", B: "1789", C: "1776", D: "1848" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 144, soru: "Matbaayı ilk geliştiren kişi kimdir?", secenekler: { A: "Galileo", B: "Johannes Gutenberg", C: "Leonardo da Vinci", D: "Isaac Newton" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 145, soru: "Sümela Manastırı hangi ilimizdedir?", secenekler: { A: "Artvin", B: "Giresun", C: "Rize", D: "Trabzon" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 146, soru: "Futbol maçlarında bir devre kaç dakikadır?", secenekler: { A: "45", B: "35", C: "50", D: "40" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 147, soru: "Modern Hemşireliğin kurucusu kimdir?", secenekler: { A: "Rosa Parks", B: "Marie Curie", C: "Virginia Woolf", D: "Florence Nightingale" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 148, soru: "I. Dünya Savaşı hangi yıl başlamıştır?", secenekler: { A: "1914", B: "1910", C: "1912", D: "1918" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 149, soru: "En büyük memeli hayvan hangisidir?", secenekler: { A: "Fil", B: "Mavi Balina", C: "Gergedan", D: "Zürafa" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 150, soru: "Safahat eseri kime aittir?", secenekler: { A: "Ziya Gökalp", B: "Yahya Kemal", C: "Namık Kemal", D: "Mehmet Akif Ersoy" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 151, soru: "Hangi ülke en çok adaya sahiptir?", secenekler: { A: "İsveç", B: "Endonezya", C: "Filipinler", D: "Norveç" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 152, soru: "Telefonun mucidi Graham Bell'in asıl mesleği nedir?", secenekler: { A: "Fizikçi", B: "Mühendis", C: "Sağır öğretmeni", D: "Doktor" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 153, soru: "Türkiye'nin ilk kadın başbakanı kimdir?", secenekler: { A: "Türkan Akyol", B: "Tansu Çiller", C: "Işılay Saygın", D: "Meral Akşener" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 154, soru: "Bir gün kaç saniyedir?", secenekler: { A: "86400", B: "43200", C: "3600", D: "1440" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 155, soru: "Mimar Sinan'ın kalfalık eserim dediği cami hangisidir?", secenekler: { A: "Şehzade", B: "Süleymaniye", C: "Selimiye", D: "Mihrimah Sultan" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 156, soru: "Limonun ekşi olmasının sebebi hangi asittir?", secenekler: { A: "Sitrik Asit", B: "Asetik Asit", C: "Laktik Asit", D: "Sülfürik Asit" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 157, soru: "Dünyanın en tuzlu denizi hangisidir?", secenekler: { A: "Lut Gölü (Ölü Deniz)", B: "Ege Denizi", C: "Akdeniz", D: "Kızıldeniz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 158, soru: "Arıların kaç gözü vardır?", secenekler: { A: "2", B: "5", C: "6", D: "4" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 159, soru: "Ayna hangi elementle kaplanır?", secenekler: { A: "Demir", B: "Gümüş", C: "Bakır", D: "Altın" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 160, soru: "Osmanlı'nın ilk deniz savaşı hangi devletle yapılmıştır?", secenekler: { A: "Bizans", B: "Ceneviz", C: "Venedik", D: "İspanya" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 161, soru: "Hangi kuş uçamaz?", secenekler: { A: "Penguen", B: "Şahin", C: "Kartal", D: "Martı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 162, soru: "İnsan kalbi kaç odacıktan oluşur?", secenekler: { A: "5", B: "4", C: "3", D: "2" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 163, soru: "Türkiye'nin en uzun nehri hangisidir?", secenekler: { A: "Kızılırmak", B: "Dicle", C: "Fırat", D: "Sakarya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 164, soru: "Kan gruplarını keşfeden kimdir?", secenekler: { A: "Karl Landsteiner", B: "Alexander Fleming", C: "Gregor Mendel", D: "Louis Pasteur" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 165, soru: "Yedi Tepe üzerine kurulu olan şehrimiz hangisidir?", secenekler: { A: "İzmir", B: "Ankara", C: "Bursa", D: "İstanbul" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 166, soru: "Periyodik cetvelde 'H' hangi elementi temsil eder?", secenekler: { A: "Hidrojen", B: "Hıva", C: "Hafniyum", D: "Helyum" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 167, soru: "Çanakkale Boğazı'nın en dar yeri neresidir?", secenekler: { A: "Kilitbahir", B: "Eceabat", C: "Lapseki", D: "Gelibolu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 168, soru: "Hangi dil en çok konuşulan dildir (ana dil olarak)?", secenekler: { A: "Çince (Mandarin)", B: "İngilizce", C: "İspanyolca", D: "Hintçe" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 169, soru: "Satrançta en güçlü taş hangisidir?", secenekler: { A: "Vezir", B: "Kale", C: "Şah", D: "At" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 170, soru: "Mona Lisa tablosu hangi müzededir?", secenekler: { A: "Uffizi", B: "Prado", C: "British Museum", D: "Louvre" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 171, soru: "Aspirin'in hammaddesi hangisidir?", secenekler: { A: "Söğüt ağacı", B: "Çam ağacı", C: "Papatya", D: "Ihlamur" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 172, soru: "Osmanlı'da matbaayı kuran ilk kişi kimdir?", secenekler: { A: "Sait Efendi", B: "Evliya Çelebi", C: "Katip Çelebi", D: "İbrahim Müteferrika" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 173, soru: "Hangi ilimizde demiryolu yoktur?", secenekler: { A: "Eskişehir", B: "Sivas", C: "Antalya", D: "Kayseri" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 174, soru: "Dünya'ya en yakın yıldız hangisidir?", secenekler: { A: "Proxima Centauri", B: "Güneş", C: "Polaris", D: "Sirius" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 175, soru: "Hangi ülkenin iki kıtada toprağı vardır?", secenekler: { A: "Mısır", B: "Hepsi", C: "Türkiye", D: "Rusya" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 176, soru: "Olimpiyat halkaları kaç tanedir?", secenekler: { A: "7", B: "6", C: "4", D: "5" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 177, soru: "İlk Selçuklu parası hangi padişah zamanında basılmıştır?", secenekler: { A: "Melikşah", B: "Tuğrul Bey", C: "Alp Arslan", D: "Sencer" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 178, soru: "Damlataş Mağarası nerededir?", secenekler: { A: "Fethiye", B: "Alanya", C: "Marmaris", D: "Bodrum" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 179, soru: "Suyun kimyasal formülü nedir?", secenekler: { A: "CO2", B: "O2", C: "H2O", D: "NaCl" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 180, soru: "Hangi organımız kanı temizler?", secenekler: { A: "Mide", B: "Kalp", C: "Böbrek", D: "Akciğer" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 181, soru: "Hangi spor dalında 'Servis' yoktur?", secenekler: { A: "Tenis", B: "Futbol", C: "Voleybol", D: "Masa Tenisi" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 182, soru: "Dünyanın en büyük şelalesi hangisidir?", secenekler: { A: "Düden", B: "Niagara", C: "Victoria", D: "Angel" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 183, soru: "En çok uydusu olan gezegen hangisidir?", secenekler: { A: "Jüpiter", B: "Satürn", C: "Mars", D: "Venüs" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 184, soru: "Topkapı Sarayı'nı hangi padişah yaptırmıştır?", secenekler: { A: "II. Abdülhamid", B: "Fatih Sultan Mehmet", C: "Yavuz Sultan Selim", D: "Kanuni Sultan Süleyman" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 185, soru: "Ses hızı havada yaklaşık kaç m/s'dir?", secenekler: { A: "1200", B: "100", C: "340", D: "300000" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 186, soru: "Karagöz ile Hacivat hangi döneme aittir?", secenekler: { A: "Selçuklu", B: "Osmanlı", C: "Cumhuriyet", D: "Bizans" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 187, soru: "Hangi ilimizde kayak merkezi yoktur?", secenekler: { A: "Bursa", B: "Şanlıurfa", C: "Kayseri", D: "Erzurum" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 188, soru: "DNA testi için ne kullanılmaz?", secenekler: { A: "Kan", B: "Parmak izi", C: "Tükürük", D: "Saç teli" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 189, soru: "Sultan Ahmet Camii'nin kaç minaresi vardır?", secenekler: { A: "5", B: "6", C: "2", D: "4" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 190, soru: "Dünyanın en küçük bağımsız devleti hangisidir?", secenekler: { A: "Monako", B: "Malta", C: "Vatikan", D: "San Marino" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 191, soru: "Hangi ülkenin bayrağı dikdörtgen değildir?", secenekler: { A: "Belçika", B: "İsviçre", C: "Japonya", D: "Nepal" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 192, soru: "Panda hangi ülkenin sembolüdür?", secenekler: { A: "Japonya", B: "Vietnam", C: "Çin", D: "Tayland" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 193, soru: "İlk insanlı uzay uçuşunu kim yapmıştır?", secenekler: { A: "John Glenn", B: "Neil Armstrong", C: "Buzz Aldrin", D: "Yuri Gagarin" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 194, soru: "Hangi hayvan uyurken gözlerini kapatmaz?", secenekler: { A: "Balık", B: "Tavşan", C: "Hamster", D: "Yılan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 195, soru: "Nobel Barış Ödülü hangi şehirde verilir?", secenekler: { A: "Oslo", B: "Stockholm", C: "Kopenhag", D: "Helsinki" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 196, soru: "Kız Kulesi hangi şehirdedir?", secenekler: { A: "Çanakkale", B: "İstanbul", C: "Antalya", D: "İzmir" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 197, soru: "Bir kilometrede kaç santimetre vardır?", secenekler: { A: "100.000", B: "1.000.000", C: "1.000", D: "10.000" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 198, soru: "Kuyruklu yıldızlar neyden oluşur?", secenekler: { A: "Metal", B: "Sıcak gaz", C: "Buz ve toz", D: "Sadece taş" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 199, soru: "Hangi kıtanın yerli halkına 'Aborjin' denir?", secenekler: { A: "Güney Amerika", B: "Asya", C: "Avustralya", D: "Afrika" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 200, soru: "Sherlock Holmes karakterinin yaratıcısı kimdir?", secenekler: { A: "Agatha Christie", B: "Stephen King", C: "Edgar Allan Poe", D: "Arthur Conan Doyle" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 201, soru: "Hangi kan grubu 'Genel Alıcı'dır?", secenekler: { A: "A Pozitif", B: "0 Negatif", C: "AB Pozitif", D: "B Negatif" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 202, soru: "Uçaklarda bulunan ve kaza anlarını kaydeden cihazın adı nedir?", secenekler: { A: "GPS", B: "Altometre", C: "Kara Kutu", D: "Radar" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 203, soru: "Eyfel Kulesi'nin mimarı kimdir?", secenekler: { A: "Gustave Eiffel", B: "Victor Hugo", C: "Le Corbusier", D: "Charles Garnier" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 204, soru: "Hangi elementin simgesi 'Fe'dir?", secenekler: { A: "Fosfor", B: "Flor", C: "Fransiyum", D: "Demir" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 205, soru: "Ata Demirer'in canlandırdığı ünlü karakter 'Hüseyin Badem' hangi film serisindedir?", secenekler: { A: "Eyyvah Eyvah", B: "Hedefim Sensin", C: "Berlin Kaplanı", D: "Olanlar Oldu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 206, soru: "İlk Türk devletlerinde ölen kişilerin mezarına ne denirdi?", secenekler: { A: "Kurgan", B: "Yuğ", C: "Balbal", D: "Şaman" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 207, soru: "Türkiye'nin en batı noktası hangisidir?", secenekler: { A: "Avlaka Burnu", B: "Dilburnu", C: "Bababurnu", D: "İnceburun" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 208, soru: "Aspirin hangi bitkiden elde edilir?", secenekler: { A: "Papatya", B: "Isırgan", C: "Söğüt", D: "Nane" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 209, soru: "Yel değirmenleriyle ünlü olan ülke hangisidir?", secenekler: { A: "Hollanda", B: "Belçika", C: "İsveç", D: "Danimarka" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 210, soru: "Hangi hayvanın kalbi kafasındadır?", secenekler: { A: "Ahtapot", B: "Karides", C: "Istakoz", D: "Yengeç" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 211, soru: "Güneş sistemindeki en soğuk gezegen hangisidir?", secenekler: { A: "Uranüs", B: "Satürn", C: "Plüton", D: "Neptün" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 212, soru: "Tarihin babası olarak bilinen kişi kimdir?", secenekler: { A: "Hipokrat", B: "Platon", C: "Heredot", D: "Sokrates" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 213, soru: "Hangi ilimizde 'Peri Bacaları' yoktur?", secenekler: { A: "Niğde", B: "Nevşehir", C: "Aksaray", D: "Ankara" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 214, soru: "Futbolda ofsayt kuralı hangi yıl getirilmiştir?", secenekler: { A: "1950", B: "1863", C: "1900", D: "1925" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 215, soru: "En hafif element hangisidir?", secenekler: { A: "Lityum", B: "Helyum", C: "Azot", D: "Hidrojen" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 216, soru: "Türkiye'nin en derin gölü hangisidir?", secenekler: { A: "Nemrut Gölü", B: "Bafa Gölü", C: "Van Gölü", D: "Salda Gölü" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 217, soru: "Hangi meyvenin çekirdeği dışında bulunur?", secenekler: { A: "İncir", B: "Böğürtlen", C: "Çilek", D: "Ahududu" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 218, soru: "Gökkuşağının ortasındaki renk hangisidir?", secenekler: { A: "Sarı", B: "Mavi", C: "Yeşil", D: "Turuncu" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 219, soru: "Dünyanın en büyük kütüphanesi nerededir?", secenekler: { A: "Londra", B: "Moskova", C: "Washington (Kongre Kütüphanesi)", D: "Paris" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 220, soru: "Türkiye'de kaç tane coğrafi bölge vardır?", secenekler: { A: "7", B: "8", C: "4", D: "5" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 221, soru: "Pisa Kulesi neden eğiktir?", secenekler: { A: "Mimari bir tercih", B: "Deprem yüzünden", C: "Savaş hasarı", D: "Temelindeki yumuşak zemin yüzünden" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 222, soru: "Hangi ilimiz 'İstiklal Madalyası'na sahip değildir?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Kahramanmaraş", D: "Adana" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 223, soru: "İnsan vücudunda kaç kemik bulunur (yetişkinlerde)?", secenekler: { A: "206", B: "406", C: "106", D: "306" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 224, soru: "Hangi gezegenin halkaları en belirgindir?", secenekler: { A: "Neptün", B: "Uranüs", C: "Satürn", D: "Jüpiter" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 225, soru: "Peyniriyle ünlü olan ilimiz hangisidir?", secenekler: { A: "Kars", B: "Hepsi", C: "Ardahan", D: "Erzurum" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 226, soru: "Mona Lisa'nın kaşları neden yoktur?", secenekler: { A: "Ressam unuttu", B: "Zamanla silindi", C: "Hiç olmadı", D: "O dönemde kaşları tıraş etmek modaydı" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 227, soru: "Tavşanlar neyle beslenir?", secenekler: { A: "Peynir", B: "Et", C: "Süt", D: "Havuç" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 228, soru: "Hangi ilimizde 'Altın Portakal' film festivali yapılır?", secenekler: { A: "Adana", B: "İstanbul", C: "İzmir", D: "Antalya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 229, soru: "Bir kilometrede kaç metre vardır?", secenekler: { A: "10000", B: "100", C: "1000", D: "10" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 230, soru: "Sinekler kaç kanatlıdır?", secenekler: { A: "6", B: "2", C: "8", D: "4" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 231, soru: "Arılar nasıl haberleşir?", secenekler: { A: "Dans ederek", B: "Ses çıkararak", C: "Kokuyla", D: "Dokunarak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 232, soru: "Hangi ağaç kışın yaprak dökmez?", secenekler: { A: "Kavak", B: "Meşe", C: "Çam", D: "Gürgen" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 233, soru: "En büyük iç organımız hangisidir?", secenekler: { A: "Bağırsak", B: "Mide", C: "Dalak", D: "Karaciğer" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 234, soru: "Güneş bir nedir?", secenekler: { A: "Yıldız", B: "Gezegen", C: "Uydu", D: "Meteor" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 235, soru: "Hangi hayvan su içmez?", secenekler: { A: "Kertenkele", B: "Kanguru Faresi", C: "Yılan", D: "Deve" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 236, soru: "Aydede şarkısında Aydede nerede durur?", secenekler: { A: "Yolda", B: "Bahçede", C: "Gökyüzünde", D: "Evinde" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 237, soru: "İnsan vücudunda kaç litre kan bulunur?", secenekler: { A: "2-3", B: "5-6", C: "10-12", D: "1-2" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 238, soru: "Hangi ilimiz 'Kayısı' ile meşhurdur?", secenekler: { A: "Malatya", B: "Elazığ", C: "Erzincan", D: "Iğdır" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 239, soru: "Tavuk mu yumurtadan çıkar yumurta mı tavuktan?", secenekler: { A: "İkisi de doğru", B: "Yumurta tavuktan", C: "Bilinmiyor", D: "Tavuk yumurtadan" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 240, soru: "Hangi meyve kış meyvesidir?", secenekler: { A: "Karpuz", B: "Kiraz", C: "Erik", D: "Portakal" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 241, soru: "Hangi hayvan kış uykusuna yatmaz?", secenekler: { A: "Kurt", B: "Kurbağa", C: "Ayı", D: "Yılan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 242, soru: "Gökkuşağı kaç renktir?", secenekler: { A: "7", B: "5", C: "6", D: "8" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 243, soru: "Türkiye'nin en kalabalık ilçesi hangisidir?", secenekler: { A: "Keçiören", B: "Esenyurt", C: "Çankaya", D: "Şahinbey" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 244, soru: "Sinekler neden vızıldar?", secenekler: { A: "Korktukları için", B: "Ayaklarını sürterler", C: "Ağızlarından ses çıkarırlar", D: "Kanat çırptıkları için" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 245, soru: "En yavaş hayvan hangisidir?", secenekler: { A: "Koala", B: "Salyangoz", C: "Kaplumbağa", D: "Tembel Hayvan" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 246, soru: "Hangi gezegenin uydusu yoktur?", secenekler: { A: "Neptün", B: "Mars", C: "Venüs", D: "Jüpiter" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 247, soru: "Pusulanın renkli ucu nereyi gösterir?", secenekler: { A: "Kuzey", B: "Batı", C: "Doğu", D: "Güney" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 248, soru: "Hangi ilimiz Ege Bölgesi'ndedir?", secenekler: { A: "İzmir", B: "Antalya", C: "Mersin", D: "Bursa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 249, soru: "Örümceklerin kaç bacağı vardır?", secenekler: { A: "4", B: "6", C: "10", D: "8" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 250, soru: "Mıknatıs neyi çekmez?", secenekler: { A: "Nikel", B: "Kobalt", C: "Bakır", D: "Demir" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 251, soru: "Dünyanın çevresini ilk kez dolaşan kimdir?", secenekler: { A: "Amerigo Vespucci", B: "Vasco da Gama", C: "Kristof Kolomb", D: "Macellan" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 252, soru: "Hangi ülkenin bayrağında akçaağaç yaprağı vardır?", secenekler: { A: "Kıbrıs", B: "Kanada", C: "Japonya", D: "Lübnan" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 253, soru: "Hangi gezegen halk arasında 'Çoban Yıldızı' olarak bilinir?", secenekler: { A: "Venüs", B: "Jüpiter", C: "Merkür", D: "Mars" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 254, soru: "Oksijeni kim keşfetti?", secenekler: { A: "Antoine Lavoisier", B: "Joseph Priestley", C: "Robert Boyle", D: "Henry Cavendish" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 255, soru: "Hangi spor dalı 'Grand Slam' turnuvalarıyla bilinir?", secenekler: { A: "Kriket", B: "Golf", C: "Beyzbol", D: "Tenis" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 256, soru: "Dünyanın en yüksek binası 'Burj Khalifa' hangi şehirdedir?", secenekler: { A: "Riyad", B: "Dubai", C: "Doha", D: "Abu Dabi" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 257, soru: "Zebra'nın çizgileri ne renktir?", secenekler: { A: "Kahverengi-Sarı", B: "Lacivert-Beyaz", C: "Gri-Siyah", D: "Siyah-Beyaz" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 258, soru: "Hangi kuşun yumurtası en büyüktür?", secenekler: { A: "Albatros", B: "Devekuşu", C: "Kartal", D: "Pelikan" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 259, soru: "İnsan vücudunda en çok bulunan element hangisidir?", secenekler: { A: "Azot", B: "Hidrojen", C: "Oksijen", D: "Karbon" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 260, soru: "Hangi dil Birleşmiş Milletler'in resmi dillerinden biri değildir?", secenekler: { A: "Rusça", B: "Almanca", C: "Çince", D: "Arapça" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 261, soru: "En çok Nobel ödülü alan ülke hangisidir?", secenekler: { A: "Almanya", B: "İngiltere", C: "ABD", D: "Fransa" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 262, soru: "Damlataş Mağarası nerededir?", secenekler: { A: "Marmaris", B: "Bodrum", C: "Fethiye", D: "Alanya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 263, soru: "Satrançta kaç kare vardır?", secenekler: { A: "72", B: "81", C: "64", D: "48" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 264, soru: "Güneş ışığı dünyaya kaç dakikada ulaşır?", secenekler: { A: "8", B: "1", C: "24", D: "15" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 265, soru: "Hangi kıtada hiç aktif yanardağ yoktur?", secenekler: { A: "Avustralya", B: "Afrika", C: "Avrupa", D: "Asya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 266, soru: "Mona Lisa tablosunu kim yaptı?", secenekler: { A: "Donatello", B: "Raphael", C: "Leonardo da Vinci", D: "Michelangelo" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 267, soru: "Hangi ülkenin başkenti Tokyo'dur?", secenekler: { A: "Tayland", B: "Çin", C: "Güney Kore", D: "Japonya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 268, soru: "Yılanlar nasıl duyar?", secenekler: { A: "Kulaklarıyla", B: "Titreşimlerle", C: "Gözleriyle", D: "Dilleriyle" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 269, soru: "Hangi kıta en büyüktür?", secenekler: { A: "Afrika", B: "Amerika", C: "Asya", D: "Avrupa" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 270, soru: "Gökkuşağı ne zaman çıkar?", secenekler: { A: "Gece vakti", B: "Yağmurdan sonra güneş açınca", C: "Sadece güneşliyken", D: "Sadece yağmur yağarken" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 271, soru: "Arılar balı nereden yapar?", secenekler: { A: "Çiçek özlerinden", B: "Topraktan", C: "Su birikintilerinden", D: "Yapraklardan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 272, soru: "Hangi gezegen güneşe en yakındır?", secenekler: { A: "Mars", B: "Venüs", C: "Dünya", D: "Merkür" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 273, soru: "Türkiye'nin en kalabalık şehri hangisidir?", secenekler: { A: "İzmir", B: "İstanbul", C: "Ankara", D: "Bursa" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 274, soru: "Kelebeklerin ömrü ne kadardır?", secenekler: { A: "1 gün", B: "Türüne göre değişir", C: "1 hafta", D: "1 yıl" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 275, soru: "Sıcaklık neyle ölçülür?", secenekler: { A: "Pusula", B: "Saat", C: "Barometre", D: "Termometre" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 276, soru: "En büyük okyanus hangisidir?", secenekler: { A: "Atlas Okyanusu", B: "Hint Okyanusu", C: "Antarktika Okyanusu", D: "Büyük Okyanus (Pasifik)" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 277, soru: "Hangi hayvanın yavrusuna 'enik' denir?", secenekler: { A: "Koyun", B: "Kedi", C: "At", D: "Köpek" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 278, soru: "Hangi ilimiz İç Anadolu Bölgesi'ndedir?", secenekler: { A: "Ankara", B: "İzmir", C: "Diyarbakır", D: "Trabzon" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 279, soru: "İnsanlar kaç dişle doğar?", secenekler: { A: "20 dişle", B: "10 dişle", C: "Dişsiz doğarlar", D: "32 dişle" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 280, soru: "Uçurtma neyle uçar?", secenekler: { A: "Yağmurla", B: "Kendi motoruyla", C: "Güneşle", D: "Rüzgarla" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 281, soru: "Kutup ayıları nerede yaşar?", secenekler: { A: "Kuzey Kutbu", B: "Ekvator", C: "Ormanlarda", D: "Güney Kutbu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 282, soru: "Kangurular nerede yaşar?", secenekler: { A: "Amerika", B: "Asya", C: "Avustralya", D: "Afrika" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 283, soru: "Ay'ın ışığı nereden gelir?", secenekler: { A: "Yıldızlardan", B: "Güneşten", C: "Dünyadan", D: "Kendi ışığıdır" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 284, soru: "Kışın hangi kıyafeti giyeriz?", secenekler: { A: "Palto", B: "Tişört", C: "Şort", D: "Sandalet" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 285, soru: "Meyveleri yemeden önce ne yapmalıyız?", secenekler: { A: "Boyamalıyız", B: "Kurutmalıyız", C: "Pişirmeliyiz", D: "Yıkamalıyız" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 286, soru: "Dişlerimizi günde en az kaç kez fırçalamalıyız?", secenekler: { A: "5", B: "1", C: "2", D: "10" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 287, soru: "Hangi mevsimde okullar açılır?", secenekler: { A: "İlkbahar", B: "Kış", C: "Yaz", D: "Sonbahar" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 288, soru: "Güneş hangi yönden doğar?", secenekler: { A: "Batı", B: "Doğu", C: "Güney", D: "Kuzey" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 289, soru: "Atatürk'ün mezarı neresidir?", secenekler: { A: "Topkapı", B: "Dolmabahçe", C: "Anıtkabir", D: "Çankaya" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 290, soru: "Ekmek neyden yapılır?", secenekler: { A: "Tuz", B: "Pirinç", C: "Un", D: "Şeker" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 291, soru: "Hangi hayvan havlar?", secenekler: { A: "Köpek", B: "Kuş", C: "Balık", D: "Kedi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 292, soru: "Ateş neyle söndürülür?", secenekler: { A: "Odun", B: "Kağıt", C: "Su", D: "Benzin" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 293, soru: "Trafik lambasında hangi renk 'Dur' demektir?", secenekler: { A: "Yeşil", B: "Kırmızı", C: "Sarı", D: "Mavi" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 294, soru: "Hangi organımızla duyarız?", secenekler: { A: "Kulak", B: "Burun", C: "Ağız", D: "Göz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 295, soru: "Süt hangi hayvandan elde edilir?", secenekler: { A: "İnek", B: "Balık", C: "Kuş", D: "Tavuk" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 296, soru: "Yumurtayı hangi hayvan verir?", secenekler: { A: "Köpek", B: "İnek", C: "Koyun", D: "Tavuk" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 297, soru: "Kaç tane mevsim vardır?", secenekler: { A: "5", B: "4", C: "3", D: "12" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 298, soru: "Balığı kim yapar?", secenekler: { A: "Tavuk", B: "Arı (Bal yapar, balık değil)", C: "Arı", D: "İnek" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 299, soru: "Hangi gezegende yaşıyoruz?", secenekler: { A: "Mars", B: "Ay", C: "Güneş", D: "Dünya" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 300, soru: "Geceleri gökyüzünde ne görürüz?", secenekler: { A: "Gökkuşağı", B: "Bulutlar", C: "Ay ve Yıldızlar", D: "Güneş" }, dogruCevap: "C" },     // 351-550: Önemli Yerler (Türkiye ve Dünya)
    { seviye: 371, kategori: "Genel Kültür", soru: "İstanbul'un en yüksek noktası kabul edilen tepe hangisidir?", secenekler: { A: "Piyer Loti", B: "Aydos Tepesi", C: "Çamlıca Tepesi", D: "Yuşa Tepesi" }, dogruCevap: "B" },
    { seviye: 372, kategori: "Genel Kültür", soru: "Edirne'deki Mimar Sinan'ın 'Ustalık Eserim' dediği yapı?", secenekler: { A: "Şehzade Camii", B: "Süleymaniye Camii", C: "Üç Şerefeli Cami", D: "Selimiye Camii" }, dogruCevap: "D" },
    { seviye: 373, kategori: "Genel Kültür", soru: "Bursa'nın simgesi olan tarihi cami?", secenekler: { A: "Yeşil Cami", B: "Emir Sultan", C: "Muradiye", D: "Ulu Cami" }, dogruCevap: "D" },
    { seviye: 374, kategori: "Genel Kültür", soru: "İzmir'in sembolü olan tarihi yapı?", secenekler: { A: "Asansör", B: "Kadifekale", C: "Kordon", D: "Saat Kulesi" }, dogruCevap: "D" },
    { seviye: 375, kategori: "Genel Kültür", soru: "Antalya'da bulunan dünyanın en iyi korunmuş antik tiyatrolarından biri?", secenekler: { A: "Termessos", B: "Aspendos", C: "Perge", D: "Phaselis" }, dogruCevap: "B" },
    { seviye: 376, kategori: "Genel Kültür", soru: "Muğla'nın Bodrum ilçesindeki antik dünyanın yedi harikasından biri?", secenekler: { A: "Rodos Heykeli", B: "Zeus Heykeli", C: "Halikarnas Mozolesi", D: "Artemis Tapınağı" }, dogruCevap: "C" },
    { seviye: 377, kategori: "Genel Kültür", soru: "Trabzon'da dik bir yamaca kurulu tarihi manastır?", secenekler: { A: "Vazelon Manastırı", B: "Mor Gabriel", C: "Sümela Manastırı", D: "Akdamar" }, dogruCevap: "C" },
    { seviye: 378, kategori: "Genel Kültür", soru: "Van Gölü üzerinde bulunan ve Ermeni kilisesiyle ünlü ada?", secenekler: { A: "Adır Adası", B: "Akdamar Adası", C: "Çarpanak Adası", D: "Kuş Adası" }, dogruCevap: "B" },
    { seviye: 379, kategori: "Genel Kültür", soru: "Denizli'deki beyaz travertenleriyle ünlü doğal güzellik?", secenekler: { A: "Pamukkale", B: "Laodikeia", C: "Afrodisias", D: "Hierapolis" }, dogruCevap: "A" },
    { seviye: 380, kategori: "Genel Kültür", soru: "Nevşehir'de peri bacalarıyla ünlü bölge?", secenekler: { A: "Kapadokya", B: "Ihlara", C: "Derinkuyu", D: "Kaymaklı" }, dogruCevap: "A" },
    { seviye: 381, kategori: "Genel Kültür", soru: "Adıyaman'daki dev heykellerin bulunduğu dağ?", secenekler: { A: "Erciyes Dağı", B: "Süphan Dağı", C: "Cudi Dağı", D: "Nemrut Dağı" }, dogruCevap: "D" },
    { seviye: 382, kategori: "Genel Kültür", soru: "Çanakkale'de bulunan ve Homeros'un İlyada destanına konu olan antik kent?", secenekler: { A: "Parion", B: "Truva", C: "Assos", D: "Alexandria Troas" }, dogruCevap: "B" },
    { seviye: 383, kategori: "Genel Kültür", soru: "Şanlıurfa'da bulunan 'Tarihin Sıfır Noktası' olarak bilinen yer?", secenekler: { A: "Balıklıgöl", B: "Göbeklitepe", C: "Harran", D: "Halfeti" }, dogruCevap: "B" },
    { seviye: 384, kategori: "Genel Kültür", soru: "Mardin'in simgesi olan ve Mezopotamya ovasına bakan yapı?", secenekler: { A: "Kasımiye Medresesi", B: "Ulu Cami", C: "Deyrulzafaran", D: "Zinciriye Medresesi" }, dogruCevap: "A" },
    { seviye: 385, kategori: "Genel Kültür", soru: "Erzurum'da Selçuklu döneminden kalan simge yapı?", secenekler: { A: "Üç Kümbetler", B: "Çifte Minareli Medrese", C: "Yakutiye Medresesi", D: "Aziziye Tabyası" }, dogruCevap: "B" },
    { seviye: 386, kategori: "Genel Kültür", soru: "Sivas'taki UNESCO listesinde yer alan tıp merkezi ve cami?", secenekler: { A: "Gök Medrese", B: "Divriği Ulu Cami ve Darüşşifası", C: "Şifaiye Medresesi", D: "Buruciye Medresesi" }, dogruCevap: "B" },
    { seviye: 387, kategori: "Genel Kültür", soru: "Kars yakınlarındaki tarihi İpekyolu şehri kalıntıları?", secenekler: { A: "Çıldır", B: "İshak Paşa", C: "Ani Harabeleri", D: "Sarıkamış" }, dogruCevap: "C" },
    { seviye: 388, kategori: "Genel Kültür", soru: "Ağrı'nın Doğubayazıt ilçesindeki görkemli saray?", secenekler: { A: "Yıldız Sarayı", B: "Dolmabahçe Sarayı", C: "Topkapı Sarayı", D: "İshak Paşa Sarayı" }, dogruCevap: "D" },
    { seviye: 389, kategori: "Genel Kültür", soru: "Karabük'te tarihi konaklarıyla ünlü ilçe?", secenekler: { A: "Safranbolu", B: "Ovacık", C: "Yenice", D: "Eflani" }, dogruCevap: "A" },
    { seviye: 390, kategori: "Genel Kültür", soru: "Amasya'nın içinden geçen nehrin kenarındaki tarihi evler?", secenekler: { A: "Yalıboyu Evleri", B: "Odunpazarı Evleri", C: "Beypazarı Evleri", D: "Tarihi Amasya Evleri" }, dogruCevap: "A" },
    { seviye: 391, kategori: "Genel Kültür", soru: "Bolu'da dört mevsim güzelliğiyle bilinen göl?", secenekler: { A: "Abant Gölü", B: "Gölcük", C: "Sünnet Gölü", D: "Yedigöller" }, dogruCevap: "A" },
    { seviye: 392, kategori: "Genel Kültür", soru: "Rize'de bulunan ve Türkiye'nin en ünlü yaylası?", secenekler: { A: "Ayder Yaylası", B: "Anzer Yaylası", C: "Gito Yaylası", D: "Pokut Yaylası" }, dogruCevap: "A" },
    { seviye: 393, kategori: "Genel Kültür", soru: "Artvin'de bulunan ve 'Türkiye'nin saklı cenneti' denilen göl?", secenekler: { A: "Nemrut Gölü", B: "Karagöl", C: "Tortum Gölü", D: "Çıldır Gölü" }, dogruCevap: "B" },
    { seviye: 394, kategori: "Genel Kültür", soru: "Isparta'nın lavanta bahçeleriyle ünlü köyü?", secenekler: { A: "Aksu", B: "Eğirdir", C: "Yalvaç", D: "Kuyucak" }, dogruCevap: "D" },
    { seviye: 395, kategori: "Genel Kültür", soru: "Burdur'daki 'Türkiye'nin Maldivleri' olarak bilinen göl?", secenekler: { A: "Karataş Gölü", B: "Salda Gölü", C: "Burdur Gölü", D: "Yarışlı Gölü" }, dogruCevap: "B" },
    { seviye: 396, kategori: "Genel Kültür", soru: "Kastamonu'daki devasa kanyon?", secenekler: { A: "Valla Kanyonu", B: "Ihlara Vadisi", C: "Karanlık Kanyon", D: "Saklıkent" }, dogruCevap: "A" },
    { seviye: 397, kategori: "Genel Kültür", soru: "Uşak'ta bulunan dünyanın en uzun kanyonlarından biri?", secenekler: { A: "İncesu", B: "Şahinkaya", C: "Ulubey Kanyonu", D: "Köprülü Kanyon" }, dogruCevap: "C" },
    { seviye: 398, kategori: "Genel Kültür", soru: "Mersin'deki doğal oluşum çukurları?", secenekler: { A: "Gilindire", B: "Astım Mağarası", C: "Cennet ve Cehennem", D: "Narlıkuyu" }, dogruCevap: "C" },
    { seviye: 399, kategori: "Genel Kültür", soru: "Hatay'daki dünyanın ilk mağara kilisesi?", secenekler: { A: "St. Pierre Kilisesi", B: "Akdamar", C: "St. Nicolas", D: "Sümela" }, dogruCevap: "A" },
    { seviye: 400, kategori: "Genel Kültür", soru: "Gaziantep'teki dünyanın en büyük mozaik müzelerinden biri?", secenekler: { A: "Efes Müzesi", B: "Hatay Arkeoloji", C: "Antalya Müzesi", D: "Zeugma Mozaik Müzesi" }, dogruCevap: "D" },
    { seviye: 451, kategori: "Genel Kültür", soru: "İstanbul'da Galata semtinde bulunan tarihi kule?", secenekler: { A: "Kız Kulesi", B: "Adalet Kulesi", C: "Beyazıt Kulesi", D: "Galata Kulesi" }, dogruCevap: "D" },
    { seviye: 453, kategori: "Genel Kültür", soru: "Mimar Sinan'ın İstanbul'daki en görkemli eseri hangisidir?", secenekler: { A: "Mihrimah Sultan", B: "Süleymaniye Camii", C: "Selimiye Camii", D: "Şehzade Camii" }, dogruCevap: "B" },
    { seviye: 455, kategori: "Genel Kültür", soru: "İstanbul'un fethi için Fatih Sultan Mehmet tarafından yaptırılan hisar?", secenekler: { A: "Kilitbahir", B: "Anadolu Hisarı", C: "Yedikule Zindanları", D: "Rumeli Hisarı" }, dogruCevap: "D" },
    { seviye: 456, kategori: "Genel Kültür", soru: "Yıldırım Bayezid tarafından yaptırılan İstanbul'daki ilk hisar?", secenekler: { A: "Yoros Kalesi", B: "Anadolu Hisarı", C: "Aydos Kalesi", D: "Rumeli Hisarı" }, dogruCevap: "B" },
    { seviye: 457, kategori: "Genel Kültür", soru: "İstanbul'da Bizans döneminden kalan dev sarnıç?", secenekler: { A: "Şerefiye Sarnıcı", B: "Yerebatan Sarnıcı", C: "Binbirdirek Sarnıcı", D: "Theodosius Sarnıcı" }, dogruCevap: "B" },
    { seviye: 459, kategori: "Genel Kültür", soru: "İstanbul'un en ünlü meydanı hangisidir?", secenekler: { A: "Beyazıt Meydanı", B: "Sultanahmet Meydanı", C: "Beşiktaş Meydanı", D: "Taksim Meydanı" }, dogruCevap: "D" },
    { seviye: 461, kategori: "Genel Kültür", soru: "Ankara'daki Anadolu'nun geçmişine ışık tutan büyük müze?", secenekler: { A: "Cumhuriyet Müzesi", B: "Etnoğrafya Müzesi", C: "Anadolu Medeniyetleri Müzesi", D: "Kurtuluş Savaşı Müzesi" }, dogruCevap: "C" },
    { seviye: 462, kategori: "Genel Kültür", soru: "Ankara'da Hacı Bayram Veli Türbesi'nin yanında bulunan antik tapınak?", secenekler: { A: "Zeus Tapınağı", B: "Apollo Tapınağı", C: "Artemis Tapınağı", D: "Augustus Tapınağı" }, dogruCevap: "D" },
    { seviye: 463, kategori: "Genel Kültür", soru: "İzmir'de Bergama ilçesinde bulunan antik sağlık merkezi?", secenekler: { A: "Akropol", B: "Bazilika", C: "Kızıl Avlu", D: "Asklepion" }, dogruCevap: "D" },
    { seviye: 464, kategori: "Genel Kültür", soru: "İzmir'in Selçuk ilçesinde bulunan antik dünyanın yedi harikasından biri?", secenekler: { A: "Artemis Tapınağı", B: "Meryem Ana Evi", C: "Celsus Kütüphanesi", D: "Yedi Uyuyanlar" }, dogruCevap: "A" },
    { seviye: 466, kategori: "Genel Kültür", soru: "Antalya'da bulunan ve suları doğrudan denize dökülen şelale?", secenekler: { A: "Düden Şelalesi", B: "Manavgat Şelalesi", C: "Kurşunlu Şelalesi", D: "Uçansu Şelalesi" }, dogruCevap: "A" },
    { seviye: 467, kategori: "Genel Kültür", soru: "Antalya'nın Alanya ilçesindeki ünlü mağara?", secenekler: { A: "Karain Mağarası", B: "Altınbeşik Mağarası", C: "Damlataş Mağarası", D: "Dim Mağarası" }, dogruCevap: "C" },
    { seviye: 468, kategori: "Genel Kültür", soru: "Muğla'nın Fethiye ilçesindeki dünyaca ünlü plaj?", secenekler: { A: "Kelebekler Vadisi", B: "Ölüdeniz", C: "Çalış Plajı", D: "Kabak Koyu" }, dogruCevap: "B" },
    { seviye: 469, kategori: "Genel Kültür", soru: "Muğla'da bulunan ve antik Likya mezarlarıyla ünlü yer?", secenekler: { A: "Patara", B: "Dalyan (Kaunos)", C: "Knidos", D: "Tlos" }, dogruCevap: "B" },
    { seviye: 470, kategori: "Genel Kültür", soru: "Muğla'nın Datça ilçesinde bulunan antik liman kenti?", secenekler: { A: "Stratonikeia", B: "Knidos", C: "Lagina", D: "Euromos" }, dogruCevap: "B" },
    { seviye: 471, kategori: "Genel Kültür", soru: "Aydın'daki antik dönem felsefe ve sanat merkezi?", secenekler: { A: "Priene", B: "Tralleis", C: "Milet", D: "Didim" }, dogruCevap: "C" },
    { seviye: 472, kategori: "Genel Kültür", soru: "Aydın'ın Didim ilçesindeki devasa tapınak?", secenekler: { A: "Artemis Tapınağı", B: "Zeus Tapınağı", C: "Hera Tapınağı", D: "Apollon Tapınağı" }, dogruCevap: "D" },
    { seviye: 473, kategori: "Genel Kültür", soru: "Çanakkale'de Şehitler Abidesi hangi yarımada üzerindedir?", secenekler: { A: "Eceabat", B: "Lapseki", C: "Gelibolu Yarımadası", D: "Biga Yarımadası" }, dogruCevap: "C" },
    { seviye: 474, kategori: "Genel Kültür", soru: "Çanakkale Boğazı'nın en dar noktasındaki kale?", secenekler: { A: "Çimenlik Kalesi", B: "Kilitbahir Kalesi", C: "Seddülbahir", D: "Bigalı Kalesi" }, dogruCevap: "B" },
    { seviye: 475, kategori: "Genel Kültür", soru: "Balıkesir'de Ayvalık açıklarındaki turistik ada?", secenekler: { A: "Avşa Adası", B: "Cunda (Alibey) Adası", C: "Marmara Adası", D: "Paşalimanı" }, dogruCevap: "B" },
    { seviye: 476, kategori: "Genel Kültür", soru: "Bursa'da Osmanlı'nın kuruluş yeri olan tarihi ilçe?", secenekler: { A: "İznik", B: "Mudanya", C: "Osmaneli", D: "Söğüt" }, dogruCevap: "A" },
    { seviye: 477, kategori: "Genel Kültür", soru: "Bursa'da bulunan ve Hristiyanlık için önemli konsil kararlarının alındığı yer?", secenekler: { A: "Trilye", B: "İznik", C: "Cumalıkızık", D: "Gölyazı" }, dogruCevap: "B" },
    { seviye: 478, kategori: "Genel Kültür", soru: "Konya'da Mevlana Müzesi'nin bulunduğu yer?", secenekler: { A: "Meram", B: "Mevlana Dergahı", C: "Alaeddin Tepesi", D: "Karatay" }, dogruCevap: "B" },
    { seviye: 479, kategori: "Genel Kültür", soru: "Konya'daki Selçuklu döneminden kalan görkemli cami?", secenekler: { A: "Selimiye Camii", B: "İplikçi Camii", C: "Alaeddin Camii", D: "Aziziye Camii" }, dogruCevap: "C" },
    { seviye: 480, kategori: "Genel Kültür", soru: "Kayseri'de bulunan İç Anadolu'nun en yüksek dağı?", secenekler: { A: "Yıldız Dağı", B: "Hasan Dağı", C: "Melendiz", D: "Erciyes Dağı" }, dogruCevap: "D" },
    { seviye: 481, kategori: "Genel Kültür", soru: "Niğde'de bulunan ve mimarisiyle ünlü Selçuklu camisi?", secenekler: { A: "Alaeddin Camii", B: "Sungurbey", C: "Dışarı Camii", D: "Paşa Camii" }, dogruCevap: "A" },
    { seviye: 482, kategori: "Genel Kültür", soru: "Aksaray'daki 14 km uzunluğundaki devasa vadi?", secenekler: { A: "Zelve Vadisi", B: "Soğanlı Vadisi", C: "Ihlara Vadisi", D: "Manastır Vadisi" }, dogruCevap: "C" },
    { seviye: 483, kategori: "Genel Kültür", soru: "Eskişehir'de Porsuk Çayı kenarındaki turistik bölge?", secenekler: { A: "Adalar", B: "Sazova", C: "Kentpark", D: "Odunpazarı" }, dogruCevap: "A" },
    { seviye: 484, kategori: "Genel Kültür", soru: "Samsun'da Kurtuluş Savaşı'nın başladığı anı simgeleyen yapı?", secenekler: { A: "İlkadım Anıtı", B: "Gazi Müzesi", C: "Onur Anıtı", D: "Bandırma Vapuru" }, dogruCevap: "C" },
    { seviye: 485, kategori: "Genel Kültür", soru: "Sinop'ta bulunan Türkiye'nin en kuzey noktası?", secenekler: { A: "Hamsilos", B: "Sarıkum", C: "İnceburun", D: "Akliman" }, dogruCevap: "C" },
    { seviye: 486, kategori: "Genel Kültür", soru: "Ordu'da şehri kuşbakışı gören ünlü tepe?", secenekler: { A: "Çamlıca", B: "Yoros", C: "Boztepe", D: "Zigana" }, dogruCevap: "C" },
    { seviye: 487, kategori: "Genel Kültür", soru: "Rize'de Fırtına Deresi üzerinde bulunan tarihi köprülerden biri?", secenekler: { A: "Şenyuva Köprüsü", B: "Hala Köprüsü", C: "Mikron Köprüsü", D: "Taş Köprü" }, dogruCevap: "A" },
    { seviye: 488, kategori: "Genel Kültür", soru: "Tokat'ta bulunan ve 'Dünyanın en görkemli mağaralarından biri' denilen yer?", secenekler: { A: "Ballıca Mağarası", B: "İnsuyu", C: "Karaca Mağarası", D: "Menzil" }, dogruCevap: "A" },
    { seviye: 489, kategori: "Genel Kültür", soru: "Gümüşhane'de bulunan damlataş mağarası?", secenekler: { A: "Karaca Mağarası", B: "Buzluk", C: "Akçakale", D: "Çal Mağarası" }, dogruCevap: "A" },
    { seviye: 490, kategori: "Genel Kültür", soru: "Erzincan'da bulunan ve doğa sporları için ünlü kanyon?", secenekler: { A: "Munzur", B: "Karanlık Kanyon", C: "Eğin", D: "Kemaliye" }, dogruCevap: "B" },
    { seviye: 491, kategori: "Genel Kültür", soru: "Tunceli'de bulunan milli park?", secenekler: { A: "Mercan", B: "Pülümür", C: "Munzur Vadisi Milli Parkı", D: "Ovacık" }, dogruCevap: "C" },
    { seviye: 492, kategori: "Genel Kültür", soru: "Elazığ'da bulunan antik kent kalıntıları?", secenekler: { A: "Keban", B: "Hazar", C: "Palu", D: "Harput" }, dogruCevap: "D" },
    { seviye: 493, kategori: "Genel Kültür", soru: "Diyarbakır'da UNESCO listesinde yer alan tarihi surlar ve?", secenekler: { A: "Hevsel Bahçeleri", B: "Malabadi Köprüsü", C: "On Gözlü Köprü", D: "Ulu Cami" }, dogruCevap: "A" },
    { seviye: 494, kategori: "Genel Kültür", soru: "Diyarbakır ile Batman arasında bulunan tarihi köprü?", secenekler: { A: "Batman Köprüsü", B: "On Gözlü Köprü", C: "Malabadi Köprüsü", D: "Hasankeyf Köprüsü" }, dogruCevap: "C" },
    { seviye: 495, kategori: "Genel Kültür", soru: "Batman'da bulunan ve sular altında kalan antik yerleşim?", secenekler: { A: "Zeynel Bey", B: "Hallan Çemi", C: "Mor Kiryakus", D: "Hasankeyf" }, dogruCevap: "D" },
    { seviye: 496, kategori: "Genel Kültür", soru: "Mardin'in Midyat ilçesindeki ünlü manastır?", secenekler: { A: "Mor Behnam", B: "Deyrulzafaran", C: "Mor Gabriel", D: "Meryem Ana" }, dogruCevap: "C" },
    { seviye: 497, kategori: "Genel Kültür", soru: "Şanlıurfa'da bulunan ve Hz. İbrahim'in ateşe atıldığı yer olduğuna inanılan göl?", secenekler: { A: "Harran", B: "Balıklıgöl", C: "Fırat", D: "Aynzeliha Gölü" }, dogruCevap: "B" },
    { seviye: 498, kategori: "Genel Kültür", soru: "Gaziantep'in simgesi olan tarihi kale?", secenekler: { A: "Ravanda", B: "Rumkale", C: "Tilbaşar", D: "Gaziantep Kalesi" }, dogruCevap: "D" },
    { seviye: 500, kategori: "Genel Kültür", soru: "Kahramanmaraş'ta bulunan meşhur yayla?", secenekler: { A: "Başkonuş Yaylası", B: "Tekir", C: "Yavşan", D: "Ekinözü" }, dogruCevap: "A" },
    { seviye: 536, kategori: "Genel Kültür", soru: "İstanbul'da Adalar içinde en büyüğü hangisidir?", secenekler: { A: "Heybeliada", B: "Burgazada", C: "Büyükada", D: "Kınalıada" }, dogruCevap: "C" },
    { seviye: 537, kategori: "Genel Kültür", soru: "İzmir'de bulunan antik çağın en önemli kütüphanelerinden biri hangisidir?", secenekler: { A: "Celsus Kütüphanesi", B: "Bergama Kütüphanesi", C: "İskenderiye", D: "Hadrian" }, dogruCevap: "A" },
    { seviye: 538, kategori: "Genel Kültür", soru: "Antalya'da bulunan ve Noel Baba olarak bilinen Aziz Nikolaos'un kilisesi nerededir?", secenekler: { A: "Finike", B: "Kalkan", C: "Demre", D: "Kaş" }, dogruCevap: "C" },
    { seviye: 539, kategori: "Genel Kültür", soru: "Muğla'da bulunan ve 'Yeryüzü Cenneti' olarak adlandırılan koy?", secenekler: { A: "Hisarönü", B: "Marmaris", C: "Gökova", D: "Fethiye" }, dogruCevap: "C" },
    { seviye: 540, kategori: "Genel Kültür", soru: "Nevşehir'de bulunan ve yerin 8 kat altına kadar inen antik şehir?", secenekler: { A: "Tatlarin", B: "Derinkuyu Yer altı Şehri", C: "Kaymaklı", D: "Özkonak" }, dogruCevap: "B" },
    { seviye: 541, kategori: "Genel Kültür", soru: "Sivas'taki Divriği Ulu Cami'nin kapısındaki ünlü figür nedir?", secenekler: { A: "Namaz kılan insan gölgesi", B: "Hayat ağacı", C: "Güneş kursu", D: "Çift başlı kartal" }, dogruCevap: "A" },
    { seviye: 542, kategori: "Genel Kültür", soru: "Edirne'de Meriç nehri üzerindeki tarihi köprü?", secenekler: { A: "Meriç Köprüsü", B: "Uzunköprü", C: "Ekmekçizade", D: "Tunca Köprüsü" }, dogruCevap: "A" },
    { seviye: 543, kategori: "Genel Kültür", soru: "Kırklareli'ndeki Türkiye'nin en büyük longoz (subasar) ormanı?", secenekler: { A: "Sarıkum", B: "İğneada Longozu", C: "Acarlar Longozu", D: "Karacabey" }, dogruCevap: "B" },
    { seviye: 544, kategori: "Genel Kültür", soru: "Sakarya'daki Türkiye'nin tek parça en büyük longoz ormanı?", secenekler: { A: "İğneada", B: "Danişment", C: "Acarlar Longozu", D: "Erikli" }, dogruCevap: "C" },
    { seviye: 545, kategori: "Genel Kültür", soru: "Yalova'daki Türkiye'nin ilk canlı ağaç müzesi?", secenekler: { A: "Baltalimanı", B: "Karaca Arboretumu", C: "Atatürk Arboretumu", D: "Nezahat Gökyiğit" }, dogruCevap: "B" },
    { seviye: 546, kategori: "Genel Kültür", soru: "Kocaeli'deki tarihi saat kulesi kimin adına yapılmıştır?", secenekler: { A: "Sultan Reşat", B: "Vahdettin", C: "II. Abdülhamit", D: "Abdülaziz" }, dogruCevap: "C" },
    { seviye: 547, kategori: "Genel Kültür", soru: "Düzce'deki Karadeniz'in Efes'i denilen antik kent?", secenekler: { A: "Tyana", B: "Sagalassos", C: "Prusias ad Hypium", D: "Stratonikeia" }, dogruCevap: "C" },
    { seviye: 548, kategori: "Genel Kültür", soru: "Zonguldak'taki Türkiye'nin ilk geziye açılan mağarası?", secenekler: { A: "Kızılelma", B: "Gökgöl Mağarası", C: "Ilıksu", D: "Cehennemağzı" }, dogruCevap: "D" },
    { seviye: 549, kategori: "Genel Kültür", soru: "Sinop'taki fiyort benzeri oluşumuyla ünlü koy?", secenekler: { A: "İnceburun", B: "Hamsilos Koyu", C: "Akliman", D: "Sarıkum" }, dogruCevap: "B" },
    { seviye: 550, kategori: "Genel Kültür", soru: "Bartın'ın tarihi dokusu ve deniziyle ünlü ilçesi?", secenekler: { A: "Ulus", B: "Kurucaşile", C: "Kozcağız", D: "Amasra" }, dogruCevap: "D" },
    { seviye: 452, kategori: "Genel Kültür", soru: "Boğaz kıyısında bulunan ve Avrupa'nın en lüks saraylarından biri kabul edilen yapı?", secenekler: { A: "Çırağan Sarayı", B: "Yıldız Sarayı", C: "Dolmabahçe Sarayı", D: "Beylerbeyi Sarayı" }, dogruCevap: "C" },
    { seviye: 454, kategori: "Genel Kültür", soru: "Sultan Ahmet tarafından yaptırılan ve 'Mavi Cami' olarak bilinen yapı?", secenekler: { A: "Sultanahmet Camii", B: "Ortaköy Camii", C: "Yeni Cami", D: "Fatih Camii" }, dogruCevap: "A" },
    { seviye: 458, kategori: "Genel Kültür", soru: "Haliç üzerinde bulunan ve Karaköy ile Eminönü'nü bağlayan köprü?", secenekler: { A: "Haliç Köprüsü", B: "Metro Köprüsü", C: "Galata Köprüsü", D: "Unkapanı Köprüsü" }, dogruCevap: "C" },
    { seviye: 499, kategori: "Genel Kültür", soru: "Fırat nehri kıyısındaki yarısı sular altında kalmış ilçe?", secenekler: { A: "Yavuzeli", B: "Nizip", C: "Birecik", D: "Halfeti" }, dogruCevap: "D" },
    { seviye: 551, kategori: "Genel Kültür", soru: "Kütahya'da Osmanlı dönemine ait tarihi çini ve seramik merkezi?", secenekler: { A: "Kütahya Çarşısı", B: "Kütahya Kalesi", C: "Germiyan Konakları", D: "Kütahya Çini Atölyeleri" }, dogruCevap: "D" },
    { seviye: 552, kategori: "Genel Kültür", soru: "Uşak'ta bulunan ve halı dokumacılığıyla ünlü tarihi bölge?", secenekler: { A: "Uşak Halı Merkezi", B: "Banaz", C: "Eşme", D: "Sivaslı" }, dogruCevap: "A" },
    { seviye: 553, kategori: "Genel Kültür", soru: "Manisa'da bulunan ve mesir macunu geleneğiyle ünlü tarihi cami?", secenekler: { A: "Muradiye Camii", B: "Sultan Camii", C: "Hatuniye Camii", D: "Ulu Cami" }, dogruCevap: "B" },
    { seviye: 554, kategori: "Genel Kültür", soru: "Afyonkarahisar'ın simgesi olan ve şehre hakim kayalık tepe?", secenekler: { A: "Afyon Kalesi", B: "Sandıklı Kalesi", C: "İscehisar", D: "Şuhut Kalesi" }, dogruCevap: "A" },
    { seviye: 555, kategori: "Genel Kültür", soru: "Kırşehir'de bulunan ve Ahilik teşkilatının merkezi kabul edilen türbe?", secenekler: { A: "Cacabey Medresesi", B: "Ahi Evran Türbesi", C: "Aşık Paşa Türbesi", D: "Melik Gazi Türbesi" }, dogruCevap: "B" },
    { seviye: 556, kategori: "Genel Kültür", soru: "Yozgat'ta bulunan ve Osmanlı dönemine ait tarihi konak/müze?", secenekler: { A: "Çapanoğlu Camii", B: "Yozgat Kalesi", C: "Nizamoğlu Konağı", D: "Başçavuş Camii" }, dogruCevap: "C" },
    { seviye: 557, kategori: "Genel Kültür", soru: "Çorum'da bulunan ve Hitit uygarlığına ait büyük açık hava müzesi?", secenekler: { A: "Alacahöyük", B: "Boğazköy (Hattuşa)", C: "Şapinuva", D: "Eskiyapar" }, dogruCevap: "B" },
    { seviye: 558, kategori: "Genel Kültür", soru: "Amasya yakınlarındaki ve Pontus Krallığı dönemine ait antik kent kalıntıları?", secenekler: { A: "Amaseia (Amasya Antik Kenti)", B: "Zela", C: "Comana", D: "Gaziura" }, dogruCevap: "A" }
);
