window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Türk Futbol Tarihi ve Süper Lig
    { seviye: 1, kategori: "Spor", soru: "UEFA Kupası'nı kazanan tek Türk takımı hangisidir?", secenekler: { A: "Fenerbahçe", B: "Beşiktaş", C: "Trabzonspor", D: "Galatasaray" }, dogruCevap: "D" },
    { seviye: 2, kategori: "Spor", soru: "Süper Lig tarihinde en çok şampiyonluk yaşayan teknik direktör?", secenekler: { A: "Mustafa Denizli", B: "Fatih Terim", C: "Şenol Güneş", D: "Okan Buruk" }, dogruCevap: "B" },
    { seviye: 3, kategori: "Spor", soru: "Süper Lig'in 'Taçsız Kral' lakaplı efsane ismi kimdir?", secenekler: { A: "Metin Oktay", B: "Tanju Çolak", C: "Sergen Yalçın", D: "Hakan Şükür" }, dogruCevap: "A" },
    { seviye: 4, kategori: "Spor", soru: "Fenerbahçe'nin 'Ordinaryüs' lakaplı unutulmaz futbolcusu kimdir?", secenekler: { A: "Rıdvan Dilmen", B: "Alex de Souza", C: "Can Bartu", D: "Lefter Küçükandonyadis" }, dogruCevap: "D" },
    { seviye: 5, kategori: "Spor", soru: "Beşiktaş'ın simgesi olan 'Kara Kartal' lakabı nereden gelir?", secenekler: { A: "Bir balıkçının sözünden", B: "Kulüp tüzüğünden", C: "Bir taraftarın tezahüratından", D: "Kurucu başkanın isteğinden" }, dogruCevap: "C" },
    { seviye: 6, kategori: "Spor", soru: "Süper Lig tarihinde bir sezonda en çok gol atan (39 gol) futbolcu?", secenekler: { A: "Enner Valencia", B: "Tanju Çolak", C: "Mbaye Diagne", D: "Metin Oktay" }, dogruCevap: "B" },
    { seviye: 7, kategori: "Spor", soru: "Türk Milli Takımı, 2002 Dünya Kupası'nda hangi ülkeyi yenerek 3. olmuştur?", secenekler: { A: "Güney Kore", B: "Brezilya", C: "Senegal", D: "Japonya" }, dogruCevap: "A" },
    { seviye: 8, kategori: "Spor", soru: "Avrupa şampiyonalarında (Euro 2008) Türkiye yarı finalde hangi ülkeye elenmiştir?", secenekler: { A: "Hırvatistan", B: "Çek Cumhuriyeti", C: "Portekiz", D: "Almanya" }, dogruCevap: "D" },
    { seviye: 9, kategori: "Spor", soru: "A Milli Takım formasıyla en çok gol atan futbolcu kimdir?", secenekler: { A: "Cenk Tosun", B: "Hakan Şükür", C: "Burak Yılmaz", D: "Nihat Kahveci" }, dogruCevap: "B" },
    { seviye: 10, kategori: "Spor", soru: "Trabzonspor'un Süper Lig'deki ilk şampiyonluk dönemi hangi yıllar arasındadır?", secenekler: { A: "1990'ler", B: "2000'ler", C: "1970'ler", D: "1980'ler" }, dogruCevap: "C" },
    { seviye: 11, kategori: "Spor", soru: "Hem basketbol hem futbol milli takımında forma giyen efsane sporcu?", secenekler: { A: "Turgay Şeren", B: "Lefter", C: "Can Bartu", D: "Metin Oktay" }, dogruCevap: "C" },
    { seviye: 12, kategori: "Spor", soru: "Berlin Kaplanı lakaplı efsane Türk kaleci kimdir?", secenekler: { A: "Volkan Demirel", B: "Turgay Şeren", C: "Rüştü Reçber", D: "Muslera" }, dogruCevap: "B" },
    { seviye: 13, kategori: "Spor", soru: "Arda Güler hangi dünya devine transfer olarak göğsümüzü kabartmıştır?", secenekler: { A: "Real Madrid", B: "Bayern Münih", C: "Manchester City", D: "Barcelona" }, dogruCevap: "A" },
    { seviye: 14, kategori: "Spor", soru: "Süper Lig'de 'Dört Büyükler' dışında şampiyon olan ilk takım?", secenekler: { A: "Başakşehir", B: "Göztepe", C: "Bursaspor", D: "Eskişehirspor" }, dogruCevap: "C" },
    { seviye: 15, kategori: "Spor", soru: "A Milli Futbol Takımı'nın ilk maçı hangi ülkeye karşıdır?", secenekler: { A: "Romanya", B: "Yunanistan", C: "Bulgaristan", D: "İtalya" }, dogruCevap: "A" },
    { seviye: 16, kategori: "Spor", soru: "Süper Lig tarihinde '100'ler kulübü'ne giren ilk futbolcu?", secenekler: { A: "Hakan Şükür", B: "Metin Oktay", C: "Tanju Çolak", D: "Lefter" }, dogruCevap: "B" },
    { seviye: 17, kategori: "Spor", soru: "Beşiktaş'ın efsane başkanı 'Süleyman Seba' kaç yıl başkanlık yapmıştır?", secenekler: { A: "20", B: "10", C: "16", D: "8" }, dogruCevap: "C" },
    { seviye: 18, kategori: "Spor", soru: "Galatasaray'ın efsane kalecisi 'Muslera' hangi ülkelidir?", secenekler: { A: "Uruguay", B: "Şili", C: "Arjantin", D: "Brezilya" }, dogruCevap: "A" },
    { seviye: 19, kategori: "Spor", soru: "Fenerbahçe'nin stadyumu Şükrü Saracoğlu hangi semttedir?", secenekler: { A: "Şişli", B: "Beşiktaş", C: "Bakırköy", D: "Kadıköy" }, dogruCevap: "D" },
    { seviye: 20, kategori: "Spor", soru: "Türkiye Kupası'nı en çok kazanan takım hangisidir?", secenekler: { A: "Trabzonspor", B: "Fenerbahçe", C: "Galatasaray", D: "Beşiktaş" }, dogruCevap: "C" },

    // 26-50: Türk Güreşi, Halter ve Olimpiyat Başarıları
    { seviye: 26, kategori: "Spor", soru: "Olimpiyat tarihinde Türkiye'ye ilk altın madalyayı kazanan sporcu?", secenekler: { A: "Mete Gazoz", B: "Hamza Yerlikaya", C: "Yaşar Erkan", D: "Naim Süleymanoğlu" }, dogruCevap: "C" },
    { seviye: 27, kategori: "Spor", soru: "Cep Herkülü lakaplı, 3 kez olimpiyat şampiyonu haltercimiz?", secenekler: { A: "Taner Sağır", B: "Naim Süleymanoğlu", C: "Halil Mutlu", D: "Sedat Artunç" }, dogruCevap: "B" },
    { seviye: 28, kategori: "Spor", soru: "Asrın Güreşçisi unvanına sahip sporcumuz kimdir?", secenekler: { A: "Taha Akgül", B: "Rıza Kayaalp", C: "Mahmut Demir", D: "Hamza Yerlikaya" }, dogruCevap: "D" },
    { seviye: 29, kategori: "Spor", soru: "Mete Gazoz hangi branşta Olimpiyat Şampiyonu olmuştur?", secenekler: { A: "Jimnastik", B: "Okçuluk", C: "Eskrim", D: "Atıcılık" }, dogruCevap: "B" },
    { seviye: 30, kategori: "Spor", soru: "Kırkpınar Yağlı Güreşleri'nde üst üste 3 kez başpehlivan olana ne verilir?", secenekler: { A: "Gümüş Madalya", B: "Kupa", C: "Pehlivan Beratı", D: "Altın Kemer" }, dogruCevap: "D" },
    { seviye: 31, kategori: "Spor", soru: "Dünya ve Avrupa şampiyonu kadın boksörümüz kimdir?", secenekler: { A: "Busenaz Sürmeneli", B: "İrem Yaman", C: "Nurcan Taylan", D: "Buse Naz Çakıroğlu" }, dogruCevap: "A" },
    { seviye: 32, kategori: "Spor", soru: "Hangi sporcumuz 'Demir Bilek' olarak bilinir?", secenekler: { A: "Adalı Halil", B: "Haydar Pazarlı", C: "Yaşar Doğu", D: "Koca Yusuf" }, dogruCevap: "B" },
    { seviye: 33, kategori: "Spor", soru: "Türk spor tarihinde ilk dünya şampiyonu kadın halterci?", secenekler: { A: "Nurcan Taylan", B: "Sibel Özkan", C: "Aylin Daşdelen", D: "Şule Şahbaz" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Spor", soru: "Rıza Kayaalp hangi spor dalında rekor sayıda Avrupa şampiyonu olmuştur?", secenekler: { A: "Tekvando", B: "Güreş", C: "Boks", D: "Halter" }, dogruCevap: "B" },
    { seviye: 35, kategori: "Spor", soru: "Olimpiyatlarda madalya kazanan ilk Türk kadın sporcu kimdir?", secenekler: { A: "Yasemin Adar", B: "Hamide Bıççın", C: "Hülya Şenyurt", D: "Nurcan Taylan" }, dogruCevap: "C" },
    { seviye: 36, kategori: "Spor", soru: "Koca Yusuf hangi güreş türüyle dünyada ün salmıştır?", secenekler: { A: "Yağlı Güreş / Karakucak", B: "Serbest Stil", C: "Sambo", D: "Grekoromen" }, dogruCevap: "A" },
    { seviye: 37, kategori: "Spor", soru: "Türkiye'nin kış olimpiyatlarındaki ilk sporcusu hangi branştadır?", secenekler: { A: "Buz Hokeyi", B: "Körling", C: "Kayak", D: "Buz Pateni" }, dogruCevap: "C" },
    { seviye: 38, kategori: "Spor", soru: "Tekvandoda Olimpiyat ikincisi olan ünlü kadın sporcumuz?", secenekler: { A: "Nur Tatar", B: "Merve Dinçel", C: "Hatice Kübra İlgün", D: "Servet Tazegül" }, dogruCevap: "A" },
    { seviye: 39, kategori: "Spor", soru: "Paralimpik oyunlarda altın madalya alan okçumuz?", secenekler: { A: "Yiğit Caner", B: "Bahattin Hekimoğlu", C: "Öznur Cüre", D: "Gizem Girişmen" }, dogruCevap: "D" },
    { seviye: 40, kategori: "Spor", soru: "Tarihi Elmalı Yağlı Güreşleri nerede düzenlenir?", secenekler: { A: "Edirne", B: "Antalya", C: "Balıkesir", D: "Manisa" }, dogruCevap: "B" },

    // 51-75: Türk Basketbolu ve Voleybolu
    { seviye: 51, kategori: "Spor", soru: "Türkiye Kadın Milli Voleybol Takımı'nın lakabı nedir?", secenekler: { A: "12 Dev Adam", B: "Filenin Sultanları", C: "Potanın Perileri", D: "Sultanlar" }, dogruCevap: "B" },
    { seviye: 52, kategori: "Spor", soru: "EuroLeague şampiyonu olan ilk Türk erkek basketbol takımı?", secenekler: { A: "Galatasaray", B: "Anadolu Efes", C: "Fenerbahçe", D: "Beşiktaş" }, dogruCevap: "C" },
    { seviye: 53, kategori: "Spor", soru: "Basketbolda '12 Dev Adam' lakabı hangi turnuvada verilmiştir?", secenekler: { A: "2006 Dünya Şampiyonası", B: "2010 Dünya Şampiyonası", C: "2001 Avrupa Şampiyonası", D: "1999 Avrupa Şampiyonası" }, dogruCevap: "C" },
    { seviye: 54, kategori: "Spor", soru: "NBA'de şampiyonluk yüzüğü takan ilk Türk basketbolcu?", secenekler: { A: "Alperen Şengün", B: "Mehmet Okur", C: "Cedi Osman", D: "Hidayet Türkoğlu" }, dogruCevap: "B" },
    { seviye: 55, kategori: "Spor", soru: "Eczacıbaşı ve VakıfBank hangi branşta dünya çapında başarıya sahiptir?", secenekler: { A: "Basketbol", B: "Yüzme", C: "Hentbol", D: "Voleybol" }, dogruCevap: "D" },
    { seviye: 56, kategori: "Spor", soru: "Dünya voleybolunda 'En Değerli Oyuncu' (MVP) seçilen milli sporcumuz?", secenekler: { A: "Zehra Güneş", B: "Gizem Örge", C: "Eda Erdem", D: "Melissa Vargas" }, dogruCevap: "D" },
    { seviye: 57, kategori: "Spor", soru: "NBA'de bir maçta en çok sayı atan Türk oyuncu (rekor)?", secenekler: { A: "Hidayet Türkoğlu", B: "Mehmet Okur", C: "Ersan İlyasova", D: "Alperen Şengün" }, dogruCevap: "D" },
    { seviye: 58, kategori: "Spor", soru: "Fenerbahçe Kadın Basketbol Takımı'nın Avrupa şampiyonluğu var mıdır?", secenekler: { A: "Evet (EuroLeague)", B: "Sadece EuroCup", C: "Sadece Türkiye Kupası", D: "Hayır" }, dogruCevap: "A" },
    { seviye: 59, kategori: "Spor", soru: "A Milli Erkek Basketbol Takımı, 2010 Dünya Şampiyonası'nda kaçıncı olmuştur?", secenekler: { A: "Dördüncü", B: "Üçüncü", C: "İkinci", D: "Şampiyon" }, dogruCevap: "C" },
    { seviye: 60, kategori: "Spor", soru: "Milli voleybolcumuz Eda Erdem'in heykeli hangi stadın önüne dikilmiştir?", secenekler: { A: "Sinan Erdem", B: "Ülker Stadyumu", C: "Burhan Felek", D: "Vakıfbank Spor Sarayı" }, dogruCevap: "B" },
    { seviye: 61, kategori: "Spor", soru: "Avrupa şampiyonu olan ilk Türk voleybol takımı?", secenekler: { A: "Arkas", B: "Vakıfbank", C: "Eczacıbaşı", D: "Halkbank" }, dogruCevap: "C" },
    { seviye: 62, kategori: "Spor", soru: "Potanın Perileri hangi milli takıma verilen isimdir?", secenekler: { A: "Kadın Hentbol", B: "Kadın Futbol", C: "Kadın Voleybol", D: "Kadın Basketbol" }, dogruCevap: "D" },
    { seviye: 63, kategori: "Spor", soru: "Türk basketbolunun 'Profesör' lakaplı efsane koçu kimdir?", secenekler: { A: "Çetin Yılmaz", B: "Aydın Örs", C: "Ergin Ataman", D: "Erman Kunter" }, dogruCevap: "B" },
    { seviye: 64, kategori: "Spor", soru: "Ergin Ataman, Panathinaikos'tan önce hangi Türk takımıyla 2 EuroLeague kazandı?", secenekler: { A: "Beşiktaş", B: "Galatasaray", C: "Fenerbahçe", D: "Anadolu Efes" }, dogruCevap: "D" },
    { seviye: 65, kategori: "Spor", soru: "Hidayet Türkoğlu NBA'de hangi takımda efsaneleşmiştir?", secenekler: { A: "L.A. Clippers", B: "Sacramento Kings", C: "Toronto Raptors", D: "Orlando Magic" }, dogruCevap: "D" },
    { seviye: 66, kategori: "Spor", soru: "Neslihan Demir hangi branşın 'Demir Leydi'si olarak bilinir?", secenekler: { A: "Boks", B: "Tenis", C: "Eskrim", D: "Voleybol" }, dogruCevap: "D" },
    { seviye: 67, kategori: "Spor", soru: "Vakıfbank Kadın Voleybol Takımı kaç kez CEV Şampiyonlar Ligi şampiyonu olmuştur?", secenekler: { A: "3", B: "1", C: "6", D: "2" }, dogruCevap: "C" },
    { seviye: 68, kategori: "Spor", soru: "Gözde Kırdar hangi takımın sembol voleybolcusudur?", secenekler: { A: "Fenerbahçe", B: "Eczacıbaşı", C: "Galatasaray", D: "Vakıfbank" }, dogruCevap: "D" },
    { seviye: 69, kategori: "Spor", soru: "Dünya Şampiyonası'nda 'Sayı Kralı' olan Türk basketbolcu?", secenekler: { A: "Ömer Onan", B: "Harun Erdenay", C: "İbrahim Kutluay", D: "Erman Kunter" }, dogruCevap: "D" },
    { seviye: 70, kategori: "Spor", soru: "Türkiye'nin en eski spor kulübü hangisidir?", secenekler: { A: "Beşiktaş (1903)", B: "Galatasaray (1905)", C: "İstanbulspor", D: "Fenerbahçe (1907)" }, dogruCevap: "A" },

    // 76-100: Dünya Sporundan Seçmeler
    { seviye: 76, kategori: "Spor", soru: "Dünya Kupası'nı en çok kazanan ülke hangisidir?", secenekler: { A: "Brezilya", B: "Almanya", C: "Arjantin", D: "İtalya" }, dogruCevap: "A" },
    { seviye: 77, kategori: "Spor", soru: "Ballon d'Or ödülünü en çok kazanan futbolcu kimdir?", secenekler: { A: "Zidane", B: "C. Ronaldo", C: "Pele", D: "Lionel Messi" }, dogruCevap: "D" },
    { seviye: 78, kategori: "Spor", soru: "Olimpiyat halkalarında toplam kaç renk bulunur?", secenekler: { A: "6", B: "4", C: "7", D: "5" }, dogruCevap: "D" },
    { seviye: 79, kategori: "Spor", soru: "Basketbolun mucidi kimdir?", secenekler: { A: "Phil Jackson", B: "James Naismith", C: "Michael Jordan", D: "David Stern" }, dogruCevap: "B" },
    { seviye: 80, kategori: "Spor", soru: "Maraton koşusunun mesafesi ne kadardır?", secenekler: { A: "21.000 m", B: "40.000 m", C: "42.195 m", D: "50.000 m" }, dogruCevap: "C" },
    { seviye: 81, kategori: "Spor", soru: "Formula 1'de 7 dünya şampiyonluğu olan pilotlar?", secenekler: { A: "Verstappen - Leclerc", B: "Senna - Prost", C: "Schumacher - Hamilton", D: "Vettel - Alonso" }, dogruCevap: "C" },
    { seviye: 82, kategori: "Spor", soru: "Teniste 'Toprak Kort' kralı kimdir?", secenekler: { A: "Roger Federer", B: "Carlos Alcaraz", C: "Novak Djokovic", D: "Rafael Nadal" }, dogruCevap: "D" },
    { seviye: 83, kategori: "Spor", soru: "NBA tarihinin en çok sayı atan oyuncusu?", secenekler: { A: "LeBron James", B: "Kobe Bryant", C: "Michael Jordan", D: "Kareem Abdul-Jabbar" }, dogruCevap: "A" },
    { seviye: 84, kategori: "Spor", soru: "Usain Bolt'un 100 metre dünya rekoru derecesi nedir?", secenekler: { A: "9.80", B: "9.72", C: "9.58", D: "9.69" }, dogruCevap: "C" },
    { seviye: 85, kategori: "Spor", soru: "Sumo güreşi hangi ülkenin milli sporudur?", secenekler: { A: "Japonya", B: "Moğolistan", C: "Güney Kore", D: "Çin" }, dogruCevap: "A" },
    { seviye: 86, kategori: "Spor", soru: "Modern Olimpiyatlar ilk kez nerede yapılmıştır?", secenekler: { A: "Roma", B: "Atina", C: "Londra", D: "Paris" }, dogruCevap: "B" },
    { seviye: 87, kategori: "Spor", soru: "Boksör Muhammed Ali'nin eski adı nedir?", secenekler: { A: "Cassius Clay", B: "Joe Frazier", C: "George Foreman", D: "Mike Tyson" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Spor", soru: "Hangi ülke 2022 Dünya Kupası şampiyonu olmuştur?", secenekler: { A: "Hırvatistan", B: "Fransa", C: "Arjantin", D: "Fas" }, dogruCevap: "C" },
    { seviye: 89, kategori: "Spor", soru: "Teniste bir yıl içinde tüm Grand Slamleri kazanmaya ne denir?", secenekler: { A: "Golden Slam", B: "Grand Slam", C: "Masters", D: "Tie-Break" }, dogruCevap: "B" },
    { seviye: 90, kategori: "Spor", soru: "Olimpiyat meşalesi nerede yakılır?", secenekler: { A: "Olimpiya Dağı", B: "Atina Stadyumu", C: "Ev sahibi şehir", D: "Roma" }, dogruCevap: "A" },
    { seviye: 91, kategori: "Spor", soru: "Futbolda sarı ve kırmızı kart ilk kez hangi yıl kullanıldı?", secenekler: { A: "1966", B: "1970", C: "1960", D: "1974" }, dogruCevap: "B" },
    { seviye: 92, kategori: "Spor", soru: "Michael Phelps hangi branşta rekor madalya sahibidir?", secenekler: { A: "Kürek", B: "Jimnastik", C: "Atletizm", D: "Yüzme" }, dogruCevap: "D" },
    { seviye: 93, kategori: "Spor", soru: "Tour de France (Fransa Bisiklet Turu) lideri hangi renk mayo giyer?", secenekler: { A: "Yeşil", B: "Kırmızı", C: "Sarı", D: "Pembe" }, dogruCevap: "C" },
    { seviye: 94, kategori: "Spor", soru: "Badminton topuna ne ad verilir?", secenekler: { A: "Birdie", B: "Shuttlecock", C: "Puck", D: "A ve C" }, dogruCevap: "D" },
    { seviye: 95, kategori: "Spor", soru: "Amerikan futbolu final maçına ne ad verilir?", secenekler: { A: "NBA Finals", B: "Stanley Cup", C: "World Series", D: "Super Bowl" }, dogruCevap: "D" },
    { seviye: 96, kategori: "Spor", soru: "Eskrimde kullanılan üç silahtan biri?", secenekler: { A: "Ok", B: "Flöre", C: "Mızrak", D: "Süngü" }, dogruCevap: "B" },
    { seviye: 97, kategori: "Spor", soru: "Tiger Woods hangi sporda efsanedir?", secenekler: { A: "Tenis", B: "Golf", C: "Yüzme", D: "Bilardo" }, dogruCevap: "B" },
    { seviye: 98, kategori: "Spor", soru: "Körling (Curling) sporu nerede oynanır?", secenekler: { A: "Su", B: "Buz", C: "Kum", D: "Çim" }, dogruCevap: "B" },
    { seviye: 99, kategori: "Spor", soru: "Dünya Kupası tarihinde en çok gol atan oyuncu?", secenekler: { A: "Pele", B: "Miroslav Klose", C: "Messi", D: "Ronaldo" }, dogruCevap: "B" },
    { seviye: 100, kategori: "Spor", soru: "Satrançta bir maçta yapılabilecek en kısa mat kaç hamledir?", secenekler: { A: "2", B: "1", C: "4", D: "3" }, dogruCevap: "A" }, 
    // 101-150: Karışık Spor Dalları, Rekorlar ve Olimpiyatlar
    { seviye: 101, kategori: "Spor", soru: "Modern Olimpiyat Oyunları ilk kez hangi şehirde düzenlenmiştir?", secenekler: { A: "Atina", B: "Londra", C: "Roma", D: "Paris" }, dogruCevap: "A" },
    { seviye: 102, kategori: "Spor", soru: "Voleybolda sahada her takımdan kaç oyuncu bulunur?", secenekler: { A: "6", B: "5", C: "7", D: "11" }, dogruCevap: "A" },
    { seviye: 103, kategori: "Spor", soru: "Hangi ülke 2022 FIFA Dünya Kupası şampiyonu olmuştur?", secenekler: { A: "Arjantin", B: "Brezilya", C: "Fas", D: "Fransa" }, dogruCevap: "A" },
    { seviye: 104, kategori: "Spor", soru: "Teniste 'Grand Slam' kazanan ilk Türk tenisçi kimdir (Gençler kategorisi)?", secenekler: { A: "Melis Sezer", B: "İpek Soylu", C: "Çağla Büyükakçay", D: "Marsel İlhan" }, dogruCevap: "B" },
    { seviye: 105, kategori: "Spor", soru: "Basketbolda bir periyot NBA standartlarında kaç dakikadır?", secenekler: { A: "15", B: "12", C: "8", D: "10" }, dogruCevap: "B" },
    { seviye: 106, kategori: "Spor", soru: "Hangi spor dalında 'triple-double' terimi kullanılır?", secenekler: { A: "Voleybol", B: "Hentbol", C: "Su Topu", D: "Basketbol" }, dogruCevap: "D" },
    { seviye: 107, kategori: "Spor", soru: "Formula 1 tarihinde en çok şampiyonluk yaşayan iki pilottan biri hangisidir?", secenekler: { A: "Sebastian Vettel", B: "Lewis Hamilton", C: "Fernando Alonso", D: "Max Verstappen" }, dogruCevap: "B" },
    { seviye: 108, kategori: "Spor", soru: "Masa tenisinde bir set kaç sayıda biter?", secenekler: { A: "11", B: "25", C: "15", D: "21" }, dogruCevap: "A" },
    { seviye: 109, kategori: "Spor", soru: "Dünya Kupası'nı hem oyuncu hem teknik direktör olarak kazanan isimlerden biri hangisidir?", secenekler: { A: "Diego Maradona", B: "Didier Deschamps", C: "Pele", D: "Zinedine Zidane" }, dogruCevap: "B" },
    { seviye: 110, kategori: "Spor", soru: "Bisiklet sporunda dünyanın en prestijli yarışı hangisidir?", secenekler: { A: "Tour of Türkiye", B: "Vuelta a España", C: "Tour de France", D: "Giro d'Italia" }, dogruCevap: "C" },
    { seviye: 111, kategori: "Spor", soru: "2024 Olimpiyat Oyunları hangi şehirde düzenlenecektir?", secenekler: { A: "Los Angeles", B: "Paris", C: "Brisbane", D: "Tokyo" }, dogruCevap: "B" },
    { seviye: 112, kategori: "Spor", soru: "Hangi branş 'sporların anası' olarak kabul edilir?", secenekler: { A: "Atletizm", B: "Yüzme", C: "Güreş", D: "Jimnastik" }, dogruCevap: "A" },
    { seviye: 113, kategori: "Spor", soru: "Snooker (Bilardo) oyununda en yüksek puanlı top hangi renktir?", secenekler: { A: "Mavi", B: "Kırmızı", C: "Pembe", D: "Siyah" }, dogruCevap: "D" },
    { seviye: 114, kategori: "Spor", soru: "Türkiye'nin olimpiyatlarda kazandığı ilk altın madalya hangi branştadır?", secenekler: { A: "Halter", B: "Güreş", C: "Boks", D: "Okçuluk" }, dogruCevap: "B" },
    { seviye: 115, kategori: "Spor", soru: "NBA'de tüm zamanların en çok sayı atan oyuncusu kimdir?", secenekler: { A: "Kobe Bryant", B: "LeBron James", C: "Michael Jordan", D: "Kareem Abdul-Jabbar" }, dogruCevap: "B" },
    { seviye: 116, kategori: "Spor", soru: "Hentbolda bir maç kaç dakikadır?", secenekler: { A: "40", B: "90", C: "60", D: "50" }, dogruCevap: "C" },
    { seviye: 117, kategori: "Spor", soru: "Yüzmede 'kelebek' stili kaç metrelik yarışlarda başlar?", secenekler: { A: "100", B: "400", C: "200", D: "50" }, dogruCevap: "D" },
    { seviye: 118, kategori: "Spor", soru: "Dünya ağır sıklet boks şampiyonu 'Iron' lakaplı sporcu kimdir?", secenekler: { A: "Anthony Joshua", B: "Mike Tyson", C: "Tyson Fury", D: "Muhammad Ali" }, dogruCevap: "B" },
    { seviye: 119, kategori: "Spor", soru: "Voleybolda savunma oyuncusuna (farklı renk forma giyen) ne ad verilir?", secenekler: { A: "Smaçör", B: "Orta Oyuncu", C: "Pasör", D: "Libero" }, dogruCevap: "D" },
    { seviye: 120, kategori: "Spor", soru: "Buz hokeyinde oyunun oynandığı diske ne ad verilir?", secenekler: { A: "Puck", B: "Top", C: "Küre", D: "Mermer" }, dogruCevap: "A" },
    { seviye: 121, kategori: "Spor", soru: "Wimbledon Tenis Turnuvası hangi zemin üzerinde oynanır?", secenekler: { A: "Halı", B: "Toprak", C: "Sert", D: "Çim" }, dogruCevap: "D" },
    { seviye: 122, kategori: "Spor", soru: "Bir maraton koşusu tam olarak kaç kilometredir?", secenekler: { A: "38.5", B: "40", C: "45", D: "42.195" }, dogruCevap: "D" },
    { seviye: 123, kategori: "Spor", soru: "Okçulukta hedefin tam ortasına (10 puan) ne ad verilir?", secenekler: { A: "Merkez", B: "Onluk", C: "Bulls-eye", D: "Göz" }, dogruCevap: "C" },
    { seviye: 124, kategori: "Spor", soru: "Satrançta en güçlü taş hangisidir?", secenekler: { A: "Kale", B: "Vezir", C: "At", D: "Şah" }, dogruCevap: "B" },
    { seviye: 125, kategori: "Spor", soru: "Kış Olimpiyatları kaç yılda bir düzenlenir?", secenekler: { A: "2", B: "4", C: "3", D: "5" }, dogruCevap: "B" },
    { seviye: 126, kategori: "Spor", soru: "Brezilyalı efsane futbolcu Pele kaç kez Dünya Kupası kazanmıştır?", secenekler: { A: "4", B: "1", C: "3", D: "2" }, dogruCevap: "C" },
    { seviye: 127, kategori: "Spor", soru: "NBA takımlarından Chicago Bulls'un efsanevi 23 numaralı oyuncusu kimdir?", secenekler: { A: "Michael Jordan", B: "Scottie Pippen", C: "Derrick Rose", D: "Dennis Rodman" }, dogruCevap: "A" },
    { seviye: 128, kategori: "Spor", soru: "Sumo güreşi hangi ülkenin milli sporudur?", secenekler: { A: "Japonya", B: "Tayland", C: "Güney Kore", D: "Çin" }, dogruCevap: "A" },
    { seviye: 129, kategori: "Spor", soru: "Golfte topun deliğe girmesi için yapılan son vuruşa ne denir?", secenekler: { A: "Chip", B: "Swing", C: "Drive", D: "Putt" }, dogruCevap: "D" },
    { seviye: 130, kategori: "Spor", soru: "2008 Pekin Olimpiyatları'nda 8 altın madalya kazanan efsane yüzücü kimdir?", secenekler: { A: "Ryan Lochte", B: "Ian Thorpe", C: "Michael Phelps", D: "Caeleb Dressel" }, dogruCevap: "C" },
    { seviye: 131, kategori: "Spor", soru: "Hangi futbolcu daha fazla Ballon d'Or ödülüne sahiptir?", secenekler: { A: "Michel Platini", B: "Cristiano Ronaldo", C: "Lionel Messi", D: "Johan Cruyff" }, dogruCevap: "C" },
    { seviye: 132, kategori: "Spor", soru: "Eskrimde hangi silah türü tüm vücudu hedef olarak kabul eder?", secenekler: { A: "Epe", B: "Kılıç", C: "Sable", D: "Flöre" }, dogruCevap: "A" },
    { seviye: 133, kategori: "Spor", soru: "Türkiye'nin ilk yerli yarış otomobilinin adı nedir?", secenekler: { A: "Devrim", B: "Anadol", C: "Etox", D: "Volkicar" }, dogruCevap: "D" },
    { seviye: 134, kategori: "Spor", soru: "Hangi branşta 'smaç' terimi kullanılmaz?", secenekler: { A: "Futbol", B: "Voleybol", C: "Tenis", D: "Basketbol" }, dogruCevap: "A" },
    { seviye: 135, kategori: "Spor", soru: "Beyzbolda bir takımın tüm kaleleri dolaşarak kazandığı puana ne denir?", secenekler: { A: "Touchdown", B: "Strike", C: "Goal", D: "Home Run" }, dogruCevap: "D" },
    { seviye: 136, kategori: "Spor", soru: "Amerikan Futbolu'nda bir 'Touchdown' kaç puandır?", secenekler: { A: "7", B: "6", C: "3", D: "2" }, dogruCevap: "B" },
    { seviye: 137, kategori: "Spor", soru: "Hangi tenis turnuvası 'Toprak Kortun Kralı' olarak bilinen Rafael Nadal ile özdeşleşmiştir?", secenekler: { A: "US Open", B: "Wimbledon", C: "Roland Garros", D: "Australian Open" }, dogruCevap: "C" },
    { seviye: 138, kategori: "Spor", soru: "Bowlingde tüm lobutları tek seferde devirmeye ne denir?", secenekler: { A: "Perfect", B: "Split", C: "Spare", D: "Strike" }, dogruCevap: "D" },
    { seviye: 139, kategori: "Spor", soru: "Hangi ülke futbol milli takımı 'Gök Mavililer' (Azzurri) lakabıyla anılır?", secenekler: { A: "Uruguay", B: "Fransa", C: "Arjantin", D: "İtalya" }, dogruCevap: "D" },
    { seviye: 140, kategori: "Spor", soru: "Su topunda bir takım kaleci dahil kaç oyuncudan oluşur?", secenekler: { A: "11", B: "7", C: "6", D: "8" }, dogruCevap: "B" },
    { seviye: 141, kategori: "Spor", soru: "Körling (Curling) sporu nerede oynanır?", secenekler: { A: "Su", B: "Çim", C: "Buz", D: "Kum" }, dogruCevap: "C" },
    { seviye: 142, kategori: "Spor", soru: "Usain Bolt'un 100 metre dünya rekoru derecesi kaçtır?", secenekler: { A: "9.72", B: "9.81", C: "9.69", D: "9.58" }, dogruCevap: "D" },
    { seviye: 143, kategori: "Spor", soru: "Hangi branşta 'servis' ile oyuna başlanmaz?", secenekler: { A: "Voleybol", B: "Tenis", C: "Badminton", D: "Basketbol" }, dogruCevap: "D" },
    { seviye: 144, kategori: "Spor", soru: "Jimnastikte denge aleti üzerinde hangi sporcular yarışır?", secenekler: { A: "Karma Takımlar", B: "Sadece Kadınlar", C: "Hem Erkek hem Kadın", D: "Sadece Erkekler" }, dogruCevap: "B" },
    { seviye: 145, kategori: "Spor", soru: "Türkiye'nin Avrupa Şampiyonu olan Kadın Voleybol Milli Takımı'nın lakabı?", secenekler: { A: "Demir Pençeler", B: "Filenin Sultanları", C: "Potanın Perileri", D: "Altın Kızlar" }, dogruCevap: "B" },
    { seviye: 146, kategori: "Spor", soru: "Bir boks maçında nakavt için hakem kaça kadar sayar?", secenekler: { A: "8", B: "12", C: "10", D: "5" }, dogruCevap: "C" },
    { seviye: 147, kategori: "Spor", soru: "Hangi ülke Ragbi sporunun ana vatanı kabul edilir?", secenekler: { A: "Yeni Zelanda", B: "İngiltere", C: "Avustralya", D: "ABD" }, dogruCevap: "B" },
    { seviye: 148, kategori: "Spor", soru: "Bilardoda beyaz topa vurulan sopaya ne denir?", secenekler: { A: "Kulüp", B: "Istaka", C: "Sopa", D: "Raket" }, dogruCevap: "B" },
    { seviye: 149, kategori: "Spor", soru: "Mete Gazoz hangi branşta Olimpiyat Şampiyonu olmuştur?", secenekler: { A: "Okçuluk", B: "Jimnastik", C: "Atıcılık", D: "Eskrim" }, dogruCevap: "A" },
    { seviye: 150, kategori: "Spor", soru: "Hangi spor dalında 'ofsait' kuralı yoktur?", secenekler: { A: "Çim Hokeyi", B: "Basketbol", C: "Buz Hokeyi", D: "Futbol" }, dogruCevap: "B" }, 
    // 149-318: Yeni Spor Soruları
    { seviye: 149, kategori: "Spor", soru: "Modern Olimpiyat Oyunları ilk kez hangi yıl düzenlenmiştir?", secenekler: { A: "1896", B: "1924", C: "1912", D: "1900" }, dogruCevap: "A" },
    { seviye: 150, kategori: "Spor", soru: "Basketbolda bir periyot kaç dakikadır (NBA hariç)?", secenekler: { A: "15", B: "8", C: "10", D: "12" }, dogruCevap: "C" },
    { seviye: 151, kategori: "Spor", soru: "Hangi ülke 2022 FIFA Dünya Kupası'nı kazanmıştır?", secenekler: { A: "Fas", B: "Hırvatistan", C: "Fransa", D: "Arjantin" }, dogruCevap: "D" },
    { seviye: 152, kategori: "Spor", soru: "Tenis maçlarında 'Sıfır' puanı hangi kelimeyle ifade edilir?", secenekler: { A: "Zero", B: "Void", C: "Love", D: "Nil" }, dogruCevap: "C" },
    { seviye: 153, kategori: "Spor", soru: "Formula 1'de en çok şampiyonluk yaşayan (7 kez) iki pilot kimdir?", secenekler: { A: "N. Lauda - M. Verstappen", B: "A. Senna - S. Vettel", C: "M. Schumacher - L. Hamilton", D: "F. Alonso - K. Raikkonen" }, dogruCevap: "C" },
    { seviye: 154, kategori: "Spor", soru: "Hentbol maçında bir takım kaç oyuncuyla sahada yer alır?", secenekler: { A: "6", B: "11", C: "5", D: "7" }, dogruCevap: "D" },
    { seviye: 155, kategori: "Spor", soru: "Süper Lig tarihinde en çok gol atan futbolcu kimdir?", secenekler: { A: "Tanju Çolak", B: "Metin Oktay", C: "Hami Mandıralı", D: "Hakan Şükür" }, dogruCevap: "D" },
    { seviye: 156, kategori: "Spor", soru: "Voleybolda bir set kaç sayıda biter (Netice seti hariç)?", secenekler: { A: "15", B: "25", C: "21", D: "30" }, dogruCevap: "B" },
    { seviye: 157, kategori: "Spor", soru: "Hangi tenis turnuvası toprak kortta oynanır?", secenekler: { A: "Wimbledon", B: "Roland Garros", C: "Avustralya Açık", D: "US Open" }, dogruCevap: "B" },
    { seviye: 158, kategori: "Spor", soru: "Türkiye'nin ilk dünya şampiyonu kadın güreşçisi kimdir?", secenekler: { A: "Buse Tosun", B: "Melek Hu", C: "Yasemin Adar", D: "Evrim Akın" }, dogruCevap: "C" },
    { seviye: 159, kategori: "Spor", soru: "NBA tarihinde tüm zamanların en çok sayı atan oyuncusu kimdir?", secenekler: { A: "Kobe Bryant", B: "Michael Jordan", C: "Kareem Abdul-Jabbar", D: "LeBron James" }, dogruCevap: "D" },
    { seviye: 160, kategori: "Spor", soru: "Buz hokeyi maçları kaç devreden oluşur?", secenekler: { A: "1", B: "4", C: "2", D: "3" }, dogruCevap: "D" },
    { seviye: 161, kategori: "Spor", soru: "Okçulukta hedefin en orta noktasının rengi nedir?", secenekler: { A: "Mavi", B: "Kırmızı", C: "Siyah", D: "Sarı" }, dogruCevap: "D" },
    { seviye: 162, kategori: "Spor", soru: "Hangi futbolcu 8 kez Ballon d'Or ödülünü kazanmıştır?", secenekler: { A: "Luka Modric", B: "Karim Benzema", C: "Cristiano Ronaldo", D: "Lionel Messi" }, dogruCevap: "D" },
    { seviye: 163, kategori: "Spor", soru: "Güreşte müsabaka yapılan alanın adı nedir?", secenekler: { A: "Tatami", B: "Kort", C: "Minder", D: "Ring" }, dogruCevap: "C" },
    { seviye: 164, kategori: "Spor", soru: "Bir beyzbol takımı kaç oyuncudan oluşur?", secenekler: { A: "7", B: "11", C: "5", D: "9" }, dogruCevap: "D" },
    { seviye: 165, kategori: "Spor", soru: "Hangi Türk basketbolcu NBA'de şampiyonluk yaşayan ilk Türk olmuştur?", secenekler: { A: "Alperen Şengün", B: "Hidayet Türkoğlu", C: "Mehmet Okur", D: "Ersan İlyasova" }, dogruCevap: "C" },
    { seviye: 166, kategori: "Spor", soru: "Olimpiyat bayrağındaki beş halka neyi temsil eder?", secenekler: { A: "Beş Okyanusu", B: "Beş Kıtayı", C: "Beş Büyük Branşı", D: "Beş Kurucu Ülkeyi" }, dogruCevap: "B" },
    { seviye: 167, kategori: "Spor", soru: "Türkiye'nin en eski spor kulübü hangisidir?", secenekler: { A: "Beşiktaş JK", B: "Fenerbahçe SK", C: "Galatasaray SK", D: "İstanbulspor" }, dogruCevap: "A" },
    { seviye: 168, kategori: "Spor", soru: "Su topu maçında bir devre kaç dakikadır?", secenekler: { A: "15", B: "8", C: "12", D: "10" }, dogruCevap: "B" },
    { seviye: 169, kategori: "Spor", soru: "Hangi ülke kriket sporunun ana vatanıdır?", secenekler: { A: "İngiltere", B: "Güney Afrika", C: "Hindistan", D: "Avustralya" }, dogruCevap: "A" },
    { seviye: 170, kategori: "Spor", soru: "Usain Bolt'un 100 metre dünya rekoru derecesi kaçtır?", secenekler: { A: "9.69", B: "9.81", C: "9.72", D: "9.58" }, dogruCevap: "D" },
    { seviye: 171, kategori: "Spor", soru: "Satrançta 'L' şeklinde hareket eden taş hangisidir?", secenekler: { A: "At", B: "Kale", C: "Vezir", D: "Fil" }, dogruCevap: "A" },
    { seviye: 172, kategori: "Spor", soru: "Voleybolda sadece savunma yapan ve farklı renk forma giyen oyuncu?", secenekler: { A: "Orta Oyuncu", B: "Smaçör", C: "Libero", D: "Pasör" }, dogruCevap: "C" },
    { seviye: 173, kategori: "Spor", soru: "Hangi futbol takımı 'Kırmızı Şeytanlar' lakabıyla bilinir?", secenekler: { A: "AC Milan", B: "Liverpool", C: "Bayern Münih", D: "Manchester United" }, dogruCevap: "D" },
    { seviye: 174, kategori: "Spor", soru: "Masa tenisinde bir set kaç sayıda biter?", secenekler: { A: "11", B: "25", C: "21", D: "15" }, dogruCevap: "A" },
    { seviye: 175, kategori: "Spor", soru: "Bisiklette 'Fransa Turu'nun liderinin giydiği formanın rengi nedir?", secenekler: { A: "Yeşil", B: "Kırmızı", C: "Pembe", D: "Sarı" }, dogruCevap: "D" },
    { seviye: 176, kategori: "Spor", soru: "Eskrimde kaç farklı silah türü vardır?", secenekler: { A: "5", B: "2", C: "3", D: "4" }, dogruCevap: "C" },
    { seviye: 177, kategori: "Spor", soru: "Badminton maçında kullanılan tüylü topun adı nedir?", secenekler: { A: "Birdie", B: "Puck", C: "Smasher", D: "Shuttlecock" }, dogruCevap: "D" },
    { seviye: 178, kategori: "Spor", soru: "NFL hangi spor dalının profesyonel ligidir?", secenekler: { A: "Buz Hokeyi", B: "Amerikan Futbolu", C: "Beyzbol", D: "Basketbol" }, dogruCevap: "B" },
    { seviye: 179, kategori: "Spor", soru: "Wimbledon Tenis Turnuvası hangi ülkede düzenlenir?", secenekler: { A: "Avustralya", B: "İngiltere", C: "ABD", D: "Fransa" }, dogruCevap: "B" },
    { seviye: 180, kategori: "Spor", soru: "Golfte topun deliğe girmesi için yapılan son vuruşa ne denir?", secenekler: { A: "Putt", B: "Chip", C: "Drive", D: "Swing" }, dogruCevap: "A" },
    { seviye: 181, kategori: "Spor", soru: "Hangi Türk teknik direktör 'İmparator' lakabıyla anılır?", secenekler: { A: "Fatih Terim", B: "Aykut Kocaman", C: "Mustafa Denizli", D: "Şenol Güneş" }, dogruCevap: "A" },
    { seviye: 182, kategori: "Spor", soru: "Bilardoda kaç tane delik vardır?", secenekler: { A: "10", B: "4", C: "8", D: "6" }, dogruCevap: "D" },
    { seviye: 183, kategori: "Spor", soru: "Boks ringi hangi şekildedir?", secenekler: { A: "Kare", B: "Altıgen", C: "Sekizgen", D: "Daire" }, dogruCevap: "A" },
    { seviye: 184, kategori: "Spor", soru: "Sumo güreşi hangi ülkenin milli sporudur?", secenekler: { A: "Moğolistan", B: "Güney Kore", C: "Japonya", D: "Çin" }, dogruCevap: "C" },
    { seviye: 185, kategori: "Spor", soru: "Michael Jordan kariyerinin büyük bölümünde hangi numaralı formayı giymiştir?", secenekler: { A: "23", B: "32", C: "45", D: "33" }, dogruCevap: "A" },
    { seviye: 186, kategori: "Spor", soru: "Atletizmde 'Dekatlon' kaç farklı branştan oluşur?", secenekler: { A: "5", B: "12", C: "10", D: "7" }, dogruCevap: "C" },
    { seviye: 187, kategori: "Spor", soru: "Yüzmede 'Kurbağalama' stilinin İngilizcesi nedir?", secenekler: { A: "Freestyle", B: "Backstroke", C: "Breaststroke", D: "Butterfly" }, dogruCevap: "C" },
    { seviye: 188, kategori: "Spor", soru: "EuroLeague'i en çok kazanan (11 kez) basketbol takımı hangisidir?", secenekler: { A: "Real Madrid", B: "Panathinaikos", C: "Fenerbahçe", D: "CSKA Moskova" }, dogruCevap: "A" },
    { seviye: 189, kategori: "Spor", soru: "Hangi futbolcuya 'Kara İnci' lakabı verilmiştir?", secenekler: { A: "Eusebio", B: "Maradona", C: "Pele", D: "Garrincha" }, dogruCevap: "C" },
    { seviye: 190, kategori: "Spor", soru: "Voleybolda servis atışını karşılayan oyuncuya ne denir?", secenekler: { A: "Pasör çaprazı", B: "Libero", C: "Blokçu", D: "Manşetçi" }, dogruCevap: "D" },
    { seviye: 191, kategori: "Spor", soru: "Snooker bilardosunda en yüksek puanlı top hangi renktir?", secenekler: { A: "Siyah", B: "Mavi", C: "Kırmızı", D: "Pembe" }, dogruCevap: "A" },
    { seviye: 192, kategori: "Spor", soru: "Hangi spor dalında 'Puck' adı verilen sert lastik bir disk kullanılır?", secenekler: { A: "Buz Hokeyi", B: "Lacrosse", C: "Curling", D: "Su Topu" }, dogruCevap: "A" },
    { seviye: 193, kategori: "Spor", soru: "Beşiktaş'ın efsanevi 'Metin-Ali-Feyyaz' üçlüsündeki Feyyaz'ın soyadı nedir?", secenekler: { A: "Tekin", B: "Güler", C: "Uçar", D: "Korkmaz" }, dogruCevap: "C" },
    { seviye: 194, kategori: "Spor", soru: "Bir basketbol maçı berabere biterse uzatma süresi kaç dakikadır?", secenekler: { A: "15", B: "3", C: "10", D: "5" }, dogruCevap: "D" },
    { seviye: 195, kategori: "Spor", soru: "Okçulukta yay ile ok arasındaki gergin ipe ne denir?", secenekler: { A: "Yay", B: "Kiriş", C: "Ok", D: "Nişangah" }, dogruCevap: "B" },
    { seviye: 196, kategori: "Spor", soru: "Hangi ülke futbolda 'Sambacılar' olarak bilinir?", secenekler: { A: "Arjantin", B: "Portekiz", C: "Brezilya", D: "İspanya" }, dogruCevap: "C" },
    { seviye: 197, kategori: "Spor", soru: "Bowlingde tüm labutları ilk atışta devirmeye ne denir?", secenekler: { A: "Spare", B: "Strike", C: "Split", D: "Double" }, dogruCevap: "B" },
    { seviye: 198, kategori: "Spor", soru: "Hangi Türk güreşçi 'Yüzyılın Sporcusu' unvanına sahiptir?", secenekler: { A: "Rıza Kayaalp", B: "Naim Süleymanoğlu", C: "Hamza Yerlikaya", D: "Taha Akgül" }, dogruCevap: "C" },
    { seviye: 199, kategori: "Spor", soru: "Wimbledon'da maç sırasında oyuncuların giymesi zorunlu olan renk?", secenekler: { A: "Sarı", B: "Mavi", C: "Kırmızı", D: "Beyaz" }, dogruCevap: "D" },
    { seviye: 200, kategori: "Spor", soru: "Futbolda kale direkleri arasındaki mesafe kaç metredir?", secenekler: { A: "7.50", B: "8.00", C: "7.32", D: "7.00" }, dogruCevap: "C" },
    { seviye: 201, kategori: "Spor", soru: "Sualtı Ragbisi kaç metre derinlikte oynanır?", secenekler: { A: "15-20 metre", B: "1-2 metre", C: "3-5 metre", D: "7-10 metre" }, dogruCevap: "C" },
    { seviye: 202, kategori: "Spor", soru: "Hangi tenisçi 'Toprağın Kralı' lakabıyla bilinir?", secenekler: { A: "Novak Djokovic", B: "Andy Murray", C: "Roger Federer", D: "Rafael Nadal" }, dogruCevap: "D" },
    { seviye: 203, kategori: "Spor", soru: "Beşli ganyan oyununda kaç koşunun birincisini bilmek gerekir?", secenekler: { A: "4", B: "6", C: "3", D: "5" }, dogruCevap: "D" },
    { seviye: 204, kategori: "Spor", soru: "Judoda en yüksek kuşak rengi hangisidir?", secenekler: { A: "Kırmızı", B: "Kahverengi", C: "Siyah", D: "Beyaz" }, dogruCevap: "A" },
    { seviye: 205, kategori: "Spor", soru: "Kış Olimpiyatları kaç yılda bir düzenlenir?", secenekler: { A: "4", B: "2", C: "6", D: "5" }, dogruCevap: "A" },
    { seviye: 206, kategori: "Spor", soru: "Futbolda bir takımın oyuncu değişikliği hakkı kural olarak kaçtır (Güncel)?", secenekler: { A: "6", B: "4", C: "5", D: "3" }, dogruCevap: "C" },
    { seviye: 207, kategori: "Spor", soru: "Hangi NBA takımı 'The Lakers' lakabını kullanır?", secenekler: { A: "Chicago", B: "Miami", C: "Boston", D: "Los Angeles" }, dogruCevap: "D" },
    { seviye: 208, kategori: "Spor", soru: "Bir golf sahasında standart olarak kaç delik bulunur?", secenekler: { A: "24", B: "12", C: "18", D: "9" }, dogruCevap: "C" },
    { seviye: 209, kategori: "Spor", soru: "At yarışlarında jokeylerin bindiği erkek ata ne denir?", secenekler: { A: "Beygir", B: "Tay", C: "Aygır", D: "Kısrak" }, dogruCevap: "C" },
    { seviye: 210, kategori: "Spor", soru: "Hangi spor dalında 'Yedi metre atışı' cezası vardır?", secenekler: { A: "Su Topu", B: "Futbol", C: "Hentbol", D: "Basketbol" }, dogruCevap: "C" },
    { seviye: 211, kategori: "Spor", soru: "Türkiye Basketbol Ligi'nin en çok şampiyon olan takımı?", secenekler: { A: "Eczacıbaşı", B: "Galatasaray", C: "Anadolu Efes", D: "Fenerbahçe" }, dogruCevap: "C" },
    { seviye: 212, kategori: "Spor", soru: "Hangi futbolcu 'El Pibe de Oro' (Altın Çocuk) lakabıyla bilinir?", secenekler: { A: "Messi", B: "Ronaldo", C: "Pele", D: "Maradona" }, dogruCevap: "D" },
    { seviye: 213, kategori: "Spor", soru: "Sörf sporunun ana vatanı neresidir?", secenekler: { A: "Avustralya", B: "Hawaii", C: "Güney Afrika", D: "Brezilya" }, dogruCevap: "B" },
    { seviye: 214, kategori: "Spor", soru: "Masa tenisinde topun ağırlığı yaklaşık kaç gramdır?", secenekler: { A: "2.7", B: "5.0", C: "1.5", D: "10.0" }, dogruCevap: "A" },
    { seviye: 215, kategori: "Spor", soru: "Körling (Curling) sporunda zeminde ne kullanılır?", secenekler: { A: "Buz", B: "Çim", C: "Kum", D: "Toprak" }, dogruCevap: "A" },
    { seviye: 216, kategori: "Spor", soru: "Bir maraton koşusunun tam mesafesi nedir?", secenekler: { A: "50.000 km", B: "21.100 km", C: "42.195 km", D: "40.000 km" }, dogruCevap: "C" },
    { seviye: 217, kategori: "Spor", soru: "Hangi spor branşında 'İp, Çember, Top, Labut ve Kurdele' kullanılır?", secenekler: { A: "Bale", B: "Artistik Jimnastik", C: "Ritmik Jimnastik", D: "Senkronize Yüzme" }, dogruCevap: "C" },
    { seviye: 218, kategori: "Spor", soru: "Süper Lig'de 'Dört Büyükler' dışında şampiyon olan ilk takım?", secenekler: { A: "Bursaspor", B: "Eskişehirspor", C: "Trabzonspor", D: "Başakşehir" }, dogruCevap: "C" },
    { seviye: 219, kategori: "Spor", soru: "Badmintonda maça nasıl başlanır?", secenekler: { A: "Hava atışı ile", B: "Kale seçimi ile", C: "Pas ile", D: "Servis ile" }, dogruCevap: "D" },
    { seviye: 220, kategori: "Spor", soru: "Karate sporunda kullanılan kıyafetin adı nedir?", secenekler: { A: "Dobok", B: "Karategi", C: "Kimono", D: "Hakam" }, dogruCevap: "B" },
    { seviye: 221, kategori: "Spor", soru: "Hangi futbolcu 'Uçan Hollandalı' lakabıyla bilinir?", secenekler: { A: "Johan Cruyff", B: "Arjen Robben", C: "Robin van Persie", D: "Marco van Basten" }, dogruCevap: "A" },
    { seviye: 222, kategori: "Spor", soru: "Bilardoda 'Bant' neye denir?", secenekler: { A: "Istakanın ucuna", B: "Deliğin içine", C: "Topların rengine", D: "Masanın kenarlarına" }, dogruCevap: "D" },
    { seviye: 223, kategori: "Spor", soru: "Amerikan Futbolu maçları kaç çeyrekten oluşur?", secenekler: { A: "3", B: "1", C: "2", D: "4" }, dogruCevap: "D" },
    { seviye: 224, kategori: "Spor", soru: "Bir voleybol file yüksekliği (Erkekler için) kaç metredir?", secenekler: { A: "2.35", B: "2.43", C: "2.50", D: "2.24" }, dogruCevap: "B" },
    { seviye: 225, kategori: "Spor", soru: "Hangi spor dalında 'Caddie' adı verilen yardımcılar vardır?", secenekler: { A: "Kriket", B: "Tenis", C: "Golf", D: "Polo" }, dogruCevap: "C" },
    { seviye: 226, kategori: "Spor", soru: "Patenli sürat pateni yarışları nerede yapılır?", secenekler: { A: "Pist", B: "Ring", C: "Oval", D: "Velodrom" }, dogruCevap: "C" },
    { seviye: 227, kategori: "Spor", soru: "Hangi takım NBA'de en çok şampiyonluk kazanan (18 kez) takımdır?", secenekler: { A: "Chicago Bulls", B: "Golden State", C: "LA Lakers", D: "Boston Celtics" }, dogruCevap: "D" },
    { seviye: 228, kategori: "Spor", soru: "Taekwondo'da 'Dobok' neyi ifade eder?", secenekler: { A: "Kuşak", B: "Selam", C: "Kıyafet", D: "Tekme" }, dogruCevap: "C" },
    { seviye: 229, kategori: "Spor", soru: "Su topunda kalecinin bone rengi genellikle nedir?", secenekler: { A: "Mavi", B: "Beyaz", C: "Sarı", D: "Kırmızı" }, dogruCevap: "D" },
    { seviye: 230, kategori: "Spor", soru: "Formula 1'de damalı bayrak ne anlama gelir?", secenekler: { A: "Tehlike olduğu", B: "Pite girilmesi gerektiği", C: "Geçiş yasağı", D: "Yarışın bittiği" }, dogruCevap: "D" },
    { seviye: 231, kategori: "Spor", soru: "Bir futbol maçında topun tamamı kale çizgisini geçerse ne olur?", secenekler: { A: "Aut", B: "Devam", C: "Gol", D: "Korner" }, dogruCevap: "C" },
    { seviye: 232, kategori: "Spor", soru: "Hangi şehir 3 kez Yaz Olimpiyatları'na ev sahipliği yapmıştır?", secenekler: { A: "Londra", B: "Atina", C: "Paris", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 233, kategori: "Spor", soru: "Zinedine Zidane aslen hangi ülke kökenlidir?", secenekler: { A: "Tunus", B: "Mısır", C: "Fas", D: "Cezayir" }, dogruCevap: "D" },
    { seviye: 234, kategori: "Spor", soru: "Hangi spor dalında 'Double-Double' terimi kullanılır?", secenekler: { A: "Futbol", B: "Tenis", C: "Basketbol", D: "Voleybol" }, dogruCevap: "C" },
    { seviye: 235, kategori: "Spor", soru: "Okçulukta okun arkasındaki tüylere ne ad verilir?", secenekler: { A: "Yele", B: "Kanat", C: "Fletch", D: "Süper" }, dogruCevap: "C" },
    { seviye: 236, kategori: "Spor", soru: "Krikette topu vuran oyuncuya ne denir?", secenekler: { A: "Batsman", B: "Keeper", C: "Fielder", D: "Bowler" }, dogruCevap: "A" },
    { seviye: 237, kategori: "Spor", soru: "Hangi Türk güreşçi 'Boğazın Boğası' lakabıyla tanınır?", secenekler: { A: "Selçuk Çebi", B: "Sinan Şamil Sam", C: "Rıza Kayaalp", D: "Hamza Yerlikaya" }, dogruCevap: "B" },
    { seviye: 238, kategori: "Spor", soru: "Bilardoda beyaz topa ne ad verilir?", secenekler: { A: "Striker", B: "Cue Ball", C: "Master", D: "Hedef" }, dogruCevap: "B" },
    { seviye: 239, kategori: "Spor", soru: "Bir hentbol maçının süresi ne kadardır?", secenekler: { A: "20+20 dk", B: "30+30 dk", C: "45+45 dk", D: "15x4 dk" }, dogruCevap: "B" },
    { seviye: 240, kategori: "Spor", soru: "Hangi futbol takımı 'Panzerler' olarak bilinir?", secenekler: { A: "Hollanda", B: "İsveç", C: "Belçika", D: "Almanya" }, dogruCevap: "D" },
    { seviye: 241, kategori: "Spor", soru: "Voleybolda bir takımın toplam kaç mola hakkı vardır (Set başı)?", secenekler: { A: "2", B: "1", C: "3", D: "4" }, dogruCevap: "A" },
    { seviye: 242, kategori: "Spor", soru: "Eskrimde kullanılan giysinin rengi nedir?", secenekler: { A: "Mavi", B: "Beyaz", C: "Gri", D: "Siyah" }, dogruCevap: "B" },
    { seviye: 243, kategori: "Spor", soru: "Teniste 'Deuce' ne anlama gelir?", secenekler: { A: "40-40 Beraberlik", B: "Hatalı Servis", C: "Set Sonu", D: "Oyun Sonu" }, dogruCevap: "A" },
    { seviye: 244, kategori: "Spor", soru: "Hangi sporda 'Handikap' terimi sıkça kullanılır?", secenekler: { A: "Yüzme", B: "Okçuluk", C: "Eskrim", D: "At Yarışı" }, dogruCevap: "D" },
    { seviye: 245, kategori: "Spor", soru: "Türkiye'nin ilk kadın Olimpiyat şampiyonu kimdir?", secenekler: { A: "Yasemin Adar", B: "Nurcan Taylan", C: "Hülya Şenyurt", D: "Merve Dizdar" }, dogruCevap: "B" },
    { seviye: 246, kategori: "Spor", soru: "Buz pateninde 'Triple Axel' hareketi kaç tur dönüş içerir?", secenekler: { A: "4", B: "2.5", C: "3", D: "3.5" }, dogruCevap: "D" },
    { seviye: 247, kategori: "Spor", soru: "Futbolda korner atışı nereden kullanılır?", secenekler: { A: "Köşe gönderinden", B: "Kale arkasından", C: "Taç çizgisinden", D: "Ceza sahasından" }, dogruCevap: "A" },
    { seviye: 248, kategori: "Spor", soru: "Hangi ülke beyzbol sporunun merkezidir?", secenekler: { A: "ABD", B: "Kanada", C: "Küba", D: "Japonya" }, dogruCevap: "A" },
    { seviye: 249, kategori: "Spor", soru: "Dama oyununda taşlar nasıl hareket eder?", secenekler: { A: "Geri", B: "İleri", C: "L şeklinde", D: "Çapraz" }, dogruCevap: "B" },
    { seviye: 250, kategori: "Spor", soru: "Hangi Türk basketbolcu NBA'de All-Star seçilen ilk Türk olmuştur?", secenekler: { A: "Mehmet Okur", B: "Cedi Osman", C: "Alperen Şengün", D: "Hidayet Türkoğlu" }, dogruCevap: "A" },
    { seviye: 251, kategori: "Spor", soru: "Dinamit lakaplı futbolcu kimdir?", secenekler: { A: "Sinan Kaloğlu", B: "Hami Mandıralı", C: "Roberto Carlos", D: "Ronald Koeman" }, dogruCevap: "B" },
    { seviye: 252, kategori: "Spor", soru: "Olimpiyatlarda altın madalya gerçekte neyden yapılır?", secenekler: { A: "Gümüş üzerine altın kaplama", B: "Saf altın", C: "Bakır ve altın karışımı", D: "Çelik üzerine altın" }, dogruCevap: "A" },
    { seviye: 253, kategori: "Spor", soru: "Hangi tenisçi 'Ekselansları' lakabıyla anılır?", secenekler: { A: "Pete Sampras", B: "Bjorn Borg", C: "Andre Agassi", D: "Roger Federer" }, dogruCevap: "D" },
    { seviye: 254, kategori: "Spor", soru: "Süper Lig'de en çok gol kralı olan futbolcu kimdir?", secenekler: { A: "Metin Oktay", B: "Burak Yılmaz", C: "Hakan Şükür", D: "Tanju Çolak" }, dogruCevap: "A" },
    { seviye: 255, kategori: "Spor", soru: "Badmintonda file yüksekliği yaklaşık kaç metredir?", secenekler: { A: "1.55", B: "1.80", C: "1.20", D: "2.00" }, dogruCevap: "A" },
    { seviye: 256, kategori: "Spor", soru: "Karate'de 'Sensei' kime denir?", secenekler: { A: "Hakem", B: "Öğrenci", C: "Öğretmen", D: "Rakip" }, dogruCevap: "C" },
    { seviye: 257, kategori: "Spor", soru: "Hangi branşta 'Mavi Kart' uygulaması (geçici oyun dışı) vardır?", secenekler: { A: "Basketbol", B: "Hentbol", C: "Futbol", D: "Voleybol" }, dogruCevap: "B" },
    { seviye: 258, kategori: "Spor", soru: "Bir maratonu 2 saatin altında koşan ilk atlet kimdir?", secenekler: { A: "Haile Gebrselassie", B: "Mo Farah", C: "Eliud Kipchoge", D: "Usain Bolt" }, dogruCevap: "C" },
    { seviye: 259, kategori: "Spor", soru: "Bilardoda topları dağıtmak için kullanılan üçgenin adı?", secenekler: { A: "Frame", B: "Rack", C: "Set", D: "Triangle" }, dogruCevap: "B" },
    { seviye: 260, kategori: "Spor", soru: "Hangi futbolcu 'Sarı Fare' lakabıyla bilinir?", secenekler: { A: "Johan Cruyff", B: "Fernando Torres", C: "Pavel Nedved", D: "Guti" }, dogruCevap: "A" },
    { seviye: 261, kategori: "Spor", soru: "NBA'de bir takımın hücum süresi kaç saniyedir?", secenekler: { A: "35", B: "30", C: "24", D: "14" }, dogruCevap: "C" },
    { seviye: 262, kategori: "Spor", soru: "Hangi spor branşı 'Kuvvet, Çeviklik ve Esneklik' üzerine kuruludur?", secenekler: { A: "Hentbol", B: "Boks", C: "Jimnastik", D: "Güreş" }, dogruCevap: "C" },
    { seviye: 263, kategori: "Spor", soru: "Snooker'da kaç tane kırmızı top vardır?", secenekler: { A: "10", B: "15", C: "21", D: "6" }, dogruCevap: "B" },
    { seviye: 264, kategori: "Spor", soru: "Atıcılıkta kullanılan silahın mermisine ne denir?", secenekler: { A: "Ok", B: "Pelet", C: "Saçma", D: "Kurşun" }, dogruCevap: "B" },
    { seviye: 265, kategori: "Spor", soru: "Hangi futbol takımı 'Kuzeyin Kralı' lakabını kullanır?", secenekler: { A: "FC Copenhagen", B: "Zenit", C: "Rosenborg", D: "Malmö" }, dogruCevap: "C" },
    { seviye: 266, kategori: "Spor", soru: "Bir sumo güreşçisine ne ad verilir?", secenekler: { A: "Yokozuna", B: "Rikishi", C: "Dojo", D: "Sensei" }, dogruCevap: "B" },
    { seviye: 267, kategori: "Spor", soru: "Sörf tahtasının üzerine sürülerek kaymayı önleyen madde?", secenekler: { A: "Pudra", B: "Yağ", C: "Reçine", D: "Vaks (Wax)" }, dogruCevap: "D" },
    { seviye: 268, kategori: "Spor", soru: "Hangi tenis turnuvası her yıl New York'ta düzenlenir?", secenekler: { A: "Amerika Açık", B: "Fransa Açık", C: "Miami Açık", D: "Wimbledon" }, dogruCevap: "A" },
    { seviye: 269, kategori: "Spor", soru: "Güreşte 'Tuş' neyi ifade eder?", secenekler: { A: "Devre arasını", B: "Faul yapmayı", C: "Müsabakanın bitmesini", D: "Puan almayı" }, dogruCevap: "C" },
    { seviye: 270, kategori: "Spor", soru: "Hangi spor dalında 'Triple-Double' yapılamaz?", secenekler: { A: "Basketbol", B: "Futbol", C: "Hepsi", D: "Voleybol" }, dogruCevap: "B" },
    { seviye: 271, kategori: "Spor", soru: "Atatürk'ün 'Ben sporcunun zeki, çevik ve aynı zamanda ... severim' sözündeki boşluk?", secenekler: { A: "Çalışkanını", B: "Saygılısını", C: "Dürüstünü", D: "Ahlaklısını" }, dogruCevap: "D" },
    { seviye: 272, kategori: "Spor", soru: "Voleybolda saha ölçüleri kaç metredir?", secenekler: { A: "8x16", B: "12x24", C: "10x20", D: "9x18" }, dogruCevap: "D" },
    { seviye: 273, kategori: "Spor", soru: "Hangi futbolcuya 'Örümcek' lakabı verilmiştir (Kaleci)?", secenekler: { A: "Casillas", B: "Neuer", C: "Buffon", D: "Lev Yaşin" }, dogruCevap: "D" },
    { seviye: 274, kategori: "Spor", soru: "Bisiklet sporunda 'Sprint' ne demektir?", secenekler: { A: "Yokuş çıkma", B: "Mola verme", C: "Yavaş sürüş", D: "Hızlı bitiriş" }, dogruCevap: "D" },
    { seviye: 275, kategori: "Spor", soru: "Körling oyununda buzu süpürmek neyi sağlar?", secenekler: { A: "Taşın durmasını", B: "Taşın yön değiştirmesini", C: "Buzun parlamasını", D: "Taşın daha uzağa gitmesini" }, dogruCevap: "D" },
    { seviye: 276, kategori: "Spor", soru: "Hangi basketbolcu 'The Black Mamba' lakabıyla bilinir?", secenekler: { A: "Kobe Bryant", B: "Shaquille O'Neal", C: "Kevin Durant", D: "Allen Iverson" }, dogruCevap: "A" },
    { seviye: 277, kategori: "Spor", soru: "Boks maçlarında dişleri koruyan aparatın adı nedir?", secenekler: { A: "Bandaj", B: "Kask", C: "Dişlik", D: "Eldiven" }, dogruCevap: "C" },
    { seviye: 278, kategori: "Spor", soru: "Hangi ülke futbol milli takımı 'Gök Mavililer' (Azzurri) olarak anılır?", secenekler: { A: "Fransa", B: "İtalya", C: "Uruguay", D: "Yunanistan" }, dogruCevap: "B" },
    { seviye: 279, kategori: "Spor", soru: "Yüzmede 'Kelebek' stilinde kollar nasıl hareket eder?", secenekler: { A: "Aynı anda ileri", B: "Hareket etmez", C: "Sadece suyun altından", D: "Sırayla ileri" }, dogruCevap: "A" },
    { seviye: 280, kategori: "Spor", soru: "Golfte 'Birdie' ne demektir?", secenekler: { A: "Par altı 1 vuruş", B: "Topun kaybolması", C: "Deliğe girmesi", D: "Par üzeri 1 vuruş" }, dogruCevap: "A" },
    { seviye: 281, kategori: "Spor", soru: "Hangi Türk takımı basketbolda üst üste 2 kez EuroLeague şampiyonu olmuştur?", secenekler: { A: "Beşiktaş", B: "Galatasaray", C: "Anadolu Efes", D: "Fenerbahçe" }, dogruCevap: "C" },
    { seviye: 282, kategori: "Spor", soru: "Masa tenisi raketinin her iki yüzü aynı renk olabilir mi?", secenekler: { A: "Hakem onaylarsa", B: "Hayır (Biri siyah biri kırmızı)", C: "Evet", D: "Sadece profesyonel liglerde" }, dogruCevap: "B" },
    { seviye: 283, kategori: "Spor", soru: "Hangi spor branşında 'İp atlamak' antrenmanın temelidir?", secenekler: { A: "Basketbol", B: "Futbol", C: "Boks", D: "Yüzme" }, dogruCevap: "C" },
    { seviye: 284, kategori: "Spor", soru: "Rugby topu ne şekildedir?", secenekler: { A: "Kare", B: "Üçgen", C: "Yuvarlak", D: "Oval" }, dogruCevap: "D" },
    { seviye: 285, kategori: "Spor", soru: "Hangi futbolcuya 'Profesör' lakabı takılmıştır?", secenekler: { A: "Andrea Pirlo", B: "Pep Guardiola", C: "Clarence Seedorf", D: "Arsene Wenger" }, dogruCevap: "D" },
    { seviye: 286, kategori: "Spor", soru: "Bowlingde en ağır top kaç 'pound' (libre) olabilir?", secenekler: { A: "16", B: "25", C: "20", D: "10" }, dogruCevap: "A" },
    { seviye: 287, kategori: "Spor", soru: "Okçulukta 'Sadak' nedir?", secenekler: { A: "Hedef tahtası", B: "Yayın adı", C: "Parmak koruyucu", D: "Okların konulduğu torba" }, dogruCevap: "D" },
    { seviye: 288, kategori: "Spor", soru: "Hangi tenis turnuvası sezonun ilk Grand Slam'idir?", secenekler: { A: "Avustralya Açık", B: "US Open", C: "Fransa Açık", D: "Wimbledon" }, dogruCevap: "A" },
    { seviye: 289, kategori: "Spor", soru: "Voleybolda bir setin 'tie-break'e (netice) gitmesi için skor ne olmalıdır?", secenekler: { A: "1-1 set beraberliği", B: "24-24 puan beraberliği", C: "Mola kalmaması", D: "2-2 set beraberliği" }, dogruCevap: "D" },
    { seviye: 290, kategori: "Spor", soru: "Hangi Türk güreşçi Olimpiyatlarda en çok madalya (3) kazanan güreşçimizdir?", secenekler: { A: "Hamza Yerlikaya", B: "Rıza Kayaalp", C: "Mustafa Dağıstanlı", D: "Mithat Bayrak" }, dogruCevap: "B" },
    { seviye: 291, kategori: "Spor", soru: "Bilardoda 'Istaka' nedir?", secenekler: { A: "Vuruş yapılan sopa", B: "Beyaz top", C: "Masadaki delik", D: "Masadaki tebeşir" }, dogruCevap: "A" },
    { seviye: 292, kategori: "Spor", soru: "Hangi futbol takımı 'Horozlar' lakabıyla bilinir?", secenekler: { A: "Portekiz", B: "Belçika", C: "Fransa", D: "Denizlispor" }, dogruCevap: "C" },
    { seviye: 293, kategori: "Spor", soru: "Bir basketbol sahası kaç metre uzunluğundadır?", secenekler: { A: "32", B: "30", C: "25", D: "28" }, dogruCevap: "D" },
    { seviye: 294, kategori: "Spor", soru: "Hangi spor dalında 'Servis' atılırken topu elden çıkarmak zorunludur?", secenekler: { A: "Hepsi", B: "Masa Tenisi", C: "Tenis", D: "Voleybol" }, dogruCevap: "A" },
    { seviye: 295, kategori: "Spor", soru: "Dama oyununda kaç taşla başlanır?", secenekler: { A: "16", B: "20", C: "24", D: "12" }, dogruCevap: "A" },
    { seviye: 296, kategori: "Spor", soru: "Hangi spor dalında 'Ofsayt' kuralı yoktur?", secenekler: { A: "Hentbol", B: "Buz Hokeyi", C: "Basketbol", D: "Futbol" }, dogruCevap: "C" },
    { seviye: 297, kategori: "Spor", soru: "Atletizmde 'Finiş' ne demektir?", secenekler: { A: "Engel", B: "Bayrak yarışı", C: "Bitiş çizgisi", D: "Başlangıç" }, dogruCevap: "C" },
    { seviye: 298, kategori: "Spor", soru: "Hangi dövüş sanatı 'Yumuşaklık Yolu' anlamına gelir?", secenekler: { A: "Kung-Fu", B: "Judo", C: "Karate", D: "Kick-Boks" }, dogruCevap: "B" },
    { seviye: 299, kategori: "Spor", soru: "Süper Lig'de 'Yüzler Kulübü'ne giren ilk yabancı futbolcu?", secenekler: { A: "Gheorghe Hagi", B: "Alex de Souza", C: "Elvir Boliç", D: "Bafetimbi Gomis" }, dogruCevap: "B" },
    { seviye: 300, kategori: "Spor", soru: "Dünyanın en yüksek seyirci kapasiteli stadı hangi ülkededir?", secenekler: { A: "İspanya", B: "Kuzey Kore", C: "ABD", D: "Brezilya" }, dogruCevap: "B" },
    { seviye: 301, kategori: "Spor", soru: "Formula 1'de pit stop sırasında tekerlek değiştiren ekibe ne denir?", secenekler: { A: "Servis ekibi", B: "Hız ekibi", C: "Pit ekibi", D: "Lastikçiler" }, dogruCevap: "C" },
    { seviye: 302, kategori: "Spor", soru: "Hangi spor dalında 'Eagles' (Kartallar) adında bir NFL takımı vardır?", secenekler: { A: "Beyzbol", B: "Basketbol", C: "Amerikan Futbolu", D: "Hokey" }, dogruCevap: "C" },
    { seviye: 303, kategori: "Spor", soru: "Voleybolda bir maç en fazla kaç set oynanabilir?", secenekler: { A: "7", B: "5", C: "4", D: "3" }, dogruCevap: "B" },
    { seviye: 304, kategori: "Spor", soru: "Hangi spor branşında 'Hava atışı' ile başlanır?", secenekler: { A: "Basketbol", B: "Futbol", C: "Hentbol", D: "Voleybol" }, dogruCevap: "A" },
    { seviye: 305, kategori: "Spor", soru: "Snooker'da pembe topun puan değeri kaçtır?", secenekler: { A: "6", B: "5", C: "4", D: "7" }, dogruCevap: "A" },
    { seviye: 306, kategori: "Spor", soru: "Hangi Türk halterci 'Cep Herkülü' olarak bilinir?", secenekler: { A: "Taner Sağır", B: "Halil Mutlu", C: "Naim Süleymanoğlu", D: "Nurcan Taylan" }, dogruCevap: "C" },
    { seviye: 307, kategori: "Spor", soru: "Bir tenis maçı en fazla kaç set sürer (Erkekler Grand Slam)?", secenekler: { A: "3", B: "4", C: "5", D: "7" }, dogruCevap: "C" },
    { seviye: 308, kategori: "Spor", soru: "Hangi ülke futbol milli takımı 'Boğalar' lakabıyla anılır?", secenekler: { A: "Meksika", B: "İspanya", C: "İtalya", D: "Arjantin" }, dogruCevap: "B" },
    { seviye: 309, kategori: "Spor", soru: "Golfte topun çimler üzerindeki yerine ne denir?", secenekler: { A: "Tee", B: "Fairway", C: "Green", D: "Rough" }, dogruCevap: "B" },
    { seviye: 310, kategori: "Spor", soru: "Hangi spor dalında 'Smaç' (Slam Dunk) terimi kullanılır?", secenekler: { A: "Futbol", B: "Hentbol", C: "Masa Tenisi", D: "Basketbol" }, dogruCevap: "D" },
    { seviye: 311, kategori: "Spor", soru: "Beşiktaş'ın stadı olan Vodafone Park'ın şimdiki adı nedir?", secenekler: { A: "İnönü Stadı", B: "Dolmabahçe Stadı", C: "Tüpraş Stadyumu", D: "Beşiktaş Park" }, dogruCevap: "C" },
    { seviye: 312, kategori: "Spor", soru: "Hangi ülke 2024 Avrupa Futbol Şampiyonası'na ev sahipliği yapmıştır?", secenekler: { A: "İngiltere", B: "İtalya", C: "Fransa", D: "Almanya" }, dogruCevap: "D" },
    { seviye: 313, kategori: "Spor", soru: "Eskrimde hedef bölgesi sadece gövde olan silah?", secenekler: { A: "Kılıç", B: "Flöre", C: "Sabre", D: "Epe" }, dogruCevap: "B" },
    { seviye: 314, kategori: "Spor", soru: "Su topu kalesi kaç metre genişliğindedir?", secenekler: { A: "5", B: "2", C: "4", D: "3" }, dogruCevap: "D" },
    { seviye: 315, kategori: "Spor", soru: "Hangi futbolcuya 'Küçük Dev Adam' denirdi?", secenekler: { A: "Emre Belözoğlu", B: "Rıdvan Dilmen", C: "Sergen Yalçın", D: "Okan Buruk" }, dogruCevap: "B" },
    { seviye: 316, kategori: "Spor", soru: "NBA'de bir çeyrek kaç dakikadır?", secenekler: { A: "15", B: "10", C: "8", D: "12" }, dogruCevap: "D" },
    { seviye: 317, kategori: "Spor", soru: "Hangi spor branşında 'Kırkpınar' turnuvası düzenlenir?", secenekler: { A: "Okçuluk", B: "Binicilik", C: "Cirit", D: "Yağlı Güreş" }, dogruCevap: "D" },
    { seviye: 318, kategori: "Spor", soru: "Dünyanın en çok izlenen spor organizasyonu hangisidir?", secenekler: { A: "Dünya Kupası", B: "Super Bowl", C: "F1", D: "Olimpiyatlar" }, dogruCevap: "A" }
 

);
 